### ISSUE TITLE
 not able to install in my laptop '

### ISSUE THREAD

**Issue by kalebrai** [ChurchApps/FreeShow#1000]
my laptop is window 11 and i7 9generation 4gb nvidia grapphic 
![Screenshot 2024-11-09 230650](https://github.com/user-attachments/assets/1ae1f1e8-c461-4a32-8eb4-6e1173af2be8)

**Comment by jerm00** [comment]
Are you running the x64 version on ARM CPU? Or arm version on x64 CPU? It looks like one or the other to me

**Comment by vassbo** [comment]
Please make sure you are using the x64 .exe version!
![bilde](https://github.com/user-attachments/assets/25c10c98-21f7-48ba-8709-0f5359990fa4)
