### ISSUE TITLE
Apply to all action and save button missing from Edit show

### ISSUE THREAD

**Issue by m-pav** [ChurchApps/FreeShow#1004]
When in edit mode making changes to a lyric or it's layout, the Apply to all" button has disappeared as well as the Save button. I used to use this all the time when adding a new show because it was useful to create a specific look for particular songs.

**Comment by vassbo** [comment]
Please press "Copy" at the bottom to get the "Apply to all" button:
![bilde](https://github.com/user-attachments/assets/8efed88f-4932-4f84-880d-d22bfd44cba7)
![bilde](https://github.com/user-attachments/assets/49aeca1f-c7a7-43f3-a9bf-cd34a3c7c6df)

I can't recall there being any "Save" button on the "Edit" page?!
