### ISSUE TITLE
[Bug Report] Large memory use when viewing Pixabay video tab

### ISSUE THREAD

**Issue by klecu** [ChurchApps/FreeShow#1007]
**Describe the bug**
When viewing Pixabay video tab in the drawer, memory use quickly climbs to several GB. Going back to image tab releases memory

**Reproducing**
Open Media drawer, go to Pixabay, and go to Videos tab

**Version (Optional)**
 - OS: Windows 11 Pro 23H2 32GB RAM
 - FreeShow Version: 1.3.0

**Comment by vassbo** [comment]
Thank you, I didn't use the thumbnails, so the issue must be that it loaded many videos at once.
