### ISSUE TITLE
Slides with next slide timer don't advance with clear slide action is on the slide.

### ISSUE THREAD

**Issue by mwb9aa** [ChurchApps/FreeShow#1008]
**Describe the bug**
Slides do not advance if a clear slide action is on the slide and the slide is set to advance via the Next slide timer.

**Reproducing**
1. Place a few pictures in a show and set them to advance using the Next slide timer (I used 4 s).
2. Create an action for clearing the slide. This is the default text layer.
3. Drag the action to the pictures.
4. The first slide plays but does not advance as expected. The clear slide action seems to clear the timers as well as the slides.

Edit: I do have a template overriding in the styles applied for that output. I noticed if I remove Slide from the active layer of the Styles, everything works as I expected. However, I couldn't find a way to create an action that would activate/deactivate the Slide Layer of the style.
 
**Screenshots (Optional)**

**Version (Optional)**
 - OS: WIndows 11
 - FreeShow Version: 1.3.0

**Additional context**
I expected clear slide to clear only the text, but it seems to clear the timer as well.

**Comment by vassbo** [comment]
Not sure why you would need to clear the slide while presenting slides. But the next slide action relies on the currently playing slide, so you should use an empty slide instead. But a new feature I added fixes this problem in the next version actually, where the last position of a cleared slide is kept active.

**Comment by mwb9aa** [comment]
It is an announcement loop, with a style applied to the output. I think I expected the slide layer to be the same as text.
