### ISSUE TITLE
[Bug Report] {Chinese Bible with Englist Chapter Name}

### ISSUE THREAD

**Issue by AngangGuo** [ChurchApps/FreeShow#1009]
**Describe the bug**
I downloaded the Chinese bible from [here](https://github.com/Beblia/Holy-Bible-XML-Format/blob/master/ChineseCUNPSSBible.xml) 
and added it into FreeShow. Everything works well except the chapter name is English.

How can I show bible chapter in Chinese?

**Reproducing**
You can download the Chinese Bible CUNPSS from 
[here](https://github.com/Beblia/Holy-Bible-XML-Format/blob/master/ChineseCUNPSSBible.xml) 

**Screenshots (Optional)**
![image](https://github.com/user-attachments/assets/8b52bbd9-46af-43a2-8605-6ef1890c9492)

**Version (Optional)**
 - OS: [Windows 10.0.19045]
 - FreeShow Version: [v1.3.0]

**Additional context**

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/645#issuecomment-2205951012
https://github.com/ChurchApps/FreeShow/issues/581
