### ISSUE TITLE
Automatic Stage View Selection based on Current Show Category

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#1013]
### Feature Description
Thanks so much @vassbo for all the hard work put into this app! I literally cannot thank you enough for such an awesome and free app. ❤️

So, for my church's song service, I like to put up a specific stage layout that uses the text from the current slide and the next slide to give the praise team a better idea of what is going on.
However, the same stage view doesn't work for presentations and slides during the other parts of the service, so I usually end up quickly changing the stage output to a simpler "current output" view for the non-singing parts of the service.

**What I'd like is the option to have the stage output automatically change in the stage show output based on the type of show being presented.** I've tried to create an action to do this for me, but I couldn't find an option that would differentiate between the slides. **I was thinking that it might be possible to either create an action or add an output setting to change the stage view output based off of the category that the show is in.** This would mean that when I switch from a show in my "presentations" category to a show in my "hymnal" category the stage will switch from a presentation-tailored one to a hymn-tailored one.

What are your thoughts on this? Does this workflow already exist?

**Comment by mwb9aa** [comment]
I did something similar for our scriptures, and the steps might work for you.

1. Create two stage layouts, one for songs (current/next text) and one with the current output. I think you already did this.
2. In the Functions tab of the drawer create two actions that change the stage output by ID. One action changes the stage layout to current/next text. The other action changes stage output to the current output layout.
3. Drag the current/next action onto the first slide of each show that needs to have that layout. For example, each song. Drag the current output action to the first slide of each show that needs the current output layout.

When the user clicks on the first slide, the action will play and change the stage layout.

Bonus: A slide can have more than one action on it at the same time.

**Comment by vassbo** [comment]
Thank you @Dcanadian. Does the method provided by @mwb9aa work for you?

**Comment by thebiblelover7** [comment]
I believe that @Dcanadian is meaning to add the ability to apply an action/macro to the first slide of the show depending on which category it is in. That way, you don't have to go through every show of the category to add it (which is very time-consuming when you have at least 600 songs.

**Comment by mwb9aa** [comment]
My steps are just a workaround. I think this feature is almost implemented, with just a few more pieces in place, I think we can have the features @thebiblelover7 and @Dcanadian are requesting.

I can create a template in the function drawer.
I can create actions to change my stage layout by ID.
I can add the actions to my group template by Right-clicking the template->Action->Run Action.
I can create a group and add the template to the group in Settings->Groups.*
I can put this global group in my Show.*

However, I don't think the run action is actually working. It is not working on either computer I am using at the moment.

*You can use an existing group, then there is no need to add it to every show because it is already in each show.

**I think the bug is that run action on a template is not actually working.**

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.1

**Comment by mwb9aa** [comment]
@Dcanadian 
Apologies if my "teacher voice" comes out and I explain something you already know. My wife says it comes out a lot.

1. Create categories (or use existing ones) in the Shows tab of the Drawer.
2. Right-click the category (Songs) and choose Category Action.
3. Pick the action you want to use. **You can only choose one action per category. If you want multiple things to happen, you have to configure that in your action.**

Actions are series of steps put into a "shortcut". Create actions by navigating to the actions section of the Function tab in the Drawer and clicking New action. @vassbo has given us tons of options, my favorite of which is being able to add multiple Start actions to a single action.

Some common actions broken by category:

- If using backing tracks or midi control from other software:

> - Select project item by index
> - Select slide by index
> - Next slide

- If using an output for streaming / lower-thirds and want to switch between layouts:

> - Change output style

- if using multiple stage outputs to workaround the issue you describe here (https://github.com/ChurchApps/FreeShow/issues/1037#issuecomment-2488752050), or want the stage and main output screen to display the same thing:

> - Change stage layout


Once you set up an action, you can click on it to activate it. You can also assign it a custom shortcut keypress (single keys only), a midi note trigger, and can drag the function onto a slide to be triggered whenever the slide goes "live".

In our service, we want the stage output to match the audience output during the announcements slides. So, I have an action set that
- Changes the output style
- Change the stage layout

Then on any show in the category Ableton, I apply an action with the following actions:
- Changes the output style
- Change the stage layout
- Clear overlays (timers)

If you have further questions, feel free to send me a dm.
