### ISSUE TITLE
[Feature Request] Ability to make sections appear as blank slides

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#1018]
![image](https://github.com/user-attachments/assets/cdcdda2d-f896-42b7-ac92-5e5148a0ab14)

We often separte different sections of the service with a blank slide.
This is so that, we get the screen to appear "off" whenever we are not on a song, without having to "stop" the presentation.

It would be nice if there was an option for "section dividers" to appear as a blank slide. Currently, when a divider is selected, the screen still outputs the previous slide.
Another way of doing it would be to have an option to always have a blank slide between different items.
So, when going from one song to another, for example, the user would have to press the right-arrow twice - one for the blank slide, and one to start the next song.

I know there are workarrounds for this scenario, but it would be useful if there was a global setting for this.

**Comment by vassbo** [comment]
I mean, maybe we can have some indicator on the sections that it's on. And only clear if pressing arrow left/right, not up/down..

**Comment by yurividal** [comment]
Yeah, currently what I have created a blank slide, with the name of each section that we have and saved them in a category called blank slides.

But the section dividers just make the organization look a lot nicer and more clear.
Maybe have a checkbox in a section that says "blank screen when this section is selected".

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.1

**Comment by yurividal** [comment]
Hi @vassbo  i just downloaded 1.3.1 , but i dont see this. Is it something i have to enable? sorry if i'm missing something

**Comment by vassbo** [comment]
In the bottom right corner of a section!
![bilde](https://github.com/user-attachments/assets/aa290518-8210-4f18-aa8e-214a339b7ec9)

**Comment by yurividal** [comment]
Perfect!I created an action to "Clear Slide", and set it to that. Works perfectly!
