### ISSUE TITLE
How to show different looks to screen and live stream?

### ISSUE THREAD

**Issue by AngangGuo** [ChurchApps/FreeShow#1020]
I want to show lyrics as full screen to projector and as one third to live stream(NDI) at the same time.
In ProPresenter, I apply different looks to Screen and Live Stream.
How can I do it in FreeShow?
Thanks.

**Comment by chalamministries** [comment]
you should be able to just create another screen. and when you turn on NDI, your Indy I receiver should see multiple screens and you just choose the right screen. 

or are you asking how to do a different theme on a separate screen?

**Comment by AngangGuo** [comment]
I tried and it has several steps to achieve it:
1. Created a lower third template for live streaming
2. Created a new style using the lower third template to override slide with template
3. Create a new output and use the above style. 

Note: The scripture slide need its own template.

Great thanks for the help!
