### ISSUE TITLE
Keyboard Shortcuts for Song Sections 

### ISSUE THREAD

**Issue by leetkrew** [ChurchApps/FreeShow#1022]
Simplify the song display with these intuitive shortcuts:
	•	Keys without a number default to the first section (e.g., V + Enter = Verse 1).
	•	Keys followed by a number specify the section (e.g., V2 + Enter = Verse 2).

Quick Reference:

	•	V + Enter: Verse 1
	•	V2 + Enter: Verse 2, and so on.
	•	C + Enter: Chorus 1
	•	C2 + Enter: Chorus 2
	•	O + Enter: Outro
	•	I + Enter: Intro
	•	B + Enter: Bridge 1
	•	B2 + Enter: Bridge 2
	•	P + Enter: Pre-Chorus 1
	•	P2 + Enter: Pre-Chorus 2

These shortcuts keep our song display organized and effortless!

**Comment by vassbo** [comment]
You can already set group shortcuts in settings>Groups.
(Clicking e.g. V will select the first verse, clicking verse again will select the next verse.)
