### ISSUE TITLE
NEED HELP ASAP (scriptures dont look right)

### ISSUE THREAD

**Issue by RIWHEATON** [ChurchApps/FreeShow#1023]
Hello. I just found out that there was a newer update to freeshow (version 1.31) and it seems like my scripture is messed up according to the screenshot i just took. Is there a way to remove the first line?

Screenshot:
https://github.com/user-attachments/assets/00830a7b-8822-40b7-89f3-ee8f266934c8

**Comment by AngangGuo** [comment]
I think you can check your scriptures template. Maybe something wrong with your template.

**Comment by vassbo** [comment]
First of all, set your "Max verses per slide" to more than 1 (that's a bug I have fixed for the next version):
![bilde](https://github.com/user-attachments/assets/9b812d92-3d9f-4636-bd79-dcfe7418aec1)

Secondly please check that your reference value does not look like this (You can try clearing the textbox and turning off the "Show reference":
![bilde](https://github.com/user-attachments/assets/9ccf607e-2839-4d78-9ecd-5d95739e89fb)

**Comment by Lpwmack17** [comment]
@vassbo So I also have this isseu, since the new version of Freeshow came out. One of the tweaks you added was "Multiple scripture references added to esch textbox when combined".
Now I think i speak for all users here, who created a custom scripture template with "Meta" for the scriptures etc. Now when the scriptures go live, we see them doubled.

It sounds complicated, but I can assure you, it's 100% because of that new tweak.

Anyways thanks :)

**Comment by vassbo** [comment]
It's actually not related to the new setting. Though I did accidentally remove an overflow check causing the reference to be added twice in certain conditions!

But as I mentioned, as long as the "Max verses" setting is not equal to the selected verses it works fine!

**Comment by RIWHEATON** [comment]
> First of all, set your "Max verses per slide" to more than 1 (that's a bug I have fixed for the next version): ![bilde](https://private-user-images.githubusercontent.com/17619496/387098436-9b812d92-3d9f-4636-bd79-dcfe7418aec1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTA4NTgsIm5iZiI6MTczMjE1MDU1OCwicGF0aCI6Ii8xNzYxOTQ5Ni8zODcwOTg0MzYtOWI4MTJkOTItM2Q5Zi00NjM2LWJkNzktZGNmZTc0MThhZWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAwNTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNDQ2ZGYwYjYwZDkxN2FmMDljODNlMWVkZGJiM2NjZTQzYzgzNmMyMWIwYWU5MGY1YTViMzUyOTk0N2YzNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5vhmTCO9l4Ks2YDDRA4R1AzmE2xyPNsryb4hd6TrGsw)
> 
> Secondly please check that your reference value does not look like this (You can try clearing the textbox and turning off the "Show reference": ![bilde](https://private-user-images.githubusercontent.com/17619496/387098758-9ccf607e-2839-4d78-9ecd-5d95739e89fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTA4NTgsIm5iZiI6MTczMjE1MDU1OCwicGF0aCI6Ii8xNzYxOTQ5Ni8zODcwOTg3NTgtOWNjZjYwN2UtMjgzOS00ZDc4LTllY2QtNWQ5NTczOWU4OWZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAwNTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhM2U0N2NlMWQzNzM5YTEzNjgyNTEzNmQ5ZDc1NGQzOTVjMTI0ZGU3MzUwMDdlODk3M2VjNTY3MjRmYjA2ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._4vqpOLurvaePHfRkrjZRfft2mQF6kHedPKiHfmJHsg)

Thanks! This worked.

**Comment by vassbo** [comment]
Should be corrected here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.2-beta.1
