### ISSUE TITLE
Minimum requirements for a smooth experience

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#1024]
Are there any minimum or recommended requirements or FreeShow to run smoothly?
After a few weeks of testing on my personal device, I have decided to trial Freeshow at my church's AV computer.
Our current projection PC has the following hardware:

- Intel i5 9400 @ 2.90Ghz CPU
- 8GB of RAM
- 256GB SSD
- Windows 10

It was never an issue to run OpenSong nor Powerpoint, obviously. But, Freeshow seemed to struggle a bit. It felt quite laggy, and CPU usage was costantly pretty high (70%-95%). Initially CPU was even higher, and it was basically unusable, since high CPU was making even slide transitions lag for like 1 or 2 seconds. I closed the NDI app i had running on the background, and it improved a bit, to the point that FreeShow was usable - but still felt a bit laggy. 

We always have the NDI viewer open, in case we need to show the camera on the main screens, so I'll have to make this work.

I tried both - hardware acceleration on and off. Doesn't seem to make any difference.

Is there an optimal setting for FreeShow? Is my PC under-spec'd?

Feel free to convert this "issue" into a github discussion if you want. I tried opening it as a discussion, but discussions don't seem to be enabled for this repo.

**Comment by vassbo** [comment]
Using NDI will cause less performance than not using it (it's very recommended with a GPU, that helps a lot).
It's basically the same requirements as Chromium: https://freeshow.app/docs/features#system-requirements

I think the way we do screen recording for NDI is pretty optimized, but there might be another way to do it. Also not sure how much the NDI sender package is optimized.

Discussions can be opened here: https://github.com/orgs/ChurchApps/discussions/categories/freeshow
