### ISSUE TITLE
[Feature Request] Sort Songs and search by Metadata - not only title

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#1025]
We have over 3500 songs in our database, and sometimes, searching by name is not the most efficient way - some songs are duplicated in different song books, etc.

It would be nice if we could search for metadata too. Even better, if the song list was actually a table, that we could sort by name, but also by CCLI number, author etc...

Being able to search or sort by these items would be really useful. Our Music group often sends the song list to the AV team based on the CCLI number only, or just the Songbook + Song Number.

In this example, the Music Group sent us only "Christian Hymns 808" 
![image](https://github.com/user-attachments/assets/5fb362b7-c5d6-4d29-a995-6fd5fa9a6963)

An idea of how the song list could look like, as a table, which users can search and sort:
![image](https://github.com/user-attachments/assets/a9f8ba89-6d46-4fc0-a8ed-3520a5222a1c)

**Comment by vassbo** [comment]
The only issue at the moment is that the metadata is not stored in the "cache", but in each individual json file.

At the moment you can search for the song name & "Number".
I think it's generally always faster to search for the song title/number, than to search or scroll for the CCLI number.

**Comment by vassbo** [comment]
From the next version you will be able to search for the CCLI number and the song will show up if there is 100% match.

It will need to be opened manually for the CCLI to automatically be added to the cache, or if you want you can write a script to add it to `quickAccess: { metadata: { CCLI: number } }`
