### ISSUE TITLE
PLEASE remove AutoUpdate. I DON'T want to delete my OLDER versions

### ISSUE THREAD

**Issue by leirbag28** [ChurchApps/FreeShow#1026]
(**Describe the feature**)
A clear and concise description of what you would like too add/change.
Please REMOVE the Automatic Downloading of a NEW version. Let US choose that by going to the site.

(Optionally describe why this feature is needed.)
Sometimes if it is our production machine and it was FORCED upgrade and it turns out the NEWER version has issues, this will be problematic. it is better we are TOLD there is a new version and let us decide. Plus one of the EXCELLENT things I LOVE about Appimage is that you can have MULTIPLE versions of the same App in case one functions better. I still have version 1.4 on my machine along with the latest as 1.4 seems to run smoother and lighter on resources. Sometimes saving money for churches means not spending money on higher end machines...so the app functioning fully on the current machines we have is a BLESSING!

(**Additional context**)

**Comment by Phantom-Matt** [comment]
You can deactivate Auto updates on Settings->Other->Auto updates.

Here:
![Captura de imagem_20241117_213336-1](https://github.com/user-attachments/assets/bec99412-faeb-44eb-b5ac-19f3eeb002bc)

**Comment by leirbag28** [comment]
Awesome! Maybe it should be off by Default? Anyone wanting to get a newer version can just get the message a New version is out and go downlod it.Sent from my iPhoneOn Nov 17, 2024, at 8:37 PM, Mateus H ***@***.***> wrote:﻿
You can deactivate Auto updates on Settings->Other->Auto updates.
Here:
Captura.de.imagem_20241117_213336-1.png (view on web)

**Comment by leirbag28** [comment]
Have a Question/request on this related subject.I recently Opened 2 older versions of FreeShow and neither version had the AutoUpdate turned off (I think theu dont sven have the option)…one was a .deb native version and the other an Appimage.I need to know where these temporary Updates that happen in the background go/stored as it says it will update upon reopening the app (which i DEFINITELY do not want) but it never does…but this is not my issue at the moment…my issue is that Inhave at least 2 or 3 EXTRA FreeShow apps in that temporary folder. I am always running on less that 500mb storage on my HD and can’t lose space like this..I need to delete them. Where can I find the .deb stored update and the Appimage update?Sent from my iPhoneOn Nov 18, 2024, at 12:38 PM, Gabe Olive ***@***.***> wrote:﻿Awesome! Maybe it should be off by Default? Anyone wanting to get a newer version can just get the message a New version is out and go downlod it.Sent from my iPhoneOn Nov 17, 2024, at 8:37 PM, Mateus H ***@***.***> wrote:﻿
You can deactivate Auto updates on Settings->Other->Auto updates.
Here:
Captura.de.imagem_20241117_213336-1.png (view on web)

**Comment by vassbo** [comment]
I don't know Linux well enough to know what to keep or not. But can't you take a backup, then delete all of the versions, then install the latest?
