### ISSUE TITLE
NOT ABLE TO SEACH KEY PHRASES

### ISSUE THREAD

**Issue by KamsyoSIGWE** [ChurchApps/FreeShow#1030]
Gooday I noticed Freeshow doesn't have the ability to search for key phrases in imported Bible files in FreeShow. Currently, the search functionality seems to only support Bibles from API.Bible, which limits the ability to locate verses or passages based on contextual phrases. This feature should allow users to:

Search for multi-word phrases (e.g., "In the beginning God").
Find results based on partial matches or fuzzy search (e.g., "beginn God").
Return results even if the phrase spans multiple verses.

https://github.com/user-attachments/assets/2f14e676-1d63-4071-8ab9-7050d89d4eb9

**Comment by KamsyoSIGWE** [comment]
Hey I know about this. But this for the .xml files for bibles uploaded it doesn't let me search up key phrases. video showing this below

https://github.com/user-attachments/assets/e0a0fa68-c0d5-4a25-b6c6-9bb5de512c71

**Comment by vassbo** [comment]
Works fine for me! Please try it in the latest version (1.3.1)
![bilde](https://github.com/user-attachments/assets/3ba4c4d4-2d26-40b8-b50a-5b87fbd017f6)

**Comment by KamsyoSIGWE** [comment]
okay it works now. but the new version duplicates the heading of the verse.
![image](https://github.com/user-attachments/assets/988232aa-f95b-4cff-a2d7-2c7ce8037508)

**Comment by vassbo** [comment]
It works fine as long as the "Max verses" setting is not equal to the selected verses!

But I have fixed that for the next version: https://github.com/ChurchApps/FreeShow/issues/1023#issuecomment-2482113359
