### ISSUE TITLE
Please add a option to play a video muted from the drawer

### ISSUE THREAD

**Issue by MR-Samy-726** [ChurchApps/FreeShow#1033]
Hello, I would like the videos to be played in the background from the drawer but without audio. Normally to do this you have to drag it onto the slides and with that, by default, the video is muted. But if I want to play another video from the media, it will play with audio by default. It would be great if there was a small button that allows you to play it by default muted. The Ctrl+M shortcut sometimes also mutes the background music and that complicates things if I want to have background music at the same time.

**Comment by vassbo** [comment]
Added an option to right click and "Play without audio" for the next version.
