### ISSUE TITLE
TEXT TRANSFORM IS NOT APPLYING TO THE EDIT WORK SPACE

### ISSUE THREAD

**Issue by fdccichurch** [ChurchApps/FreeShow#1036]
**Describe the bug**
Text transform is not applying to the edit work space but in the slide pane on the left it applies. Though it not affects on the text in presentation but it gives confusion when editing the text, thank you.

**Reproducing**
EDIT > TEXT > TEXT TRANSFORM > UPPERCASE

**Screenshots (Optional)**
![image](https://github.com/user-attachments/assets/afe8aaf9-d65a-430d-b1c3-dd9d18ebc437)

**Version (Optional)**
 - OS: [Windows 11]
 - FreeShow Version: [e.g. 1.3.1]

**Additional context**

**Comment by vassbo** [comment]
Because of this issue it has to be like that: https://github.com/ChurchApps/FreeShow/issues/1001

But you can see in the top left corner of the item that a text transform is active!

**Comment by vassbo** [comment]
TIP: You can right click the slides/textbox and choose "Format">"Uppercase" to actually change the text casing, if you know you would like it to stay like that.

**Comment by fdccichurch** [comment]
Oh, I see so I have to format each slide to uppercase to change all. :( Okay thank you for your response.

**Comment by vassbo** [comment]
If you don't want to use custom uppercase style in a template, you have to change them manually.

But you can use Ctrl+A to select all slides, to format them all at once!
