### ISSUE TITLE
Stage Display Outputs not Receiving Text From Song Slides

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#1038]
**Describe the issue**
Recently I've been playing around with multiple outputs for a more advanced stage display setup. However, today I opened FreeShow to find that even though the Primary input is receiving text and displaying it as normal, the two stage layouts are getting data - one of them is showing an accurate progress bar for the song - but not displaying the song text at all. (See attached screenshot)

I don't think that this issue has to do with output routing in Settings, but I'm genuinely baffled as to why this slide text isn't showing up on my stage displays.

**Reproducing**
1. Install FreeShow 1.3.1
2. Create Stage Display outputs
3. Probably mess something up somewhere 😁
4. Click on a slide from a song to load it in output
5. Observe the bug 🔎 🐞 

**Screenshots**
![IMG_1425](https://github.com/user-attachments/assets/7e100553-e896-4b1b-8827-479052d9f244)

**Version (Optional)**
 - OS: Latest MacOS
 - FreeShow Version: 1.3.1

**Comment by vassbo** [comment]
It works as it should!
See this: https://github.com/ChurchApps/FreeShow/issues/957#issuecomment-2454177944

**Comment by vassbo** [comment]
If it was unclear you should set the "Source output" to your "Primary" output!

**Comment by vassbo** [comment]
No, because most of the time you would not need access to it. Also if you didn't have the "For Play" output, or you had renamed to "Primary" to go first you would not need to set it at all!
