### ISSUE TITLE
[Minor Bug] "!" shows in wrong position if a category or tag has an ! at the end

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#1044]
Just noticed that if you have a category or tag name that ends with an "!", it shows the wrong name on the slide details.

We have a category amd tag names Praise!, and this is how it shows on song details:

![image](https://github.com/user-attachments/assets/50b404cc-f955-4f9f-a67b-6a6e7bba10f6)

I don't think this affects the functionality. It might just be a cosmetic bug

**Comment by vassbo** [comment]
I had the text direction set to right-to-left here so the text kept right when overflowed.
But apparently that also swapped certain characters.
![bilde](https://github.com/user-attachments/assets/a164bba0-4682-48f4-b1ea-e9cade430939)

As long as I'm aware there's no way of doing that without the rtl direction, so I guess I will revert that change then!
![bilde](https://github.com/user-attachments/assets/e342b143-6fbe-43ce-baf6-e669bdba6637)
