### ISSUE TITLE
[Feature Request] Bulk edit the "Number" using the magic wand button 

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#1045]
Hi. 
I made a python script to that added a "Number" attribute to all my songs. 
The Number shows in the metadata information, as expected:

![image](https://github.com/user-attachments/assets/1f1032a2-577b-48a3-a360-a9de5d46f5d0)

But, in order for it to be recognized by opensong, and become searchable, i have to manually click the magic wand button, on every song.
Once i click the magic wand, the number appears as a pink number in front of the song title, and i can search fot it. 
Like this:
![image](https://github.com/user-attachments/assets/1e7f4827-764d-4531-9230-6d9a89af3278)

Is there a way to apply this for all the songs in bulk?

**Comment by vassbo** [comment]
In addition to the `metadata`: `number` key, you also have to add the number to the `quickAccess`: `number` key so it's searchable, and probably update/delete the `shows.json` (cache) file.

I forgot to auto add to the quickAccess when importing (if the metadata number is available) so I'll add that.

**Comment by yurividal** [comment]
thanks! the trick was to delete the shows.json file, or else, it kept overwritting and deleting my quickaccess : number (which was already part of my script).

the first time i oppened freeshow after deleting shows.json, it took a while (almost 3 minutes) for the app to start. But it seems to be all good now.

**Comment by vassbo** [comment]
Great! It takes a while because it has to read through all of your .show file and parse the data again.

That's why I'm not sure it's a good idea to do this at this point in time: https://github.com/ChurchApps/FreeShow/issues/1025
