### ISSUE TITLE
[Feature Request] Use ""natural sorting"instead of "alphabetical" for song numbers

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#1046]
Hi. As you know, i just bulk-added song numbers to all my songs.
I noticed that they are sorted by strict alphabetical order.
Using natural sorting makes more sense in this case, since it will make numbers follow a natural order.

Example:
Instead of 
1
10
2
20
21
3

it would produce
1
2
3
19
20
21

![image](https://github.com/user-attachments/assets/7f024099-228d-4ad7-a187-d4c5b138d290)

**Comment by vassbo** [comment]
It does do that actually when the numbers does not start with a string.
But I'll add a number parser for the "number" data.

**Comment by yurividal** [comment]
Thanks, as always.

Yeah, we have the initials of the song book before the number. I think its just a legacy thing from when we used song-books, but changing it now is impossible. There are way too many processes and things on the Music Group that relly on these "song numbers" being consistent for us.

Thanks again @vassbo
