### ISSUE TITLE
Option to save songs with overlays (motion backgrounds)

### ISSUE THREAD

**Issue by franklinis** [ChurchApps/FreeShow#1047]
When we have a song in Freeshow, I don't know or see an option to save it with desired background.

Am I missing something ?

**Comment by Phantom-Matt** [comment]
> When we have a song in Freeshow, I don't know or see an option to save it with desired background.
> 
> Am I missing something ?

If you go to "File"->"Save" that should save all changes you made, even overlays and media applied to shows.

**Comment by Phantom-Matt** [comment]
Also, you can drag a video to the first slide of a song and all slides will get the video as background.

**Comment by vassbo** [comment]
As @Phantom-Matt suggested, you should be able to drag and drop and video/image to a slide to add as background.

**Comment by franklinis** [comment]
> > When we have a song in Freeshow, I don't know or see an option to save it with desired background.
> > Am I missing something ?
> 
> If you go to "File"->"Save" that should save all changes you made, even overlays and media applied to shows.

Unfortunately this didn’t work for me. But dragging and media into the slide worked for me.
