### ISSUE TITLE
Limit lines per slide like scripture

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#1049]
**Describe the feature**
The feature in the scripture tab that allows you to limit the amount of verses per slide would be nice to have built into the templates. That way, you could specify, for example, that there will be no more than four lines on any slide, and a minimum of two. Once you apply the template, it automatically breaks up the slides accordingly.

**Additional context**
This will be helpful during events that require scripts, or for plays. This ensures that you can paste a long document into a show, and have it automatically break it into slides, ensuring that everything is big enough.

**Comment by chalamministries** [comment]
So what happens if you have more lines than the template allows? What happens then? In scripture, each verse is a seperate item. Not sure we can separate a slide you entered with 5 lines to only show 2 and split. Am I understanding your request right?

**Comment by chalamministries** [comment]
Okay the only issue with that would be if you created a five-line slide you can't just have it show differently or it would cut off the rest of the lines. However an idea would be a feature where you can put however many lines you want on a slide and then hit a button to automatically split them. But in order for it to actually work it would have to create individual slides with two lines each. You wouldn't be able to have one slide with five lines and it just automatically show it split.

What do you think about that?

[Steven Gauerke](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2vtgwt)	[2vtgwt]Web Developer

On December 1, 2024 at 20:04 GMT, David via Info ***@***.***> wrote:

Yes, I would be wanting to have the 5 line slide split into two, two line slides, and one one line slide. Potentially there could also be the option to have a constant header across all the slides, too.

**Comment by vassbo** [comment]
@chalamministries Using the "Lines" output style you can set a max amount of lines per slide for the output.
We also have the "Split in two" format option that could work with a "Split with X lines per slide".

But if we also allow a template to auto split into multiple slides (as the "New show" - "Max verses per slide" does), then it's automatic and we ensure we have a preview of the text before we output to make sure it looks good.

**Comment by vassbo** [comment]
![image](https://github.com/user-attachments/assets/a9281d7f-96b4-4332-97f2-780d5448feb5)

**Comment by maxstrosch** [comment]
> ![image](https://private-user-images.githubusercontent.com/17619496/396394845-a9281d7f-96b4-4332-97f2-780d5448feb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwMjEyMjksIm5iZiI6MTczNzAyMDkyOSwicGF0aCI6Ii8xNzYxOTQ5Ni8zOTYzOTQ4NDUtYTkyODFkN2YtOTZiNC00MzMyLTk3ZjItNzgwZDU0NDhmZWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE2VDA5NDg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3OGM0MzNjMmNlYzM4YmRmMmE4MTllNzdlN2RhMjllMDc1MGU2N2E1MDJjZWZmNjlmMzM0NTg5MmYxOGVmYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lQRNMwZRX-mKjkoK38r6ZPaLYM_zYjmcv8JC0bQ4zD8)


Where do I have to look for it?

**Comment by vassbo** [comment]
In a template on the right side:
![image](https://github.com/user-attachments/assets/e717e995-5780-4f19-849c-e3ad6d3c3874)
