### ISSUE TITLE
Identifying Songs with the Same Title

### ISSUE THREAD

**Issue by fdccichurch** [ChurchApps/FreeShow#1050]
**Describe the feature**
Are there ways to identify whether songs with the same title are different and determine the singers? Could there be future features to make this process easier?

**Additional context**

**Comment by mwb9aa** [comment]
You can create different versions of the same song. For example, if I have the song Amazing Grace I can choose + New layout. From there, I can name the layout with the names of the singers and rearrange the order of the song.

**Comment by vassbo** [comment]
When creating shows you should use layouts as @mwb9aa.

When creating a new show with the same title as an existing show the app will alert you.

Lastly if you go to settings>Other you can click "Remove duplicated shows" to get an overview over all shows with the same title (to see the content and optionally remove any duplicates).
