### ISSUE TITLE
Mac M1: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by iAmCLY** [ChurchApps/FreeShow#1051]
**Describe the bug**
The app cant load/start

**Version (Optional)**
 - OS: MacOS 15.1.1
 - FreeShow Version: [e.g. 1.0.0]

**Additional context**
Error Log says:
Uncaught TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

**Comment by vassbo** [comment]
What FreeShow version did you install?
