### ISSUE TITLE
Duplicate Reference Textbox on Last Selected Verse

### ISSUE THREAD

**Issue by JosephYoung42** [ChurchApps/FreeShow#1052]
**Describe the bug**
When adding scripture to a show, the last verse added shows both the book, chapter, and verse along with a duplicated book and chapter that overlaps in the bottom textbox. Investigating further it looks like a duplicate reference textbox is created on the slide.

**Reproducing**
If you add a single verse or multiple, the last verse has the duplicate book & chapter.

**Screenshots (Optional)**
Settings for adding scripture: 
<img width="394" alt="image" src="https://github.com/user-attachments/assets/03f7a321-95f1-42c6-9639-7b71fff55b2b">

How the slide looks:
<img width="1306" alt="image" src="https://github.com/user-attachments/assets/1a4417c6-3157-4e75-8e00-7d58ac8219a0">

**Version (Optional)**
 - OS: MacOS
 - FreeShow Version: 1.3.1

**Additional context**
This issue just started happening in 1.3.1, but I'm not sure if the last time we were using 1.3.0 or the version prior to that. 

Also workaround is to edit the slide after it's created to delete the extra text box.

**Comment by Lpwmack17** [comment]
This issue has already been fixed in the new beta Version 1.3.2-beta.1
