### ISSUE TITLE
Add Filter to Separate Songs from Other Shows and Scriptures in RemoteShow

### ISSUE THREAD

**Issue by Lpwmack17** [ChurchApps/FreeShow#1053]
Currently, all shows, songs, and scriptures are mixed together in the interface, making it difficult to find specific content. 
To improve user experience, I propose adding a filter feature that allows users to separate songs from other shows and scriptures.

Filter Options: Add filter options to categorize content into “Songs,” “Shows,” and “Scriptures.”
User Interface: Implement a dropdown menu or tabs for easy navigation between these categories.
Default View: Set a default view that shows all content, with the option to apply filters as needed.

God Bless!

**Comment by yurividal** [comment]
This has already been suggested a few times, and it seems like it is not something the developer(s) see as needed.

I remember from a previous discussion about this item, one of the features that emerged was the ability to automatically put scripture shows into a scripture category under shows.

**Comment by Lpwmack17** [comment]
Well @yurividal I noticed the Devs putting nee festures into RemoteShow, such as looking verses with the correct version or something similar on RemoteShow, i just want something similar like that 🤷‍♂️🙏

**Comment by vassbo** [comment]
By default the "Scriptures" category is an archive (you can right click any category to mark as archive) meaning the shows in the archived categories will not show up in the "All" shows list/search.

This way you can also mark e.g. the "Presentation" category as archive, and you got your different "filters".

You can also apply "Tags" to any show for further organization, and filter by tags!
