### ISSUE TITLE
[Bug Report] FreeShow gets confused whether a song is locked for editing or not

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#1054]
Something is wrong with my freeshow, that some elements of the UI think a song is locked for editing, and some think it's unlocked.
Toggleing "Lock for editing" flips the 2, and makes the parts that think its locked to behave as unlocked, and vice versa. See video bellow for better explanation:

https://github.com/user-attachments/assets/3886f616-1563-4c50-a7dc-01242e6e25f8

Initially, song is locked. But i can still right-click and get the edit menu (with change group, slide actions, etc) but at the same time, the "Edit" screen on the top is greyed out.

Then, i unselect "Lock for editing". Now, the right-click menu is no longer available. The padlock now shows locked, and the "Edit" screen is now enabled.

If i go into the edit screen, i can click but can't change the text on any slides.

It is like if some of the areas of the UI think the song is locked, and some think its not.

**Comment by vassbo** [comment]
Thanks. How to reproduce?

**Comment by yurividal** [comment]
Hi @vassbo i'm not really sure how it entered this state. But, it seems to be permanently stuck on this state, and it only seems to happen with some songs. The one i used in the example is a song that i recently added manually, so maybe that's how to trigger it?

Do you want me to send my full configs, and you can try to reproduce it?

If so, just remind me again how to do it and ill send it over

**Comment by yurividal** [comment]
I often do a "select all" and "lock for editing", because i want to make sure my songs are ALWAYS locked to avoid any accidental mess-ups. So, maybe it got lost in one of these.

A feature to "Automatically lock all shows on exit" would be nice, by the way. =)

**Comment by vassbo** [comment]
I think I found the issue, it was toggling the value for each individual show including the cached shows.
I changed it to only get/set the value from the first selected show and toggle based on that.
