### ISSUE TITLE
Import issue for Songbeamer song files

### ISSUE THREAD

**Issue by r0xx5** [ChurchApps/FreeShow#1057]
**Describe the bug**
Import issue for Songbeamer song files

**Reproducing**
After importing SongBeamer songs (in Latin1 or UTF-8), the songs appear with text, but only up to a maximum of 50. 

If I import more than 50, all files are shown without text. 

The same issue occurs if I import 1 to 50 songs, save, close program and then return to it; all SongBeamer files are not display texts. I have also tried using different target folders for import.

Normal native Show files worked without problems all the time.

Also the number of the song is not in the meta data after import

**Screenshots (Optional)**
![Bildschirmfoto 2024-11-25 um 00 51 10](https://github.com/user-attachments/assets/19405349-e725-4bd9-b795-242c495a4738)
![Bildschirmfoto 2024-11-25 um 00 51 36](https://github.com/user-attachments/assets/52a7d4bb-0c0f-4daf-bec8-9ce6b9d3e24a)

sample .sng (songbeamer file)
[1. Großer Gott, wir loben dich.sng.zip](https://github.com/user-attachments/files/17895629/1.Grosser.Gott.wir.loben.dich.sng.zip)

**Version (Optional)**
 - OS: Mac OS Sequoia 15.1 same on VM Windows 11 arm
 - FreeShow Version: 1.3.1

**Comment by vassbo** [comment]
Thanks! Got this fixed. Is the "number" the "QuickFind" key?

**Comment by r0xx5** [comment]
hi thanks for your fast answer. We use following Keys in sng files:

**#LangCount**=1
**#Title**=Title
**#OTitle**=orginal title
**#Author**=Text Author
**#Translation**=Translatione
#**(c)**=Copyright Publisher
**#NatCopyright**=Nationales Copyright
**#Melody**=Music Author
**#Rights**=Rights
**#Keywords**=tags
**#Bible**=Bible Passage
**#Songbook**=Songbook w/o Number
**#AddCopyrightInfo**=additional Infomartionen
**#ChurchSongID**=internal Song Number, which will be shown in the Slides
**#Editor**=SongBeamer 6.04i
**#Version**=3
**#Key**=Key

For Example:

<img width="394" alt="Bildschirmfoto 2024-11-25 um 20 23 34" src="https://github.com/user-attachments/assets/6ab20d54-5590-49c2-97aa-e1761e29fea5">
<img width="389" alt="Bildschirmfoto 2024-11-25 um 20 26 13" src="https://github.com/user-attachments/assets/5ea1e1a6-3f95-462f-a351-185ced343e8f">
