### ISSUE TITLE
Stage Layout Id

### ISSUE THREAD

**Issue by Jsiwolowski** [ChurchApps/FreeShow#1060]
**Describe the bug**
Stage Layout Id is missing. I cant to set Stage Layout Id.

**Version (Optional)**
 - Windows
 - FreeShow Version: 1.3.1

**Comment by Lpwmack17** [comment]
Can you maybe elaborate? And it would help if you send a screenshot or picture of the issue.
Thanks.

**Comment by vassbo** [comment]
If you are talking about the action, you need to create a stage layout on the "Stage" page:
![image](https://github.com/user-attachments/assets/ab995710-ecd4-4371-a0b6-6e0b106566dc)

Also see this, it might be related: https://github.com/ChurchApps/FreeShow/issues/916#issuecomment-2429099877

**Comment by vassbo** [comment]
There never was any "Stage page" option. You probably need to use the "Change stage output layout" action!

The "Change stage layout by ID" in the screenshot was renamed to "Change stage connections layout", and the "Select output style by ID" is renamed to "Change output style".
