### ISSUE TITLE
Use NDI source as background

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#1061]
Hi. I am trying to accomplish a setting where i want to display a song, and have the background of the song be the input from my OBS camera, via NDI.
(This is an edge case. The idea is that when we have baptisms, everyone wants to be able to see the baptistry, so we usualy project the OBS Camera onto the Church's screens, and overlay the song lyrics on top of it).

I tried to create a blank show, and add drag an NDI input into it, but it doesn't work. 

Freeshow detects my NDI cameras from OBS, but always fails to load them.

![image](https://github.com/user-attachments/assets/e260d6fd-d80a-4ee3-a6d0-2eb19cac2e2f)

The, after a long time, i get this:

![image](https://github.com/user-attachments/assets/bb7c2f30-6d6d-4895-b773-cb877736b5b1)

I don't have any other programs reading NDI on that computer.

**Comment by vassbo** [comment]
Probably the same as this: https://github.com/ChurchApps/FreeShow/issues/998
@yurividal Do you have any idea what the issue could be and how to debug it? It might be related to the NDI package..

**Comment by yurividal** [comment]
I tried updating NDI to latest version, but that didn't help. Sorry I wasn't aware of the other report. Seems like it's the same issue
