### ISSUE TITLE
Option to Override “Override Slides with Template” for a Single Show

### ISSUE THREAD

**Issue by Lpwmack17** [ChurchApps/FreeShow#1062]
Description:
I have encountered a challenge while using the “Override Slides with Template” option in FreeShow.

Use Case:
For certain shows, such as announcements, I need the slides to appear correctly both on the livestream and on the congregation screen. However, the current behavior of “Override Slides with Template” applies the template’s layout universally, including any overlays or pictures in my slides. This results in unwanted black stripes (designed for song lyrics) showing up, which disrupts the intended display for these specific slides.

Request:
Would it be possible to implement a way to override or bypass the “Override Slides with Template” option on a per-show basis? This would allow more flexibility for slides that aren’t strictly tied to the template’s layout, like announcements or image overlays, while still keeping the template intact for other elements like song lyrics.

This feature would greatly improve usability in scenarios where diverse slide types are used.
https://github.com/user-attachments/assets/45ebd925-611c-486d-ac13-a5b350a23405

[![image](https://github.com/user-attachments/assets/8c248d07-ec25-4d00-be4c-cc09aef84528)]()

**Comment by vassbo** [comment]
Create a new style without a template and create an action in that specific show to change the output style to the one without template!
