### ISSUE TITLE
Music playlist stops at the end of the first item

### ISSUE THREAD

**Issue by gyuris** [ChurchApps/FreeShow#1066]
**Describe the bug**
Music playlist stops at the end of the first item. Does not jump to any other item. Music layer remains on, but without sound.

**Reproducing**
1. Create a new music playlist.
2. Play it. 
3. Wait until the end of the first song...

**Version**
 - OS: Windows
 - FreeShow Version: 1.3.2. Previous 1.3.1 works well.

**Comment by colanct** [comment]
I am also experiencing the same issue. However, it is not consistently reproduceable.

**Comment by colanct** [comment]
Thank you.  It is fine with cross fade = 0.
