### ISSUE TITLE
Audio playlist crossfade is not honoured when duration is set to zero and playlist is advanced manually 

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#1068]
Audio playlist crossfade is not honoured when duration is set to zero and playlist is advanced manually.
Functions correctly with any duration >0.

v1.3.2
Win10

**Comment by colanct** [comment]
This issue still occurs in v1.3.3-beta.1.

When crossfade is set to zero, and:
 -  the playlist is advanced manually, the actual crossfade is around 6 seconds.
 - the playlist advances automatically, the defined crossfade is applied correctly.

When the defined crossfade is >0:
-  the applied crossfade is correct for both manual and auto advancing.

**Comment by vassbo** [comment]
Thanks. Got it fixed!

**Comment by colanct** [comment]
Confirmed fixed in v1.3.3-beta.2.
Thank you.
