### ISSUE TITLE
Spaces not working in RemoteShow Search when "Quick Show" enabled

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#1069]
**Describe the bug**
In the remote show in 1.3.0 and 1.3.1, I noticed that whenever "quick show" was enabled, spaces weren't added when I was searching.

After updating my church's setup to 1.3.2, I noticed that when searching songs in RemoteShow on Chrome (via an iOS client) the spacebar had no effect, and there wouldn't be any spaces added to my searches. Thankfully, that didn't affect the functionality of the search service, but it is an error nonetheless.

**Reproducing**
Use RemoteShow on any 1.3 variant and try to search with "Quick Show" enabled.

**Additional context**
I have no idea what the "Quick Show" toggle is supposed to do, but it seems to be breaking functionality. What's the deal with that feature?

**Comment by vassbo** [comment]
Great, if you do not use it just leave it disabled.
https://freeshow.app/docs/remote#search-shows

**Comment by vassbo** [comment]
Spaces does not work at all in the search 1.3.2. I got that fixed.

But the search result matching does not count for the spaces, so you can search normally without any spaces and it should work normally.
