### ISSUE TITLE
VideoPsalm imports

### ISSUE THREAD

**Issue by SAvolunteer** [ChurchApps/FreeShow#1070]
Probably not a bug, but I'm unable to import from Videopsalm. The instruction is to find .vpc or .json file, but the only files of these types are;
CommonSettings.json
FontStyles.json
Meta.json
Settings.json

The songbooks and bibles don't display a file type, but appear to be .vpc files. However nothing happens when I select these.

Screenshot:    https://github.com/user-attachments/assets/2e87602c-6ee0-4d31-ad93-be4ca4e08624

 - OS: Windows 10
 - FreeShow Version: 1.3.2

**Comment by vassbo** [comment]
The files in the screenshot are probably .vpc files, could you send them over to dev@freeshow.app? And I'll check out the issue.

**Comment by SAvolunteer** [comment]
Hi Kristoffer, thankyou for your prompt response. I'm interested in using FreeShow because of its templates and overlays features.

I'm attaching all the Song and Bible files we use with VideoPsalm at church.

On a different topic, can you tell me how I can add a logo (file also attached) to the corner of my slides. An overlay which did this would be perfect so I can add the logo to media files as well as songs and scriptures.

Many thanks for your help.
Bob

**Comment by vassbo** [comment]
You can't attach files to the GitHub email system, please send them to this email: dev@freeshow.app

You can create an overlay with the logo, right click it and choose "Lock to output" to make sure the logo stays active always.

**Comment by SAvolunteer** [comment]
Sorry Kristoffer, I was rushing to send you the files before I left for a hospital appointment and not really paying attention.  I'll resend to the correct email when I get back
Bob

⁣Get BlueMail for Android ​
