### ISSUE TITLE
Auto Focus Search on Scripture Drawer Toggled

### ISSUE THREAD

**Issue by chalamministries** [ChurchApps/FreeShow#1073]
**Describe the feature**
Go ahead and focus on the scripture search box when the scripture drawer is selected. I dont think it would hurt that it gets focued because you would click out of it when you click on the book

**Comment by vassbo** [comment]
You can simply press CTRL/CMD + F to focus on the search box!

This should not be done as letter shortcuts are used to trigger actions/slides etc., and this would make it inconsistent with the other drawer tabs. This will also make navigating the current sohw I did have it auto focus on the search box
