### ISSUE TITLE
Reset/Restart Timer Automatically or from the API

### ISSUE THREAD

**Issue by mwb9aa** [ChurchApps/FreeShow#1078]
**Describe the feature**
I would like to be able to have a timer reset automatically when it ends or be able to call a timer reset by creating an action/use the API.
Last week, I needed a two-minute timer several times during service and had to click the reset button on the Functions->Timers pages for the timer.

I could have created multiple timers, but that seemed redundant if the time was going to be the same.

I also could see for minute-to-win-it style games where the same timer is reused by multiple slides.

**Additional context**
The API allows starting, pausing, and stopping timers, but not resetting a timer via a call or creating an action. If done automatically, maybe having the timer reset **if** the "allow timer overflow" is not selected would work. The timer does reset if I close and reopen the program, but I don't think that is ideal.

**Comment by vassbo** [comment]
This should have worked, but it looks like it does not trigger properly at the moment, I'll check that out:
![image](https://github.com/user-attachments/assets/cfe771c0-4a85-4759-b6a4-528868bf24ab)

**Comment by vassbo** [comment]
Should work as expected here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.3-beta.1
