### ISSUE TITLE
Changes to a template won't apply

### ISSUE THREAD

**Issue by sweenu** [ChurchApps/FreeShow#1079]
**Describe the bug**
I added the number metadata to our song template and when creating a new slide, the template works perfectly but for existing slides, the new changes won't apply. I tried to "Remove template from show" and add back again and it fails. I also tried applying another template and switching back, and it still applies the old version of the template.

**Reproducing**
I don't know exactly how to reproduce the problem, however, here's a capture that shows the issue:

https://github.com/user-attachments/assets/053aece9-7fbd-432e-896d-0508ce141255

As you can see, in the first slide, without template, I can apply without issue but on the second slide, it won't budge.

**Version (Optional)**
 - OS: Tried both on Windows and Linux
 - FreeShow Version: 1.3.2

**Comment by Lpwmack17** [comment]
There should be a setting in the option style, to override the slides with your template, its called „Override Slides with template“

**Comment by sweenu** [comment]
@Lpwmack17 Still the same behavior with this option.

**Comment by vassbo** [comment]
It's because the textboxes have text content, and we don't want to override that. If you remove the old {meta_title} then the new metadata will be applied.

**Comment by vassbo** [comment]
Tip: Select all slides, and choose "Format">"Find and replace text" to quickly remove the old meta_ values.

**Comment by sweenu** [comment]
Thank you !
