### ISSUE TITLE
Additional Sort Options for Projects

### ISSUE THREAD

**Issue by jquyatt** [ChurchApps/FreeShow#1082]
**Describe the feature**
At the moment, Project items in the left panel can only be sorted by name or date, ascending. Including more options for sorting through Projects would make it easier to keep large collections of projects organized

**Additional context**
I consistently name my projects starting with the YYMMDD date scheme, and currently, sorting by Name only allows me to see earlier events first. If I could sort by Name Descending, it would properly sort project items where later dates are shown first.

**Comment by vassbo** [comment]
All right, I added sort by Name descending and modified date.
