### ISSUE TITLE
Toggle Option for House of Worship Features and Settings

### ISSUE THREAD

**Issue by jquyatt** [ChurchApps/FreeShow#1083]
**Describe the feature**
Basically borrow this feature from ProPresenter: https://support.renewedvision.com/hc/en-us/articles/360041348414-Toggling-House-of-Worship-Settings-Features#:~:text=In%20the%20initial%20%E2%80%9CWelcome%20to,Integrations%E2%80%9D%20based%20on%20your%20need.

For FreeShow, this would include the Quick Lyrics option in the New Show window, the Lyrics View option in the Show panel, the Capitalize Words option in Groups settings, etc.

**Comment by vassbo** [comment]
I don't see why you would want to disable these features?
There are many features that not everyone use, but there shouldn't be a point of hiding them.
