### ISSUE TITLE
Stuck in trigger edit menu

### ISSUE THREAD

**Issue by PavelS-CZ** [ChurchApps/FreeShow#1084]
**Describe the bug**
After I create a new Trigger, I then try to edit it AND set the value to nothing, but then I get stuck and cannot leave this window. Anywhere I try to click, nothing happens, not even the close Free Show button.

In order to fix I had to shut it down with task manager

 - FreeShow Version: [e.g. 1.3.2]
 
![obrazek](https://github.com/user-attachments/assets/607c57d0-1cf5-4c30-b63e-43f0f38f0ab3)

**Comment by PavelS-CZ** [comment]
I tried changing the "Value" but it wont affect anything.

**Comment by PavelS-CZ** [comment]
Great and now the whole freeshow wont work after restarting through task manager, it wont let me click or do anything inside the editor. Every button is now without a response

**Comment by vassbo** [comment]
Thanks, will check that out.

Please go to %AppData%/freeshow if you are on Windows, and edit the settings_synced.json file and remove any triggers here if there are any.

**Comment by vassbo** [comment]
Got this fixed for the next version! If you still experience the freeze on startup it can be fixed by following the intructions in my previous comment.
