### ISSUE TITLE
Naming issue with saving Shows to OneDrive

### ISSUE THREAD

**Issue by jquyatt** [ChurchApps/FreeShow#1086]
**Describe the bug**
When some show files are saved and the Show Location is saved within OneDrive, the file is saved with a space at the beginning of the file name, which OneDrive doesn't appreciate:
<img width="359" alt="Screenshot 2024-12-05 at 7 00 21 AM" src="https://github.com/user-attachments/assets/f29f5359-56a4-4305-9b58-ca19f474a096">

**Reproducing**
- Set up Show save location in your OneDrive directory
- Create a new project
- Add a new unnamed show. It should appear in the Project panel named as "Unnamed", grayed out
- Add another new unnamed show. It should appear in the Project panel named "2"
- Save within FreeShow
- Microsoft OneDrive Sync should ask user to rename 2.show 

**Version (Optional)**
 - OS: macOS Sonoma 14.7 (23H124)
 - FreeShow Version: macOS Sonoma 14.7 (23H124)

**Comment by vassbo** [comment]
Looks like it starts with a space. Will fix that.

**Comment by vassbo** [comment]
You can delete that, I actually changed it so all new shows with no name will start with "Unnamed" before the number, I think that should resolve this, not sure why this got a space in your case.
