### ISSUE TITLE
macOS Sequoia 15.1.1 | Start Actions | Audio Streams 

### ISSUE THREAD

**Issue by MrDownie** [ChurchApps/FreeShow#1088]
In macOS Sequoia, the start action for an audio stream does not trigger the stream to start.

Other actions actions like start playlist work fine, and audio streams work fine when triggered manually. 

I was hoping another user that has upgraded to Sequoia might see if the trigger is working for them. 

macOS Sequoia 15.1.1 
Freeshow Version 1.3.2 (1.3.2)

Thank you.

**Comment by vassbo** [comment]
Thank you! Got this fixed.

**Comment by MrDownie** [comment]
Thank you!
