### ISSUE TITLE
change in font color

### ISSUE THREAD

**Issue by CCR2024** [ChurchApps/FreeShow#1090]
When I change the color of the font on slides of music words, for example i change from white to a dark font.  and then i send it to primary front It doesn't change the color on the front tv

**Comment by CCR2024** [comment]
I am not sure ? How do I know ? When I click on outputs it gives me two.
Obs YouTube and  primary front!
It sends the slide to the primary front!
But wrong color if I change color!

**Comment by CCR2024** [comment]
My guess is that it is turned on when Micheal set it all up.  Can you tell
me where that is at so i can see if it is on?
Janet

**Comment by vassbo** [comment]
Probably a custom template as @Dcanadian mentioned.
See this: https://github.com/ChurchApps/FreeShow/issues/999#issuecomment-2467387881
