### ISSUE TITLE
OSC support 

### ISSUE THREAD

**Issue by zax71** [ChurchApps/FreeShow#1091]
**Describe the feature**
I would like to use FreeShow in a professional setting using Open Sound Control (sent via open stage control) to change slides and show/hide elements for a game show in sync with lighting from an EOS desk. OSC seems like the best way to achieve this and is supported by most other professional software too.
**Additional context**
`/freeshow/slide/<id>`
`/freeshow/visible/<slide id>/<object>/<state>`

those would be all that I’d use. But I’m sure other commands would be of great use to others

**Comment by vassbo** [comment]
FreeShow supports http REST commands, https://freeshow.app/api
Looks like it's possible to use that: https://openstagecontrol.discourse.group/t/what-is-the-best-way-to-call-a-rest-api/999
FreeShow is also integrated into Bitfocus Companion.
Would that work for you?

I don't fully get what the two different commands you mentioned would do..
Would you mind explaining what the different values mean?

**Comment by zax71** [comment]
Ah yeah that does seem like it could work.” - albeit partially jankily. Those commands I suggested were to advance to the next slide/scene and another to show/hide an element in a scene

**Comment by vassbo** [comment]
All right, because I guess it would have to look like this in that case:
Next slide: `/freeshow/slide/next`
Play specific slide: `/freeshow/show/<id>/slide/<slide id>`
Clear all: `/freeshow/clear`

I guess it would make sense to create a wrapper converting to the existing API.

**Comment by vassbo** [comment]
I added support for OSC, see this file for available actions with prefix `/freeshow`: https://github.com/ChurchApps/FreeShow/blob/5963efb17a3146c6a5039eb3600d8afdd5b50590/src/frontend/components/actions/apiOSC.ts
Feel free to customize with actions and open a pull request.

All you need to do is set send to the correct ip/port:
![image](https://github.com/user-attachments/assets/c7a15050-1744-4102-81c3-dd0f26beb63c)

And set the address:
![image](https://github.com/user-attachments/assets/2bb30a80-baa3-4ce6-ad56-3f73f93067c9)

A few examples:
```
/show/<id>/start
/slide/next
/clear/all
```

**Comment by zax71** [comment]
Cool! That was real fast xD

**Comment by TPaulManohar** [comment]
Interesting,  Please add OSC functionality to main release.

This can help us control Freeshow very professional ways. Even we can use TouchOSC to control.

**Comment by zax71** [comment]
I ended up making a custom Godot game so it’s good to hear that someone can make use of this feature!

**Comment by donert** [comment]
I’d like to see it used in the opposite direction … being able to emit OSC. This is the feature request I made for ProP and am still waiting. 
I request that you add the ability to originate OSC commands from ProPresenter as a new class of ‘Communication’. 

The communication device definition should allow for the singular definition of network parameters (eg destination IP address) and a set of message templates that can be emitted by this device. These templates shall contain variable placeholders that will be have value substitutions when adding as an action to a slide or macro. (An optional feature on the device configuration UI would be a “where used” map which would report on where each template is used).

When adding and action to a slide or macro, you would be able to pick a device, one of the defined templates, and supply the values for the variables for that template.   

Templates should be exportable and importable. 

This feature would enable me to simplify my production environment, and I think many others would benefit from this as well.

**Comment by vassbo** [comment]
@TPaulManohar OCS already working in production, maybe unclear but the WebSocket/REST option must be enabled in the Connection settings!

@donert Sounds interesting, I'll consider it.
I guess we can send data directly from an action, similar to how we can send HTTPS-Requests (screenshot).
But the action would be "Emit OSC", and you can choose from a predefined set of outputs/listeners and set a custom value that should be sent, or choose a message from a predefined set of values for that output. Did I get it right?

![image](https://github.com/user-attachments/assets/b9ca4349-9ab1-4104-9dd0-50adac2fd7df)

**Comment by TPaulManohar** [comment]
@vassbo , We enabled Websocket/Rest in connection Settings, But we use Bitfocus Companion app. We didn't tried that Freeshow as ability that OSC is enabled in the same port "5505". 

Let me check that in the same port "5505" will work OSC commands.

@vassbo Here we if need new custom OSC command, then we need to create new action for custom OSC commands in freeshow.

**Comment by vassbo** [comment]
@donert Please check out "Emitters" in the latest pre-release: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.4-beta.1

You should be able to do everything you described! Can be found in the bottom right corner in Functions>Actions. Then you can set a "Emit data" action with the chosen "Emitter".
![image](https://github.com/user-attachments/assets/d2ecff78-69c4-4b4d-833f-5a2d0bd8e45b)

**Comment by TPaulManohar** [comment]
Hi @vassbo 

I'm testing OSC with using TouchOSC software [https://hexler.net/touchosc](https://hexler.net/touchosc ) , And I enabled the port 5505.  Then I start connected with `ip:port` with send OSC command `/freeshow/clear/all `  & `/freeshow/clear` Freeshow app is not responding to those OSC command.

Did I missed some here..?

Connection on TouchOSC
<img width="553" alt="Screenshot 2025-01-13 at 4 45 46 PM" src="https://github.com/user-attachments/assets/e122fc4f-a028-425c-b73f-d0d06d1086a6" />


OSC Command
<img width="1439" alt="Screenshot 2025-01-13 at 4 46 47 PM" src="https://github.com/user-attachments/assets/7d50e146-e7e5-461a-9115-71f830750e93" />

Once we trigger that OSC Command `/freeshow/clear/all` & `/freeshow/clear` and back  freeshow app didn't cleared.

Freeshow Connections Settings
<img width="1439" alt="Screenshot 2025-01-13 at 4 56 23 PM" src="https://github.com/user-attachments/assets/c86f0bcb-0898-40e9-a7a4-3046592515e7" />

Can you help me over here..!!

**Comment by vassbo** [comment]
The host should be 127.0.0.1 / localhost if you are running both programs on the same computer.

**Comment by TPaulManohar** [comment]
@vassbo, `Localhost or 127.0.0.1 `working, If I need to send OSC message on Network then I can use the IP address of that computer which run the Freeshow app.

**Comment by vassbo** [comment]
Correct!

**Comment by TPaulManohar** [comment]
Thanks @vassbo

**Comment by TPaulManohar** [comment]
@vassbo Above one scenario,  I ran TouchOSC & Freeshow are on same computer, There I used `127.0.0.1:5505` that one work prefect.

I'm tested on Network, Freeshow app is running on Different computer(192.168.5.219) and triggering OSC Commands from iPad(192.168.5.112) using TouchOSC app , thats not working.

**Comment by vassbo** [comment]
Make sure the firewall and router allows the connection. I can't help you any more with that!

**Comment by TPaulManohar** [comment]
@vassbo  I use other OSC app in same network those are working perfectly. Let me check where that issue getting.

**Comment by TPaulManohar** [comment]
@vassbo I found the issue, 

When i sending the OSC Command from one computer(192.168.5.249) to another Freeshow running computer(192.168.5.216) at port 5505 on network it is not working. OSC only working on localhost `127.0.0.1:5505`

![Freeshow network Issue](https://github.com/user-attachments/assets/38b14cbe-a687-43fb-a0ba-1c985f158f5f)


I used this software to debug [https://hexler.net/protokol](url) OSC commands whether it receiving to Freeshow running computer, Its receiving, but Freeshow OSC is  not listening. 

In [https://hexler.net/protokol](url) Protokol app I forward request from 192.168.5.249 to 127.0.0.1 then only its working.

![Protokol](https://github.com/user-attachments/assets/e24155b0-3cf9-44b9-9441-15a3fd3920f5)

Forward Setting on Protokol
![Protokol Setting](https://github.com/user-attachments/assets/b0dc6672-dfa6-475e-9a1e-c41ed621a75f)


I think In OSC.api code, we need to listen OSC call from, like this `0.0.0.0:5505` instead of `127.0.0.1:5505` and i tested bitfocus companion app that one working with this ip `192.168.5.216:5505`

Please can you check this

Thanks,
Paul.

**Comment by vassbo** [comment]
Thanks @TPaulManohar. That makes sense, the OSC package I used listened on 127.0.0.1 by default, so I changed it to listen on 0.0.0.0 and that should hopefully work.

**Comment by TPaulManohar** [comment]
Hi @vassbo ,

In v1.3.4- beta2, OSC commands receiving  on 0.0.0.0:5505. Is there possibility that OSC can also send back commands as feedback.

**Comment by vassbo** [comment]
@TPaulManohar You can use the "Emit data" to send OSC commands from FreeShow.

**Comment by SeriousRick** [comment]
Google AI result seemed to imply an incoming OSC message /freeshow/slide/5 would trigger Slide 5, but that doesn't seem to work. Here and at links above, I only see /slide/next and /slide/previous. Should triggering slide by integer work, or is that false info? If not, would it be possible to implement this?

**Comment by vassbo** [comment]
You can't. This is what's currently possible: https://github.com/ChurchApps/FreeShow/blob/main/src/frontend/components/actions/apiOSC.ts

I guess that's possible.

**Comment by vassbo** [comment]
Should work in the next version: https://github.com/ChurchApps/FreeShow/commit/87a19a731f3f533dea84db2d0607a1451d8c57e6
