### ISSUE TITLE
PlanningCenter Integration Discussion

### ISSUE THREAD

**Issue by Auxority** [ChurchApps/FreeShow#1093]
Hey there, first of all, thanks for building this amazing Open-Source project. I love that the focus is not on making as much profit as possible, but instead on helping churches with their services to spread the gospel.

We recently switched to PlanningCenter, because there wasn’t an open-source alternative that worked for our worship leaders. But with all the images, videos, and song lyrics during our services we started looking for a simpler solution, to make it easier for our tech team.

I recently built an integration for YouTube in PlanningCenter using a TamperMonkey script (on my GitHub profile), so our tech team can create a new stream from PlanningCenter in one click. Now that I know how their OAuth2 flow works, I was wondering whether I could attempt to create a PlanningCenter integration for FreeShow.

This feature would allow us to get all the assets and lyrics from PlanningCenter into FreeShow in one click (or a couple if they still need to authenticate). Saving more time for our tech team, and helping the congregation and worship team by providing the correct lyrics and images/videos at the right time.

Now I’d like to ask, are there any objections to me building this integration? Or is there anyone out there willing to help?

**Comment by mbyrdLCS** [comment]
I think that sounds awesome! I just wanted to make sure you had a chance to check out our alternative to Planning Center: https://chums.org/. It’s open-source and could greatly benefit from a church like yours using it. If your worship guy is looking for services function we have that it is just called plans.

**Comment by Auxority** [comment]
Thanks! If the tech team agrees with the switch to FreeShow, then I'll start building the integration :)

I just checked chums out, and it works well. But for now we'll keep using PlanningCenter because of the CCLI SongSelect integration and other features (like one click transposing, block out dates, automatic scheduling) we would miss out on. I hope that we would be able to use it in a couple of years (when more missing features have been added and when I have time to add the remaining missing features), but for now we need an intermediate solution.

**Comment by vassbo** [comment]
Awesome @Auxority!
That would be nice to have if it works well.

More people have also requested this feature: https://github.com/ChurchApps/FreeShow/issues/333

**Comment by vassbo** [comment]
All right, it can be closed! :)

**Comment by thebiblelover7** [comment]
@mbyrdLCS 
> I think that sounds awesome! I just wanted to make sure you had a chance to check out our alternative to Planning Center: https://chums.org/. It’s open-source and could greatly benefit from a church like yours using it. If your worship guy is looking for services function we have that it is just called plans.

A little late to the discussion, but I don't see the ability to plan a service like Planning Center with specific songs, sermon, etc. I only see the ability to select roles and positions... am I looking in the wrong place?

**Comment by mbyrdLCS** [comment]
We are currently building this out. Will be coming in an update soon.

**Comment by Auxority** [comment]
Oh that's awesome to hear! If you need any help with the OAuth2 flow, let me know.

**Comment by thebiblelover7** [comment]
Let us know if possible :)! I'd love to test it, etc.

**Comment by vassbo** [comment]
Try it out: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.6-beta.1
https://freeshow.app/docs/faq#planning-center-integration

**Comment by Auxority** [comment]
Awesome! Works great so far. Of course there are some things that could be improved, but as a first version this is really really cool!

**Comment by vassbo** [comment]
Cool! Feel free to make changes and send a PR as you find things you want changed.
