### ISSUE TITLE
How to import Bible in Standard Jet DB or XML BibleShow 

### ISSUE THREAD

**Issue by mickythekiller** [ChurchApps/FreeShow#1095]
How to import Bible in Standard Jet DB BibleShow 
I can convert it in XLM but import doesn't work please
thanks
`<?xml version="1.0"?>
<LSG1910>
 <Bible>
  <RECORD>
   <ID Type="Long Integer">1</ID>
   <Book Type="Integer">1</Book>
   <Chapter Type="Integer">1</Chapter>
   <Verse Type="Integer">1</Verse>
   <Scripture Type="Memo">Au commencement, Dieu créa les cieux et la terre.&lt;p&gt;</Scripture>
   <Sync Type="Text">
   </Sync>
  </RECORD>
  <RECORD>`

**Comment by vassbo** [comment]
That format is not supported, you can try to use this: https://github.com/vassbo/bible-converter
This is the XML format FreeShow uses: https://github.com/vassbo/json-bible
