### ISSUE TITLE
Video media playback automatically mutes audio

### ISSUE THREAD

**Issue by NachtaktiverHalbaffe** [ChurchApps/FreeShow#1098]
**Describe the bug**
When I start playback for video media, on windows the audio is automatically muted. I have to enable Audio every time after I started playback.

This only occurs on windows. I also have Linux, there it works fine with same settings 

**Reproducing**
- Add Video to project
- Start playback of video via clicking on the video thumbnail

**Screenshots (Optional)**
State when starting playback:
![image](https://github.com/user-attachments/assets/9063aadc-a0b0-4e4b-aabe-a00eec7b171d)

Expected state:
![image](https://github.com/user-attachments/assets/3af5c5a2-44ca-42d7-a0dd-4d5d34c7a025)

(
The screenshots are both from Linux and are only for demonstration purposes)
**Version (Optional)**
 - OS: Windows
 - FreeShow Version: 1.3.2

**Additional context**

**Comment by vassbo** [comment]
I can't reproduce, make sure the output window is active when playing the video.
It should never be muted when playing from a project..

**Comment by NachtaktiverHalbaffe** [comment]
I recorded a Screen-Capture where I also show my settings in the end. This should show the bug and maybe it helps for idenitfying the problem

https://github.com/user-attachments/assets/8413d1aa-7d4b-4ed4-9685-599a2367b25f

**Comment by vassbo** [comment]
Thank you. I could not recreate the issue with the same settings..
This issue is not related to the Windows version itself, but must be something else..
Not sure why this happens for you on this specific system.

Would you like to send over all of the data files, so I can see if there is something with this setup?
Settings>Other>"Backup everything", then send the .json files to dev@freeshow.app

**Comment by NachtaktiverHalbaffe** [comment]
You should have a Mail in the Inbox with the backup files

**Comment by vassbo** [comment]
Thank you! I found the issue, you had a second hidden key output that received the audio.
Will work in the next update, or you can update the outputs in settings.json file.

**Comment by NachtaktiverHalbaffe** [comment]
Will the next update before 23rd December? Can you otherwise specify the key/place in the settings which I must override if you have the time? I have a christmas worship event there and would be helpful if I get it fixed until there

**Comment by vassbo** [comment]
It will come in a few days.

**Comment by vassbo** [comment]
Btw, It's already working in the latest beta that came 6 days ago: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.3-beta.2
