### ISSUE TITLE
Error in video output and font enhancement

### ISSUE THREAD

**Issue by marcosmolina7** [ChurchApps/FreeShow#1100]
**Describe the bug**
ERROR
Starting with the error, in the first video I show how I have everything configured in this final computer, because I do tests first in my computer to later pass it to this one that is seen in the video 1, it is worth mentioning that this error does not occur with my computer (of tests), only in this other one.

The error arises when I configure the timer that we have as a church which is a video, that when it finishes, it starts or follows the second video which is the welcome video, but in the NDI output that has been configured, this change is not made, only as if it wanted to do it but it does not do it at the end, but in the Main output, it does it. As I show in video 1, everything is well configured, according to me, but I still get comments. It should be noted that although I have advanced the timer, it does not matter if I let it run out, and also mention that the action that when the first one finishes and the second one starts automatically no longer occurs if it is removed or if you click on the clear button in the texts button.

IMPROVE
I have been testing the program which is very good, and I am glad that we are not stagnating but keep improving it. Now, in video 2, I show how I have also configured an NDI output with transparency and that it has the format commonly used to display the lyrics of the song but with a background line. Everything is fine, but I feel that it is annoying that the NDI input that I mention is being put and removed in the mere transmission, because when putting a slide without text, it continues putting the line, or that when a video is put through a slide and the box where the text or the lyrics are put is removed, and still continues throwing the background lines, then I think it would be good to configure the background line, only when there are only lyrics. Also, if it is me who is not doing it right, please let me know.

**Reproducing**
You can configure 3 video outputs, the main one (the one that goes to a screen), the second one that is a copy of the main one with transparency (I do it this way because the format or aspect ratio of the first one is not 16:9) and the third one that is the one of the lyrics with only 2 lines for the songs and with transparency. The two NDI outputs, I have them with the option to hide in configurations.

**Screenshots (Optional)**
Video 1 (ERROR)
https://drive.google.com/file/d/1fH-AfS2GWfjGsdPsX_QLZGh5mDtynYjt/view?usp=sharing

Video 2 (IMPROVE)
https://drive.google.com/file/d/1r8mfcpkub3lzDRMuqZOJcdZ8itxtJOyT/view?usp=sharing

**Version (Optional)**
 - OS: Window 11
 - FreeShow Version: 1.3.2

**Comment by vassbo** [comment]
Thank you!

Let me try to fix the video "Next when media finished" issue on the second output.
And let me fix the textbox showing up in your output with a custom template when there should be no textbox.
