### ISSUE TITLE
wants to know Fsb file import code.

### ISSUE THREAD

**Issue by sachinlobo11** [ChurchApps/FreeShow#1101]
Question: I have a fsb file externaly. I have a encrypted fsb file and I wants to import. only verses are encrypted. I wanted develop a decryption module for my fsb file. Which module is responsible for this?. Can Anyone helpme with explaining.
I see that fsb files stored in documents folder.

**Comment by sachinlobo11** [comment]
Thanks but I know how to import bible and json format. 

```
{
    "name": "Bible Name",
    "metadata": { "publisher": "" },
    "books": [
        {
            "number": 1,
            "name": "Genesis",
            "chapters": [
                {
                    "number": 1,
                    "verses": [
                        {
                            "number": 1,
                            "text": "gffgfbchgcu77t478cbuh"     /// Encrypted text
                        },
                        ...
                    ]

```
https://github.com/vassbo/json-bible/blob/b58d688eac396b428f901ae19de39fe14d4fd2a1/index.ts#L45

I am planing to develop decyption module. I know how to decrypt it. But I dont know where to place my code. I know where toplace code in vassbo's repo. But in this FreeShow I cant find .


So I am particularly [Refereng to this code ]( https://github.com/vassbo/json-bible/blob/b58d688eac396b428f901ae19de39fe14d4fd2a1/index.ts#L45) Repo contains logic/algorithm to read. Where have been implemented  the logic in FreeShow module?

 `default async function Bible(bibleOrPath: Bible | string) `=> This one is esponsible for Reading content from index.ts in json-bible repo. But which function is responsible in Freeshow?

**Comment by vassbo** [comment]
Okay, but why is it encrypted? It should be plain text. If it's not plain text the issue is in the file itself, and you can simply create a script to decrypt the text in the JSON file.
