### ISSUE TITLE
Edge Blending?

### ISSUE THREAD

**Issue by emassen** [ChurchApps/FreeShow#1102]
Hi,

I have not found it and I believe this does not exist yet, is there any idea that this exists in software one day?

**Comment by vassbo** [comment]
I thought this would be hard, but it was actually quite easy with CSS `-webkit-mask-image`

What you can do if you have two HDMI outputs to two projectors, you can simply create one output and resize it to expand across two screens. And then from the next version there will be an "Edge blending" option in the "Choose screen" popup, and then choose the area that should be blended.
