### ISSUE TITLE
Ability to Add Video With Transparent Background

### ISSUE THREAD

**Issue by christokarna** [ChurchApps/FreeShow#1103]
Hi, i've been using this software for a while and it's great software and I'm grateful for the people that working on this software.

Basically, I want to upgrade the lyrics to the next step which is using video lyrics, I wanted to add a video with a transparent background and add another video as the background, but sadly it's not possible, and the video won't even play. 
Does the software have this kind of thing? or do I need to use a specific extension for this to happen?

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/295#issuecomment-1822958904
