### ISSUE TITLE
[Feature Request] Clear-to-Logo action button

### ISSUE THREAD

**Issue by joelabs** [ChurchApps/FreeShow#1104]
Advanced apologies if I missed an existing similar item from searching.

Feature request of a button similar to the "Clear All" but 
a) clear all text and background layers, then
b) projects a designated "logo" image to the background layer, path/to/image configured in the application settings.  

When we don't want to project any actual content but not leave the display blank, the organization's logo display is handy, and having a pre-configured designated action button saves operator from searching the Media bin.

The other software suite my team has migrated from had this kind of button, and through our rather impromptu transition its about the only feature we're "missing", and a non-critical one at that.   Thank you for continued development on this software suite!  I had evaluated v1.2.1 a while back but dropping in v1.3.2 removed all prior hesitations and is rocking along.

**Comment by vassbo** [comment]
Great! Simply add a background media to styles in the settings, and toggle "Clear style background when slide is active" so this will image/logo show up when pressing "Clear all".

You can further automate different styles with actions to have different logos etc.
