### ISSUE TITLE
Planning Center service integration

### ISSUE THREAD

**Issue by snicolai** [ChurchApps/FreeShow#1109]
Planning center can be used for planning a service in a distributed fashion.  It would be useful to have FreeShow download a service similar to how ProPresenter can.

Details of the Planning Center API are at:
https://www.planningcenter.com/developers

Planning Center also has an integration with CCLI.  I don't know if this would be a useful workaround for the CCLI API being discontinued.

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/333#issuecomment-1848955899
https://github.com/ChurchApps/FreeShow/issues/1093#issue-2725227003

**Comment by vassbo** [comment]
Try out the Planning Center integration in the latest pre-release: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.6-beta.1
Docs: https://freeshow.app/docs/faq#planning-center-integration

**Comment by jerm00** [comment]
Thanks for adding this! The account linked easily, and a new category appeared in shows, but it's empty. The planning center song titles are identical to the corresponding FreeShow files, I assume it's supposed to place them in that category if they're in the upcoming Sunday service?

**Comment by vassbo** [comment]
It gets any services lists one week ahead of time, so if you don't have one no projects/shows will be added.
