### ISSUE TITLE
Allow lables and folders to be imported on the initial setup - read from data folder

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#1112]
Hi. I just installed freeshow on a new computer. 
My Data folder lives in a google drive, which is synced to the old computer.

When i installed freeshow for the first time in the new computer, it prompted me for my data folder.
I pointed it to the Data folder in google drive.
It hung for a minute or two (i think because i have too many songs, it was reading them all), and eventually i got all the songs.
Nice.

But, the tags, folders etc didn't come with the songs.

![image](https://github.com/user-attachments/assets/257c3714-1d68-4036-bcf8-4007d419f66d)

it would be very nice if the tags, folders and even the projects lived in the data folder, where we can sync between different devices.

**Comment by yurividal** [comment]
Same for templates, and Scriptures. Nothing was imported to the new computer. They remained the default ones. 

![image](https://github.com/user-attachments/assets/b8fc4ffb-9a04-43e8-9173-d931def460f6)

**Comment by mwb9aa** [comment]
I had that the same thing with 1.3.3 Beta 2. I installed on a new computer, but no labels or groups came with the transfer.

**Comment by vassbo** [comment]
It should sync with the built in Google Drive option, but when using a third party sync you need to also sync the user data, this can be done by enabling this:
![image](https://github.com/user-attachments/assets/341054d5-3b11-4316-82fc-c882236850bd)

Alternatively a backup and import also includes everything.

**Comment by yurividal** [comment]
Thanks @vassbo 

May i suggest that this option (save user settings in data folder) be displayed in the initial pop-up, when the user first installs?

**Comment by vassbo** [comment]
That is an option, but I think most users will not know what that does anyway, and as it's not a common setting, I don't think it makes sense in the initial popup. I hope the more advanced users using custom sync should be able to find that in the settings.

It is documented at least: https://freeshow.app/docs/data

**Comment by vassbo** [comment]
I don't think it matters as this setting is for more advanced users, and the program automatically takes a backup when you toggle the option in case it overwrites any data. If the user plan on using it then it can simply be turned on when setting up the new computer, before importing any data.

**Comment by vassbo** [comment]
The way the system works at the moment means it would write over the files regardless if this option was enabled when initalized or not.

**Comment by vassbo** [comment]
We could simply ask the user if the data should be overwritten or not if there is existing data.

**Comment by yurividal** [comment]
Yes, that would be cool. At least I can safely explain to my team how to
get an exact copy of Freeshow from church on their devices

**Comment by yurividal** [comment]
NICE!
