### ISSUE TITLE
update to transitions

### ISSUE THREAD

**Issue by lwallace22** [ChurchApps/FreeShow#1115]
**Describe the feature**
A clear and concise description of what you would like too add/change.
Optionally describe why this feature is needed.

on the transitions between slides with the text it's forcing you to have an in between transition or the transitions between slides dont work, in pro they have to where an in between is not needed just an in an out and seems must more efficient and time saving especially for the fast songs churches may do. Is there any way to make not having to have an in between transition an option for text and transitions not act or look as if they not working??

**Additional context**
<img width="560" alt="Screenshot 2024-12-17 102145" src="https://github.com/user-attachments/assets/7b8d783d-915a-4858-b422-65f22af62a9a" />

**Comment by vassbo** [comment]
Not sure I get what you mean, you don't need to set the between transition, but it's optional in case someone might need it.

**Comment by lwallace22** [comment]
I have tried that and I don’t have the in between unselected the
transitions start glitching and not working at all would it be helpful to
send you a recording ?

**Comment by vassbo** [comment]
Okay, is it related to this?: https://github.com/ChurchApps/FreeShow/issues/1006

If not you can send a recording, that will help.

**Comment by lwallace22** [comment]
so are you telling me on the output screen it should transition fine even
though acting up in computer i see no results

**Comment by lwallace22** [comment]
20241221-1502-52.5274791.mp4
<https://drive.google.com/file/d/1K4-RdslZ78KGLwvfB0fFlWf3oSB4w0_q/view?usp=drive_web>
