### ISSUE TITLE
Shows disappeared.

### ISSUE THREAD

**Issue by K8lynd** [ChurchApps/FreeShow#1116]
I created about 15 shows yesterday and when I opened FreeShow today they were gone and my Project was also gone.

**Version**
 - OS: [Windows 11 Home]
 - FreeShow Version: [v1.3.2]

**Comment by vassbo** [comment]
Yeah, please check the comment from @Dcanadian.

The files should be stored in your Documents/FreeShow folder, please check there if you see anything.
If you do then go to settings>Other and make sure the paths here are pointing to the correct paths.

Also make sure you do not have any system cleaner set up that might have deleted the files.

**Comment by K8lynd** [comment]
I guess I thought it save automatically, my bad I could not find the shows but thanks for those suggestions.  My new question is, is there a way for me to few the same projects on another computer.  For example.  If I create a project on my office laptop, can I pull it up on our media computer or projecting?
