### ISSUE TITLE
Documentation regarding Template vs Layout vs Theme vs Style 

### ISSUE THREAD

**Issue by melonkernel** [ChurchApps/FreeShow#1120]
** It would be great with more information for new users how to set up their look & feel **

If would be good to have a place where information is gathered regarding how to create your custom slides for pre-meeting information, the look &  feel for songs sermons,  etc.

and an explanation on the differences between teplates, layouts, themes, styles etc..

**Comment by vassbo** [comment]
You should be able to find all the information you need in the docs: https://freeshow.app/docs

https://freeshow.app/docs/templates
https://freeshow.app/docs/layouts
https://freeshow.app/docs/styles
