### ISSUE TITLE
Please add translate names of books

### ISSUE THREAD

**Issue by stepansyusin** [ChurchApps/FreeShow#1121]
**Describe the feature**
Need translation of book titles
<img width="1367" alt="Снимок экрана 2024-12-21 в 02 38 43" src="https://github.com/user-attachments/assets/15275ca9-9efe-468b-9072-974513de2787" />

P.s. Thank you very much for the great program
The Bible here is much more convenient than in ProPresenter

**Comment by vassbo** [comment]
Thank you! 😊

You can change it by editing the Bible file. Please see this: https://github.com/ChurchApps/FreeShow/issues/581

**Comment by stepansyusin** [comment]
Thank you very much!
Be blessed!
