### ISSUE TITLE
MP4 support

### ISSUE THREAD

**Issue by frnchesko178** [ChurchApps/FreeShow#1123]
It is required to add support for video output in MP4 format, I do not understand why this basic video format is still not supported by this program.

Our church uses animated backgrounds for texts in MP4 format, but when we wanted to try switching to this application, we came across the fact that this application does not support our backgrounds in MP4, and writes: "unsupported video",
In this regard, I ask you to add support for this format.

**Comment by chalamministries** [comment]
It does support mp4 format. All of our backgrounds are mp4 and it works fine. Can you maybe upload one of your backgrounds from dropbox or something so I can look at its metadata?

Also what version do you have and where did you get your backgrounds?

**Comment by Phantom-Matt** [comment]
Hi. FreeShow actually supports MP4 videos but currently can't work very well with H265/HEVC videos. You can check on any media player that has an "Media Info" option (VLC, for example, has this function).

Using any decoding app (like a video converter) you can change the decoding process to H264 and the video should work.

**Comment by frnchesko178** [comment]
https://dropmefiles.com/NxRgL
Here is the file that I am trying to use, but the application refuses to support it.

Application version 1,3,3

> Он поддерживает формат mp4. Все наши фоны в формате mp4, и он отлично работает. Не могли бы вы загрузить один из ваших фонов с Dropbox или откуда-нибудь ещё, чтобы я мог посмотреть его метаданные?
> 
> Также, какая у вас версия и откуда вы взяли свои фоны?
