### ISSUE TITLE
Slide text colors

### ISSUE THREAD

**Issue by CCR2024** [ChurchApps/FreeShow#1125]
When Freeshow was set up for me I believe that the output for font was set to white and I am trying to get it to change and it won't. 
So my question is how do you change it if I am doing song slides and need to change to a different color.  I change it but when it casts it to screen it goes back to white. 

Also - as a new user - when i click on the settings wheel and output I had the hardest time seeing the bottom three outputs.  I kept fighting it and fighting it and then finally I saw that I was on the wrong output.  is there any way you can integrate a feature at the top next to outputs where you would choose the output there?  I just think at the bottom it is not user friendly.

**Comment by vassbo** [comment]
Thanks @CCR2024, please see the comment from @Dcanadian.

In version 1.3.3 I just changed it so if you have an output style with a custom template, if the text in the template is white (default), then the text color set on the text in the slide will be used.

As the "Add" button for creating new outputs is at the bottom, I think it should be natural to assume that it's located at the bottom, this is consistent across different menus (Outputs, Styles, Theme, Layouts).

**Comment by CCR2024** [comment]
I think the problem is that it was set up so that it works with a white
font and I didn’t set it up so I don’t know how to correct that!
If I am reading  it correctly you have directions in your email that I will
have to try !
I will let you know if it works
