### ISSUE TITLE
How to integrate SyncThing media sync with FreeShow filesystem

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#1126]
**Problem Summary**
There's been a lot of talk recently in #1048 about how FreeShow's recommended Google Drive sync doesn't sync media files. I recently decided to implement the suggested workaround of using SyncThing to mirror the media folders from my church's computer to mine at home in the hopes that FreeShow would be able to "find" the files on both computers. However, even though SyncThing is working like a dream (would recommend!), FreeShow is not recognizing the media.

Just to clarify once again - the media for the shows is stored in the exact same location in the filesystem on both the computers, which both run MacOS Sequoia 15.2. The shows are synced through Google Drive. Both computers are also running v1.3.3

**Possible Solutions/Considerations**

- Does the "Media Path ID" have anything to do with this issue? I can't find much in the issues or FreeShow docs about it, so I don't really know what that does, or how to configure it.
- Since my computer has synced through Google Drive for a while without the background files, FreeShow might not want to "re-search" through my files for the media. Is there a way I can force it to look for them now that they are present on the computer? (My apologies for the non-technical language 😁)
- Should I back everything up and try a fresh install? _(Note: Doesn't work.)_
- Should I try re-importing all the media manually? (There's a reason this is the last option)

Is there anything else I should try?

**Comment by vassbo** [comment]
Let me try to answer this:
- The "Media Path ID" should be the same in your case. See this: https://github.com/ChurchApps/FreeShow/issues/214#issuecomment-1666579008 & https://github.com/ChurchApps/FreeShow/issues/834#issuecomment-2357560461
- If you add the folder containing the media files to the "Media" drawer, then FreeShow should automatically search through them and find any matching files.
- I think you should not need to re-import the media manually, but let me know if the above methods does not work.
