### ISSUE TITLE
Stage display `current slide notes` text formatting output auto-sizing not applied to output, only preview

### ISSUE THREAD

**Issue by vicholz** [ChurchApps/FreeShow#1127]
**Describe the bug**
Stage display `current slide notes` text formatting output auto-sizing not applied to output, only preview. Auto-size option applies to the preview thumbnail and not the actual output.

**Reproducing**
1. Create a stage display
2. Add `current slide`, and `current slide notes` in boxes next to each other taking up half the screen each.
3. Enable `auto-size` for the `current slide notes` text.
4. Add some long notes to a slide and select it to be displayed (its text will not be sized to fit on the stage display output).
5. Go back to the stage display config and look at the preview (its text will not be sized to fit on the stage display preview).

**Screenshots (Optional)**
![image](https://github.com/user-attachments/assets/1e157aaa-642b-499f-a0d5-6c7911ada18d)

**Version (Optional)**
 - OS: Windows 11
 - FreeShow Version: 1.3.3

**Additional context**
Another issue is that the auto-size option stops working even in the preview if you increase the font size then turn on `auto-size`.

**Comment by m-esag** [comment]
I would like to report a similar issue.
I am testing the Normal Presentation Screen, Stage and Streaming. However, the Output style does not allow me to change the stye. I followed the manual from the website which showed how to set up the screens but i am unable to pick a different style like Bottom third for streaming.

![Screenshot From 2024-12-22 18-09-10](https://github.com/user-attachments/assets/64b70f67-5573-49a9-af48-819c34b3a595)
![Uploading Screenshot From 2024-12-22 18-12-00.png…]()

**Comment by vicholz** [comment]
@m-esag What are you using to stream? If OBS, you can try the following:
1. In FreeShow: create a new stage layout with a text box in the lower section of the slide, then set the background to green. 
![image](https://github.com/user-attachments/assets/0f9a6f3e-616d-481b-aa82-aae73e614007)
2. In OBS: create a new `Browser Source` with http://localhost:5511/?name=NameOfLayoutCreatedInStep1 as the source, and move it to the top of the sources. NOTE: you must enable `StageShow` under FreeShow Settings/Connection.
![image](https://github.com/user-attachments/assets/209a9bbf-87d4-4329-963e-a9c9cdb21827)
3. In OBS: right-click on the `Browser Source` you created and select filters, then add a new `Chroma Key` filter and set the `Key Color Type` to `Green`.
![image](https://github.com/user-attachments/assets/31b3ee29-b5cd-4a82-a352-0d02d3232cba)

**Comment by vassbo** [comment]
@vicholz I will fix this.

@m-esag You need to go to "Styles" right under "Outputs" in the settings, and change the values here, or create multiple "Styles", then you will be able to choose a style.

**Comment by m-esag** [comment]
> @vicholz I will fix this.
> 
> @m-esag You need to go to "Styles" right under "Outputs" in the settings, and change the values here, or create multiple "Styles", then you will be able to choose a style.

Thank you, I was not sure what the Manual meant with styles but i found the setting and works. I thought it was the same as templates.
