### ISSUE TITLE
Add option to add overlays as background

### ISSUE THREAD

**Issue by vicholz** [ChurchApps/FreeShow#1128]
**Describe the feature**
Currently all `Overlays` can be added over the slide or under the slide text. It would be nice to have a `Add as background` option when dragged over slides.

**Additional context**
Nope.

**Comment by vassbo** [comment]
If you enable "Place under slide" as you mentioned, that acts like a background?!!

How and why would this be need to be changed?

**Comment by vicholz** [comment]
@vassbo If you add a background to a slide with text, it clears/replaces the background/image from the previous slide. This may not actually be needed. I found that if I add an image from media it adds it as a background image so it does what I described. Thanks!
