### ISSUE TITLE
Add `white-space: pre;` as default CSS for text and/or add toggle for it under `Lines` or `Text` options.

### ISSUE THREAD

**Issue by vicholz** [ChurchApps/FreeShow#1129]
**Describe the feature**
Currently song text gets wrapped awkwardly when there are longer words that result in longer lines. The longer line ends up being wrapped right before the last word of the line resulting on one word on one line. This affects readability and doesn't look good. Adding `white-space: pre;` forces wrapping to only happen on new lines which makes it look much cleaner. It would be nice to have this set as default and/or have a toggle for it under the `Lines` or `Text` options.

**Additional context**
None.

**Comment by vassbo** [comment]
In the "Text" option there is an option `Text on one line` which does the same thing!
