### ISSUE TITLE
Sync added YouTube videos

### ISSUE THREAD

**Issue by klecu** [ChurchApps/FreeShow#1132]
**Describe the feature**
Included added YouTube videos in the synchronized data. Currently videos added from one instance show only as a video ID in the project and are not playable.

**Comment by chalamministries** [comment]
Are you referring to cloud synced data? Can you provide us a screenshot?

@vassbo this might need to be changed to a bug

**Comment by vassbo** [comment]
I thought it was set up to sync, but it wasn't. Changed it so to sync YouTube/Vimeo data as well! :)
