### ISSUE TITLE
Can't play .mov files

### ISSUE THREAD

**Issue by bryanyeap0922** [ChurchApps/FreeShow#1133]
**Describe the bug**
.mov video files won't play.
mp4 files has no issues playing

**Version (Optional)**
 - OS: MacOS
 - FreeShow Version: 1.3.3

**Comment by vassbo** [comment]
Unsupported codec by Chromium, same issue as this: https://github.com/ChurchApps/FreeShow/issues/1123
Just convert it to mp4 or another mov codec.
