### ISSUE TITLE
Closed Captions for Locally Hosted Videos

### ISSUE THREAD

**Issue by Alterios** [ChurchApps/FreeShow#1134]
**Describe the feature**
Enable closed captions for videos uploaded from local sources. Supporting closed captions embedded within the media file (internal) and separate caption files (external) would improve accessibility for hearing-impaired participants in meetings. Additionally, this feature can be useful for displaying lyrics for locally created music videos. Support for external closed caption files should include, at minimum, support for VTT and SRT files. 

**Additional context**
Enabling closed captions for videos sourced from local files is essential. By providing support for both internal captions embedded in the media and external caption files, we can ensure that hearing-impaired members can fully engage in meetings. Furthermore, this feature enhances the experience of locally created music videos by displaying lyrics, making them more enjoyable and inclusive for all viewers. I am hearing impaired, and the lack of captioning is a barrier to considering FreeShow for our church.

**Comment by vassbo** [comment]
Subtitle/caption support for local videos will be comming in the next update. Captions can be managed from a video added to the project:
![image](https://github.com/user-attachments/assets/a0da0727-d4f0-499a-a720-eca89126f8eb)

If a mp4 video has embedded subtitles they should be automatically extracted and imported.

Local files can also be imported (vtt/srt). SRT should be converted into WebVTT.
If it's another subtitle format an online converter can be used to get the VTT format.
