### ISSUE TITLE
Remote advance to next show

### ISSUE THREAD

**Issue by coding-vicar** [ChurchApps/FreeShow#1138]
It would be helpful when using Remote on a mobile device in ‘Show’ and ‘Output/Slide’ views if at the end of each show in the presentation tapping on the right side would advance to the next show (as pressing the right arrow key on the computer running Free Show would).

It is cumbersome when controlling from a small-screened device to need to click into ‘Project’ view to at the end of each show to advance to the next one.

**Comment by TPaulManohar** [comment]
In remote control, we found that output screen(preview  screen) content getting cropped.

And in project when we click the items that select, That show item need to display it like lyrics mode.

In iPad when we rotate to landscape remote control, it visible as like as desktop mode. When in portrait mode it not showing all options it disappeared lot of functionality. Even in mobile phones we can't operate the Freeshow, it harder to control.
