### ISSUE TITLE
Songs Dissapear 

### ISSUE THREAD

**Issue by Maruis101** [ChurchApps/FreeShow#1139]
**Describe the bug**
Songs dissapear after i have updated the software not the first time it happens 

**Reproducing**
If the software can update with out removing content loaded on the prrevious version 

**Screenshots (Optional)**
not applicable .

**Version (Optional)**
 - OSWindows
 - FreeShow Version: [1.3.3

**Additional context**

**Comment by vassbo** [comment]
This does not have anything to do with the updates! They should also still be on your system if you haven't accidentally deleted them.

Please check that the storage location in settings>Other is pointing to the correct location, should be `Documents/FreeShow/Shows`, if not you can find the folder with all of your .show files and change the location.

**Comment by Maruis101** [comment]
Hi

Thanks for the mail will check and advise

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vassbo** [comment]
Probably the same issue as this: https://github.com/ChurchApps/FreeShow/issues/1116
