### ISSUE TITLE
Save Video State Option

### ISSUE THREAD

**Issue by aspectxlol** [ChurchApps/FreeShow#1141]
**Describe the feature**
In My Church we get a video Sermon every week, so we play the video, but in the middle of the video we have to stop and continue the prayer. after the prayer we have to continue the video
ive been trying to find an easy way to save the state of the video but the current best way is just to use windows media player, but what if theres a way freeshow could save the current state of the video so that the next time i play the video it plays it from the last saved state

**Additional context**
-

if there are any questions feel free to ask!

**Comment by vassbo** [comment]
You can add timestamps to the video:
1. Open the video preview, click "Show media preview controls":
![image](https://github.com/user-attachments/assets/03acfa5b-694e-4aa7-b83b-b1b8d20a5e2f)
2. Click "Toggle time marker":
![image](https://github.com/user-attachments/assets/a0fdf3c9-98c6-4635-9b9a-46598752e435)
3. Seek to any time where you want to start the video from, and click "Add time marker":
![image](https://github.com/user-attachments/assets/4a8d2748-1f4f-426c-ada7-af8dca2dd737)

**Comment by vassbo** [comment]
Now when you click the time marker the video should start from that timestamp.

**Comment by aspectxlol** [comment]
thank you!
