### ISSUE TITLE
Optionable 4:3 shows ratio

### ISSUE THREAD

**Issue by PavelS-CZ** [ChurchApps/FreeShow#1142]
Currently, Free show editor is set to 16:9, it would be nice if there was an option to change slide scaling to 4:3. Reason is that our Church has 4:3 projector machine and when we send a signal in 16:9 a lot of the projectable area goes to waste since it's empty.

**Comment by Phantom-Matt** [comment]
Hi. If you go to Settings -> Styles -> Resolution and click on the dropdown menu, you can select the first option that says "720p 960/720 4/3". Doing that, the program will "be set" to 4:3. Hope that helps. Merry christmas.

**Comment by PavelS-CZ** [comment]
@Phantom-Matt Thank you brother!!!!! Merry Christmas to you too 👍 :)
