### ISSUE TITLE
Powerpoint Presentation 

### ISSUE THREAD

**Issue by Maryland-Wesleyan** [ChurchApps/FreeShow#1143]
I appreciate the integration of PowerPoint in this tremendous app, FreeShow. The issue is whenever I switched from the presentation I can't resume to a specific slide.

I have been using an aged old app cliicker called i-Clickr and I am able to see the slides on the device to navigate and resumed on any slide from the controller. 

My request should not be too tall to have similar features on the ControlShow device. Since we do a lot of presentations and the presenters usually have full control of their slide transition. Also make the display center on the preview screens

**Comment by vassbo** [comment]
Not sure what you need here? Could you clarify.

Regarding the PowerPoint presentation, I can't do much more advanced than it already is at this moment, unfortunately.

**Comment by Maryland-Wesleyan** [comment]
If you "can't do much more..." I am not sure it warrants clarification. However, what I was asking is that the slides or thumbnails with the numbers display on the remote as reference point.

When we switch from the presentation to display scriptures and to resume we have to scan through from the beginning to get to where we were instead of just selecting the correct one to continue.

Like I said we are exposed to this feature, only hoping for an additional feature on the clicker or "RemoteShow".

**Comment by vassbo** [comment]
Okay, I see.. That would be hard to do with PowerPoint.

I guess you can import the presentation slides as images, that way you will see all the slides with a preview on the RemoteShow interface.
