### ISSUE TITLE
Reflow Editor

### ISSUE THREAD

**Issue by AngangGuo** [ChurchApps/FreeShow#1145]
For documents with very long textes, it'll spend lots of time to copy/paste several lines at a time.
Or if I make the text shrink to fit and it'll be very small and can't see exactly where to split the text.
Is there a way to split/combine them similar to the reflow editor in ProPresenter? 
Thanks.

**Comment by vassbo** [comment]
This is similar to the "Reflow Editor" I guess:
![image](https://github.com/user-attachments/assets/7cbbae4a-aa0e-4b11-9bf6-ff6c19d88ed4)

But in this case I think it's better to use the "Text edit" found in the bottom of the "Edit" page:
![image](https://github.com/user-attachments/assets/2a19c413-f83d-4809-8b5a-6565b372dc11)

**Comment by AngangGuo** [comment]
Yes, It works great. Thanks.
