### ISSUE TITLE
Song lyrics multiple arrangment version

### ISSUE THREAD

**Issue by Grayan2013** [ChurchApps/FreeShow#1146]
Able to make multiple arrangements of any lyrcis song by using group available (Chorus, verse, break, tags, ...)
And be able at any time to select the arrangement that we want for this particular song lyrics.
All this arrangement will be like a layer on the same song that we could recall at any time.

Exemple  SongA

arrangement 1

Intro chorus verse1 verse1 intro break verse2 chorus verse3 break chorus outro

Arrangement 2
Intro chorus verse1 Intro break verse1 verse2 chorus verse1 verse2 break outro

So when select songA I could recall arrangement 2 or 1 when I need it.

**Comment by Bagel94** [comment]
When you have your song open, in the bottom left of the slide selection area there is a button called layout. This does what you are looking for.

![image](https://github.com/user-attachments/assets/815dffe7-5e77-4a5d-a1c6-196dea5a1ea1)
