### ISSUE TITLE
PowerPoint cannot open via the items

### ISSUE THREAD

**Issue by EFKB-Techniker** [ChurchApps/FreeShow#1149]
**Describe the bug**
When a PowerPoint presentation is supposed to start, FreeShow waits for a moment and then the following error message appears: 'Could not start presentation, please open it manually and try again!' At the same time, the PowerPoint is opened, but FreeShow has no access to the opened PPTX. I can only control the PPTX via PowerPoint.

**Reproducing**
- add PPTX Slide
- open it

**Screenshots (Optional)**

**Version (Optional)**
 - OS: [Windows 10]
 - FreeShow Version: [1.3.3]

**Additional context**

**Comment by vassbo** [comment]
I have tried fixing this, but there does not seem to be a lot that I can do about it with my knowledge at the moment.

I think it should work if you open the presentation first, and then start from FreeShow.

**Comment by rwiebe** [comment]
Unfortunately, it does not lead to the desired result. This error message still appears.

Could it possibly be related to the installed Office version? On a computer with pre-installed Office, the behavior is different compared to when I download the Office package from my Office Business account.
We use Office for non-profit organization

**Comment by vassbo** [comment]
All right, @rwiebe.

That might be related, but it seems to happen sometimes, and not always. I'm not sure why, also not sure if there is a good way to fix it. This is the script: https://github.com/vassbo/slideshow/blob/master/connector-win-ppt2010.js
