### ISSUE TITLE
Freeshow cannot open Powerpoint with Umlaute (Ä. Ö. Ü, ß) or cryllic letters

### ISSUE THREAD

**Issue by EFKB-Techniker** [ChurchApps/FreeShow#1150]
**Describe the bug**
When a PowerPoint Slide will be open, it canceled with Error. 

It seems that this letters are internal translated, like a browser did it.
**Reproducing**
Please give some steps we can follow to recreate this issue.

**Screenshots (Optional)**
![1](https://github.com/user-attachments/assets/8c8ffcc5-3a9c-40cb-b0e3-16a00bfc1c39)

Translation is:
The search for C:\\Users\Beamer\Downloads\BegrÄ%ÄYungstext.pptx was unfortunately unsuccessful. Maybe the file was moved, renamed, or deleted?

**Version (Optional)**
 - OS: [Windows 10]
 - FreeShow Version: [1.3.3]

**Additional context**

**Comment by vassbo** [comment]
This seems like a limitation with the shell script, and I can't seem to do anything about it unfortunately, I have tried.
![image](https://github.com/user-attachments/assets/a53ce8d3-264a-41e4-85a1-9ed2c01c9ba3)

It should work better if you do not have those letters in the name.
