### ISSUE TITLE
Suggestion: Create show w/ template

### ISSUE THREAD

**Issue by freezemarco** [ChurchApps/FreeShow#1152]
Hello together, I‘ve a suggestion for a new feature: In ProPresenter you can choose a template as base for creating a new show. The reason why I think it will be helpful is, that I use a style with 4 text boxes for my slides: 2 text boxes for main language and optional 2 boxes for second language. Currently (my understanding?) I have to create multiple text boxes at first to match with my preferred templates. 

Marco

**Comment by Phantom-Matt** [comment]
Hello. Usually there's a "Default" template that gets used when making a song. If you change said template, all your songs will be on that format. Is that what you want to do? Otherwise, just click on the template when selecting the song. Hope this helps.

**Comment by freezemarco** [comment]
Maybe that helps me..😅 Where can I change the "Default" template?

**Comment by archangel-man** [comment]
@freezemarco
In the drawer where Templates are selected, you can right-click and say Edit.

@Phantom-Matt 
I have found that using Quick Lyrics to create a song (Show) doesn't seem to use my modified/custom Default template.
It's easy enough to apply afterward, but doesn't seem to pick it up for Quick Lyrics.

**Comment by freezemarco** [comment]
I'm not sure if that is a solution for my issue. I want that a new show will be created with a explicit template/style from the beginning. 
I know that I can apply a template afterwards, but if I have different text boxes, I have to "re-build" the style first when I create a show, before I can correctly apply a template.

**Comment by vassbo** [comment]
@freezemarco You should be able to simply apply any template after creating a show, without needing to "re-build" anything, not sure what you mean by that.
Also if you hold the Shift key while clicking a template the items will shift around if you have multiple textboxes.

The template of the active show should automatically be applied, if not the "Default" will be used as @Phantom-Matt mentioned.

If you want to you can do this, but it's not necessary:
You can in theory create a new action "Set template on active show", choose the template you want and apply that action to a show category by right clicking e.g. "Songs", and clicking "Category action". That way by selecting that category you know all the shows in there will have the same template.
