### ISSUE TITLE
Projects freezing the program

### ISSUE THREAD

**Issue by Phantom-Matt** [ChurchApps/FreeShow#1153]
**Describe the bug**
After doing some everyday tasks and editing a show on a project, the app froze. After trying to open the app again and selecting the **project**, the freeze effect reappers. Opening the shows on the project did not froze the app.

Edit: After some tests, opening **any project** made the app freeze.

**Reproducing**
I did not see any specific action that brought this into action, but i'll upload the _error_log.json_ to give more answers.

**Screenshots (Optional)**
[error_log.json](https://github.com/user-attachments/files/18271370/error_log.json)

**Version (Optional)**
 - OS: Linux
 - FreeShow Version: 1.3.3

**Comment by vassbo** [comment]
Thank you. I think I managed to fix this.

**Comment by Phantom-Matt** [comment]
@vassbo I'm having [some difficulties](https://github.com/user-attachments/files/18302601/log_npm_install.txt) on building the package, so i didn't have a chance to test. After switching between versions and some more testings, it seems that sections that have actions assigned always freeze the app, so i deleted every section and the program stop freezing.

About the building, what can be done? I wish to test these new shiny features.

**Comment by vassbo** [comment]
Thank you for the sections info, will double check that.

NDI 6.1.1 is released so it can't find 6.1.0 anymore. Will update and release a beta next week probably.

**Comment by vassbo** [comment]
Check it out: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.4-beta.1
