### ISSUE TITLE
Freeshow crashes due to power saving?

### ISSUE THREAD

**Issue by snoekieboe** [ChurchApps/FreeShow#1154]
**Describe the bug**
Running Freeshow for extended periods of time on macOS consitently makes freeshow (and even propresenter) crash.

**Reproducing**
Running Freeshow for extended periods of time on macOS consitently makes freeshow (and even propresenter) crash.

**Screenshots (Optional)**
Sorry no screenshot available

**Version (Optional)**
 - OS: MacOS 15.2
 - FreeShow Version: 1.3.3

**Additional context**
Every time free show crashes i have the following entry in error.json:

		{
			"time": "2024-12-29T21:08:46.091Z",
			"os": "darwin",
			"version": "1.3.3",
			"active": {
				"window": "main",
				"page": "show",
				"show": {
					"id": "0f828862056",
					"type": "show",
					"index": 0
				},
				"edit": {
					"slide": 7,
					"items": []
				}
			},
			"drawer": {
				"active": "shows"
			},
			"type": "unhandledrejection",
			"source": "See stack",
			"message": "The play() request was interrupted because video-only background media was paused to save power. https://goo.gl/LdLk22"

**Comment by vassbo** [comment]
That error message should not have anything do to with it. Does the program freeze or just force close?

Please see this: https://freeshow.app/docs/faq#the-app-is-slow

**Comment by snoekieboe** [comment]
I run this on a M1 Mac Mini and it is the only application running at the moment.
Next to that i do not display the show on the Mac Mini it self (presentation is not enabled) i DO run the show through NDI (640x480 stream).

All the options you mention (enable hardware acceleration, remote show) are already in line with the recommendations.

Don't know what to do to resolve this. any other pointers?

**Comment by vassbo** [comment]
Must be the NDI capture then, but this seems like the same issue as this: https://github.com/ChurchApps/FreeShow/issues/1041
