### ISSUE TITLE
Power point problems

### ISSUE THREAD

**Issue by pastordavid** [ChurchApps/FreeShow#145]
Anytime I make a power point that has pictures or  and import them to free show the pictures the pictures to import with power point. How to Import my power point with pictures.

**Comment by vassbo** [comment]
Hi, you have to export/convert the PowerPoint to PDF, then import it.

I might add some sort of PowerPoint conversion for more than just text sometime in the future.

**Comment by pastordavid** [comment]
I just tried covering it to pdf and it would import to freeshow

**Comment by vassbo** [comment]
Hmm... Did you click on "PDF" in the import popup, select and open the .pdf file, then waited for 3-10 seconds?

It's working fine on Windows, so I can see if I can fix it if it's a problem on just Mac!

**Comment by pastordavid** [comment]
Yes I did and nothing happens Sent from my iPhoneOn May 12, 2023, at 1:33 PM, Kristoffer Vassbø ***@***.***> wrote:﻿
Hmm... Did you click on "PDF" in the import popup, select and open the .pdf file, then waited for 3-10 seconds?
It's working fine on Windows, so I can see if I can fix it if it's a problem on just Mac!

**Comment by pastordavid** [comment]
I went to put on free show upload it and nothing happened Sent from my iPhoneOn May 12, 2023, at 1:33 PM, Kristoffer Vassbø ***@***.***> wrote:﻿
Hmm... Did you click on "PDF" in the import popup, select and open the .pdf file, then waited for 3-10 seconds?
It's working fine on Windows, so I can see if I can fix it if it's a problem on just Mac!

**Comment by pastordavid** [comment]
After I imported is it suppose to autmatic pop up or is there a step I am missing. If so what’s the next step. Once I imported what’s next?Sent from my iPhoneOn May 12, 2023, at 1:33 PM, Kristoffer Vassbø ***@***.***> wrote:﻿
Hmm... Did you click on "PDF" in the import popup, select and open the .pdf file, then waited for 3-10 seconds?
It's working fine on Windows, so I can see if I can fix it if it's a problem on just Mac!

**Comment by pastordavid** [comment]
In other words i when to import selected pdf upload an nothing happens Sent from my iPhoneOn May 12, 2023, at 1:33 PM, Kristoffer Vassbø ***@***.***> wrote:﻿
Hmm... Did you click on "PDF" in the import popup, select and open the .pdf file, then waited for 3-10 seconds?
It's working fine on Windows, so I can see if I can fix it if it's a problem on just Mac!

**Comment by vassbo** [comment]
Okay. You are doing everything correct!

I suppose it's not working on Mac for some reason, so I will investigate the issue and let you know when there are any updated on this issue! 😊

**Comment by vassbo** [comment]
In the meantime you can use an online PPT to JPG converter, create a new show, and just drag in all the images!

**Comment by pastordavid** [comment]
Also I can’t upload pdf to my Linux computer either Sent from my iPhoneOn May 12, 2023, at 1:44 PM, Kristoffer Vassbø ***@***.***> wrote:﻿
In the meantime you can use an online PPT to JPG converter, create a new show, and just drag in all the images!

**Comment by vassbo** [comment]
Okay, I will investigate!

**Comment by vassbo** [comment]
It seems like the [package](https://www.npmjs.com/package/pdf-poppler) I use does not support Linux. Also I guess it's not fully supported on MacOS either.
I have looked at many different alternatives, but all of the other ones requires you to install a third party application (like imagemagick, ghostscript or python), to convert the PDF to an image.
So I guess I'm just gonna close this for now, until there is a better alternative!

- I recommend using this website to convert PPT to JPG: https://cloudconvert.com/pptx-to-jpg
- Or this website to convert PDF to JPG: https://www.ilovepdf.com/pdf_to_jpg
- Then just drag the images from the computer into the program.
