### ISSUE TITLE
Support proBundle files

### ISSUE THREAD

**Issue by odlg** [ChurchApps/FreeShow#225]
Please add support for importing ProPresenter proBundle files. For now I was able to unzip them and import the .pro files from within the proBundle.

**Comment by vassbo** [comment]
I don't think I will add support for this, at least for now. As I don't see the need, when it's basically just a .zip folder.

**Comment by odlg** [comment]
I guess most people does not know it is just a zip file, so perhaps some note in the documentation?

**Comment by vassbo** [comment]
True, I can do that.
