### ISSUE TITLE
Software freezing up

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#230]
Software is freezing up at random times

- When on Stage Display in Chrome, it is randomly freezing up on a slide and need to refresh the web page for it to work (it hasn't done this in the past)
- Sometimes the output display is freezing up
- Sometimes the software is freezes up and crashes and need to restart it

**Comment by vassbo** [comment]
Thank you. I will investigate these issues.

When the software freezes I have to know what caused it, so please give me an explanation of what you are doing right before it happens, so I can recreate the scenario. If not I can't fix it!

**Comment by JacobAkers** [comment]
What I’ve noticed is the stage display freezes when you click on the last slide of a show.

Sent from my iPhone
Jacob Akers

On Aug 7, 2023, at 5:13 AM, Kristoffer Vassbø ***@***.***> wrote:

﻿

Thank you. I will investigate these issues.

When the software freezes I have to know what caused it, so please give me an explanation of what you are doing right before it happens, so I can recreate the scenario. If not I can't fix it!

**Comment by kinghamr** [comment]
Sometimes it freezes upon when its in editing mode, I'll have to restart the software

**Comment by vassbo** [comment]
Thank you. I'll see if I can find and fix it.

**Comment by kinghamr** [comment]
Basically when I’m like editing a show/song that when it freezes

**Comment by vassbo** [comment]
Yes, but what specifically are you editing? Do you add a new item, or do you change a specific value?
I have tried editing various things in a show and it doesn't freeze.

**Comment by kinghamr** [comment]
I'm just editing song lyrics.....
That's strange though.....

Here's a question, upon startup, the software isn't bringing up my songs at
times like it dosen't see it until I have to go into settings for it to get
them again... Is there a fix for that?

**Comment by vassbo** [comment]
Hmm... I'll keep an eye open for this, but I don't know what's causing it.
Maybe undo is related.
