### ISSUE TITLE
Not Saving Changes Goes Back to Zero

### ISSUE THREAD

**Issue by aJaaaang** [ChurchApps/FreeShow#244]
Hello @vassbo I have an issue where when I change a little bit of the project and did not save it, the app goes back to zero. However, I can retrieve my created shows back to the app again. The only issue is when I didn't save it the whole thing goes over again.

I want to recommend that whenever I didn't save the change, goes back to the previous version of edit. Thanks!

![Screenshot (423)](https://github.com/vassbo/freeshow/assets/130219498/b5d41e28-ba48-4955-8edc-d1368e3b673f)

I know that there's an autosave in the app but it's frustrating when you don't save and go back to zero.

**Comment by vassbo** [comment]
This should not happen. I have no idea why, but I'll see if I can fix it.

**Comment by vassbo** [comment]
I can't find the issue. Have you set up any cloud sync or simular?
Has this happend more than one time (after saving something first, then not saving)?
Not saving the program will not write anything to the computer. So maybe an error with the computer?

**Comment by vassbo** [comment]
This should not happen, but I recommend taking a backup from time to time just in case something goes wrong!
![image](https://github.com/ChurchApps/FreeShow/assets/17619496/304ed3de-969d-488a-9750-47b7b143b9ce)
