### ISSUE TITLE
Dual Audio Issue/Music Player Keeps Playing Music

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#246]
I am hearing dual audio for some reason when I have the audio linked to the slides and I don't "double-click" the slide to try to make this error....

When I try to stop the audio, upon pressing "ESC" or the "X" underneath the output monitors, the volume level ducks but keeps going...

**Comment by vassbo** [comment]
Hmm... I'll take a look.

**Comment by vassbo** [comment]
Do you still have this issue in the latest version?

**Comment by kinghamr** [comment]
I need to test it
Have been at work today
I’ll install it and test it out later on tonight
