### ISSUE TITLE
Feature Request: Dual Views

### ISSUE THREAD

**Issue by MrDogeBro** [ChurchApps/FreeShow#256]
It would be nice to have the ability to have two views side by side for certain use cases. This could be a button near the bottom of the main layout view, which would allow you to enable the second view window, and then you could choose what view to put in that view window independently of the main view window. You could also then drag the center line to change the sizing split of both view windows. I have mocked up a rough idea of what it would be like below.

![Dual View Mockup](https://github.com/vassbo/freeshow/assets/35872177/43b2070c-e58a-4d65-adea-12ec76f04d53)

**Comment by vassbo** [comment]
Hmm... I don't want there to be too many options.
What would be the use case for this? Why not toggle between the standard grid view, and the text editor?
