### ISSUE TITLE
Media Fill Style 

### ISSUE THREAD

**Issue by ejbramos** [ChurchApps/FreeShow#260]
I don't know if there is a way to possibly fill or stretch the media or shows to the entire screen or zoom. Since currently the default is 16:9 but my problem is that sometimes I am required to have 4:3 option or 16:10 resolution. Especially in 16:10, most resources can be found in 4:3 and 16:9 but in 16:10, there are limited resources. So if there is a way to fill the screen even with a stretched look or zoomed look is possible then I would be very grateful or if there is a way to do that already. How will I do that. Thank you!

**Comment by vassbo** [comment]
You can do this for each individual image by right clicking, choosing "Edit", then changing "Fit" on the right from "Contain" to "Cover"/"Fill". Or to do it for all images, add a style to the output, and change "Media fit" in the "Styles" in settings.
Hope you understand.

**Comment by ejbramos** [comment]
I just want to ask where in this edit part I can find or change the "Fit" to "Contain" or "Cover/Fill" in this slide. 


![Screenshot (20)](https://github.com/vassbo/freeshow/assets/113459961/36576f9b-d808-486c-a97a-4b7ce3299ab5)

**Comment by vassbo** [comment]
Right click the image to edit it:
![image](https://github.com/vassbo/freeshow/assets/17619496/4b8e92c5-93ab-48df-80d4-9d6a755634fa)

**Comment by ejbramos** [comment]
I think there is a bug regarding the Media fit and changing it to "fill" or "contain". Once I start presenting a "show", background is going back to its native resolution. I tried playing a media file and its works well filling the black bars.

**Comment by vassbo** [comment]
Okay thanks, I'll take a look.

**Comment by vassbo** [comment]
Hey @ejbramos, are you able to send a video showing the issue. I can't recreate the issue.

**Comment by ejbramos** [comment]
I cannot really fully recreate the issue right now with a proper projection but there is a preview in the app that you refer to. It is a trial setup for you guys to try right now. Try forcing your output to 4:3 aspect ratio like 1920x1440 or 1024:768. then using a 16:9 set up. At least I want my 16:9 setup to stretch or fill but nothing is happening. 

P.S. Try fast forwarding because some parts of the video lagging so fast forward in some parts of the video

Link of the Video: https://drive.google.com/file/d/1q_4pzf6zBk3VVuxRkdgpYodYCLGAnQ7y/view?usp=sharing

**Comment by vassbo** [comment]
Okay. Please note that this will only change the resolution inside the window!
To stretch the entire window you have to click the "Choose screen" button, and change the size of the actual output window.

**Comment by ejbramos** [comment]
This is noted but you can refer to my video as my video "Choose screen" has 4:3 aspect ratio display settings and my show and some media files have 16:9 settings. When trying to present, which can be seen through the preview panel on the top right. It does not fill or stretch the media or show from 16:9 to 4:3.


Another thing just to clarify, what does "Media Fit" do. Does it specifically entails media files that is not in a certain or project, or it refers to all media whether it may be a background or anything within a "project" or "show".

**Comment by vassbo** [comment]
Okay, thank you. "Media Fit" applies to all backgrounds, either in a show, or directly from the drawer. But it does not currently work well on videos, only images.

**Comment by vassbo** [comment]
I figured out that for this to work you had to change resolution in "Styles" to e.g. 1440x1080, in addition to the window resolution being 4/3 in outputs. And for 16/9 images to stretch the "Media Fit" has to be set to "Cover". You probably have to create a new template to use for the text, because it's the wrong resolution.
