### ISSUE TITLE
Dual Issues: Blank Slide / Slide Flashing Issues

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#261]
Issue 1: 
I noticed that when you go "Backwards" using the keyboard when there's a slide with text on it, it goes to a "blank slide"

Issue 2:
I noticed that when you reduce the slide line count in "Options-Styles-Lines" it will flash when you advance lines or slides

Here's a YouTube Video of the issue since this site won't let me post the video here
https://www.youtube.com/watch?v=Di2ePZhEW4A

**Comment by vassbo** [comment]
Thank you. I will fix these issues!
