### ISSUE TITLE
Lack of controll for timers

### ISSUE THREAD

**Issue by not-my-username** [ChurchApps/FreeShow#263]
When following the documentation on how to use timers, it says they can be controlled by "Timers" in the drawer. How ever this button does not exist in the application version i am using (latest as of this post v0.9.7) When trying it again on an older version V0.8.4, the button does exist, but the entire application is frozen.

OS: EndeavourOS (Arch) Linux x86_64 (has been tested on Windows 10 with the same issue)

**Comment by vassbo** [comment]
The "Timers" button can be found in the "Calendar" tab in the drawer: https://freeshow.app/docs/calendar#timers
It has moved in a previous version, but the docs should be updated. I can add a link to the text you mentioned to make it more clear.
I hope this helps. :)

**Comment by not-my-username** [comment]
All good, thanks!
