### ISSUE TITLE
 ProPresenter 7 Song Import Issue

### ISSUE THREAD

**Issue by Rickard-Se** [ChurchApps/FreeShow#265]
Encountered a bug when importing ProPresenter 7 song files into Freeshow. The song title appears but not the content, showing empty black boxes instead. Attached is a sample song file for replication.

Attachment:
[030 Gud är trofast.zip](https://github.com/ChurchApps/FreeShow/files/12829292/030.Gud.ar.trofast.zip)

**Comment by vassbo** [comment]
Thank you. This will be fixed. 😊
