### ISSUE TITLE
Add custom audio output

### ISSUE THREAD

**Issue by MrSam7K** [ChurchApps/FreeShow#266]
For example I want to play slides with audio to other monitor but it keeps playing out of my speakers (I want to be able to hear anything else but freeshow out of them)

**Comment by vassbo** [comment]
You can do this in the system settings, but I'll see if I can make it possible from within the program.

**Comment by vassbo** [comment]
FreeShow is currently on Electron version 21, which does not support changing the output of the AudioContext (which is used in our case). You will have to just change this manually until we upgrade to Electron 24 or later.

I have tried upgrading some time ago but could only get it to work on Windows.
On a side note upgrading means the program will no longer support Windows 7 or 8, but it will support HEVC/H.265 encoded videos as well.
