### ISSUE TITLE
Unable to install to Apple Ventura 13.6

### ISSUE THREAD

**Issue by NeoAcla** [ChurchApps/FreeShow#267]
Hi, i want to try this software on my apple macbook pro but unfortunately after downloading and trying to install it show's error message

“FreeShow” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.

Any idea?

**Comment by vassbo** [comment]
We should soon have code signed the application, so you won't get this message. But until then you will have to allow it manually.
Please follow the instructions here: https://freeshow.app/docs/macos
If you are still stuck, then just search the web for a guide.
