### ISSUE TITLE
Red text on bible verses

### ISSUE THREAD

**Issue by mtgileadtech** [ChurchApps/FreeShow#270]
I would like to see when the scripture is outputted to the screen and other outputs. That when there is a verse that has Jesus speaking which is Red in the bible. For it to show Red on the outputs. For example “But he answered and said, (ALL THIS IS RED) _It is written, Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God.”_

**Comment by vassbo** [comment]
I will see what I can do.

**Comment by vassbo** [comment]
@4vwzc5ffr8-bot Yes, it works when supported by the Bible itself.
