### ISSUE TITLE
Selection for Importing .chordpro impossible because typo

### ISSUE THREAD

**Issue by baccalla** [ChurchApps/FreeShow#271]
Hello
i've tried to import .chordpro on the app but seems impossible
In the selection menu, files .chordpro does not appears because it seems there is a small typo on the selection type (lack an "r" see screenshot ".chopro" instead of ".chordpro")  
![image](https://github.com/ChurchApps/FreeShow/assets/13984708/d540384a-de3a-4e68-a845-4c1e0160befe)

Best regards

**Comment by vassbo** [comment]
This will be fixed.

**Comment by baccalla** [comment]
Nice. thank you
Tested this day, it works

Best regards
