### ISSUE TITLE
Unwanted '2' Appended to Show Name when Renaming with Different Letter Case

### ISSUE THREAD

**Issue by johnjairus10** [ChurchApps/FreeShow#273]
**Problem**
When renaming a show, such as a song or presentation, by changing only the letter case (e.g., from 'amazing grace' to 'Amazing Grace'), the application erroneously appends '2' to the show's name. 

**Steps to Reproduce**
1. Open the application and access the library of shows.
2. Select a show name  (e.g., 'amazing grace').
3. Rename the show and modify the letter case (e.g., 'Amazing Grace').
4. Save the changes.

**Expected Behavior**
After following the steps above, the show's name should correctly change to 'Amazing Grace' without any extra characters appended.

**Actual Behavior**
Instead, the application appends '2' to the renamed show, resulting in the show name 'Amazing Grace 2'.

**Comment by vassbo** [comment]
Thank you!
