### ISSUE TITLE
Unable to import files

### ISSUE THREAD

**Issue by kissibaah** [ChurchApps/FreeShow#274]
Unable to import openlyrics files and opensong doesn't really show the lyrics, only titles. Also unable to import powerpoint

**Comment by vassbo** [comment]
Please send over the files that doesn't work, so I can fix it.

**Comment by Rend71** [comment]
Trying different ways to import, still failed.
VideoPsalm [Kidung Jemaat.json](https://github.com/ChurchApps/FreeShow/files/13274527/Kidung.Jemaat.json)
EasyWorship [https://drive.google.com/file/d/17dazXwsjByEmvTFlfCMncDoJuHpviU2G/view?usp=drive_link](url)
OpenLP [https://drive.google.com/file/d/1wdrWpuSZZ1Zj6WGIrqNBJR4ce4zFqOJo/view?usp=sharing](url)

**Comment by kissibaah** [comment]
I found a way to import them. Not as openlyrics files though. They came as
"unidentified" I think. I had to convert them to txt files. Over 3000 of
them.

**Comment by Rend71** [comment]
If worked correctly, the book contains 478 songs, except the VideoPsalm version, because I included some old song versions there. I'll wait for the official Import guide on FreeShow Youtube channel. Thanks for your hard work.

**Comment by vassbo** [comment]
Great, thanks.

**Comment by Prezib** [comment]
Hi is there any workaround while we wait or is the eta for the fix close? need to import out easyworship database

**Comment by vassbo** [comment]
@Prezib If you are able to send over the EasyWorship songs on mail: dev@freeshow.app, I can take a look to see if it works, and possibly send back the converted files.
