### ISSUE TITLE
search the bible

### ISSUE THREAD

**Issue by Prezib** [ChurchApps/FreeShow#279]
under the search instead of only the books of the bible, will you be able to add searching of the bible as well, I belive API.bible allows this

**Comment by vassbo** [comment]
You can search for all the books, chapters and verses in the selected bible. I don't see why you would need to search for a bible, in most cases people don't use more than a few different versions. 🤔

**Comment by Prezib** [comment]
Hi, I meant searching for a phrase in the bible

**Comment by vassbo** [comment]
Makes sense. I'll see what can be done.

**Comment by lubomsky** [comment]
I think I should just pin my issue to this enhancement because it's really close.
When I try to import the Bible from "API.Bible", I cannot use special symbols (I've tried only polish ones).
Console logs this:
```
Electron Helper (Renderer)[7535:111006] 
CoreText note: Client requested name ".PingFangSC-Regular", 
it will get TimesNewRomanPSMT rather than the intended font. 
All system UI font access should be through proper APIs such as 
CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
```

**Comment by vassbo** [comment]
Looks like an issue with Chromium on Apple devices: https://github.com/electron/electron/issues/33317
I guess I can't do anything about it.
Have you tried setting a different font in the Scripture template?

**Comment by lubomsky** [comment]
Well, I’ve just reinstalled macOS (I had to many trash), and now it works flawlessly ;)Thanks for the memory Wiadomość napisana przez Kristoffer Vassbø ***@***.***> w dniu 13.11.2023, o godz. 17:22:﻿
Looks like an issue with Chromium on Apple devices: electron/electron#33317
I guess I can't do anything about it.
Have you tried setting a different font in the Scripture template?

**Comment by Prezib** [comment]
hi, to add to this, can the need to add a ":" when searching for a scripture be removed?

**Comment by vassbo** [comment]
The ":" or "," or "." seperates the chapter from the verses, there has to be a way for the program to know that.

**Comment by Prezib** [comment]
thanks, its good to know about the comma and fullstop
