### ISSUE TITLE
I have tried to use the padding attribute in the CSS box to draw a box around the text automatically mainly for creating a transparent lyric lower third, but adding padding seems to have no effect.

### ISSUE THREAD

**Issue by Benjamin72070** [ChurchApps/FreeShow#282]

**Comment by vassbo** [comment]
Do you have an example image of the style you are looking to get?

**Comment by Benjamin72070** [comment]
I would be happy with a template with a semi-transparent black background across the bottom of the screen that OBS can overlay on a livestream.   I tried using the style and template override with a green background and chroma key filter.  That either washed the semi-transparent background out or left green tinges.  I tried using enable alpha key but that for some reason had the lyrics and background on a black screen instead of transparent background.

**Comment by vassbo** [comment]
I think it's possible with some tweaking, but if you are able to use NDI, that would be the best. Because NDI supports transparent video streams. See this: https://streamgeeks.us/how-to-use-ndi-with-obs/

**Comment by Benjamin72070** [comment]
I was not able to use NDI because it is not well supported in Linux.  I guess I will need to use Windows.  That does not exactly resolve part of the issue.  I cannot find a way to dynamically draw a filled box around the text.  Regular CSS will allow for the padding attribute to create such a textbox effect, but I am unable to replicate this in Freeshow.

**Comment by vassbo** [comment]
Right. The textbox has a fixed size so that would not be possible the way it currently works, but please see my comment here: https://github.com/ChurchApps/FreeShow/issues/284#issuecomment-1809960971.
