### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by Benjamin72070** [ChurchApps/FreeShow#285]
Is there a way to make FreeShow portable?  If we could carry the app around on a flash drive with all the media that was associated with it in folders on the same USB drive, it would help those that either have no internet or unreliable internet at any location that they use the program.

**Comment by halcycon** [comment]
Further to this issue - we have just started using FreeShow in our Church, and have the need to sync the content across multiple PCs. We currently use a self-hosted NextCloud instance, and so on each PC I have pointed all the FreeShow content (or so I thought) to (for instance) "C:\Shared_Folder\FreeShow" - unfortunately when shows are imported (from PDF for example) the decoded image content still ends up in the users home folder. 

Likewise, I bit the bullet and set up the Google Drive Sync, but that has the same effect as running a backup/restore - that is to say the shows move, but the content associated with the shows does not. On inspecting the .show files, I can see the absolute path is encoded - a simple solution to the original issue (and the extension of it that I am seeing) could be making that a relative path, and during installation the ability to select the path for all the content (or equally to be able to change this in the settings)?

I welcome comments and criticism of this approach...

**Comment by vassbo** [comment]
Thanks. Sounds like something that needs work.

**Comment by vassbo** [comment]
All data files that are not settings related are stored in a set "Data location". I also added an option to change the user data store path to that location in the settings (Save user data at data location), meaning they can stored in a synced folder or stored on a USB drive. Maybe not the safest to store the data on a flash drive, but I found a portable executable to be too slow for the use case.
