### ISSUE TITLE
NDI output

### ISSUE THREAD

**Issue by OnceI** [ChurchApps/FreeShow#287]
Hello, first of all fun to see the progress in the project!
Unfortunately, I am experiencing problems with NDI. I use Freeshow on computer 1 and NDI monitor on computer 2. Both connected with cat5e and cat6 cable and the longest distance to the router is 5 meters. They are the only devices on the network. Firewall and antivirus turned off on both computers.
When I use Freeshow NDI output, the video does not play smoothly. Tested both 30fps and 60fps in Freeshow and various low latency settings in NDI Monitor. The video stutters and hangs and becomes completely unusable on computer 2. When I instead use NDI screen capture on computer 1, both regular and HX, it works smoothly and it doesn't matter if Freeshow NDI is still on. I can also send two streams without problems. I monitored both computers resources (CPU, GPU, RAM) and neither was at 100% with two streams.

All help is gratefully received. And if you need anything else from me, I'll be happy to help.

Greetings Oncel from Sweden

**Comment by vassbo** [comment]
Try going to "Other" in the settings, and set "Preview frame rate" from "Auto" to "Full", then restart and try again. Does that work?

**Comment by OnceI** [comment]
Thank you! An easy fix and now it works like a charm.
