### ISSUE TITLE
Message Alerts

### ISSUE THREAD

**Issue by Benjamin72070** [ChurchApps/FreeShow#289]
I think it would be useful to have message alerts available on at least the stage output.  Would be great to have message alerts on whichever screen you wanted them on.  If it is possible and not too difficult, it would be great to have 2 different alerts.  One for the stage (foldback) output and the other for general use wherever you wanted to add it.  If any of this is easily added, it would be awesome to have a editable list of quick alerts to send.

**Comment by vassbo** [comment]
Shouldn't be very difficult. I guess I'll just use "Variables" for this.

**Comment by vassbo** [comment]
You can now add variables added under the "Overlays" drawer tab, to the "Stage" output.
