### ISSUE TITLE
Cannot enable NDI

### ISSUE THREAD

**Issue by Benjamin72070** [ChurchApps/FreeShow#290]
The enable NDI switch under outputs is greyed out.  I have installed NDI 5 Runtime.  Is there something else I need to do?

**Comment by vassbo** [comment]
NDI is currently not supported on Linux.

**Comment by Benjamin72070** [comment]
I know I was running FreeShow on lInux previously, but issues with OBS caused me to revert to Windows.  I am running FreeShow on Windows and enable NDI is greyed out even after installing the NDI runtime.  Do I need the SDK also?

**Comment by vassbo** [comment]
Probably because the data was moved from Linux. Try deleting the "os" entry in the "settings.json" file here: %AppData%/freeshow.
