### ISSUE TITLE
Importing many openLP songs issue

### ISSUE THREAD

**Issue by odlg** [ChurchApps/FreeShow#293]
Attempting to import 870 openLP songs shows a window with an "Importing" text and a checkmark button. Does that mean it is done importing?
I now have 23 songs in a created openLP folder in Shows.

I wish there was some progress information.
I wish there was some feedback with which song it failed to import and also some information regarding the problem.
Wonder if they are imported in the same order as shown in the file selector.

**Comment by vassbo** [comment]
If the "Importing" popup is still there, it means that it is in progress with the importing, but it might have failed. Are you able to send over a zip file with the OpenLP songs? So I can see what went wrong. I can also add a progress bar. And I think they are imported in the selected order, but they are sorted alphabetically in the drawer anyway.
