### ISSUE TITLE
[feature] Include MOV with alpha channel

### ISSUE THREAD

**Issue by GameFluencer** [ChurchApps/FreeShow#295]
With the lower thirds or the name popup. I have a .mov with a popup I like, but I noticed it doesn't support mov with alpha channel, maybe this can be included in a feature.

**Comment by vassbo** [comment]
The support for MOV files by Chrome/Electron is not very good. But you can use another video format called WebM.
Using a program called [Shutter Encoder](https://www.shutterencoder.com/), you can convert .mov files to .webm, see this video: https://youtu.be/C67S5x7QWzc?t=202
