### ISSUE TITLE
App crashes when opening midi control on linux

### ISSUE THREAD

**Issue by aforman75** [ChurchApps/FreeShow#296]
I am running free show on Ubuntu studio and when I open the action tab under settings  to add a midi command the app crashes. I am a Noob with Linux but trying to learn.  This is the message i get when I open the program in terminal. 
ALSA lib conf.c:4553:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
Segmentation fault (core dumped)
 Any help would be appreciated.

**Comment by vassbo** [comment]
Looks like a problem with the "JZZ" MIDI package, and the Ubuntu Studio distro, so I can't do much about it. Worked fine in my testing.
Have you tried this solution: https://askubuntu.com/a/1298612

**Comment by aforman75** [comment]
Unfortunately that did not work. I will try to uninstall free show and reinstall and see if that works.
