### ISSUE TITLE
Adding SVGs

### ISSUE THREAD

**Issue by Benjamin72070** [ChurchApps/FreeShow#299]
Is there a way to add an SVG?

**Comment by Benjamin72070** [comment]
I see that a SVG can be added to a slide at least by dragging it into the window.  I was hoping that I would be able somehow to change the color of a single color svg, but I see that is not possible and it makes sense.  Is there a way for us to add custom icons?

**Comment by vassbo** [comment]
Just click the "Icons", under "Items" to get a list of SVGs, here you can also add custom SVGs. When they are added as an item you can change the color and size.

**Comment by Benjamin72070** [comment]
I was trying so hard to figure out how to add shapes that I completely missed the "Manage Icons" at the bottom of the Icons page.  Thank you.  That is awesome.  Now, I can make some simple SVGs in Inkscape to enhance slides and template design.
