### ISSUE TITLE
Export to Project Pop up

### ISSUE THREAD

**Issue by ejbramos** [ChurchApps/FreeShow#300]
If possible, can you add an error or something regarding naming project since currently I am experiencing "Exported" Pop up when exporting projects but due to my project naming it is not exporting. Can you add specific characters that would allow to export. A video reference can be shown on this problem,

Link of the Video: https://we.tl/t-1ImyRsPr3t

P.S. Sorry you have to download the video first to watch

**Comment by vassbo** [comment]
Thank you. This will be fixed.
