### ISSUE TITLE
Trigger Action?

### ISSUE THREAD

**Issue by Benjamin72070** [ChurchApps/FreeShow#301]
When I pick Trigger from the Actions options, it just says nothing here.  I checked the documentation and it is not even referenced, so I have no idea how to use it.  I suspect it is similar to other programs based on JavaScript where you can trigger countdowns or even, if configured right, control OBS scenes with WebSockets.  

I currently use Bitfocus Companion to control cameras and OBS and the ATEM switcher instead of presentation software to trigger events, but it would be cool to have as an option if Companion does not have a plugin for other software or hardware that can be controlled this way.   I am aware that lots of software and hardware can be controlled via MIDI which you do have implemented.

**Comment by vassbo** [comment]
Yep, it's used to send a "command" via HTTP (often used to change a camera preset), something like this: http://IP?cam=2&preset=5

**Comment by Benjamin72070** [comment]
Where do you type in the trigger commands?  Am I just not seeing it in the settings?

**Comment by vassbo** [comment]
Sorry, I talked about the "Triggers" in the "Overlays" drawer tab. But in the "Actions" settings tab, you can press "Add" in the bottom center to add a trigger, they are activated when receiving a set MIDI input.
