### ISSUE TITLE
Persistent Custom Colors 

### ISSUE THREAD

**Issue by Benjamin72070** [ChurchApps/FreeShow#302]
Is there a way to add persistent custom colors to the color palette?  I currently just paste them into the CSS field for each slide or template.   It would just be easier and faster to use if they could be added to the palette.  I understand if it is too much work for the benefit.  I wish I was proficient in JavaScript.  I would contribute to the project with ideas including code.

**Comment by vassbo** [comment]
I guess this can be done.

**Comment by vassbo** [comment]
You can go into "Other" in settings and choose "Manage colors"
