### ISSUE TITLE
packaging: flatpak

### ISSUE THREAD

**Issue by yozachar** [ChurchApps/FreeShow#303]
Hi, really appreciate your work on FreeShow. I'd like to see it packaged as a Flatpak application and published on https://flathub.org/. I can contribute, if you guys are open to it?

**Comment by vassbo** [comment]
Thank you! If you are able to figure out a working solution we are open to any contribution.
Here is the "electron-builder" documentation on flatpak: https://www.electron.build/configuration/flatpak.html

**Comment by vassbo** [comment]
Closing as this is not generally supported by `electron-builder`: https://www.electron.build/flatpak

![bilde](https://github.com/user-attachments/assets/a77956fe-c571-44d6-b5a6-df43b6633f33)

**Comment by vassbo** [comment]
https://github.com/electron-userland/electron-builder/issues/7154
