### ISSUE TITLE
[BUG] Imported ProPresenter 7 Slides Lose Formatting

### ISSUE THREAD

**Issue by nhammake** [ChurchApps/FreeShow#305]
The text is there, but the custom font and sizes are lost on the import. Screenshots of the import and the correct format attached.

[IncorrectFormatting.zip](https://github.com/ChurchApps/FreeShow/files/13483401/IncorrectFormatting.zip)

**Comment by nhammake** [comment]
[Advent Title PRO File.zip](https://github.com/ChurchApps/FreeShow/files/13484485/Advent.Title.PRO.File.zip)

I figure this might make sense to also upload the PRO file in question I imported.

**Comment by vassbo** [comment]
I have chosen to not convert the formatting as they are stored in such different ways on the different softwares, and it would take a while to implement. And in most cases for song lyrics you are good with just using a new template. And in the other cases it does not take very long to add the styling again manually after it's imported. So this will unfortunately not be changed.
