### ISSUE TITLE
[Feature] AV1 & HEVC Video Format Support

### ISSUE THREAD

**Issue by nhammake** [ChurchApps/FreeShow#306]
My Pixel 6a Phone records in AV1 and I use it to record on the go footage with a wireless USB-C microphone. Adding the video though the media browser plays the sound, but with a black/blank picture. I have to convert it to H.264 with another program like Handbrake first for it to show up correctly.

I am starting to store 4K video backgrounds in HEVC/H.265 format for quality and storage saving and these files also play with black/blank video. Again, I have to convert to H.246 with Handbrake for them to work correctly in FreeShow.

**Comment by vassbo** [comment]
The Electron version used does not support HEVC/H.265. But support for it was recently added in Chromium, I have tried upgrading but had some issues with MacOS and Linux, also Windows 7/8 is no longer supported in that version. So I'll wait a bit longer to upgrade.
In the meantime, you can use a converter like this: https://www.onlineconverter.com/hevc-to-mp4

**Comment by vassbo** [comment]
The day is here! 🥳 Pre-release 1.2.5 should support these formats! Just make sure the hardware acceleration is not disabled! (Settings>"Other", turn off "Disable hardware acceleration"!)
