### ISSUE TITLE
[Feature] Set Video Start and End Points

### ISSUE THREAD

**Issue by nhammake** [ChurchApps/FreeShow#307]
It would be nice to be able to take a raw video from my phone and throw it in FreeShow and set a Start (In) and End (Out) point so I don't have to edit the beginning and end of it and export the video with another program. I record a bit of silence before and after videos to make sure I have enough video to fade between segments, and sometimes it's too much and needs cut down.

**Comment by vassbo** [comment]
Good suggestion.

**Comment by vassbo** [comment]
Video times can be added in the video "Edit" section on the right.
