### ISSUE TITLE
Auto size respect line breaks?

### ISSUE THREAD

**Issue by Joost1991** [ChurchApps/FreeShow#309]
Hi,

Thanks for your excellent tool! Our church is currently looking into this tool to replace Easyworship, since it would allow us to prepare at home for every member of our technical team.

One thing I seem to miss from Easyworship is the feature to auto size the text. Yes, you can do this currently in FreeShow by using the 'Auto Size' feature, but one major difference is that EasyWorship respects the longest line and does the resizing based on that. 

Does FreeShow currently support this? Or is there a CSS thing I can apply to manage the same?

Thanks!

**Comment by vassbo** [comment]
I figured out you could just use this CSS property: "white-space: nowrap;"
But will add a toggle in the next update. 😊
