### ISSUE TITLE
Lower third

### ISSUE THREAD

**Issue by Prezib** [ChurchApps/FreeShow#314]
We are struggling to set up a lower third for our stream. We use an image like the attached but are unable to fit the scripture and reference into it. What do you suggest or can you add the scripture as an item in the editor? 
[logo lower third new.zip](https://github.com/ChurchApps/FreeShow/files/13532789/logo.lower.third.new.zip)

**Comment by vassbo** [comment]
Looks like images in templates don't work properly currently.

**Comment by vassbo** [comment]
You should be able to add "Image" items to templates and they will be used properly in scriptures now.
