### ISSUE TITLE
Scripture not showing

### ISSUE THREAD

**Issue by mtgileadtech** [ChurchApps/FreeShow#315]
Went to bring up scripture for todays service. It is not working right. I can click on Book of bible that I need but it never shows chapter numbers or verse numbers or verse it self. All it shows beside the books of the bible is a circle with pink going around it. I have even updated to new version. v0.09.9 and v1.0.0 both have issues as well as previous versions.

**Comment by vassbo** [comment]
Probably the Bible API that's overloaded. Have reached out to them to increase the limit, but haven't received any response yet.
