### ISSUE TITLE
TYPING ISSUE & TEXT PREVIEW

### ISSUE THREAD

**Issue by SKU003** [ChurchApps/FreeShow#317]
Hi, so when I try to type as you can see in the video, I tried to move the "upon" bottom of the other text and so I tried to first remove the space and then enter so it can go underneath but as you see the type indicator went straight back to the begin of the text, meaning enter doesn't bring it under a text like in ProPresenter or even Microsoft Word.

Also, let me add that I've noticed that the preview of the text doesn't follow the text the moment you use "Auto Size". As seen at the moment, the Text is still big yet I've changed it back to Font size 100.

![FreeShow_B0dPVlcJAJ](https://github.com/ChurchApps/FreeShow/assets/117542049/42e51bde-d48d-4db1-9d20-b9f6b33d72d9)

**Comment by vassbo** [comment]
I could not replicate this behaviour, works as expected for me. Does this happen on all songs, or just this one?

Also the preview on the left not updating after turning off the "Auto size" is only temporary, and updates when you leave "Edit" mode, so I don't see any need to do anything about that.

**Comment by vassbo** [comment]
Okay, closing for now. Let me know if you experience it again, and maybe know why.
