### ISSUE TITLE
DELAY WITH OPENING APP

### ISSUE THREAD

**Issue by SKU003** [ChurchApps/FreeShow#318]
Hi, so I was having an issue where I realised I would double press on FreeShow thinking I hadn't actually pressed on it but it because I realised it didn't close the start menu like the way ProPresenter or any other app would have done the moment you'd clicked on it. This would lead me opening more than one FreeShow program. And for a moment thought that it didn't close at all.

https://github.com/ChurchApps/FreeShow/assets/117542049/5b94769c-5a6c-4a2e-b2fc-2ea9477383f2

**Comment by vassbo** [comment]
Thanks. I'll see what can be done about this.

**Comment by SKU003** [comment]
Thank you for your response, and be blessed.

**Comment by vassbo** [comment]
Is this better in the latest update?

**Comment by vassbo** [comment]
Is this better in the latest update?
