### ISSUE TITLE
Process has to be manually killed

### ISSUE THREAD

**Issue by bwhitson** [ChurchApps/FreeShow#319]
I can dump what ever info you need but please see the video. The process never dies. This happens on both Ubuntu 22.04.03 and macOS 14. I've left the process running over night on my Ubuntu desktop and it never dies.

https://github.com/ChurchApps/FreeShow/assets/55523413/9c7590a1-17cb-4ba2-9b87-d6064d4999df

**Comment by vassbo** [comment]
Thanks. I'm guessing it's the output window process that's not closing. I'll take a look.

**Comment by bwhitson** [comment]
I can't seem to get a screen shot of it but when I right click the remaining icon in my mac's launcher the window showing open is in fact the "output"... so confirmed... I guess?

![Screenshot 2023-12-08 at 10 02 28 AM](https://github.com/ChurchApps/FreeShow/assets/55523413/edf68362-4ba3-43f9-b514-c5ff3605fe21)

**Comment by vassbo** [comment]
This should work in the latest version. Let me know if not.
