### ISSUE TITLE
BLUR BOX EDIT BUGGING OUT

### ISSUE THREAD

**Issue by SKU003** [ChurchApps/FreeShow#320]
Hello, hope you're well.

When going to edit, the blur box is bugging out. Just thought you should know.

And let me just say again I adore this software, absolute pure genius it is.

EDIT: So apparently with the other video, I'm not quite so sure now what's the problem

https://github.com/ChurchApps/FreeShow/assets/117542049/5c599e97-cdfe-4999-91e8-84ec7d1129b5

https://github.com/ChurchApps/FreeShow/assets/117542049/e810c1f6-71f5-4b98-bee2-0dd4eb1f881f

**Comment by vassbo** [comment]
Managed to fix it by disabling the scroll bar when not zoomed in.
