### ISSUE TITLE
HOW TO IMPORT BIBLES?

### ISSUE THREAD

**Issue by SKU003** [ChurchApps/FreeShow#328]
I'm having issues to importing Bibles, causes I'm not sure how exactly, thought when I go to import scriptures I would be able to import by a link or just by taking from videopsalm. I just don't know how thought if I click on opensong icon or freeshow on scripture was a link. I just wanted to download the Bible Version.

![Files_0JQYI8STJz](https://github.com/ChurchApps/FreeShow/assets/117542049/1af96a7e-a691-4968-98cd-62b26b2f0f05)

![Files_qNLy5J7Evv](https://github.com/ChurchApps/FreeShow/assets/117542049/8b1621a4-100f-4a00-bd48-f662e422a819)

**Comment by vassbo** [comment]
You can use a bible from the API. Or a local bible that has to be in Zefania or beblia.com in XLM format, or OpenSong format. You can search the web to find some.
Please go to "Import", then "Scripture", select the correct format, and choose the file.
