### ISSUE TITLE
SongSelect Import

### ISSUE THREAD

**Issue by AndyGysau** [ChurchApps/FreeShow#329]
Hello everyone,
Is there a function for SongSelect (CCLI) import in the near future?
What I would also miss is that you can display a video link from Canva.

I look forward to an answer from you.

Kind regards, Andy

**Comment by vassbo** [comment]
We'll see what can be done about this.

**Comment by AndyGysau** [comment]
Thank you.

**Comment by vassbo** [comment]
I were not able to get an API access token at the moment.
But you can just search and copy any lyrics from https://songselect.ccli.com/, and import quickly into the program from the clipboard.

As for the Canva video, you can just add and use the "Website" item on a slide.

**Comment by vassbo** [comment]
Update: https://github.com/ChurchApps/FreeShow/issues/572#issuecomment-2163179642
