### ISSUE TITLE
Saving any changes made (bug)

### ISSUE THREAD

**Issue by therealloej** [ChurchApps/FreeShow#330]
There seems to be a bug where you can't save any of the changes you make and you are forced to "Quit without saving", 
this is something I noticed after the 1.00 release.

But overall, thanks for the great work!

**Comment by vassbo** [comment]
Thanks. This happens when you load a local scripture, so it works as long as you don't open the "Scriptures" tab in the drawer. But there will be an update with a fix very soon!

**Comment by vassbo** [comment]
This is resolved in the latest version.

**Comment by therealloej** [comment]
Oh wow that was fast! 😅 Thanks for the heads up will be updating to
Version 1.1.0
