### ISSUE TITLE
Need to toggle video feed resolution

### ISSUE THREAD

**Issue by olatimmy** [ChurchApps/FreeShow#331]
There is no option to toggle the video feed resolution like in propresenter

**Comment by vassbo** [comment]
What would be the use case for this?
You can change the resolution ratio in the "Styles" setting, the resolution set here will affect a NDI feed being sent. It won't directly affect the output as that is determined by the video resolution itself, and text is vectored meaning they will have "infinite" resolution.

**Comment by olatimmy** [comment]
The problem is I can't scale the video feed to fit the resolution of the
screens I am using

**Comment by vassbo** [comment]
Have you tried changing "Media fit" to "Cover" in "Styles"? That should stretch the video to fill the screen resolution.

**Comment by olatimmy** [comment]
Yes i have, it doesnt seem to solve it

**Comment by vassbo** [comment]
"Media fit" should work properly for videos also in the latest version.
