### ISSUE TITLE
Can we have a planning center

### ISSUE THREAD

**Issue by olatimmy** [ChurchApps/FreeShow#333]
can we also have a planning center as https://www.worshiptools.com/en-us/planning?utm_source=desktop

**Comment by vassbo** [comment]
I suggest using [B1Church](https://b1.church/), also by ChurchApps. We might integrate the two solutions with each other sometime.

**Comment by vassbo** [comment]
Try it out: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.6-beta.1
https://freeshow.app/docs/faq#planning-center-integration

**Comment by m-esag** [comment]
> I suggest using [Chums](https://chums.org/), also by ChurchApps. We might integrate the two solutions with each other sometime.

I just saw today from the newsletter about the new update and saw that this is new. My church is starting to use planning center but I am interested to see CHUMs and are there plans for integration to advise people to use it.

**Comment by vassbo** [comment]
Nice! I actually realized that CHUMS does not have a service planner at the moment, but if we get that added, it's a possibility.
