### ISSUE TITLE
Control OBS through actions

### ISSUE THREAD

**Issue by dsaderholm** [ChurchApps/FreeShow#334]
I'd like the ability to switch scenes and go live in Open Broadcaster Software by adding an action to a slide in FreeShow. I have tried using a "Send MIDI out" action with obs-midi-mg and a loopback MIDI device on both MacOS and Windows, but on Mac it crashes OBS, and on Windows it works unreliably. One of the easiest way to do this would probably be using OBS WebSocket.

**Comment by vassbo** [comment]
Found this: https://www.reddit.com/r/obs/comments/z3ixzg/switching_scenes_based_on_browser_url/?rdt=60354
You can try using this [Advanced Scene Switcher](https://obsproject.com/forum/resources/advanced-scene-switcher.395/) to change the scene using the [HTTP Triggers](https://freeshow.app/docs/overlays#triggers).

**Comment by vassbo** [comment]
Found this: https://www.npmjs.com/package/obs-websocket-js
But I guess it would be better to integrate FreeShow into Bitfocus Companion.

**Comment by dsaderholm** [comment]
I attempted to use the Advanced Scene Switcher, but It didn't work. OBS websocket doesn't support HTTP Triggers unless you use a third party program, but that didn't work for me. That second comment looks good, though.

**Comment by dsaderholm** [comment]
Any updates on this? This would be so nice to automate my live stream.

**Comment by vassbo** [comment]
Yes, I just made a working module two days ago. It will work in the next update. 😊

**Comment by TPaulManohar** [comment]
@dsaderholm 
Please check out our video for controlling OBS from freeshow with using Functions. I hope this can help you.

https://youtu.be/iheqxahuByA
