### ISSUE TITLE
"Next After Media" Not Working

### ISSUE THREAD

**Issue by yoramdes** [ChurchApps/FreeShow#335]
I tried putting 2 videos, one to play after the next, and toggled the "Next After Media" action, but it wasn't working and would just loop the first video. After some time it finally worked, but only once, and when the first video ended, it would replay the first few seconds of the first video before switching to the next.

**Comment by thuox** [comment]
This issue seems to have resurfaced. Adding "Next After Media" to a slide with a video on it doesn't go to the next slide when the video ends in 1.1.3.

**Comment by yoramdes** [comment]
It works now, but it still replays the first seconds of the first media before switching to the next media. It would be greatly appreciated if you can fix that

**Comment by vassbo** [comment]
I think this should be better in the latest version.
