### ISSUE TITLE
Bible keyword Searching

### ISSUE THREAD

**Issue by Prezib** [ChurchApps/FreeShow#337]
Hi, will it be possible that when using the keyword search we can click the search result you want to go live directly from the search result page? Right now, we have to make a note of the scripture reference and then type it

**Comment by vassbo** [comment]
You can create a scripture collection to show multiple versions at the same time. I don't see any good use case to change version to the same reference.

**Comment by Prezib** [comment]
Thanks, the use case is when pastor is preaching and wants to read from
different versions not at the same time. I think because we use to use
easyworship and this made it easier for us.

For example if we read Gen 1:1 in nkjv and he wants to read in amplified
and later NLT to better explain. Unfortunately we don't get the scriptures
before time that's why it's tricky

**Comment by vassbo** [comment]
Okay, makes sense. I'll see what can be done.
