### ISSUE TITLE
media background flashes

### ISSUE THREAD

**Issue by Prezib** [ChurchApps/FreeShow#339]
I may be doing something wrong, but when I have a media background of my slide it flashes when content changes. I have

https://github.com/ChurchApps/FreeShow/assets/139170824/4ef6fcb0-78dc-4572-832c-af707deb9858

 included a video

**Comment by vassbo** [comment]
Yep, that's the fade transition, you can turn that off for that specific item, in the template. By right clicking on the image item, and setting transition to "none".

**Comment by Prezib** [comment]
Hi, I had raised this earlier and you advised it was the transition which I have now checked and it still flashes despite being none. Not sure if there is anything else I am doing wrong
[FreeShow 2023-12-18 18-10-22.zip](https://github.com/ChurchApps/FreeShow/files/13707135/FreeShow.2023-12-18.18-10-22.zip)
