### ISSUE TITLE
Wrap Scripture text 

### ISSUE THREAD

**Issue by Prezib** [ChurchApps/FreeShow#340]
Also , can the scripture preview be wrap text so we can see the full text instead of 3 dots. picture attached
<img width="738" alt="Screenshot 2023-12-17 233334" src="https://github.com/ChurchApps/FreeShow/assets/139170824/8bccc9f3-35d3-44b7-a747-4ea51a8369ca">

**Comment by vassbo** [comment]
I think that will make it much more cluttered, and harder to select verses. You can see the full verse in the preview by selecting it.

**Comment by Prezib** [comment]
Thought about that, the issue arise because on a smaller screen you cannot
see both the preview box and scripture preview. We closed the preview
section to give the preview more space but that meant you can't actually be
sure of what verse you are putting up

**Comment by Prezib** [comment]
Unless the scripture preview box, can be moved to the top where the show
preview slides go when you go to the scripture tab?

**Comment by vassbo** [comment]
Makes sense, I can make it so all text shows up when the preview is closed then. :)

**Comment by Prezib** [comment]
Awesome, thank you so much!
