### ISSUE TITLE
Next slide preview during songs

### ISSUE THREAD

**Issue by StevePirateX** [ChurchApps/FreeShow#344]
**Feature Request:**

Various presentation software allows the congregation to preview the next slide/content during the song.

It allows for the congregation to know what's coming up in case the lyrics are really fast to sing or if the operator misses the cue etc.

[Proclaim's Implementation](https://support.proclaim.logos.com/hc/en-us/articles/19863388529805-Dynamic-Lyric-Scrolling-Song-Transition)

**Comment by vassbo** [comment]
This can be done using the "Mirror" item, and enabling "Next slide text".
