### ISSUE TITLE
alert ticker

### ISSUE THREAD

**Issue by Prezib** [ChurchApps/FreeShow#345]
Is there a way to include an alert ticker function like in Easy Worship? We use this to put up quick messages like move your car, pick up children or for quick messages

**Comment by vassbo** [comment]
In the "Overlays" tab in the drawer, you can create different overlays/alerts to show different messages.

**Comment by Benjamin72070** [comment]
Kristoffer, is there a way to assign overlays to specific outputs?  We might need to send alert to congregation, but we might also need to send a message only to the pastor or others on the confidence monitor, but not the main output.  I know we had discussed the use of variables on the stage monitor.  When you are a one man operation in the AV department, you need a quick button to send messages.  I don't always have time in a busy service to open the stage display and show and dismiss the variables,  Maybe they can be assigned to hotkeys?

**Comment by vassbo** [comment]
Only the active output will show the overlay selected, so when you just select one of the outputs in the top right the overlay will just get applied to that one. For the stage you can just permanently have the variable there, but just add the text when you want to show it. I might add a toggle in "Variables" to show/hide the values, that way you can create one overlay and one stage view 
 that show all the time (but invisible) with all the different messages, and just toggle them easily at the same time from the drawer.
