### ISSUE TITLE
Need to scale video feed

### ISSUE THREAD

**Issue by olatimmy** [ChurchApps/FreeShow#346]
I am not able to scale the video feed, could it be because I am using an av to USB converter. 

![超级截屏_20231224_103139](https://github.com/ChurchApps/FreeShow/assets/153416781/e69eebdd-39e8-4bd4-a3d6-4729efdc4ed7)
![超级截屏_20231224_103123](https://github.com/ChurchApps/FreeShow/assets/153416781/b9ed3b25-1e8c-4e30-894f-c64bdf83c9ec)
![超级截屏_20231224_103056](https://github.com/ChurchApps/FreeShow/assets/153416781/ce833bbf-d7b6-4499-aee6-50d14e69c1d7)
![超级截屏_20231224_103039](https://github.com/ChurchApps/FreeShow/assets/153416781/40b63ce9-196d-48c9-ab0e-c0829149cc50)

**Comment by vassbo** [comment]
Should work in the next update. :)
https://github.com/ChurchApps/FreeShow/issues/331
