### ISSUE TITLE
Keynote Import

### ISSUE THREAD

**Issue by ejbramos** [ChurchApps/FreeShow#347]
I just want to suggest this feature to add a keynote import feature since some apple users uses keynote as a presentation tool rather than powerpoint since it is free. We can use online converters for Keynote to PPTX but sometimes it changes format so if possible for it happen. I would be great

**Comment by vassbo** [comment]
You can **import both Keynote and PowerPoint presentations as PDF**, that will keep all the layout correct, without transitions. Importing PowerPoint directly is just extracting the text currently, as it would be a lot of work implementing support for correct PowerPoint format, that means I also do not have any plans currently of doing it for Keynote unfortunately.

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/491
