### ISSUE TITLE
smarty tags?

### ISSUE THREAD

**Issue by Benjamin72070** [ChurchApps/FreeShow#348]
Is there a way to easily add {smarty tags} in slides for things like slide numbers, group names or such?  In Holyrics, there is a way to list the verse number on the slide and even the metadata using a menu.  I would think an easier way to do that is with tags.  I know there is  way to add metadata to the slides via the metadata tab, but this would give way more flexibility and allow creating different templates with different metadata formats.  It could also be used to add custom HTML and CSS tags like in OpenLP.   And also, Merry Christmas.

**Comment by vassbo** [comment]
Merry Christmas! 😃 I'll see.

**Comment by vassbo** [comment]
Right click a textbox to get a list of "Dynamic values" you can use.
