### ISSUE TITLE
controlling FreeShow via HTTP

### ISSUE THREAD

**Issue by Benjamin72070** [ChurchApps/FreeShow#349]
I know there is a way to control FreeShow via MIDI.  I have been told that MIDI control can be hit or miss.  Is there a way to control the app via HTTP commands or JavaScript?  I only ask because it is an Electron app and has a webserver.

**Comment by vassbo** [comment]
You have HTTP "Triggers" in the "Overlays" tab, I don't think they work in this version, but they will in the next one.

**Comment by Benjamin72070** [comment]
I think I must not have explained what I meant very well.  I am speaking of an API of sorts for FreeShow.  I was meaning incoming HTTP commands instead of outgoing commands.

**Comment by vassbo** [comment]
Makes sense! I am hoping to integrate FreeShow into Bitfocus Companion. That would make that possible.

**Comment by crbon** [comment]
+1

**Comment by winternet-studio** [comment]
It needs to have both a REST and WebSocket API - like ProPresenter has. The WebSocket API we eg. use for receiving change events so we can change the look on the stage display between songs and other type of slides.

**Comment by BalogAbel** [comment]
+1 for this feature. It would make FreeShow easy to integrate to any software or workflow

**Comment by vassbo** [comment]
Added WebSocket/REST API in the latest version, as well as a Bitfocus Companion module. 😊
You can find all the API commands in this file: https://github.com/ChurchApps/FreeShow/blob/main/src/frontend/utils/api.ts
