### ISSUE TITLE
Icon color not changing

### ISSUE THREAD

**Issue by Benjamin72070** [ChurchApps/FreeShow#350]
The icons that you have installed for us to use are able to have their color changed.  When I upload an SVG that I have found or created using Inkscape, the color does not change even if I pick a color.  Where do I find SVGs that it is possible to change the color of?  Is there something I can alter in the SVG code to make this work?  Also, is it possible to add opacity to icons?

**Comment by vassbo** [comment]
You can edit the SVG to change the color, the thing is that some SVGs have multiple colors, but I'll see if it can be done if a color is selected. Also you can change the opacity in the "Item" tab.

**Comment by Benjamin72070** [comment]
The only way that I found to change the opacity of the icon is under foreground opacity, but that changes the opacity of everything but the background.

**Comment by vassbo** [comment]
![image](https://github.com/ChurchApps/FreeShow/assets/17619496/eed9c69c-ee08-4007-a8c3-b9795fa312ee)
