### ISSUE TITLE
Support linux arm64

### ISSUE THREAD

**Issue by odlg** [ChurchApps/FreeShow#352]
I now have a MacBook Pro M2 running Asahi Linux and I would like to run FreeShow on it. I tried to build it by running:
`npm install`
`npm run build`
`npm run release`
The last command fails with:
![image](https://github.com/ChurchApps/FreeShow/assets/2950255/a486e058-d819-4fa0-8d96-342ea5ad5d7b)

At that point the appimage is built. But running it fails with:
`./FreeShow-1.1.0-arm64.AppImage: error while loading shared libraries: libz.so: cannot open shared object file: No such file or directory
`
In `dist/linux-arm64-unpacked` the `freeshow` command works and invokes FreeShow.

**Comment by vassbo** [comment]
The .AppImage and .deb version from the web should work.

I have pushed a small change to the dev branch now, try if that works.
If you just need it for testing you can use the "npm start" command. (You might need to increase the app start timeout in "index.ts", if the building takes longer)

**Comment by odlg** [comment]
The .AppImage and .deb files from the web are x86_64. Recent MacBooks use 64-bit arm processors. Attempting to execute it gives an error:
```
$ ./FreeShow-1.1.0.AppImage 
bash: ./FreeShow-1.1.0.AppImage: cannot execute binary file: Exec format error
$
```
The changes you committed does not make the produced  `FreeShow-1.1.0-arm64.AppImage` work.

**Comment by vassbo** [comment]
Okay. Try using "npm run release --arm64". Does that work?

**Comment by odlg** [comment]
Still exact same error as screenshot above running `npm run release --arm64`
Attempting to run the AppImage gets:
```
$ ./dist/FreeShow-1.1.0-arm64.AppImage 
./dist/FreeShow-1.1.0-arm64.AppImage: error while loading shared libraries: libz.so: cannot open shared object file: No such file or directory
$
```

**Comment by odlg** [comment]
Looks like an upstream issue: https://github.com/electron-userland/electron-builder/issues/7835

**Comment by vassbo** [comment]
Hmm... I also found this: https://github.com/AppImage/AppImageKit/issues/1092#issuecomment-1346367364
Does that work?

**Comment by odlg** [comment]
Yes, now the AppImage works.

**Comment by vassbo** [comment]
Awesome! Now it's just the case of creating releases that also works..

**Comment by odlg** [comment]
When starting the AppImage, there are troubles checking for new versions, I guess. But that is not surprising as it is not supported yet. :-)
```
Checking for update
Error: Error: Cannot find latest-linux-arm64.yml in the latest release artifacts (https://github.com/ChurchApps/FreeShow/releases/download/v1.1.0/latest-linux-arm64.yml): HttpError: 404 
"method: GET url: https://github.com/ChurchApps/FreeShow/releases/download/v1.1.0/latest-linux-arm64.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Sat, 30 Dec 2023 20:21:24 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "AB9E:48C76:CCDB5EC:D003655:65907BC4"
}
    at createHttpError (/tmp/.mount_FreeSh6mpdYn/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_FreeSh6mpdYn/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/tmp/.mount_FreeSh6mpdYn/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:527:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6915)
    at SimpleURLLoaderWrapper.emit (node:events:527:28)
    at Object.newError (/tmp/.mount_FreeSh6mpdYn/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:47:19)
    at GitHubProvider.getLatestVersion (/tmp/.mount_FreeSh6mpdYn/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:75:46)
    at async AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_FreeSh6mpdYn/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:298:19)
    at async AppImageUpdater.doCheckForUpdates (/tmp/.mount_FreeSh6mpdYn/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:312:24)
(node:243405) UnhandledPromiseRejectionWarning: Error: Cannot find latest-linux-arm64.yml in the latest release artifacts (https://github.com/ChurchApps/FreeShow/releases/download/v1.1.0/latest-linux-arm64.yml): HttpError: 404 
"method: GET url: https://github.com/ChurchApps/FreeShow/releases/download/v1.1.0/latest-linux-arm64.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
```

**Comment by vassbo** [comment]
Looks like it can't be build using GitHub actions yet: https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/

**Comment by vassbo** [comment]
Linking this: https://github.com/electron-userland/electron-builder/issues/5689#issuecomment-792876001

**Comment by odlg** [comment]
The link in https://github.com/ChurchApps/FreeShow/issues/352#issuecomment-1872610616 seems to relate to running the original OSX on the arm mac. I am running linux on it. 
Universal binaries is a Apple OSX thing.

**Comment by vassbo** [comment]
Yes, but I need the same config for the electron builder packaging on Linux.

**Comment by vassbo** [comment]
I looked into it a bit more, and managed to make it work with this configuration:
```json
"target": [
    {
        "target": "AppImage",
        "arch": ["x64", "arm64"]
    },
    {
        "target": "deb"
    }
]
```

**Comment by vassbo** [comment]
Please check out the arm64 version on the website: https://freeshow.app/downloads
And let me know if it works or not. 😉

**Comment by odlg** [comment]
It works just fine.

**Comment by vassbo** [comment]
Awesome! 😁

**Comment by yanguoyu** [comment]
> It works just fine.

Hi, does the arm64 work well with your arm64 computer? Could you tell me if you downloaded the AppImage or Deb?

**Comment by odlg** [comment]
@yanguoyu I use the AppImage. You need to make it executable first, see https://appimage.org/ for how to run an AppImage

**Comment by yanguoyu** [comment]
> @yanguoyu I use the AppImage. You need to make it executable first, see https://appimage.org/ for how to run an AppImage

Hi, I have made it executable. My Linux version is Ubuntu 24.04.6 and is Arm64. And after I execute the AppImage, there's nothing happened.

<img width="789" alt="image" src="https://github.com/ChurchApps/FreeShow/assets/12881040/8e1c8ea1-eda6-46f9-9cd7-232b1c5bf924">

**Comment by odlg** [comment]
If you start it in a terminal, do you get any output?
I get:
```
Starting FreeShow...
libva error on Linux can be ignored
Loading main window content
REMOTE on: 5510
STAGE on: 5511
[97544:0104/092029.063932:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[97544:0104/092029.070607:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[97544:0104/092029.076130:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Capture - starting: default
Checking for update

```

**Comment by yanguoyu** [comment]
> If you start it in a terminal, do you get any output? I get:
> 
> ```
> Starting FreeShow...
> libva error on Linux can be ignored
> Loading main window content
> REMOTE on: 5510
> STAGE on: 5511
> [97544:0104/092029.063932:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
> [97544:0104/092029.070607:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
> [97544:0104/092029.076130:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
> Capture - starting: default
> Checking for update
> ```

It will throw exception like this

<img width="576" alt="image" src="https://github.com/ChurchApps/FreeShow/assets/12881040/bbd6d46e-e641-41fe-a6be-7a47ab8d03cd">

**Comment by odlg** [comment]
Aarh, yes, you need the workaround mentioned in https://github.com/ChurchApps/FreeShow/issues/352#issuecomment-1872597569

**Comment by yanguoyu** [comment]
> Hmm... I also found this: [AppImage/AppImageKit#1092 (comment)](https://github.com/AppImage/AppImageKit/issues/1092#issuecomment-1346367364) Does that work?

Thanks, I mistakenly thought that the action was executed on the package machine. It was needed to execute on my computer.
