### ISSUE TITLE
TRANSITIONS BUG

### ISSUE THREAD

**Issue by SKU003** [ChurchApps/FreeShow#353]
Hi, I don't know what can cause it, but it's like the transitions works when it wants too. Cause when I wanted to take footage of it, it started working again even when I closed and opened it again it worked but honestly most of the time it never works even when I try other transitions and this is both for text and Media transition. Because I'm sure the next time I open it, it won't work.

**Comment by vassbo** [comment]
I'll see if I can figure it out. Hiding and showing the outputs again after the app has started should make the transitions work always.

**Comment by vassbo** [comment]
Let me know if you still experience this in the latest version. I'm not sure what causes it.

**Comment by lwallace22** [comment]
could you advise which version does not have this issue ?

**Comment by vassbo** [comment]
@lwallace22 Looks like it happens sometimes for some users in all versions.
