### ISSUE TITLE
Selectable multiple outputs

### ISSUE THREAD

**Issue by webnerdnick** [ChurchApps/FreeShow#354]
This is something no  other software like this has but would be AWESOME.  First off, ability to assign multiple outputs, with ability to link/group. But here’s the best part- for each slide, the ability to decide which output to send it to. Link or grouped outputs get the same, but with the ability to send a slide or even a component of a slide to another output would be killer.  Use case: we have 3 screens up front for the audience. A huge screen in the middle for backgrounds and key points and 2 smaller screens on the right and left which display lyrics and Bible passsages.  It’d be great to create a presentation with all the passages and then throughout have slides that have points or themes for the center screen. And as you progress through the presentation, everything gets displayed where you want it.  Perhaps this is done through tagging a slide for which output it goes on, or some other context menu with visual cues.  In PP7 there are some complicated ways around doing this using “looks” but this isn’t native in any of the different software I’ve used or tested.

**Comment by vassbo** [comment]
Awesome suggestion!

**Comment by vassbo** [comment]
Right click any slide to "Bind to" any outputs.
