### ISSUE TITLE
Stage View Scripture Display

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#358]
I tried all that I could but I couldn't figure out how to display the scripture in the stage view. Can you please help me out with it

**Comment by vassbo** [comment]
Currently you have to create a show from the scriptures in the bottom right, for them to show in the stage output.

**Comment by abhishikthraj** [comment]
Oh got it, but I think it would be more easier to do it directly on double clicking the scripture. This will be very helpful as we can display the scripture on the go as the speaker quotes.
