### ISSUE TITLE
Lower thirds Image Issue

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#359]
I have a lower third on the green screen in my output. In my lower thirds template I have two items, one is the textbox and the other is the media item. I have added an image to the slide but it is being displayed in the lower third position but not in the media postion

**Comment by abhishikthraj** [comment]
@vassbo This is the exact same issue when I tried adding the Timer item to the same template

**Comment by vassbo** [comment]
Okay, I'll take a look.
