### ISSUE TITLE
The app frequently freezes 

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#360]
I don't understand what the issue might be but the application is freezing a lot of times. Thankfully it didn't happen during the meeting but this has been a constant issue since the last update and it is persisting in the latest update too. Refer the attached video for reference. Thank you

https://github.com/ChurchApps/FreeShow/assets/58181678/48ddf8a9-f85d-434d-bea5-212505610f09

**Comment by vassbo** [comment]
Please go to settings, "Other", and click "Open log file". If you can send over the log file I can probably figure out what is causing it.

**Comment by abhishikthraj** [comment]
Here is the log file attached.

[error_log.json](https://github.com/ChurchApps/FreeShow/files/13816721/error_log.json)

**Comment by vassbo** [comment]
Thanks.

**Comment by ip4368** [comment]
This should be fixed by https://github.com/ChurchApps/FreeShow/commit/915e4205f92dc435330c0fa49aead50debb2b69d

It is yet to be released. I think v1.1.0 is free from this bug.
