### ISSUE TITLE
PPT Support

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#361]
Does free show support powerpoint presentations to be imported as slides? If yes, can you please help me out how to add one. If not, I request you to kindly add that feature.

**Comment by vassbo** [comment]
Yes, in the top left, in the "File" menu, you can click "Import". Here you can choose either "PowerPoint" to import just the text, or choose "PDF" to import the slides as images with styling. This means you have to export or convert the PPTX file to a PDF file.

**Comment by abhishikthraj** [comment]
Oh thanks, also can you let me know how to play videos from free show in the audience output screen. I have tried doing that from the media tab but I couldn't play. It made the screen blank.

**Comment by vassbo** [comment]
It should play when you just click on the video, but make sure if you have set any "Styles" that the "Background" layer is enabled. If not does images work, or are they also blank?

**Comment by abhishikthraj** [comment]
The images are working fine but I faced the issue only with the video. I was able to play one video while testing but it didn't work during the meeting. I'm nit sure what's the issue

**Comment by pratikspatel813** [comment]
Does importing PPT files work on Mac?

**Comment by vassbo** [comment]
It should work.

**Comment by pratikspatel813** [comment]
PPT file extension: I got the finished dialogue box, but no slides populated. 
PPTX file extension: All it says is importing

**Comment by abhishikthraj** [comment]
I'd rather suggest you to have a feature where you can import the text from ppt or import the ppt along with the formatting

**Comment by vassbo** [comment]
Importing PowerPoint with formatting is a lot of work, so I won't do that at this point in time.

**Comment by abhishikthraj** [comment]
Okay no problem

**Comment by crbon** [comment]
+1

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/491
