### ISSUE TITLE
Windows security issue

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#362]
I have been getting this security error is being popped up while I'm installing this application. Can you please have a look at this please

![image](https://github.com/ChurchApps/FreeShow/assets/58181678/ae27cf2f-6e6a-4f63-960f-320cf7af0f7d)
![image](https://github.com/ChurchApps/FreeShow/assets/58181678/389cd9a8-2785-4af8-9217-f2b762b0b27c)

**Comment by vassbo** [comment]
Yeah, we have just tried code signing the app, if it works, this error should go away when enough people have installed the app. If not we will try to make it work. It might take some time.

**Comment by abhishikthraj** [comment]
No problem, you are doing great work mate
