### ISSUE TITLE
Not an issue, just grateful this exists.

### ISSUE THREAD

**Issue by timmypidashev** [ChurchApps/FreeShow#365]
Just wanted to get in here and say thank you to the devs, I just randomly stumbled on this in my github feed, and this is going to up our church presentation game big time. We have been using softprojector for bible and propresentor for slides concurrently, and it has been a pain. So much overload i started writing my own simple program to fix all of our issues and add some features we've been missing, though it hasn't gotten far yet. I'm glad I didn't put in too much time into my software yet because freeshow seems to have all the features we can ask for, including multiple custom outputs. Very grateful for all the time put into it, this made my day. I will do my best to contribute back some day as well, seeing as this is a very neat codebase too. Thx yalls :heart:

**Comment by vassbo** [comment]
Thank you so much for taking you time writing this @timmypidashev. It means a lot! 😊 We are always happy for help.
Hope you get good use of it. And if you are missing a specific feature, please feel free to request it. 😄
