### ISSUE TITLE
Application freezes when trying to assign a group through right-click menu AFTER renaming a group

### ISSUE THREAD

**Issue by vbc-plano-av** [ChurchApps/FreeShow#366]
Error log attached. Groups had been working fine, but I recently edited the global groups and now it freezes whenever I try to right-click and choose a different group for a slide.

[error_log.json](https://github.com/ChurchApps/FreeShow/files/13836988/error_log.json)

**Comment by vbc-plano-av** [comment]
Update: I dragged and dropped a different group from the Show screen, and it seemed to fix things.

The issue seems to happen when I *rename a group*. Until I reset the group on that slide, the right-click group menu is broken.

**Comment by abhishikthraj** [comment]
I have raised the same issue, probably they are having a look at what's causing it.

I believe this issue is observed after the latest update v1.1.1

**Comment by vassbo** [comment]
Thanks. We will look into it.

**Comment by Prezib** [comment]
My issue is similar, so will add here. I get frequent freezes when in edit mode usually when I right click on a slide or trying to switch between slides to open.

**Comment by dsaderholm** [comment]
I have the same issue. I even deleted everything related to FreeShow, and it still crashes when right-clicking and trying to change the group. I didn't even rename any groups.
