### ISSUE TITLE
FreeShow Shows directory

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#367]
Why are all the show files not being saved in the dedicated shows folder that you have? They are being saved in the parent directory.

![image](https://github.com/ChurchApps/FreeShow/assets/58181678/070b555d-b64d-4faa-9bf6-c6107d9d0e08)

**Comment by vassbo** [comment]
Please go into the "Other" settings and check that the "Show location" is set to that folder.
![image](https://github.com/ChurchApps/FreeShow/assets/17619496/5843c32f-1f6f-4434-8196-4be2ea19270f)

**Comment by abhishikthraj** [comment]
Got it! I got confused as it has a dedicated folder and yet it is being saved in the parent directory
