### ISSUE TITLE
Text  autosize

### ISSUE THREAD

**Issue by Prezib** [ChurchApps/FreeShow#369]
We are using autosize for are scripture but the text first flashes before adjusting to size. Is there anyway it can do that part before the output? Video attached
[VID_20240107_113914.zip](https://github.com/ChurchApps/FreeShow/files/13853320/VID_20240107_113914.zip)

**Comment by vassbo** [comment]
I'll try to do something about it, I probably have to cache the text, and wait to output.

**Comment by Prezib** [comment]
Thanks, will that cause a longer delay?

**Comment by vassbo** [comment]
Not any noticeable.

**Comment by Prezib** [comment]
Hi, was this fixed in the latest update or not yet? because I am still getting the flash before adjustment

**Comment by vassbo** [comment]
Not fixed yet. Tried to, but ran into some problems.

**Comment by Prezib** [comment]
any update on this in the latest version?

**Comment by vassbo** [comment]
No, sorry. I have realized that I have to rework the way transitions work entirely. To hopefully get smoother transitions overall.

**Comment by Prezib** [comment]
No worries, is that in the roadmap yet?

**Comment by vassbo** [comment]
Yes, this will be prioritized.

**Comment by abhishikthraj** [comment]
Same issue for me, hope this will be addressed by the next update. Thank you🙂

**Comment by abhishikthraj** [comment]
Hey @vassbo, this issue is fixed for the main outputs but it still flashes for the stage view

**Comment by vassbo** [comment]
Thanks. Will see if this can be fixed. But I don't think it's a big issue, because the stage is not for the audience.

**Comment by abhishikthraj** [comment]
Yes but it is just so that the singers are not confused when it flashes...
