### ISSUE TITLE
Feature: Individualized Fade Times

### ISSUE THREAD

**Issue by MrDogeBro** [ChurchApps/FreeShow#370]
It would be nice if you could have more control over the fade times of items. For example, being able to set different sets of fade parameters for different outputs would be nice. And then on top of that, being able to change the fade times for individual circumstances would also be nice. For example, I want the text to fade when it is coming from no text, or going to no text, but just cut without any fade when it's changing from one set of text to another.

**Comment by vassbo** [comment]
Thanks. I will have to redo the transitions before this can be done.
