### ISSUE TITLE
Considering releasing 915e4205f92dc435330c0fa49aead50debb2b69d as a patch or new version?

### ISSUE THREAD

**Issue by ip4368** [ChurchApps/FreeShow#371]
Seems like 915e4205f92dc435330c0fa49aead50debb2b69d contains a fairly important fix. Right click menu to change the slides' group is pretty much unusable.

Or is the recommendation to go back to v1.1.0 for the time being?

**Comment by vassbo** [comment]
You can go back for the time being. Might be some time before the next release.
