### ISSUE TITLE
Jest test to ensure release quality

### ISSUE THREAD

**Issue by ip4368** [ChurchApps/FreeShow#372]
Hey, first of all, much appreciate the work in this project. I had similar idea like 2-3 years ago, but never got time to make it happen.

Looking at the amount of issues opened recently, I think the project is getting even more traction, which is great for the community. I am trying to adapt this at my church too.

I think at the point of time, release quality matters, especially for retaining user base and keeping the traction.

The proposal is that to add some (e2e) test, to ensure the basic functionality is working fine.

I am happy to investigate and probably send some PR for adding jest support, but I would like to get some initial feedback on whether it is welcomed. If so, I can work on it.

**Comment by vassbo** [comment]
Hi, thank you. 😊 That is very welcome. I have tried adding testing, but never managed to implement it properly, so if you want to create basic testing for common features that would be awesome! 😃
