### ISSUE TITLE
Typo In Documentation in Show Section under "# Finding your shows"

### ISSUE THREAD

**Issue by niicode** [ChurchApps/FreeShow#373]
[#Finding your shows](https://freeshow.app/docs/show#finding-your-shows)

The second sentence in that paragraph reads 
"In the top right corner og the drawer you will find a serach bar to search through all of your shows."

The typos here are with **og** which I think should be **of** and **serach** which I think should be **search**

**Comment by vassbo** [comment]
Thank you! 😊
