### ISSUE TITLE
The sigle row orientation of scripture chapters is cursed

### ISSUE THREAD

**Issue by McEazy2700** [ChurchApps/FreeShow#374]
![Screenshot from 2024-01-14 10-00-01](https://github.com/ChurchApps/FreeShow/assets/102771161/4ed38c3b-d399-4edf-9cb5-9591655f0451)

Proposed fix:
Please implement some kind of grid layout, example bellow.

![Screenshot from 2024-01-14 10-09-22](https://github.com/ChurchApps/FreeShow/assets/102771161/a7770164-9ecb-41e8-9b28-f98aea3f11a7)

It doesn't have to be this large, but you get the point.
Also FreeShow slaps. Great job guys.

**Comment by McEazy2700** [comment]
Is there a way to search for for a verse, like `Book Chapter: Verse`

**Comment by vassbo** [comment]
Yep, the search icon in the top right of the drawer (Or `CTRL/CMD+F`):
![image](https://github.com/ChurchApps/FreeShow/assets/17619496/c7e29081-4255-482a-b264-20ed40e7695a)

Start by typing any book (it will autocomplete when it finds one match), then press space and type any chapter, and use one of these letters (**: , .**) to then type a verse (you can also select multiple using **-** or **+**. E.g: **John 3:16-17+21**
