### ISSUE TITLE
Translate a song

### ISSUE THREAD

**Issue by rubenschellingerhout** [ChurchApps/FreeShow#375]
I live in the Netherlands and am looking for a way to present English text with its translation on one slide. When the template is switched, the English line should switch with the Dutch one.

**Comment by thebiblelover7** [comment]
This would be great! The way I found to do this, is to create a slide with two text boxes, and then create a template with two text boxes, in which one box is hidden (off screen, or opacity at 0), and then I could switch between languages by switching between templates. It also allows you to send one language to a screen, and another language to another.
Hopefully I explained myself well.

**Comment by vassbo** [comment]
Great solution @thebiblelover7.
It's also possible to have one template with two identical textboxes, but right clicking on the textboxes allows you to use "Bind to" to select your primary output on one, and select another output on the other. Then clicking on the template multiple times will toggle the text between the two textboxes.

**Comment by rubenschellingerhout** [comment]
But i want the 2 language's on the same page... So the audience can see what they're singing.
