### ISSUE TITLE
New Project V1.1.2

### ISSUE THREAD

**Issue by rubenschellingerhout** [ChurchApps/FreeShow#378]
In the new version, when I make a new project i can not import shows in because there stands 'select a project'
<img width="358" alt="image" src="https://github.com/ChurchApps/FreeShow/assets/82027374/9aa66a7a-004e-41a6-afa4-ecdcd9fe25e0">

**Comment by vassbo** [comment]
This is an old bug, it happens just sometimes, and I don't know why.
But you should be able to just select another project and select the created project again, and it should work.

**Comment by abhishikthraj** [comment]
I just saved a new project, I saved, closed the app and came back and the project is missing

**Comment by vassbo** [comment]
This does not happen for me. 🤔 Is it not in the "Projects" tab either (The folder icon)? It should still be there.

**Comment by abhishikthraj** [comment]
Yes, It's not there in any folders

**Comment by abhishikthraj** [comment]
I just switched back to the previous version of the free show. Even there is issue with the output on multiple screens. The lyrics are just flashing a milli second on the first time and getting disappeared. Unable to see them there after.

I'll add it as an issue tomorrow, I'm a bit busy today.

**Comment by vassbo** [comment]
Okay, I'll investigate.

**Comment by abhishikthraj** [comment]
Thanks

**Comment by abhishikthraj** [comment]
@vassbo As I told you, I switched back to v1.1.1 and I'm facing the same issue there too. The project that I saved is deleted. I created it multiple times and it is getting deleted every time I restart the app. Also I have set-up Google Drive sync for it.

**Comment by vassbo** [comment]
Are you using cloud sync? If you do, do you have the same issue with it turned off?

**Comment by vassbo** [comment]
Continues here: https://github.com/ChurchApps/FreeShow/issues/381
