### ISSUE TITLE
Issue while creating and saving the project

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#381]
I switched back to v1.1.1. The project that I saved is getting deleted. I created it multiple times and it is getting deleted every time I restart the app. I have the same issue in the v1.1.2
Also I have set-up Google Drive sync for it. I could see the project in the folder's list when I disabled uploading data and synced but the app froze when I tried opening that project. 

Here's the log file for your reference
[error_log.json](https://github.com/ChurchApps/FreeShow/files/14007060/error_log.json)

**Comment by vassbo** [comment]
When you turn off cloud sync, do you still have this issue?

**Comment by abhishikthraj** [comment]
I mean, there is no issue when the cloud sync is turned off but the project itself is not retrieved even after saving it. That's the primary issue. The project that I created and saved it missing completely.

**Comment by vassbo** [comment]
Okay.
