### ISSUE TITLE
Multi-Screen Display Issue

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#382]
There is an issue with the output on multiple screens. The lyrics are displayed correctly on the main screen but in the second screen and the stage view they just flashed a split second on the first time and got disappeared. Unable to see them there after.

**Comment by abhishikthraj** [comment]
Hey @vassbo , what would you suggest me as for time-being until the issue in the new version are fixed? Would you suggest me to switch back to v1.1.1? 

As these issues are more like a road blocks and we are unable to proceed further.

**Comment by vassbo** [comment]
You you can go back if you need to.
https://github.com/ChurchApps/FreeShow/releases/tag/v1.1.1
