### ISSUE TITLE
Disable thumbnail generation of videos

### ISSUE THREAD

**Issue by pvdl** [ChurchApps/FreeShow#385]
I added an extra remote folder in the 'Media' section.
This remote folder is an S3 bucket. (Linux mounted folder).

When the folder is added, it takes ages to render all video thumbnails. After rendering, the thumbnails are not stored. So next time selecting the folder I have to wait again when rendering is completed

Is it possible to select rendering on or off?
Or can the view switched to a list of videos instead of a thumbnail wall?

**Comment by vassbo** [comment]
The thumbnails should be stored in cache, so I don't now why not. But I will probably make it not show thumbnails in list mode then, as I don't see any need for it. And make the program remember the selected view mode on restart.

**Comment by pvdl** [comment]
Thank you so much!
List mode in Media is for me a good solution.
Tested the result: Browsing in media folders works far more quicker.
