### ISSUE TITLE
Import songs from EasyWorship

### ISSUE THREAD

**Issue by abojne4** [ChurchApps/FreeShow#386]
Hello. Thank you for this great app. I ran into a problem when importing songs from EasyWorship. I can import from the file SongsWords.db but then the songs do not include the song names. How do I import that the original song names will be included?
Also, the songs include words in our language and also the letters that are not in English (e.g. č, š, ž, ...). When importing, these appear as a code, for example instead of "č" the songs include "u369?".
How can I fix that?
Thank you.

**Comment by vassbo** [comment]
Hi, I will fix the issue with the encoded characters.
You should select both the "SongsWords.db" and the "Songs.db" file at the same time when importing to get the proper names imported.

**Comment by abojne4** [comment]
Thanks for your quick response and explanation. I successfully imported the database by selecting both files.
Thank you for fixing the character encoding. Please, let me know when that will be included in the program. Thanks.

**Comment by vassbo** [comment]
Should be fixed now in the latest version!
