### ISSUE TITLE
Having rundown as a "Flow"

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#387]
I'm trying to go through each slide with a Logitech Remote and some slides I have to click manually and was wondering if it would it be possible to add a "Flow View" to view all of the slides and "Flow Text" to view all of the text for the playlist in the service project set?

<img width="290" alt="image" src="https://github.com/ChurchApps/FreeShow/assets/38868273/df46730d-4032-4475-8034-00c95e3e2bda">

Thanks in advance!

**Comment by vassbo** [comment]
I made it so you can use the arrow keys (that should include the Logitech Remote) to go back and forward between shows in a project. (Found it a bit hard to implement "Flow" in the current state of the program.) Hope this works!
