### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by captainalwell** [ChurchApps/FreeShow#388]
The app freezes when one outputs a video source or video file. The video outputs drags and lags

**Comment by vassbo** [comment]
Does it freeze completely or just lag? The preview might be lagging a bit on slow computers, but the actual main output should not be lagging as much.

**Comment by Cop-media** [comment]
I have the same issue as well. It does lag quite a lot. 
Starts out great with any video file, but begins lagging continuously after about 30s-1min, and I don't by any means have a slow computwe

**Comment by Cop-media** [comment]
Also, could a message/ alert feature be included? Scrolling and Still messages, could be under overlays.
Finally, could presenter by worship extreme be included for importing songs/ schedules?
Thanks much

**Comment by vassbo** [comment]
Try setting this to "Full" in the "Other" settings:
![image](https://github.com/ChurchApps/FreeShow/assets/17619496/c36ef26b-0c59-4fab-9f3d-6d6631c1a1b9)

You can use "Variables" and "Overlays" for alert messages.

Maybe you can send over a couple of the Presenter song files to dev@freeshow.app, and I'll take a look.

**Comment by Cop-media** [comment]
Hey, I can't thank you enough really.
I did, and the lags have almost completely disappeared.
I can't seem to find a way of getting the song files just yet, not sure if that's an option they have at this time, I'll keep checking, and will be sure to send them as soon as I figure out how to.
Again, you have my deepest gratitude.

**Comment by captainalwell** [comment]
I have done your recommendation but it still lags a little. The audio and
video are scarcely in sync because of this. I use a very high speed Macbook
Air device so I don't think it's a matter of system speed. Please help

**Comment by captainalwell** [comment]
Also, since the version v1.1.2, the scripture auto size has stopped
working. Once the template is edited to enable font auto size, the output
goes blank. Please check and help

**Comment by vassbo** [comment]
This is fixed for the next version. Also the preview should be faster, even on slower computers.
