### ISSUE TITLE
freeshow application freezes on start up

### ISSUE THREAD

**Issue by EstherOgunshile1** [ChurchApps/FreeShow#389]
When i open the app, the application just hangs on the loading page. It does not open 
I currently a mac user

**Comment by vassbo** [comment]
Weird. Are you able to open the application using the command line and see if you get any errors there?

**Comment by EstherOgunshile1** [comment]
how do i do this, from the command line?

**Comment by EstherOgunshile1** [comment]
Hi, I gave it try via the terminal on my mac and still having the same issue. I also tried downgrading to see if it was the version, all the way to v0.94. It still hangs at this point
<img width="748" alt="freeshow screnshot" src="https://github.com/ChurchApps/FreeShow/assets/45460997/389c615f-f56f-4774-ad02-4241b52ff877">

**Comment by vassbo** [comment]
Thanks. That's really strange. I would have thought that it would show an error in the terminal at least. Not an expert on macOS.

Does the program have the proper read/write permissions?

**Comment by vassbo** [comment]
Are you able to navigate to this path: **~/Library/Application Support/FreeShow/**
And see if you have an **error_log.json** file there, if you do, you can send that here.

**Comment by EstherOgunshile1** [comment]
I am unable find freeshow in the folder Application support. Is there anywhere else I could find it?

**Comment by vassbo** [comment]
It should be there.. Maybe that's the issue then. 🤔

@jzongker Do you have any idea as to why it won't start up on this specific OS/device?

**Comment by EstherOgunshile1** [comment]
hi does anyone know what i can do to fix this?

**Comment by vassbo** [comment]
Not sure if this helps. But first try uninstalling the entire application, then install it again.

But before you open, please check out the Mac security settings.
Go to settings, "Security & Privacy", then find a list of "Privacy" options. Here one should be "Files and Folders", make sure FreeShow is allowed here, also please try some of the other options that makes sense, then try opening the application again.
Does this make any difference?

As a last resort you can try opening a local version of the dev environment to see if you get any errors there.

**Comment by EstherOgunshile1** [comment]
Hi, I gave adding freeshow to the privacy and security and didnt get anywhere, will give the dev environment a try. How would i go about doing this?
<img width="712" alt="privacy screenshot " src="https://github.com/ChurchApps/FreeShow/assets/45460997/3f4488a7-b385-43b2-bfb9-d7da701d8b78">

**Comment by vassbo** [comment]
Okay. You need to install node js and the download the files in this project on GitHub, then extract and from the CMD, run "npm install", and then "npm start".

**Comment by EstherOgunshile1** [comment]
Okay gave the dev environment a try, this is what i am getting:
<img width="1220" alt="dev environment" src="https://github.com/ChurchApps/FreeShow/assets/45460997/e8a29e50-bb36-4f95-8cef-b0d937c0453e">

**Comment by EstherOgunshile1** [comment]
Could not load app content. Please check console for any errors! - got this message too at the end

**Comment by vassbo** [comment]
Thanks! Looks like this is the issue, but not sure how to fix it:
![image](https://github.com/ChurchApps/FreeShow/assets/17619496/360b203b-674b-45f6-a6e5-4d582f8f2a80)

The only simular issue I could find was this: https://github.com/quasarframework/quasar/issues/16741

**Comment by vassbo** [comment]
Looks like a pretty new error, found these also:
- https://github.com/jdms754/electron-forge-vite-esm-test/issues/1
- https://github.com/electron/electron/issues/37876#issuecomment-1984873828

**Comment by EstherOgunshile1** [comment]
Oh Okay, Please let me know if you do find a solution as I am still unable to use freeshow

**Comment by EstherOgunshile1** [comment]
Just was wondering if this new error means anything to you: (**node:14564) electron: Failed to load URL: http://localhost:3000/ with error: ERR_CONNECTION_REFUSED
(Use `Electron --trace-warnings ...` to show where the warning was created)**
Failed to load window: {"errno":-102,"code":"ERR_CONNECTION_REFUSED","url":"http://localhost:3000/"}
[14564:0425/201405.984128:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)

**Comment by EstherOgunshile1** [comment]
I also found out how to send over a log file for this issue from the console app, I have attached it to this comment. 
[FreeshowLog.txt](https://github.com/ChurchApps/FreeShow/files/15119820/FreeshowLog.txt)

**Comment by vassbo** [comment]
Thanks. Not sure why it does not load, but it should not throw ERR_CONNECTION_REFUSED.

**Comment by vassbo** [comment]
Does adding this to `scripts/entitlements.mac.plist` change anything?
```
<key>com.apple.security.app-sandbox</key>
<true/>
```

**Comment by EstherOgunshile1** [comment]
yeah it removed the ERR_CONNECTION_REFUSED error but not the other errror: **[31595:0427/211902.964330:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
Loading content again. App is probably not finished building yet**

**Comment by vassbo** [comment]
Okay, great! The "Autofill.enable' wasn't found" is just a warning that can be ignored.
Did it load the app interface after waiting 2 minutes?

**Comment by EstherOgunshile1** [comment]
The app still hangs at startup and does not load

**Comment by vassbo** [comment]
Okay, please try changing this from false to true in your dev environment, and check if you get any errors in the browser console!
https://github.com/ChurchApps/FreeShow/blob/a06825266b4c96b3dcaf0389636db435b02ae295/src/electron/utils/windowOptions.ts#L28

**Comment by EstherOgunshile1** [comment]
Okay tried this and it finally loads!
Was glithcing for a bit and then showed this: 
<img width="1440" alt="random freeshow error" src="https://github.com/ChurchApps/FreeShow/assets/45460997/12f1f593-ffd9-4b2c-904e-6e886ef8fd54">
 
screenshot of terminal:
<img width="1392" alt="terminal sc" src="https://github.com/ChurchApps/FreeShow/assets/45460997/05428071-17cc-44f1-b2fb-1f0cb4eaa7e8">

But then opens like normal:
<img width="1440" alt="freeshow working" src="https://github.com/ChurchApps/FreeShow/assets/45460997/574bc460-2729-4bcc-8717-1f4781e2cd60">

errors on browser console before opening like normal:
<img width="1440" alt="console error 1 on startup" src="https://github.com/ChurchApps/FreeShow/assets/45460997/8ff66258-a55a-42ab-aeba-de4c5b01e4eb">
<img width="1440" alt="console error 2 on startup" src="https://github.com/ChurchApps/FreeShow/assets/45460997/3ec83fd6-4eb1-45ae-a45c-7e3bffe4abc2">


Thanks for your help, just was wondering how to get this working outside the dev environment?

**Comment by vassbo** [comment]
Awesome! Maybe the error in the fist image has something to do with it..
Looks like it took a very long time to load. 🤔

**Comment by jzongker** [comment]
I think another application may have port 3000 in use..?  When freeshow isn't running maybe just open up a web browser and go to `http://localhost:3000/` and `https://localhost:3000/`, or run `netstat` from a terminal.

**Comment by vassbo** [comment]
Good suggestion @jzongker. I still don't get why it does not load in production in the first place, because it doesn't use port 3000 in the main application. 🤔

**Comment by EstherOgunshile1** [comment]
Just checked and port 3000 is not in use: 
<img width="1026" alt="localhost" src="https://github.com/ChurchApps/FreeShow/assets/45460997/7d031a27-2d7f-4985-bc96-92738aa78946">

**Comment by EstherOgunshile1** [comment]
Okay I have opened up the acpplication outside of the dev environment and it seems to be working. Was there any recent changes added?As I did not upgrade the application or anything?

**Comment by vassbo** [comment]
Awesome news! I don't think anything special has changed, but glad it's working now. 😊
