### ISSUE TITLE
Allow us to set whether videos will loop or not

### ISSUE THREAD

**Issue by MrSam7K** [ChurchApps/FreeShow#390]
So I have this situation, I have scheduled video to play 10 minutes before my service and everything works perfectly but I always have to disable looping when video is running, it kind off defeats whole purpose of having scheduled video. Thank you!

**Comment by vassbo** [comment]
You can disable looping here:
![image](https://github.com/ChurchApps/FreeShow/assets/17619496/049b06ff-6ca8-42f4-a5fb-a53ac1dd7493)

**Comment by MrSam7K** [comment]
That only disables looping for that one time, at least for me

**Comment by vassbo** [comment]
It should save for the video in that show. But if not I'll take a look.
