### ISSUE TITLE
RemoteShow is glitching out and not showing slides

### ISSUE THREAD

**Issue by acflash123** [ChurchApps/FreeShow#391]
I tried using StageShow recenctly and it's not showing the slides properly. When using it i would see this on my screen. and could not read the content of the slides. Any help will be be greatly appreciated.

![image](https://github.com/ChurchApps/FreeShow/assets/77359697/cef53606-7aad-4af1-abad-83dea27ba04e)

**Comment by vassbo** [comment]
Will see if this can be fixed

**Comment by vassbo** [comment]
In the latest version it will send over the slide resolution if that's changed. Should be fixed if that was the case here.

**Comment by acflash123** [comment]
It still hasn't fixed the problem. I normally use an IPad or Samsung Tablet
to view the remoteshow and it's not showing the full slide screen. Is there
a setting to change the resolution for specific devices connecting.

**Comment by vassbo** [comment]
Try clearing the cache on the website. Does that change anything?

**Comment by acflash123** [comment]
It didn't work for firefox but i was able to make it work on google chrome.
I don't know if that was the issue.

**Comment by vassbo** [comment]
Okay, thanks. That could be the issue then.

**Comment by acflash123** [comment]
Thanks, You're a Godsend. This is really helping our church upgrade in the
music ministry and we appreciate all the hard work you have done. God
Bless.

**Comment by vassbo** [comment]
Figured out Firefox does not yet support the CSS zoom attribute used in Chrome:
https://developer.mozilla.org/en-US/docs/Web/CSS/zoom
So either just stick with Chrome, or allow the experimental option. :)
