### ISSUE TITLE
New Project is not being saved

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#393]
This issue persists in the latest version (v1.1.3). When I create and save a project, the project is not being saved and the project is being disappeared when I restart the application. 

This has been a one of the major concern as I have lost my work multiple time forgetting that the project is not being saved.
The work around that I just found is to export the project and then import it back again when I reopen the application.
Please look into this issue. Thank you.

**Comment by vassbo** [comment]
I will look into it. I guess it's caused by the cloud sync.

**Comment by vassbo** [comment]
Related: https://github.com/ChurchApps/FreeShow/issues/381

**Comment by abhishikthraj** [comment]
I tried by removing the cloud sync too... Still facing the same issue...

**Comment by frankybobby** [comment]
I am having the same issue. I BACKUP everytime. However PROJECTS disappear and the original folder and example project loads. I think the cloud may be the issue. I have tried diligently to sync and have gone over your instructions multiple times without any success. So Ive switched OFF Auto sync. The key saves and then the Sync spinner never stops. Sometimes there is an error "" and sometimes there is none. Additionally "CLOUD SYNC" may need a better troubleshooting article. Thanks. PS> We are launching the system this week at church.

**Comment by abhishikthraj** [comment]
This issue has a resolution in the issue number #404
