### ISSUE TITLE
Performance lowered with the new update

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#394]
The initial loading time of the app has increased and after the app is open, I'm unable to click anything (probably it is loading things in the backend). After the new update, it is taking very longer than usual for the start-up and for the application to be ready for use.

Thank you for all your hard work!

**Comment by vassbo** [comment]
Thanks. Not sure what this can be. How much longer do you think the startup takes in average?

**Comment by abhishikthraj** [comment]
It is taking 30 sec to 1min. I can see the shows and the screens loading. Previously everything use to be ready by the time the window is opened and it was a bit quicker...

**Comment by vassbo** [comment]
Okay, I'm not sure what has happened here. 🤔

**Comment by abhishikthraj** [comment]
Yeah, looks strange. Not only during the start-up but sometimes it was slowing down in between too. For me, as far as I observed, the performance slowed down whenever I touched something with the displays... Hope this can give you a clue what might have gone wrong

**Comment by vassbo** [comment]
Does changing the "Preview frame rate" in the "Other" setting from "Auto" to "Optimized" improve anything?

**Comment by abhishikthraj** [comment]
No

**Comment by abhishikthraj** [comment]
Hey @vassbo, I think this performance issue must be addressed as quickly as possible as this is affecting during the live session. Every time I make a change with the displays it is almost freezing everything for a minute or so. Also the media that I have on my local machine, it is taking too long to load in freeshow I guess. I have some videos which I wanted to present from the media tab as a background. All I could see is the loading screen spinner.

**Comment by vassbo** [comment]
You can downgrade to the previous version if you want. Find it under "Releases" here in GitHub.

**Comment by abhishikthraj** [comment]
For now I think I can manage but just wanted to convey that I noticed performance issues multiple times and maybe due to various reasons not only on start-up and changes in output screens...

**Comment by vassbo** [comment]
How does it perform in the latest version?
