### ISSUE TITLE
Songbook number in metadata

### ISSUE THREAD

**Issue by sweenu** [ChurchApps/FreeShow#397]
Just started using FreeShow, I love it!

I'd love to be able to set the songbook number like I used to in OpenLP: https://manual.openlp.org/songs.html#authors-topics-song-book
With that information, it would be nice if the info could be shown next to the title (the same way the "modified date" is) and if we could sort by songbook number.

**Comment by vassbo** [comment]
Thanks. I'm not sure this would be needed. Wouldn't it be easier to add a "songbook" number to the start of the song title? I guess it could be combined with metadata if that's better, but I don't want it to be too cluttered.

**Comment by sweenu** [comment]
As you want. It would give more flexibility, like the ability to put the number and even the songbook's name anywhere on the slide. But yeah, for now I'll go ahead and add it to the title.
