### ISSUE TITLE
Template: Not found

### ISSUE THREAD

**Issue by sweenu** [ChurchApps/FreeShow#398]
I might have made a mistake somewhere but most of the songs I've imported have `Template: Not found` instead of `Template: None` which means they don't use the default template.
Two questions:
- is there a way to reset the template to be None?
- is there a way to bulk edit because it's going to be a lot of work if I have to do it manually for each songs.

**Comment by vassbo** [comment]
Probably a deleted template. You can't reset it at the moment. Also you would have to change them individually, but you can set an output style with a template. I will think if there's a better way of doing this.
