### ISSUE TITLE
Template inheritance

### ISSUE THREAD

**Issue by sweenu** [ChurchApps/FreeShow#399]
I need to have the logo of our church present in the same place for different type of slides (e.g. welcome slide, lord supper slide, announcement slide, ...) but the other elements are different.

I'd be good to have a way to have a base template from which others inherit. On this base template, I would have just the logo and when I change something about it, it would also change it everywhere on the child templates.

Is there already a way to do that, that I missed?

**Comment by vassbo** [comment]
You can just use an overlay with the logo and lock it to the output.
Does that meet your needs, or is there another use case that requires this template "nesting"?

**Comment by sweenu** [comment]
So I see that I can assign an overlay to a slide but then the overlay stays. In my case, I have the overlay of the logo on my first "welcome" slides but then I don't want it when it goes to a song. I would have to assign the "Clear overlays" action to the first slide of each of my songs.

The real need behind all of this, is to have the ability to create a theme. A theme would have different type of slides for example "welcome slide", "song style 1", "song style 2", "announcement", ... Each of these slides would have some commonality, for example, the font, or background. Right now, I could emulate themes in some way, by creating a template category for my theme and putting all the relevant template in this category. However, if I decide to change the font of the "theme" then I will have to go and change it on each template. Even worse, if I try to change the position of an image everywhere, I will have to go to each slide and change the position in the css to be consistent. Overlays would allow me not to have to do this everywhere but their is no way for me to say: "Presentation slides have this overlay but Songs slides don't".

**Comment by vassbo** [comment]
Okay, I guess it would make more sense to link overlays to templates then.
