### ISSUE TITLE
Media Controls when playing from slide

### ISSUE THREAD

**Issue by thuox** [ChurchApps/FreeShow#400]
It would be really helpful if we could control the currently playing media from a slide with controls under the output window on the right, similar to how we can control it in the preview window when a video is opened from the media drawer.

**Comment by vassbo** [comment]
Would be nice!
If you add the video as a background to a slide you can control it, like from the drawer.

**Comment by thuox** [comment]
Wait, are you saying we can do that right now? I don't see the controls anywhere.

**Comment by vassbo** [comment]
Yes, right under the background/media clear button there is a small button that can be clicked to change the controls from slide back to media.

**Comment by thuox** [comment]
Thank you! Could you please add that to the docs? It's difficult to know that button is there otherwise. Maybe under the paragraph titled "Add as backgrounds".

**Comment by vassbo** [comment]
Added to docs: https://freeshow.app/docs/media#control-videos-playing-in-output
