### ISSUE TITLE
Include Media and Audio files in Cloud Sync

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#402]
Media and audio files are presently excluded from cloud sync.  They have to be processed separately, which makes collaboration and multi-device use difficult.

Including these files in the sync will significantly improve the usefulness of a synchronised cloud repository, and will make multi-device use and collaboration much simpler.

**Comment by vassbo** [comment]
You can just simply set up some other sync for all media files. Maybe sometime I can add a way to add the media files directly into the show files.

**Comment by colanct** [comment]
Thank you.  I'll investigate a stand-alone sync for all media files, as you suggest.

**Comment by chanx** [comment]
how about if we set the media folder to our cloud folder? like OneDrive or GoogleDrive, can Freeshow handle it?will all the media and the library automatically sync to cloud?

**Comment by vassbo** [comment]
Yes, that will work @chanx! You can download the Google Drive/OneDrive desktop app, and select your media folder for a working media sync!

**Comment by vassbo** [comment]
I actually think it's better to just use a reliable already existing option for media sync, and with the addition of the "Bundle media" button (https://github.com/ChurchApps/FreeShow/issues/401#issuecomment-2288280511), I think I will close this. Even ProPresenter 7 started relying on sync methods like that.

**Comment by colanct** [comment]
Agreed, thank you.
Google Drive synced to the same mapped drive on all our devices is working well for us. Having all media paths identical across all synced devices removed reliance on FreeShow having to repeatedly find missing files.

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/1925#issuecomment-3749783329
