### ISSUE TITLE
FREESHOW HANGS

### ISSUE THREAD

**Issue by usajerhel** [ChurchApps/FreeShow#403]
The Freeshow hangs when I try to change the motion backgrounds of the lyrics. Does Freeshow does not support 4k videos or multiple clicks? Or it is just my computer?

**Comment by vassbo** [comment]
Does it freeze or just stutter? Maybe it helps if you change the "Preview frame rate" in the "Other" settings to "Optimized"?

**Comment by usajerhel** [comment]
> Does it freeze or just stutter? Maybe it helps if you change the "Preview frame rate" in the "Other" settings to "Optimized"?

Hi, it freeze when I try to change motion backgrounds and after multiple clicks or change it freeze that you can't use the FreeShow and you need to End Task in task manager. But I will try your suggestion and see if it will occur again, thank you!

**Comment by vassbo** [comment]
Okay. Are you able to send over the error log, by finding "Open log file" in settings under "Other"?

**Comment by vassbo** [comment]
Let me know if you still encounter this issue in the latest version.
