### ISSUE TITLE
Save functionality is not working across the app

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#404]
The save functionality is not working across the app at various places. I'm mentioning various instances that I observed this. Please look into this.

1. The changes made to the templates is not being saved.
2. The changes made to the stage view layout is not saved
3. I deleted a timer and saved it, when I restarted the app I see it again
4. I imported a Bible and saved but that is lost when the app is restarted
5. I added merged to Bible translations as a collection and saved it and that is also lost
6. Changes in Overlays and Variables are not being saved
7. Also, as I already mentioned in the other issue, new project created is not being saved

The save functions that are working are shows and settings as far as I observed, not sure about others

**Comment by vassbo** [comment]
When going to the "Others" settings, do you have enabled the "Save user data at data location" enabled? Try turning it off!

**Comment by abhishikthraj** [comment]
Yes it worked that way! What's the difference?

**Comment by vassbo** [comment]
That is off by default, and you will only need that if e.g. you want to transfer the saved data in a USB storage device.

**Comment by abhishikthraj** [comment]
Oh okay got it
