### ISSUE TITLE
Scripture in Stage show is not working

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#405]
In the new update the scripture in the stage view was added. I could see it work but when I actually connected the screens, the scripture in stage view is not being displayed for some reason.

**Comment by vassbo** [comment]
Looks like it works, but the stage has to be activated first, then the scriptures. Does it work then?

**Comment by abhishikthraj** [comment]
Sorry, my bad, I think now I understood why it wasn't working. I was disabling the output screen which I selected for the stage view when I was displaying the verses.
