### ISSUE TITLE
Add background blur for text color

### ISSUE THREAD

**Issue by CresthaSabin** [ChurchApps/FreeShow#406]

**Comment by vassbo** [comment]
Please provide a description of what you mean.

**Comment by abhishikthraj** [comment]
If you meant you should be able to blur the background color for text, you can do that by modifying background opacity

**Comment by abhishikthraj** [comment]
@vassbo One enhancement feature that you can add here is, currently we set background color for the whole line, also, you can give an option to add background color for text alone. I'm able to do that with the css option that you have given below. Also, another enhancement the you can do is to add gradients along with colors. 

The css option is one of the great thoughts for sure!
