### ISSUE TITLE
Two Bible translation display 

### ISSUE THREAD

**Issue by Shak1811** [ChurchApps/FreeShow#407]
Requesting to enhance our  Freeshow software to support the simultaneous display of two bible translations, enabling comparative study and deeper understanding. This feature will greatly benefit our congregation by offering diverse perspectives side by side. Your consideration in implementing this enhancement would be greatly appreciated.

**Comment by vassbo** [comment]
You can select two or more scriptures , right click and choose "New collection". This will behave as one but show multiple scriptures.

**Comment by Shak1811** [comment]
I'm specifically inquiring about the ability to display two distinct Bible translations concurrently, such as KJV and NLT, rather than multiple scriptures.

**Comment by vassbo** [comment]
That's what I mean. Select e.g. KJV and NLT on the left side in the drawer, right click, and choose "New collection".

**Comment by Shak1811** [comment]
I apologize for my confusion. Your guidance in helping me understand its operation is greatly appreciated. It's working wonderfully!
