### ISSUE TITLE
Searching for media via the drawer media tab does not find files

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#411]
Searching for media via the drawer media tab does not find files, even when they are visible in the drawer.  However, if the media file extension (for example: png or jpg) is used, then all files of that type are returned, provided they are contained in the selected folder or in a folder one level beneath.  Files in lower-level sub-folders are not found.  A subsequent search for a media file then returns expected results.   This same behaviour occurs on a Win 10 and on a Win 11 PC.

The search function on all other drawer tabs functions correctly.

Could this contribute to media files not being found consistently when they are located at a different location on another device that is using cloud sync?  If so, is there a way to maximise the likelihood of such files being found automatically?

Thank you.

**Comment by vassbo** [comment]
Found the issue, it did not convert the letter case in the search box.
For now you can find most files by searching in lower case, but this will be resolved in the next update.

**Comment by colanct** [comment]
Ah, good.  Thank you.

Is the scope of the search function limited by design to one sub-folder level, or is that apparent limitation part of the issue you found?

Could this issue also result in inconsistent finding of media files that are not at the original location as defined in the show file (like for an exported project or a project synced to another device)?

**Comment by vassbo** [comment]
The search scope is limited intentionally.

Media files are not exported or synced, they are just stored on the computer.

**Comment by colanct** [comment]
Thank you for fixing the search box case issue on the media tab, in 1.1.4.
I raised issue #421 for the same problem on Audio, Overlays, and Templates tabs.

**Comment by colanct** [comment]
Thank you for fixing the search box case issue on the media tab, in 1.1.4.
I raised issue #421 for the same problem on Audio, Overlays, and Templates tabs.
