### ISSUE TITLE
Language russian

### ISSUE THREAD

**Issue by Evgeniydjdeluxe** [ChurchApps/FreeShow#412]
1.You can add Russian 2. I would like a smoother animation of the video output when I output to the second screen.

**Comment by vassbo** [comment]
1. Please head over here: https://explore.transifex.com/nettbiter/freeshow/ to request and translate your language.
2. You can try increasing the transition duration.

**Comment by Evgeniydjdeluxe** [comment]
I translated it into Russian, tell me how to upload the language to freeshow?

**Comment by Evgeniydjdeluxe** [comment]
> 1. Please head over here: https://explore.transifex.com/nettbiter/freeshow/ to request and translate your language.
> 2. You can try increasing the transition duration.

I translated it into Russian, tell me how to upload the language to freeshow

**Comment by vassbo** [comment]
Great, thanks! It will be included in the next update. :)
