### ISSUE TITLE
Cannot Create a Countdown Timer

### ISSUE THREAD

**Issue by AndyMac521** [ChurchApps/FreeShow#414]
Hey everyone!

I'm liking FreeShow quite a bit, but there seems to be a bug in version 1.13...

When I edit my timer I just created, I can't make it be a countdown timer at all. I just get this blank menu and can't select anything. 
![image](https://github.com/ChurchApps/FreeShow/assets/161170536/b83a659e-57d6-465a-9612-0795180223d3)

Can you please help? 

Thanks!

**Comment by vassbo** [comment]
You have to create a timer in the "Calendar" drawer tab, and the "Timers" menu. Then you can select it when you add a timer item.
