### ISSUE TITLE
Software starts bugging when i add video for presentation.

### ISSUE THREAD

**Issue by CresthaSabin** [ChurchApps/FreeShow#415]
Wheneven i add background video and music, application start to slow down and hangs up. Video start lagging and i can't click anything.

**Comment by vassbo** [comment]
You can revert to the previous version for now if it's too much.

**Comment by CresthaSabin** [comment]
It lags even more that latest one.

**Comment by vassbo** [comment]
Okay. Try changing the "Preview frame rate" in the "Other" settings, from "Auto" to "Optimized". If that does not help, then I guess it's caused by a slow computer.
