### ISSUE TITLE
How to play multiple music files sequentially

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#417]
Is there a way to play multiple music files sequentially:
 1.  when only one slide is displayed, or 
 2.  while a looped slide show is in progress? 

Thank you.

**Comment by vassbo** [comment]
Currently you can do this by creating a custom show with one audio file on each slide, and set the action "Next after media" on the slides. You will probably need to create a seperate "invisible" output for them to play along side other slides. I will add some sort of playlist sometime.

**Comment by colanct** [comment]
Thank you.
