### ISSUE TITLE
Doesn't apply the lyrics the way I had put

### ISSUE THREAD

**Issue by SKU003** [ChurchApps/FreeShow#418]
Hi, 

I don't know why, but it doesn't want to apply the text he way I had wanted. Like you can see on the Grid View I had put it bold but on what the preview is, isn't what I had applied or didn't even apply it. It's the same when you added Gaussian blur but doesn't appear even if you close FreeShow and then open in back up. It only works when it wants to work. Likewise, it's hard for me to be creative on your software when I'm unable to even change the font itself. And feels like more work to redo it all on a new show, and it's one of the reasons I'm delaying myself to use FreeShow in gigs.

![FreeShow_kMAfGjeHfC](https://github.com/ChurchApps/FreeShow/assets/117542049/c3197e66-b6d3-49db-ae77-a62a0d469d3e)
![FreeShow_hWeE3QADXV](https://github.com/ChurchApps/FreeShow/assets/117542049/24248608-0b5b-4993-935a-6413dd3d2302)

https://github.com/ChurchApps/FreeShow/assets/117542049/f9ad3548-0384-4b5c-a257-b9ad09c0b708

**Comment by Bagel94** [comment]
By chance have you set an output style in the settings? Go to settings -> outputs. Then see if "Use style" is in use. If it is not set to a style, it should be a "-". 

If this has been set to a style, your templates will not be changed in the live output.

**Comment by vassbo** [comment]
It should work fine. I think the same as @Bagel94, please follow the steps in his comment, and see if that helps.

**Comment by SKU003** [comment]
Hi, sure thing, I'll check that out.

I've checked and it was on default.
![FreeShow_6wGnXjjdN0](https://github.com/ChurchApps/FreeShow/assets/117542049/4342d6d9-239a-4d4a-999c-af0d6c5a78a0)

**Comment by SKU003** [comment]
Hi, I don’t think you understand I didn't mean can I meant can't. I can't find Bagel94 comment or the steps you had given him. It's showing nothing on him, he hasn't posted anything or commented on anything. 

Secondly, I didn't turn on default it was already put so my problem persists. I was showing you it was already in default so I don't know what's causing the issue. 

Could you kindly, paste the steps you'd given to bagel94 so I can fix it. 


![Screenshot_20240229_185102_GitHub.png](https://github.com/ChurchApps/FreeShow/assets/117542049/d3f96646-7cd8-4c27-9f7a-70f65e3f070d)

**Comment by Bagel94** [comment]
@SKU003 if you go back to the settings window where it says, "Use Style", click on default and change it to **"-"**. That will then allow you to use your templates.

**Comment by vassbo** [comment]
Yes, just set the style back to no style (-)!
![Screenshot_20240229_175422_Chrome](https://github.com/ChurchApps/FreeShow/assets/17619496/077c3934-96d8-4714-8041-9da8bae55bb9)
