### ISSUE TITLE
1.1.4 not working in linux

### ISSUE THREAD

**Issue by shawneehbc** [ChurchApps/FreeShow#424]
Hello, after updating to 1.1.4 the program no longer loads. I have tried it on two different computers, and its the same story. We are using SNAP to install and keep Freeshow up to date.

**Comment by vassbo** [comment]
Do you get any errors in the console?

**Comment by shawneehbc** [comment]
I'm not sure how to do that? If you give me instructions I will try. I executed Freeshow through the GUI when I went to snap/freeshow/current/freeshow and it loaded fine. When I tried to go to the "current" directory though the terminal there were no files visible in that directory. Sorry I am still new to Linux

Thanks and God bless,
James Horsley

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by shawneehbc** [comment]
So, i forgot to state the program wont load when I click on the GUI's purple Freeshow icon. For whatever its worth I am running Ubuntu 22.04 LTS on all of the computer I am trying it on.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by vassbo** [comment]
Okay, thanks. Please see this: https://www.wikihow.com/Run-a-Program-from-the-Command-Line-on-Linux

I will check it out myself, I know it works for some people on Linux.

**Comment by shawneehbc** [comment]
Here is what it says in terminal
***@***.***:~/snap/freeshow/current$ freeshow
mkdir: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/freeshow/35/gnome-platform/lib/x86_64-linux-gnu/libselinux.so.1)mkdir: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/freeshow/35/gnome-platform/lib/x86_64-linux-gnu/libselinux.so.1)

But when I go thorugh the GUI the current directory isn't empty and it executes fine when I double click on the freeshow program.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by vassbo** [comment]
Thanks! 🤔

**Comment by eeickmeyer** [comment]
I have fixed the snap. Turns out the patch I was using to update `electon-builder` to a newer supported core and gnome dependency was broken. That's fixed now, and a new version of the snap has been uploaded.

**Comment by vassbo** [comment]
Fixed now! Thanks to @eeickmeyer.
https://github.com/ChurchApps/FreeShow/pull/425

**Comment by shawneehbc** [comment]
Thanks to all of you, and may God bless your ministry!

Sent with [Proton Mail](https://proton.me/) secure email.
