### ISSUE TITLE
Disabled slides can be selected and be seen in stage view

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#427]
1. I'm able to click on the disabled slides and it is being presented. 
2. Disabled slides can be seen in the stage view in place of next slide which should not be happening.

**Comment by vassbo** [comment]
1. You should be able to click on them. (But it skips when using keyboard shortcuts)
2. I will fix the stage issue.

**Comment by abhishikthraj** [comment]
Okay thanks. 
I know it skips with keyboard shortcuts. I thought it would be good if you don't let the user click on it and only enable right click so that they will be able to enable the slide.
