### ISSUE TITLE
Some video backgrounds are not loading

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#428]
I have some video backgrounds which I want to have as song background. All I see is just the loading spinner and they are taking forever to load. Also I'm unable to see the preview for the some picture backgrounds. Please help me out with this issue.
Some of the video backgrounds are of 4K resolution. Could that be a problem?

**Comment by vassbo** [comment]
I guess it's related to this: https://github.com/ChurchApps/FreeShow/issues/306

**Comment by vassbo** [comment]
When you click on the video (when it's spinning), does it show anything in the output?

**Comment by abhishikthraj** [comment]
No

**Comment by vassbo** [comment]
Okay, please convert the video to another format as explained in the referred issue, and let me know if that helps.

**Comment by abhishikthraj** [comment]
> Okay, please convert the video to another format as explained in the referred issue, and let me know if that helps.

Thanks it helped but it is better if you can add support to the HEVC /H.265 video files as well.

**Comment by vassbo** [comment]
Some day we will update Electron, but that will mean less support for older devices!
