### ISSUE TITLE
Flickering in Display

### ISSUE THREAD

**Issue by ejbramos** [ChurchApps/FreeShow#429]
Currently we are having flickers when displaying in FreeShow v1.1.4. I cannot recreate the whole flickering since the problem is not predictable and not periodic but flickers once in a while. It became evident starting v1.1.3 and to v1.1.4, so I currently I reverted to v1.1.2 to avoid flickers. The flickers does not happen on the operator monitor (Monitor 1) but happens with Display Monitor (Monitor 2). It flickers in a way that the display crashed for a moment that will display the desktop for a moment then shows the screen again. 

Currently Using:
FreeShow v1.1.12

Flickers occur on:
FreeShow v1.1.13 and v1.1.14

PC Specs:
OS: Windows 11
CPU: Intel i7 11800H
Memory: 2x8GB 3200MHz
Storage: 500GB SSD
Integrated GPU: Intel UHD
Dedicated GPU: Nvidia GeForce RTX 3050 Laptop

**Comment by vassbo** [comment]
Please try going into settings "Other", and change the "Preivew frame rate" from "Auto", to "Optimized"/"Full". Does that change anything?

**Comment by vassbo** [comment]
Let me know if you still encounter this issue in the latest update?
