### ISSUE TITLE
Glitch in show preview when pressing the ALT key

### ISSUE THREAD

**Issue by pvdl** [ChurchApps/FreeShow#430]
Make a project
Add a show.
Add in the show some text slides and static images.
Make next slide timers for each slide and images.
So each slide has a small overlay timer-icon.

If you press (and hold) the ALT key, all overlay (timer) icons disappear and also for all images the preview disappears.
When releasing the ALT key all is restored back.

Version 1.1.4 Linux (Ubuntu)

**Comment by vassbo** [comment]
Thanks. This is not a glitch, you can hold the ALT-key if you want to show the slide without the overlay/background.

**Comment by pvdl** [comment]
Normal
![Screenshot from 2024-03-10 17-35-27](https://github.com/ChurchApps/FreeShow/assets/1476340/012bef96-742f-42fb-a0b1-f445f7099c3a)
 
ALT pressed
![Screenshot from 2024-03-10 17-36-14](https://github.com/ChurchApps/FreeShow/assets/1476340/76651c5b-748f-4ac0-b515-d3bb6a665786)

**Comment by vassbo** [comment]
Yes, if you press the slides while holding the ALT-key it won't start the timer, or output the backgrounds you have set, that's why they are hidden.
