### ISSUE TITLE
Planning Center Online integration

### ISSUE THREAD

**Issue by Jhalfast** [ChurchApps/FreeShow#437]
I can't seem to find if this is a feature - current or planned... any insight to share?

**Comment by vassbo** [comment]
Not sure if and when this will be added.

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.6-beta.1

**Comment by vassbo** [comment]
Try out the Planning Center integration in the latest pre-release: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.6-beta.1
Docs: https://freeshow.app/docs/faq#planning-center-integration
