### ISSUE TITLE
Timer placed on an overlay does not start

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#439]
A timer within an overlay does not start on the slide Action > Start timer.  
The timer displays correctly when the overlay is attached to a slide, but never starts.
Is there a trick to start it, or is this a bug?

The same timer functions correctly when added directly to a slide.

**Comment by vassbo** [comment]
Thanks. Probably a bug. Will check it out.

**Comment by vassbo** [comment]
I realized that you can just add a invisible timer item to the slide, but I will make it start when there is an overlay with a timer on the slide in the next version.

**Comment by colanct** [comment]
Thank you for the feedback.  That's a useful work-around.

**Comment by colanct** [comment]
Now fine in 1.1.5.  Thank you.
