### ISSUE TITLE
Featured Requests

### ISSUE THREAD

**Issue by danielamankwaah** [ChurchApps/FreeShow#440]
Love the Freeshow app, been using it for 2 years and it keeps getting better and better.

I would love to recommend the following features for your future builds:
- The ability to loop audio 
- The ability to adjust audio level for individual audio playback files
- The ability to set up an audio playlist
- The ability to play segment of a video (start and stop)
- Improved Text Transitions

**Comment by vassbo** [comment]
Amazing! Thank you. :)

- You can loop audio in the audio preview (double click or right click and select "Show preview") - it does not save the looping for that audio file, which I guess would be nice.
- Would be nice.
- Should be added soon. - I was thinking each folder added from the computer could be a playlist.
- Right click a video and select "Edit", here you can set a "Start" and "End" time.
- Should also come soon.
