### ISSUE TITLE
BUG: artistmetadata on songimport

### ISSUE THREAD

**Issue by Kimosaj** [ChurchApps/FreeShow#441]
Hi, I have a problem when I'm importing songs from a textfile. The metadata for artists is always cutted by the first letter.

**Comment by vassbo** [comment]
Thanks. Are you able to send an example file where this occurs.

**Comment by Kimosaj** [comment]
I'm sorry for the late response. The textfiles are from Songselect. Because of copyright I will only post a small snippet of the relevant part.
Here it is:
[Praise.txt](https://github.com/ChurchApps/FreeShow/files/14770312/Praise.txt)

And here is a screenshot of the metadatasection after import:
![Bildschirmfoto vom 2024-03-27 09-28-08](https://github.com/ChurchApps/FreeShow/assets/39066306/63509800-c30f-4ba1-9040-b61b574cf9b0)

**Comment by Kimosaj** [comment]
The next thing is the wrong order of the metadata, so that the artist are importet in to the licence section and so on.

**Comment by vassbo** [comment]
Okay, thanks.
