### ISSUE TITLE
Obtrusive cloud sync pop-up blocks normal use

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#443]
The cloud sync pop-up that appears for every sync blocks normal use for the duration of the sync.  This happens regularly when auto-sync and auto-save are both enabled. 

Thank you.

**Comment by vassbo** [comment]
Actually just changed this. Will take effect in the next update. :)

**Comment by colanct** [comment]
Ah, excellent; thank you.

**Comment by colanct** [comment]
Thank you.  That's much better.
