### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by usajerhel** [ChurchApps/FreeShow#444]
I would like to ask how to  resize the scripture font size ? I can't seem to find the adjustment of font size for the scripture.
![IMG_20240320_191822](https://github.com/ChurchApps/FreeShow/assets/128767590/20904d85-4e97-4f64-a3fd-f9ed2801dfa7)

**Comment by vassbo** [comment]
Hi, you have to edit the "Scripture" template. Or change to a different custom template.
