### ISSUE TITLE
Templates not loading correctly

### ISSUE THREAD

**Issue by Dexiion** [ChurchApps/FreeShow#447]
Hi guys!

I was trying to add some templates to my shows. I found two issues that I am not sure if they are a bug or maybe I am doing something wrong. Here they are:

First, when I try to apply a template to a show, the template to the first slide is not beeing applied, I have to drag the template to the first slide

![BUG_TEMPLATE_1](https://github.com/ChurchApps/FreeShow/assets/61138950/9f8e0913-6bfc-4204-8c15-2cab4b7540e2)

Second, I have a template with a visualizer (the two white lines are two visualizers, I didn't know how to made them so I find this way😅), when I apply another template the visualizers are not being removed

![BUG_TEMPLATE_2](https://github.com/ChurchApps/FreeShow/assets/61138950/9cd6248c-7328-4272-bb0f-ce7fb5275288)

I tried to find on the code where the templates are being applied but I did not found it, If you tell me where they are I can take a look a it. Is there any way I can debug the code easyly with breakpoints, threads, variables, etc?

Thanks in advance! 😄

**Comment by vassbo** [comment]
Hi, I will see if I can fix the problem with the first slide, and change it so the items can be removed. 😊
For the lines, you can also just use textboxes with a white background color.

**Comment by Dexiion** [comment]
I also tried with text boxes, but as It detects It as a text box, It tries to put the lyrics on it and end up like this:

![image](https://github.com/ChurchApps/FreeShow/assets/61138950/c7fa6b74-e901-471a-ae27-49e9f5a18eba)

I also notices that the issue with the visualizer happens with everything that is not a text box as you can see on the GIF:

![BUG_TEMPLATE_3](https://github.com/ChurchApps/FreeShow/assets/61138950/981c2bbf-aa05-47fc-a65b-71332291f700)

I made a [PR ](https://github.com/ChurchApps/FreeShow/pull/449) fixing the problem for the template not applying on the first slide 😉

**Comment by vassbo** [comment]
Thanks to your PR, i figured out that you must have added a template to that first slide already by dragging a template on to it!

To reset go to Edit, and click the arrow on the right side to show the "Slide" options, here you can set the slide template back to none. :)

**Comment by Dexiion** [comment]
Understood, thanks! 😄
