### ISSUE TITLE
Next on Media Finished not working for mp4 videos

### ISSUE THREAD

**Issue by halrobertson** [ChurchApps/FreeShow#448]
Next On Media Finished not working for me on mp4 videos. Plays video, then stops. If I include a slide timer the length of the video, it will advance.

Also, instructions say Next On Media Finished will work even if the video is set to loop. My looping videos play continuously until I switch to the next slide (this is how I prefer it).

**Comment by vassbo** [comment]
Seems like this happens just some of the time..
