### ISSUE TITLE
Templates not adding media and duplicating items

### ISSUE THREAD

**Issue by Dexiion** [ChurchApps/FreeShow#454]
Hi!

I just downloaded the new 1.1.5 version and I noticed two bugs on templates. First when the template contains a media is not beeing added and adds a duplicated item (camera in this case) as you can see here:

![BUG_TEMPLATE_4](https://github.com/ChurchApps/FreeShow/assets/61138950/8ec36e96-c267-4fb9-8ba3-047fce4fdabf)

Also with every click on the template there are items that are being duplicated to infinity:

![BUG_TEMPLATE_5](https://github.com/ChurchApps/FreeShow/assets/61138950/507e8995-a3bf-4a84-a107-1a8a544c0232)

Thanks in advance!

P.S: Sorry for being such a pain with templates 😅

**Comment by vassbo** [comment]
Okay, will check it out.
