### ISSUE TITLE
NEW UPDATE RELEASES: HOW TO RESTART THE APPLICATION?

### ISSUE THREAD

**Issue by SKU003** [ChurchApps/FreeShow#455]
I'm trying to understand what you mean by that when you release a new update when I open the application. Because I thought it's somewhere in the toolbar to restart then it will update by itself or just close the application, and it will update itself. Or if I click the checkmark, it will update it for me. Because It's an option rather than going to the FreeShow website to download it manually there. So how do I restart, where do I go for that?

![FreeShow_P74LI5kYhG](https://github.com/ChurchApps/FreeShow/assets/117542049/b9b17533-48de-47ba-af6d-e09a7e38ff3a)

**Comment by vassbo** [comment]
It's not yet working on Windows, so you will have to manually update for now until we can get the code signing to work properly.

**Comment by SKU003** [comment]
Understood, much appreciated.

**Comment by abhishikthraj** [comment]
Actually it is auto updating without my knowledge on the background. I don't understand why. I wanted to stay on the v1.1.4 but it keeps auto updating.

**Comment by abhishikthraj** [comment]
No it's on my windows 10 and windows 11 laptops

**Comment by vassbo** [comment]
Okay, great! It has never worked on the different laptops I have tested it on for some reason.
