### ISSUE TITLE
Sync Issues in version 1.1.5 & 1.1.6

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#457]
Initiating a manual cloud sync when auto sync is disabled displays the syncing popup indefinitely and windows shows briefly that FreeShow is not responding. This appears to be v1.1.5 regression as it was fine in v1.1.4.  Auto sync on save seems to be functioning correctly.

**Comment by vassbo** [comment]
How is this in the latest version?

**Comment by colanct** [comment]
Hello. For v1.1.6:
-  when Auto sync is enabled, manual sync functions as expected (large pop-up for duration of sync).
- when Auto sync is disabled, no pop-up is displayed on manual sync.  However, the small "Saved" notification appears in the bottom Right.  I'm unsure if a sync is made. Maybe related to removing sync on autosave.

So, the original issue appears to be fixed, but another anomaly has appeared.

Thank you.

**Comment by colanct** [comment]
I've setup a test PC to test this further after finding inconsistencies.  I've found:

**With auto sync enabled**
1. The initial manual sync displays the pop-up (spinning on darkened background), but it stays open indefinitely, necessitating manual closing of it.
2. The sync appears to be incomplete (probably as indicated by the syncing pop-up not closing.
3. Project names are then displayed correctly, but most of the Shows within each project display as _Unnamed_.
4. Subsequent manual syncs close the pop-up after a reasonable period, but there is no change to Shows shown as Unnamed.
5. After closing and reopening the app (which triggers auto sync x2), the Show names beneath all projects display correctly.

**With auto sync disabled**
1. A manual sync appears to invoke a save, but no sync is performed.
