### ISSUE TITLE
Sync issue in new version

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#460]
After installing the latest update, there seems to be an issue with the cloud syncing. Newly created items and edited items are not getting synced. New projects are getting synced though, and if you have created a new show on a separate device, it sees that a show is there but just says "unknown" in its spot. Then edited items are not getting updated on the other computers.

**Comment by vassbo** [comment]
Thanks. I'll check it out.

**Comment by colanct** [comment]
We are experiencing similar issues in v1.1.5, and have had to stop syncing and collaboration.  In new projects, shows are listed as Unnamed or sometimes as their hex identifier.

**Comment by vassbo** [comment]
Okay, will see if this can be fixed. You can downgrade if this a a big deal!
