### ISSUE TITLE
Bitfocus Companion Module "Crashed"

### ISSUE THREAD

**Issue by coshiro1** [ChurchApps/FreeShow#461]
Hello, upon downloading and adding the BC module (it did not show up on the list without adding it manually), it shows a status of "Crashed".

![image](https://github.com/ChurchApps/FreeShow/assets/53509111/74b268f4-4b95-42c7-a6ae-8d34313b8edc)

I am on Windows 11 Pro 22H2 Build 22621.3374, Bitfocus Companion 3.2.2+6688-stable-7417d2a0, and FreeShow v.1.1.5 if that helps. Thank you!

**Comment by vassbo** [comment]
Please click on the terminal output, and let me know what error you get.
![image](https://github.com/ChurchApps/FreeShow/assets/17619496/fe2dd9a6-8275-4391-817c-a8eb39c0db8c)

**Comment by coshiro1** [comment]
Hello, thanks for your reply. Sorry I should have included that in my initial post! Here it is:
![image](https://github.com/ChurchApps/FreeShow/assets/53509111/41194b60-aa85-42bb-9a8e-40ccfedd43ce)

**Comment by vassbo** [comment]
Have have to do "npm install"

**Comment by pvdl** [comment]
Maybe helpful:
https://github.com/bitfocus/companion-module-churchapps-freeshow/issues/1

This is for Linux Ubuntu / Mint, but I think this procedure should also work for MS Windows as @vassbo mentioned.
