### ISSUE TITLE
Fallas en reproduccion de video

### ISSUE THREAD

**Issue by Intercentral** [ChurchApps/FreeShow#462]
Hola, excelente herramienta de trabajo para las iglesias, Muchas Gracias. 
Quiero informar algo que me pasa desde la primera version, el programa la mayoria de las veces cuando voy a  una carpeta que tenga videos parpedea una o tres veces seguidas y solo  reproduce el audio mas no la imagen del video, le doy reproducir con el reproductor de windows y el video reproduce bien, la extencion del video es .mp4. en los servicios me envian diferentes formatos de video y los tengo que convertir a .mp4 para llevarme la sorpresa de que algunos videos los muestra otros no. tambien ocurre con los videos loops que utilizo de fondo para la proyeccion de las letras. instale un paquete de codec de video a windows pensando que iba a solucionar el problema, pero no. por esto ultimamente deje de usar archivos de video con el programa, solo utilizo imagenes, El programa corre en Windows 10 core i5 6500 8gb RAM y tarjeta grafica AMD RAdeon HD 7800, para evitar inconvenientes con la reproduccion de videos en los servicios utilizo VLC, para ir a la fija. pero me gustaria enviarlos desde FreeShow

**Comment by vassbo** [comment]
Thanks, will check it out! It should work better if you go back to the previous version.
