### ISSUE TITLE
Flickering Text Transition

### ISSUE THREAD

**Issue by usajerhel** [ChurchApps/FreeShow#463]
Hi! I have a issue in our freeshow. The Freeshow sometimes flicker randomly and it feels so heavy to use after the 1.1.5 update. 

Also, I would like to ask if we can do this type of lyrics show in our live feed using the freeshow or do we need an another application to use?. Like the picture below. Thanks!

![Screenshot 2024-04-04 140812](https://github.com/ChurchApps/FreeShow/assets/128767590/b93ffe16-1988-43f3-b09b-d9cf1de5b67d)

**Comment by vassbo** [comment]
Thanks. You can create a seperate output with a custom template that is like the one in the image, you can also set the "Lines" to 1 for just that output.

**Comment by vassbo** [comment]
Does it help setting the "Preview frame rate" to "Optimized" in the "Other" settings?
