### ISSUE TITLE
Chords are not displayed on the stage view

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#464]
I recently tried to add chords to my songs but I noticed that the chords not displayed on the stage view but it is only displayed on the main screen. I want to have the chords to be displayed only on the stage view to the musicians and not the whole audience.

**Comment by abhishikthraj** [comment]
Oh thanks I think I didn't, but I don't want to have chords in the main display. How do I do that?

**Comment by abhishikthraj** [comment]
Actually I'm unable to toggle it on or off in the stage view. I see it in the on state but I'm unable to toggle it

**Comment by vassbo** [comment]
You have this same toggle for a normal textbox to turn that on/off.
Try creating a new stage layout and see if you can toggle it on/off there.

**Comment by abhishikthraj** [comment]
Thank you it works
