### ISSUE TITLE
NDI only output (disable HDMI)

### ISSUE THREAD

**Issue by H01001000** [ChurchApps/FreeShow#469]
Hi, I wonder if it is possible to disable the output to e.g. HDMI, and make it output at NDI only?

p.s. it is possible to switch the layout for stage output on NDI? (else I make a new feat request)

**Comment by vassbo** [comment]
Yes, by not clicking the button in the top right corner you will not activate the HDMI outputs, but the NDI is still active.

In the "Stage" view, you can add an external window for the stage display and enable NDI for that.
