### ISSUE TITLE
Text formatting issues

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#470]
We have been facing multiple issues in the latest version of the freeshow app. 
1. There are issues while copy pasting the text. Sometimes it totally doesn't paste the text and sometime it doesn't paste the text at the place where my cursor is placed and sometimes the text is pasted but it is not visible - it appears when I go to shows tab and come back to edit tab.
2. While typing and sometimes when I hit the enter button, the cursor suddenly skips and gets placed in the start or end of the text or text box. It also happens when I delete or hit backspace and type something the cursor skips and gets placed somewhere else.
3. Some times when I paste text in between an existing text, it doesn't get pasted as expected. I text sometimes gets pasted at a different place or gets pasted twice or something

https://github.com/ChurchApps/FreeShow/assets/58181678/4339e996-0d01-46f1-bc55-ebad1528e8d4

I have attached a sample for one of the issue

**Comment by vassbo** [comment]
Okay, thanks.

**Comment by abhishikthraj** [comment]
Can you please re-open this issue. The issues still persists
