### ISSUE TITLE
Trigger for scripture and overlay

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#471]
I have a feature request. I want to clear overlay when I present the scripture from the scripture tab. I guess you would need to add a trigger for that  Can you please add that? It would be very helpful

**Comment by vassbo** [comment]
Actions can have a "Custom activation" in the next update, including "Activate when scripture is started".

**Comment by abhishikthraj** [comment]
Thanks a lot! it is very useful. In the same way is it possible to add 'Activate when scripture is cleared'?

**Comment by vassbo** [comment]
In the latest prerelease you can active an action when a slide is cleared: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.0
