### ISSUE TITLE
Add a Text box element to the stage screen editor 

### ISSUE THREAD

**Issue by QuintonJKolb** [ChurchApps/FreeShow#473]
It would be nice to be able to add a simple label to the stage screen. Currently there is not an option to do so.

**Comment by vassbo** [comment]
If you mean to add any text, you can do so by using variables?!

**Comment by QuintonJKolb** [comment]
That's true. I was just wondering if there was a simple label you could add to the stage screen just like to normal slides.

**Comment by vassbo** [comment]
Not a stage textbox. But what would be the usecase compared to just using a variable textbox?

**Comment by QuintonJKolb** [comment]
Just If you wanted to have a label to display text, i.e. a label that says 'Time Left' above a Timer object.

**Comment by vassbo** [comment]
Okay, would be better to just integrate that into each stage box then, I guess. Just turning on/off a default label.

**Comment by QuintonJKolb** [comment]
Yeah, just being able to add a simple label to place next to items, like being able to add a label that actually says 'Current slide' and to place it above the Current Slide element on the stage display.
