### ISSUE TITLE
OBS Browser Source, OutputShow Resolution pixelated, StageShow Resolution fine

### ISSUE THREAD

**Issue by doellme** [ChurchApps/FreeShow#474]
What am I doing wrong?

I want to use the OutputShow on port 5513 as Browser Source in OBS. The resolution is very pixelated. When I keep all settings and only switch to port 5511 (StageShow instead of OutputShow), the resolution is perfect.
Also viewing port 5513 in an independent chrome browser, the resolution is perfect.
Must be something specific in OutputShow in combination with OBS.

I did set the OBS Browser source width and height to 1920x1080 so that is not the problem.
I also tried to compare the HTML/Javascript differences between port 5511 and 5513 to find the issue but my knowledge is too limited on how this all works.

I am on a Mac and tried different macOS and Chrome and OBS versions, all the same.

Using NDI the resolution is fine as well but I need to use Browser Source because it eats up much less CPU than NDI does.

Here's a screenshot of the OBS window (left) and a Chrome browser window (right):

![image](https://github.com/ChurchApps/FreeShow/assets/67099117/1c559890-a44c-46ee-94d1-458e409ca41a)

**Comment by doellme** [comment]
Also I found that switching slides is considerably slower on OutputShow port 5513 than compared to StageShow port 5511. Maybe this helps identifying the issue...

**Comment by vassbo** [comment]
The OutputShow sends the entire output video encoded. But the StageShow only receives text, making it much faster and not pixelated, so use stage if you can. But if you want to mirror the exact output as OutputShow does, make sure the window OBS captures is big enough. I'm not sure why it's so pixelated, I guess it's an issue in OBS.

**Comment by doellme** [comment]
Thanks for the fast reply, but I am not capturing an output window from FreeShow, I am trying to use the OutputShow port 5513 web output as a browser source input in OBS (which I believe OBS then captures from an "invisible" chrome browser that it starts under its hood).

In contrast to NDI this is very low CPU and very low bandwith. And it also works fine across machines and networks. And it is very reliable and stable because in contrast to window/screen capture, the identifiers never change. [h2r.graphics](https://h2r.graphics) and [overlays.uno](https://overlays.uno) all use web output and browser source. I'd love to be able to use FreeShow in the same way. I think others will love that feature as well, once more people recognize the benefits.

The web output for StageShow has a good resolution in OBS (but is missing the style templates and transitions from OutputShow, of course). However, the web output for OutputShow seems resolution-wise like an exact size copy of the small FreeShow output preview window in the top right corner. But only when called from OBS browser source.

What I don't get is: Why is the OutputShow web output fine when called manually from a standalone chrome browser but pixelated when called from OBS as a browser window under its hood? If it is an issue in OBS, then why does it not happen with the StageShow web output and with the control web outputs? They are all perfect both in standalone and in OBS.

What is the difference here? Please help me find the pattern so that FreeShow can offer a third output option which would be browser source input to OBS in addition to the already existing direct window/screen capture and NDI...

**Comment by vassbo** [comment]
Right, I guess the window size of the OBS browser is very small then. Is it possible to increase the size?

**Comment by doellme** [comment]
Thanks for staying with me. Let's follow that lead:

As the browser size thing in OBS happens under the hood and off-screen, I wouldn't know how I could, as an OBS user, change the size of the OBS browser using the mouse (it is an invisible object), but of course there is the width and height properties of the browser source in OBS which I did set to 1920x1080:
<img width="378" alt="image" src="https://github.com/ChurchApps/FreeShow/assets/67099117/2727b2f2-45bf-43e8-90f8-f28b6b283c5a">

This seems to have no effect on the resolution displayed for the OutputShow web page, but it does affect the resolution and size in OBS of all other FreeShow web pages and also all non FreeShow web pages like h2r or uno or any other web page that I tried.

To me, this would strongly point to something being special about the OutputShow web page on port 5513.

And I think I found something: What I learned is that OBS uses CEF [Chromium Embedded Framework](https://github.com/chromiumembedded) for rendering web content off-screen, more specifically [this specific fork with OBS specific patches](https://github.com/obsproject/cef), so basically an _older_ version of chromium, 103.0.5060.134 from July 2022 and not the current chrome browser on my desktop. Because my 123.0.6312.122 desktop chrome browser does resize the OutputShow web page, only the OBS CEF does not.

So there must be something that prevents a chromium 103.0.5060.134 browser from allowing itself to be resized, and that something special must be part of the OutputShow web page, but is not a part of the StageShow web page.

Do you have any idea?  Maybe port 5513 output is somehow the same object as the small output window preview in the top right corner of FreeShow and the width and height of that small preview window has somehow become a property of the port 5513 output?

Sorry for my bad way of explaining things, but maybe there is something to it?

I would love to use FreeShow OutputShow web page on port 5513 as browser source in OBS!

**Comment by vassbo** [comment]
Okay, thanks. You said the OutputShow 5513 worked fine in a normal browser window. Which means that the resolution sent should be high, so it is not the small preview being sent.
As I explained earlier StageShow is unrelated to this problem as it sends just the text, meaning it can't be pixelated.
I will continue to investigate, and let me know if you find anything useful!

**Comment by doellme** [comment]
I think I found something...

The OutputShow port 5513 CSS uses
body {
    height: 100svh;
    width: 100svw;

while the StageShow port 5511 CSS uses
body {
    height:100%

And it seems that the small viewport height and width settings do not work properly with old chromium 103:

[https://caniuse.com/viewport-unit-variants](https://caniuse.com/viewport-unit-variants)

<img width="476" alt="image" src="https://github.com/ChurchApps/FreeShow/assets/67099117/81fac43d-474e-4fd9-925e-00135b295c53">


Any chance you could change the src/server/output_stream/App.svelte CSS to old-style 100% width/height settings to make it compatible with the old chromium browser inside OBS?

**Comment by vassbo** [comment]
Thanks! I will see if it's possible to change that.

**Comment by doellme** [comment]
Hej Kristoffer,

will you be able to include the src/server/output_stream/App.svelte CSS modification into the new release?

It's just two lines 123/124

height: 100svh;
width: 100svw;

to

height: 100%;
width: 100%;

Thanks a million!

**Comment by vassbo** [comment]
Hi, will do that. The reason to use svh/svw instead of % in the first place was to get the size better on mobile devices, because that was the initial use case for OutputShow to stream to a bunch of phones where there was no projector.

**Comment by vassbo** [comment]
In the meantime I think you should be able to use the "Current output" item in the stage display, there shouldn't be much of a difference.
