### ISSUE TITLE
Slide animation is not working in  main output screen

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#475]
The text transitions is not working properly in main audience screen output. It is working fine with the backgrounds but it is taking time and flashing directly for the text

**Comment by vassbo** [comment]
Okay, I changed it to be easier to manage, but will try to improve.

**Comment by abhishikthraj** [comment]
Sure thanks

**Comment by vassbo** [comment]
Updates here: https://github.com/ChurchApps/FreeShow/issues/463
