### ISSUE TITLE
Edit "Quick Lyrics"

### ISSUE THREAD

**Issue by Pistos** [ChurchApps/FreeShow#477]
I'm a programmer, so maybe my expectations are "wrong", but after using the Quick Lyrics when creating a new Show, I thought I could "reopen" what I provided for the Quick Lyrics, to make some edits, as if the Quick Lyrics were "source code" for the show slides.

I'm guessing that it's not really source code, it just acts as a sort of initialization script for the slides, then the slides are created and remain in the native FreeShow format. This is understandable, but I wonder if an "edit Quick Lyrics" feature could be provided.

A basic implementation approach could be: store the last Quick Lyrics input string, and allow the user to edit, but, on submission, just completely reset and overwrite the generated slides (with the newly entered Quick Lyrics string).

I suppose this is already doable by closing (discarding) the Show, and creating a new one.

**Comment by vassbo** [comment]
You can do that: https://freeshow.app/docs/views#text-edit
![image](https://github.com/ChurchApps/FreeShow/assets/17619496/704e8dd2-aa3c-46cb-a127-cd5d4dedf78a)

**Comment by Pistos** [comment]
Great. Thank you!
