### ISSUE TITLE
Unable to load any images

### ISSUE THREAD

**Issue by Pistos** [ChurchApps/FreeShow#478]
FreeShow seems unable to load or render any image files. In Media, it just shows spinners. When I drag to the main area, nothing shows. The JS console shows 404 errors, with the application seemingly trying to load from `http://localhost:3000/path/to/image/files`.

![freeshow--images-spinner](https://github.com/ChurchApps/FreeShow/assets/2885/bb6bd02e-faac-4ac5-9948-63f4e118b6a3)
![freeshow--console-errors](https://github.com/ChurchApps/FreeShow/assets/2885/07a6ab30-3361-434a-8037-1acf318e99b3)

**Comment by vassbo** [comment]
Not sure why this is. Does it work when you use the app and not the dev build?

**Comment by Pistos** [comment]
I might try that later, but, for now, let's try to debug the from-source build.

What is the port 3000 listener doing? Is it just a plain proxy or pipe from filesystem to serving files over HTTP? Or is it more than that? Does it have configuration I can check, such as a `root_dir_to_serve_files_from` setting?  Can it only serve files in dirs relative to the launch directory of FreeShow?

Are there special dependencies or libraries FreeShow needs in order to render files which I might not have installed on the system?

**Comment by vassbo** [comment]
It's just for rendering files (used for live reload). It is only used in the dev environment, and not the main application.

**Comment by Pistos** [comment]
Okay, I learned some things. You appear to be using https://github.com/thgh/rollup-plugin-serve for serving on port 3000. `rollup-plugin-serve` has a config parameter `contentBase`, which you are setting [here](https://github.com/ChurchApps/FreeShow/blob/a06825266b4c96b3dcaf0389636db435b02ae295/rollup.config.mjs#L68-L76) to be `"public"`. I can further see that there is a `public/` dir in the project root dir. If I copy an image file there, and then manually browse to `http://localhost:3000/x.jpg`, then I can see the image (in a regular browser). So that's some progress.

However, in FreeShow, there continue to be 404 errors because (according to the dev console), FreeShow is trying to fetch the image from `http://localhost:3000/home/dev/git/FreeShow/public/x.jpg`. It is using the entire absolute path of the image file, instead of merely the relative path relative to the repo root.

If I make a symlink in the root of the entire filesystem to the file(s) in `<repo root>/public`, and then add the root (`/`) as a Media folder, then the image appears in FreeShow, because the request inside FreeShow is `http://localhost:3000/x.jpg`, which is correct for what `rollup-plugin-serve` is expecting.

So, it seems to me that the bug is that FreeShow is building the `localhost:3000` URLs incorrectly.

**Comment by vassbo** [comment]
Okay, I guess it does not like the uncommon folder path it is given, starting with "/". I just pushed a dev build that should fix the issue, please try it out: https://github.com/ChurchApps/FreeShow/tree/c5fdb695db324cecf7cc2055cab9e068f17a43cb

**Comment by Pistos** [comment]
Yes, I can see the files now. Thank you.
