### ISSUE TITLE
Stage View Text Auto size

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#479]
Text auto-size for time in stage view is not being reflected as expected. It is going beyond the text box and it's getting clipped

**Comment by jzongker** [comment]
@abhishikthraj Does it happen on resize, like this?  I should be able to fix that if so.

https://github.com/ChurchApps/FreeShow/assets/1447203/8be819e3-6b20-45c3-9a26-677b36324289

**Comment by vassbo** [comment]
@Dcanadian This is another issue that was resolved in May.
