### ISSUE TITLE
Pasting in a new song

### ISSUE THREAD

**Issue by brimstav** [ChurchApps/FreeShow#482]
Is there a way  when manually adding a new song,  of pasting the text in the quick lyrics box?
I find that  I can't paste in the text  I can only type text in which  takes a lot of time.
thank you

**Comment by celilo** [comment]
There's no right click menu available, but a simple "Ctrl V" works for me in both Windows and Linux

**Comment by brimstav** [comment]
Wow, thank you that worked! I didn't know that short cut existed.

**Comment by celilo** [comment]
That's a standard keyboard shortcut that works in Windows and Linux in pretty much any program and not specific to FreeShow.
You can use "CTRL/CMD + V" according to the FreeShow shortcut reference.
https://freeshow.app/docs/shortcuts

I noticed that there is sometimes a screen redraw issue when directly editing a slide, where it appears that the text did not paste. However, if you click on another slide and return the the slide with the pasted text, the text is there.
