### ISSUE TITLE
app freeze

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#483]
The app kept freezing multiple times when I was trying to change the backgrounds in a live event and I had to kill the app from task manager. Can you please check the issue, I'm attaching my log file.

Thank you
[error_log.json](https://github.com/ChurchApps/FreeShow/files/15202167/error_log.json)

**Comment by vassbo** [comment]
Thanks, will definetly check this out. 👍

**Comment by greyAdaks** [comment]
I use the application on Linux, and sometimes, I encounter this issue occasionally. I would greatly appreciate it if you could provide a specification sheet for this application. This will help users understand the PC requirements necessary for optimal performance. If such a specification sheet exists, could you please direct me to it?

**Comment by vassbo** [comment]
@greyAdaks The freeze is not due to PC issues, the problem is in the code directly.
But here you go: https://freeshow.app/docs/features#system-requirements
