### ISSUE TITLE
Bug: NDI Output Laggy

### ISSUE THREAD

**Issue by MrDogeBro** [ChurchApps/FreeShow#485]
It seems that ever since v1.1.5, the NDI output has been much more laggy than in v1.1.4. It is just much slower to change and unresponsive, if it even changes sometimes, making v1.1.5 not usable for me and annoying since it constantly automatically downloads and forcibly installs v1.1.5. Any information on why this is or when it will be fixed if it's not an issue on my end would be nice. Thanks.

**Comment by vassbo** [comment]
Thanks. Will check it out.

**Comment by MrDogeBro** [comment]
Still seems to be present in v1.1.6 at least for me.

**Comment by MrDogeBro** [comment]
Thanks!
