### ISSUE TITLE
Feedback and Issues with Freeshow

### ISSUE THREAD

**Issue by FeranmiOyerinde** [ChurchApps/FreeShow#486]
Hi [Team Freeshow],

I hope this message finds you well. I've been using Freeshow and wanted to provide some feedback based on my experience. I'm grateful for the effort you've put into developing this software, but I've encountered a few issues that I believe could enhance its usability and performance.

1. **Lack of Control Over Video Resolution and Frame Rates:**
   I've noticed a significant limitation in controlling video resolution and frame rates within Freeshow. Having more control over these parameters would greatly enhance the flexibility and quality of video output.

2. **NDI Output Source Quality and Functionality:**
   Unlike other software like OBS, Freeshow's NDI output source doesn't function as a discoverable source for other software. It doesn't mirror the source properly, limiting its compatibility and usefulness for live streaming and broadcasting purposes.

3. **Limited Output Design Customization:**
   Freeshow lacks the ability to customize output designs for different outputs. For instance, in EasyWorship, users can have different design templates for each output, allowing for greater flexibility and customization. Implementing similar functionality in Freeshow would enhance its usability for various presentation scenarios.

4. **Performance Issues:**
   Freeshow appears to suffer from performance issues, particularly when it comes to displaying videos. It tends to crash intermittently, and there are noticeable frame skips during playback. Enhancing the overall performance and stability would greatly improve the user experience.

I understand that software development is a complex process, and these issues may require time and resources to address. However, I believe that resolving these concerns would greatly benefit the user community and contribute to the overall success of Freeshow.

If you need any further details or assistance in troubleshooting these issues, please feel free to reach out. I'm more than willing to provide additional feedback or assist in any way I can.

Thank you for considering my feedback, and I look forward to seeing improvements in future updates of Freeshow.

Best regards,
[Oyerinde Feranmi]

**Comment by vassbo** [comment]
Thanks. 😊👍

**Comment by alanbjoseph** [comment]
>
> 3. **Limited Output Design Customization:**
>    Freeshow lacks the ability to customize output designs for different outputs. For instance, in EasyWorship, users can have different design templates for each output, allowing for greater flexibility and customization. Implementing similar functionality in Freeshow would enhance its usability for various presentation scenarios.
> 

As far as I remember, there is a 'Styles' tab in the settings menu that lets you do precisely this.

You set a style and then go to the 'Outputs' tab and specify the style you want that particular output to use.

My church has two styles set-up.
One is a Main Stage View for Stage presentation, and another lower third view for OBS.

In outputs tab, I specify the stage view to follow the 'StageView Style' and the OBS NDI output to follow 'LowerThird Style'.

**Comment by vassbo** [comment]
@FeranmiOyerinde I need your input on point two.

1. The normal output is not limited by a set frame rate and resolution. If you send it via NDI you can change the frame rate in the "Outputs" settings. And the frame rate of the output preview can be changed in the "Other" settings.
2. Can you explain more what you mean here? FreeShow does send out NDI that can be received by e.g. OBS. What do you mean it doesn't function as a discoverable source? And what do you mean by "doesn't mirror the source properly"?
3. See @alanbjoseph's answer.
4. Should become more stable with each new update. :)

**Comment by FeranmiOyerinde** [comment]
@vassbo 
Thank you for the clarification! I want to clarify that I'm not talking about NDI input. My concern is with the hardware resolution options. Specifically, when I use a capture card, I can't change the resolution or adjust the frames per second.

Also, regarding the mirroring issue, I appreciate your attention to it. The problem has been resolved, and now it mirrors properly to OBS and similar applications. However, it's still not possible to set different themes for different outputs.

Thanks again for your work on this project!

**Comment by vassbo** [comment]
Thanks. I'm glad that issue got fixed!

First of all as I already explained in point 1: if you are not sending via NDI, but just capturing the screen, the output is not limited by any frame rate, it's rendering as fast as the computer can handle, you can change the output window resolution in the "Outputs" settings, but the content like text is using SVG so that's not limited by the resolution, the only resolution limit is the input of the media and the window size. So if you want to adjust e.g. the frame rate you probably have to tweak some capture card settings. Hope this makes sense, I don't know your setup so I can't know exactly the issue.

Secondly you can create different "Styles" (with different layouts/templates, etc.) and apply them to the different "Outputs" however you want.

**Comment by FeranmiOyerinde** [comment]
@vassbo 
Thanks for the explanation. Just to share my experience, I’m using an HDMI capture card that supports up to 4K resolution. Before switching to Freeshow, I was using EasyWorship, which allowed me to change the resolution, frame rate, color space, and aspect ratio directly within the software. In Freeshow, these options aren’t currently available. It might be useful to consider adding similar features to provide more control over the output settings for users.

**Comment by vassbo** [comment]
But if you change the resolution of the output window to 4K I'm pretty sure the capture card will also capture in 4K!
The frame rate / color space is based on what the computer is rendering and not what the software is sending.
![bilde](https://github.com/user-attachments/assets/8bc365e2-1cc7-45d5-996b-ed96986f6ecc)
