### ISSUE TITLE
Custom stage views / Chords stage view

### ISSUE THREAD

**Issue by istvanmate** [ChurchApps/FreeShow#487]
Hello, just found this project through everyone praising PP, and this was advertised to me as the free alternative for it, so I downloaded and gave it a try. So far it looks great, works fast, and I can see why it is going so strong.

I come from a heavily customized OpenLP background, in which we store all our songs for our worship team as well, not just the congregation. I find the chords function in FS to be in a very early stage both in features and looks. Are there plans to develop it further? I will definitely contribute, like I did in OpenLP.

The features I miss in FS currently which we use in OpenLP are:
- a worship team specific stage view, containing: chords, notes, scores (optionally MuseScore link or similar), basically things that are hidden in the slides but visible on the stage view, and the option to view the whole song with scrolling capability (for rehearsals). We currently sync our songs to our church website for off-church availability. Example song: https://www.trinitydebrecen.hu/openlp/#songid=42 (turn on chords and notes for full view).
- a lowerthird stage view, where 3-6 lines are consolidated into 1-2 lines for streaming compatibility, with options of adding extra characters, like "," or ".", removing new line, lowercasing/uppercasing the first character of the next word

If this is something, that you could tolerate in FS, then I will look forward to migrating to FS, also will look into learning Svelte.

**Comment by vassbo** [comment]
Hi, thanks. The chords feature could definetly be improved, any contributions here are welcome!

- You can make different stage layouts for different teams, with chords only in the stage display.
- You can also set a custom live stream output with lower thirds by editing "Styles" in the settings.

The features you asked for are already there, but feel free to ask more questions.
Svelte should be pretty simple to learn, so feel free to improve on e.g. the way chords work. :)
