### ISSUE TITLE
Disable multimedia keys?

### ISSUE THREAD

**Issue by Evgeniydjdeluxe** [ChurchApps/FreeShow#488]
Can you add a function to disable multimedia keys play the next previous one? I want to use this feature in other background players, but when I run freeshow, the multimedia doesn't work in the other player. Device MacBook Pro 14 m1pro

**Comment by Evgeniydjdeluxe** [comment]
Mac OS Sonoma

**Comment by vassbo** [comment]
You can now disable in the settings.

**Comment by Evgeniydjdeluxe** [comment]
> You can now disable in the settings.

I downloaded version 1.1.6 - when playing videos on the second screen, the control does not turn off (the buttons on the mac f7,f8,f9 play next, nothing has changed (

**Comment by Evgeniydjdeluxe** [comment]
Disable presenter controller keys - It didn't work, it doesn't turn off on my mac
![IMG_4313](https://github.com/ChurchApps/FreeShow/assets/161082661/0bd6238b-f595-42bb-8d80-23bc92146896)

**Comment by vassbo** [comment]
Oh right, I didn't know you meant these keys.

**Comment by vassbo** [comment]
If these keys still changes the slides in the latest version when you activate "Disable presenter controller keys", that means I can't do anything about it. But they should work if you unfocus the FreeShow window.
