### ISSUE TITLE
Feature Request: Remote Drawing

### ISSUE THREAD

**Issue by jfentress7** [ChurchApps/FreeShow#489]
Amazing application! 
We would love to have the ability to actually draw (ability to underline, circle, free draw) in the control_show the way we can from the host client. This would allow our pastor to draw connections and show exegesis work from scripture from his iPad up at the pulpit (Control_Show) to the FreeShow Host Client on our PC in the booth sending out to the projector. Hopefully this makes sense. If not please reach out and i’ll get back to you asap.

**Comment by vassbo** [comment]
Thanks. Makes sense. 👍

**Comment by jhewarren** [comment]
would likely be more accessible if the feature request was in the title (remote drawing?) as opposed to the generic feature request - which could be anything.
Not meaning as a criticism. I just had to open the issue to see what the request was

**Comment by jfentress7** [comment]
good to know thank you. i’m new to github.

**Comment by jfentress7** [comment]
Is there any chance of escalating this request? I know you guys are hard at work already with this software and it is appreciated. This missing feature is actually the only thing keeping us from being able to switch away from our current software/hardware. We are desperate to get rid of it and have something more stable. Thank you again for all you do.

**Comment by vassbo** [comment]
@jfentress7 Will see if I can get it done for the next update.

**Comment by chanx** [comment]
This feature already in Connection->Remote Show, am I right? but will be more useable if on remote show page(like on ipad/mobile browser), on drawing tab, we can see the current main screen so the pastor can draw/interact on the screen more precisely. For now the pastor only can guess, am i already point at the right place, because there is only a black touchpad view on the mobile screen. thanks.

**Comment by vassbo** [comment]
@chanx This feature is available in the ControlShow connection. I added a thumbnail preview to the draw touchpad for the next version!

**Comment by vassbo** [comment]
Should be available in 1.3.1!
