### ISSUE TITLE
Intermittent Crashing of Show being edited

### ISSUE THREAD

**Issue by lapwilson** [ChurchApps/FreeShow#490]
There are times I will be editing a show (song lyrics or quick text) and I will just be carried back to a blank Edit Screen showing recently edited shows.

When I re-open, the last edits I made were not saved.

**Notes**: Auto save is on (2 mins); Cloud sync is on (on startup and save) is selected.

**Version**: V1.1.5 (for Mac)

**Comment by vassbo** [comment]
Thanks, I think this might have something to do with auto save or cloud sync. Might be better in the next update.

**Comment by vassbo** [comment]
How is this in the latest update?

**Comment by vassbo** [comment]
Should be fixed. Related: https://github.com/ChurchApps/FreeShow/issues/468
