### ISSUE TITLE
Grammar Error in Documentation

### ISSUE THREAD

**Issue by greyAdaks** [ChurchApps/FreeShow#496]
![image](https://github.com/ChurchApps/FreeShow/assets/150811338/d96664db-7708-4569-adc8-d36908b01c89)

I was reading the docs and I came across this error in the highlighted paragraph.

Suggestion from `ChatGPT`:
When editing a show, you will see a few buttons at the center bottom. One of them displays a `'note'` icon with the label `'Chords'`. Click on it to enable chords mode. This will display any existing chords and add a '+' button to the top right corner of all textboxes. Click the '+' button to add a chord, or right-click to choose from a list.

**Comment by lubomsky** [comment]
There is dedicated repo for the website: https://github.com/ChurchApps/FreeShowWeb/issues
