### ISSUE TITLE
Poor Media Playback Performance

### ISSUE THREAD

**Issue by awildeone** [ChurchApps/FreeShow#498]
Greeting devs,

**First**: As a regular ProPresenter user for over 10 years, I'm very excited about FreeShow. Already the feature set is great. That said, in the first 5 minutes I've run into issues that rule out using the app and I want to provide any feedback I possibly can to help change that.

Here's a few of them:

- Clear function is slow to respond
- Video output lags when playing files, frequently when interacting with UI elements
- Multiple audio sources run at once (feature not a bug?)

**Environments**: I was able to reproduce this on my Mac as well as my Windows desktop.

- MacOS 13.6.6, Intel i7 2.6Ghz, 32GB, dGPU. System resources were not being heavily used.
- Windows 11 23H2, 16GB, GTX1080 (GPU was being used)

### Clear All video delay issue:

How to reproduce the issue:

1. Load media files into a fresh show file and create a project.
2. Set transition time for media and slides to 0 seconds
3. Drop media into slide area
4. Click slide to activate media
5. Click "Clear Output" banner below output screeen
6. Media takes 1-3 seconds to clear.

The issue does not exist with the text layer. This clears immeidately when clicked.

What I've done as a sanity check:

- [ ] Test on MacOS
- [ ] Test on Windows
- [ ] Restart both macOS and Windows, then test again (no change)
- [ ] Test with lower bitrate files (no change)
- [ ] Test with audio attached to image slide (audio fades out even when the media transition is set to 0?)

### Video lagging issue:

How to reproduce the issue:

This issue appears to be easily reproducable on macOS, but not on Windows when I started testing. Though my eyes have told me it was happening on Windows. But as its not easily reproducable in the same methods, it's possibly related to a different issue.

This happened with video and audio files

1. Load media files into a fresh show file and create a project.
2. Set transition time for media and slides to 0 seconds
3. Drop media into slide area
4. Click slide to activate media
5. Click any other interactive elements. This was highly reproducable when clicking the tabs of the media browser.
6. **Bonus**: When clicking pause on a playing video, the video stops 1-2 seconds after clicking the pause button. That's not supposed to happen lol. But this was only on the macOS system.
8. **Bonus#2 **: When clicking between image slides, they took a quarter second or more (both macOS and Windows) to advance.

### Multiple audio sources playing at once when triggered:

When clicking multiple slides with audio, the default behaviour is to keep playing any slide that has been clicked. The only way to stop all of the audio is to click stop media or clear all (issue with that listed above).

This could be my fault, but I can't find a setting other than adding a "clear audio" trigger to every slide with an audio element to it plays exclusively. Similar to ProPresenters audio playlists. But in the general slides window, this was very different behaviour from Pro6/7. Though maybe its trying to be closer to QLab? More looking for your dev thoughts.

Thanks in advance. I'm happy to provide additional testing if needed.

**Comment by jzongker** [comment]
Just adding a bit more info here.  I'm able to reproduce this issue (or something similar) in the 1.1.5 production version, but it appears to be working correctly on the current dev version.  

Here's a video showing how it behaves on each.  The first round is live, the second is dev.  On the live version it appears to immediately stop the video, start up another copy, and then stop that copy two seconds later.
https://github.com/ChurchApps/FreeShow/assets/1447203/4937bd37-b8bf-436d-81ea-6d06ed5af51e

**Comment by jzongker** [comment]
@awildeone Version 1.1.6 was just release which I believe fixes the video lagging issues.  Could you confirm when you get a chance?

**Comment by awildeone** [comment]
@jzongker Just upgraded my PC to 1.1.6 (I'm happy to test on my Macbook if thats helpful).

**Clear All Delay**: This is _much_ better in this update. I wasnt seeing the delayed clear responses like I was previously. The new issue is that when multiple layers are running (text, & video, text & still image), they do not clear at the same time when the transition time is set to 0 seconds (I know lots of people like fades, but I typically run 0 seconds by default). From what I'm seeing, it looks like the background process is clearing things with a delay between commands. When I reset the fade times for slides and media back to their defaults, I wasn't able to tell if they were staggard.

**Multiple Audio Only Playback**: If there are multiple audio only (no visual layer) they still play over each other. Maybe an audio only media player would be good in a bigger version update? Then adding triggers to the slides if someone wants to have the audio player start a song or playlist?

**Comment by celilo** [comment]
> The new issue is that when multiple layers are running (text, & video, text & still image), they do not clear at the same time when the transition time is set to 0 seconds (I know lots of people like fades, but I typically run 0 seconds by default). 

I had the same issue on the previous version as well as the new release (Win10/11). When clicking through slides in sequence or using a GoToNext timer the problem occurs. However, if I manually toggle back and forth between two slides, the transition is perfect, probably due to Chrome caching the media.

**Comment by TPaulManohar** [comment]
Same issues I'm also facing lagging  and stuck, responses are delay in (Win10)
