### ISSUE TITLE
[Feature request] Shuffle slides in presentations

### ISSUE THREAD

**Issue by etsnyman** [ChurchApps/FreeShow#502]
Hi and thanks so much for FreeShow. I think it's absolutely fantastic and I would love to have it used more.

My feature request is to **be able to shuffle slides in presentations**.

This may seem silly or useless, but I have been in worship for about 24 years by now, ever since I was about 13, and this is a feature no presentation software has been able to provide yet. The ability to shuffle slides for announcements, music videos, or photos could be game-changing. This could possible be in the right-mouse-click menu or just a button next to the timer, or at a better place the dev's can think of.

Use-cases: Many congregations have slides, videos, or songs they play beforehand. The ability to shuffle them so that congregants are not bored or frustrated with having everything in the same order every service could be very useful. At the same time, many youth services and festivals I have been to and served in either the band or technical team has needed to play videos beforehand. For now, we have had to use VLC as a separate program, which does not work well with 2nd screens, or the tech person has to manually shuffle videos inside Resolume Avenue (or other expensive apps) on another PC/Mac.

Not only could this feature eliminate volunteers and beginners having to shuffle videos manually, but it could also bring all, or most, the features one needs at a professional level into one single application on one single laptop.

Again, I know this might seem trivial or silly, but at this moment, I am unaware of any other presentation program, such as ProPresenter, EasyWorship, or OpenLP, which would be able to do such a thing. This could really push FreeShow into the pro level use in my opinion.

Thanks again for the fantastic software. I am no programmer, and I have no idea how to code, but I can't wait to start getting other members/churches in my denomination to start using it.

**Comment by vassbo** [comment]
This is actually added in the latest version! You can create "Actions" in the "Functions" drawer tab, one of them is "Play random slide". If you add this action to every other slide, then it should move to a random one.

**Comment by etsnyman** [comment]
> This is actually added in the latest version! You can create "Actions" in the "Functions" drawer tab, one of them is "Play random slide". If you add this action to every other slide, then it should move to a random one.

Really? I will go check now. If so, FreeShow is about 1 or 2 features away from completely replacing 2 or 3 laptops running different pieces of software at our big (I mean thousands of people) youth festivals.

**Comment by etsnyman** [comment]
@vassbo Hi again. I tried it and it appears to work, but I seem to be having problems with "Next after media" again. I shall open a new Issue with a video linked, sometime over the weekend.

**Comment by vassbo** [comment]
@etsnyman I realized when the media transition duration was less than 0.9, an error in the calculation made the "premove" add to the duration instead of reducing it, meaning the video cleared before it realized that it had reached the end.

**Comment by jquyatt** [comment]
I'm trying to implement this for an event I have tonight. Adding "Play random slide" to all of my slides only seems to cause a continuous loop of new random slides retriggering, despite the Next Slide Timer being set to 10s. 

> This is actually added in the latest version! You can create "Actions" in the "Functions" drawer tab, one of them is "Play random slide". If you add this action to every other slide, then it should move to a random one.

If I followed this suggestion, every slide I applied this to would immediately jump to a new random slide, which could also cause another retrigger if it were to randomly select another slide with this action enabled. The only way I can imagine getting around this is having a dummy slide in between each actual slide to be presented, and if I'm working with a large slideshow, that's impractical to set up.

Is there a more practical way to set this up currently?

**Comment by vassbo** [comment]
You have to use a dummy slide in between, but I suppose I can add a "wait" action for multiple actions in the same action group.

**Comment by jquyatt** [comment]
I'm still having trouble utilizing this. I made an action as you showed above and I am not able to easily apply the action to every slide in my show, only dragging one at a time. What's the proper workflow here?

**Comment by vassbo** [comment]
I might add back the "Run action" slide action.
