### ISSUE TITLE
Show Layouts is not working

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#503]
The different layouts of a show should be able to have different versions if the same song but the changes made in one layout is being reflected in all the layouts

**Comment by vassbo** [comment]
I think this is working as expected. The different layout are used to arrange the slides in a different way, including adding different layers to the slides, but the slides in itself are supposed to be global between layouts. If that's what you meant by changes being reflected!?

**Comment by abhishikthraj** [comment]
Let's say I have a show, In one layout I want the lyrics on the side of the screen, so I create a new layout and and reposition the text in the second layout. Once I do that the text position changes in the first layout as well. 

**Please note the first slides of the attached images below**

![image](https://github.com/ChurchApps/FreeShow/assets/58181678/0118ab51-4bb9-4062-b3e5-7f07864641a1)

![image](https://github.com/ChurchApps/FreeShow/assets/58181678/ff0cbe87-746d-41cd-bfb8-ba767bb908d9)

![image](https://github.com/ChurchApps/FreeShow/assets/58181678/5c6e0a7d-8185-4d4f-b1b1-7ac8bd3076a5)

**Comment by vassbo** [comment]
Yes, this is expected. You you can copy the slides if you want to change the style, or set a different output style with a custom template that aligns the text.
