### ISSUE TITLE
Intel Mac build for v1.1.6

### ISSUE THREAD

**Issue by JVoorn85** [ChurchApps/FreeShow#505]
Please build not just for ARM Mac's but also for Intel x64 Mac's.

**Comment by thebiblelover7** [comment]
Yes please!

**Comment by vassbo** [comment]
Github Actions was updated, so I didn't know it changed from Intel x64 to arm64. Fixed for the next build! @jzongker are you able to build 1.1.6 for x64, and upload it to the release?

**Comment by jzongker** [comment]
Yes, I'm unable to test it on my ARM M1, but the x64 build is available here..

https://github.com/ChurchApps/FreeShow/releases/download/v1.1.6/FreeShow-1.1.6-x64-mac.zip
