### ISSUE TITLE
Import from SoftProjector

### ISSUE THREAD

**Issue by Cadmiel83** [ChurchApps/FreeShow#509]
Is there any chance to be able to import from SoftProjector application ?

In SoftProjector in SONG category you are able to create SongBooks, and save the song in which book you would like.
The books cand be exported with an *.sps extension.

Is it possible to have this feature to import this "books" which we have already written ?

**Comment by vassbo** [comment]
This should be possible. Are you able to send over an example file?

**Comment by Cadmiel83** [comment]
hi,
yes I can send.In attach you can find an exported file from Softprojector
Thank you
Cu stima,Cadmiel Stoica0745790558 

    On Tuesday, May 14, 2024 at 10:39:20 PM GMT+3, Kristoffer Vassbø ***@***.***> wrote:  
 
 


This should be possible. Are you able to send over an example file?

**Comment by vassbo** [comment]
Please send the file directly to this mail: dev@freeshow.app. I don't think it works via the GitHub mail system. :)

**Comment by Cadmiel83** [comment]
Hello,
any news qith my request of importing lyrics from SoftProjector ?
Thank you.
Cu stima,Cadmiel Stoica0745790558 

    On Tuesday, June 18, 2024 at 04:42:53 PM GMT+3, Kristoffer Vassbø ***@***.***> wrote:  
 
 


Closed #509 as completed.

**Comment by vassbo** [comment]
You can do this in 1.1.9! File>Import>SoftProjector.

**Comment by Vitlyr** [comment]
Is there anyway I can import bible translations from softprojector?

**Comment by vassbo** [comment]
@Vitlyr You can't, but you can import XML, find a list here: https://freeshow.app/resources#scriptures
