### ISSUE TITLE
Can't install on Mac

### ISSUE THREAD

**Issue by dr-ngubo** [ChurchApps/FreeShow#510]
Here are the details of my Mac and the error message

<img width="470" alt="Screenshot 2024-05-13 at 15 43 57" src="https://github.com/ChurchApps/FreeShow/assets/28754098/1a3ebb91-55e8-4432-aff1-bc6a5959bed7">

<img width="253" alt="Screenshot 2024-05-13 at 15 45 05" src="https://github.com/ChurchApps/FreeShow/assets/28754098/262ba57d-b595-4cd6-8c55-0e56b4f37c59">

<img width="254" alt="Screenshot 2024-05-13 at 15 42 19" src="https://github.com/ChurchApps/FreeShow/assets/28754098/547243ee-e174-4a89-a947-23c025216741">

OS: `Sonoma 14.4.1`

Version installed: `FreeShow-1.1.6-arm64.dmg`

**Comment by thebiblelover7** [comment]
@dr-ngubo Try downloading [FreeShow-1.1.6-x64-mac.zip](https://github.com/ChurchApps/FreeShow/releases/download/v1.1.6/FreeShow-1.1.6-x64-mac.zip) which is the Intel x86 version instead of the M1 version...

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/505
