### ISSUE TITLE
Program crashes when activating NDI (Mac)

### ISSUE THREAD

**Issue by Henry5510** [ChurchApps/FreeShow#512]
Hello,
I use Freeshow on my Macbook (M2) so I use the ARM version of the program. As soon as I activate NDI in the settings, the program closes/crashes. I have installed the lastest version (1.1.6-arm64). Did I not consider something? If not I would be very thankful if you could fix this.

**Comment by lumi-dee** [comment]
I'm also experiencing the same issue. Was trying to download the arm64 version of 1.1.6 for a Mac M2, and it kept crashing upon startup. I reverted to 1.1.5 and turned off NDI, and then reinstalled 1.1.6 and it worked, but as soon as I switched back on NDI the program crashes. I did find that I can still run the x64 version of 1.1.6 without problem (that I've seen so far) however.

**Comment by vassbo** [comment]
NDI is not yet supported on the arm64 architecture. Just pushed a dev version that should work. Anyone able to test it?
https://github.com/ChurchApps/FreeShow/tree/68384f598e6755e6e4eaf0cd3984f0457060f4cb

**Comment by Henry5510** [comment]
I would test it but I don't know how.

I have to do something with the package.json, right? But what? Have I have to do it in a folder of the program (Macintosh HD/libary)? Thank you for your fast help.

**Comment by vassbo** [comment]
Thanks. Please download the code above as a zip file, then follow these steps:
https://github.com/ChurchApps/FreeShow?tab=readme-ov-file#help-the-development

Let me know if you get stuck.

**Comment by vassbo** [comment]
Here is the code download for you: https://github.com/ChurchApps/FreeShow/archive/68384f598e6755e6e4eaf0cd3984f0457060f4cb.zip

**Comment by Henry5510** [comment]
I installed the node.js and then I write npm install into the Terminal app. I also don't know what the first point means: Clone the code in this repo. Does this mean I have to download the Code? I have (of course). 

This comes after I enter npm install:

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/test/package.json
npm ERR! errno -2
npm ERR! enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/Users/test/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /Users/test/.npm/_logs/2024-05-14T21_03_41_560Z-debug-0.log


Thanks for your help.

**Comment by vassbo** [comment]
Yes, you have done the first step.

Make sure the terminal window is pointed to the same folder path as the extracted zip file.
https://apple.stackexchange.com/a/438999

**Comment by Henry5510** [comment]
OK it look like its working. Do I need the Command Line Tools from Apple (I think I need because there is an error right now ;) )? And do I have to uninstall the old/normal version of freeshow?

**Comment by vassbo** [comment]
I don't know if you need that, but if it says so you can try.
You do not need to uninstall the normal version. :)

**Comment by Henry5510** [comment]
I'm sorry to say that, but I don't get the Command Line Tools App and without there comes an error. Possibly lumi-dee can test it with success. I'm very very sorry.

**Comment by vassbo** [comment]
No worries. Thank you for trying.

**Comment by TPaulManohar** [comment]
Its crashes in 1.1.6

**Comment by vassbo** [comment]
@TPaulManohar You can use the x64 build, or it should work in the current dev version and the next update.

**Comment by jzongker** [comment]
I compiled the dev version on M1 Macbook Air and can confirm NDI output is working now.

**Comment by TPaulManohar** [comment]
@vassbo I'm using 1.1.6 - arm - x64 Stable Build on MacBook Pro M2.  
Waiting for next release update.

**Comment by chrisspiegl** [comment]
Is there any update on when the next release will come to bring M1 NDI support?

**Comment by vassbo** [comment]
Should come out in a few days.

**Comment by chrisspiegl** [comment]
This is incredible. The new release uses 10% CPU on my MacBook Pro M1 Max (with the intel version that had NDI working it was at 220%)! And NDI is working as expected 👍.
