### ISSUE TITLE
Video Looping Toggle Per-File

### ISSUE THREAD

**Issue by lumi-dee** [ChurchApps/FreeShow#514]
Hi there. Been using FreeShow for about a month now and have been enjoying it so far, despite a few issues that are understandable considering the program is relatively new (1.1.6 fixed a good bit of performance issues so thanks!).

I have a request(?)/query. Is there a way that the video loop toggle can be saved per media file? For example, I have a 5 minute countdown video, which leads into a blank slide with (Next on Media Finished). Unfortunately, to make this work I have to manually disable the Loop button every time I play the file. It would be nice to have a Looping On/Off option on the media file itself. Sometimes you *do* want auto looping, for a welcome slide loop or similar items, it's just a bit frustrating that it doesn't exist as an option for each individual media file (unless I'm missing some sort of setting).

Thanks in advance!

**Comment by vassbo** [comment]
Thank you. You should be able to use this button to toggle it on/off, per show, which I guess should be fine in your case:
![image](https://github.com/ChurchApps/FreeShow/assets/17619496/8267e2e0-6479-4fb5-8dec-58695ac3c880)

**Comment by vassbo** [comment]
Okay, then it's a bug.
