### ISSUE TITLE
Song lyrics download 

### ISSUE THREAD

**Issue by majikcarpetrider** [ChurchApps/FreeShow#515]
On MacOS since updating I am unable to download song lyrics. I reloaded the older version and I am able to download lyrics. Is this a bug or am I overlooking something. Thanks

**Comment by vassbo** [comment]
This is probably a bug. I'll check it out.

**Comment by majikcarpetrider** [comment]
ThanksOn May 14, 2024, at 4:51 PM, Kristoffer Vassbø ***@***.***> wrote:﻿
This is probably a bug. I'll check it out.

**Comment by lukestein** [comment]
Can confirm: lyrics works for me in Mac 1.1.5, spins endlessly in 1.1.6

**Comment by majikcarpetrider** [comment]
Yep. That's the problem.

**Comment by eanderson143** [comment]
Can confirm spinning on Windows 10 as well.

**Comment by RCPPinder** [comment]
I can confirm that this is not working on the PC version as well V1.1.6 on Windows 11
