### ISSUE TITLE
Add a progress bar for audio files

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#518]
Add an audio progress bar in the output panel, similar to the useful one displayed for video.
While progress can be shown via the "Preview" feature, that large format is unsuitable during live presentations.

Thank you.

**Comment by vassbo** [comment]
The reasoning for using the preview is when you have multiple audio files playing at the same time, but I guess this could be activated when there is only one audio file playing.

**Comment by colanct** [comment]
Thanks.  Playing multiple audio files simultaneously seems highly exceptional.  Or, am I misunderstanding something?

**Comment by colanct** [comment]
Nicely improved in 1.1.7; thank you. 
Audio progress bar added and simultaneous playing of multiple audio files is removed.
