### ISSUE TITLE
Cloud Sync issues still persist

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#523]
After trying out version 1.1.6, I thought it was good and everything was working okay.

Last night after putting together a couple new songs and trying to put backing audio to them, I saved, synced, and closed.

Now this morning, songs that were not newly created, sermon slides, and scriptures that happened to be in the same project as the new songs are now all missing their contents.

I can search the saved shows.json in google drive, and the show is listed, but if I search the shows_contents.json file, anything related to the messed-up items is not in there. The items local file just has a ["random #'s", null]. (See image 3)

Items that I had recently looked at/presented/add to project are now getting listed as unlabeled and then cannot be added back to the label they were under....

Nor can I re-add slides to those items that say they cannot find layouts. This was also an issue in version 1.1.5 and seemed to start with the change to background syncing.

1 thing that I noticed is that with one computer running 1.1.6 and the others running 1.1.4, it never caused an issue with the sync. It only seems to start once all computers are running the same version from 1.1.5 up. But not 100% sure of that..

![image](https://github.com/ChurchApps/FreeShow/assets/73187905/1d308c9e-d017-48e5-9549-b06c2a9e0181)
![image](https://github.com/ChurchApps/FreeShow/assets/73187905/54bc699a-9cbb-4e7d-8161-2fa3d71142b9)
![image](https://github.com/ChurchApps/FreeShow/assets/73187905/7234d745-e022-442d-a325-3c66b8fe0255)

**Comment by vassbo** [comment]
Okay, thanks. I'll check it out! Please ensure you have a backup of the old SHOWS_CONTENT file just in case (you can use the Google Drive file history)
Related: https://github.com/ChurchApps/FreeShow/issues/457#issuecomment-2109620887

**Comment by Bagel94** [comment]
@vassbo Thanks for taking a look!!

I ended up just making a backup off our Church PC. Made sure it was disconnected from the internet so it wouldn't sync :).
