### ISSUE TITLE
Cloud sync has become unusable

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#524]
Cloud sync has become unusable.

After creating a new show, adding it to a project, and then closing the app with auto sync enabled, the app appears to not detect the change and fails to trigger an auto sync.  This is evidenced by Projects.json and Shows_Content.json not been updated.

Reopening and closing the app corrects the issue probably due to syncing on startup.

However, other download-only syncing devices (both Win 10 with V1.1.6) end up in an unrecoverable sync state, whereby the Show files are never updated and appear as "Unnamed" in the project panel.  To fix this, as a last resort, I reset the entire sync, deleted all cloud-synced files on the cloud and on the slave/download-only synced device.  After configuring a new sync, all files synced correctly, but the app had to be closed and reopened before the Show names appeared correctly in the project.

Once a subsequent change was made on the master device (with bi-directional sync), the issue of Projects.json and Shows_Content.json not being updated (as described above) recurred.

Also noteworthy is that both Win 10 PCs occasionally report FreeShow is not responding when the Save and/or Sync is invoked.

**Comment by vassbo** [comment]
Related: https://github.com/ChurchApps/FreeShow/issues/457#issuecomment-2109620887
