### ISSUE TITLE
Feature Request - Another View to Show the Entire Project

### ISSUE THREAD

**Issue by awheeler010** [ChurchApps/FreeShow#525]
It would be great to be able to see all the shows (slides, media, songs, etc.) in the entire project in the main view. Right now you can only see the slides in the currently selected show, but to have another view where you're able to see the entire project would be very helpful.

**Comment by vassbo** [comment]
Comming next version!
![bilde](https://github.com/user-attachments/assets/3e2b70d6-eda9-4418-8d4a-73971fcfc916)
