### ISSUE TITLE
Next slides timer does not work

### ISSUE THREAD

**Issue by JoJo26josh** [ChurchApps/FreeShow#530]
I am new to free show.

The slides do not transition automatically. The timer does not start or reset, resulting in static slides.

This happened after the update...When i was in v.1.1.5 Did not had any issue but after the update v.1.1.6
this issue started.

And other issue which i found that when i open the app. When i click the sides it does not show up on live screen.
But i after configuration the screen then shows up.. Before the update when i open the app and click the sides it will always show the live screen.
![Screenshot 2024-05-18 223752](https://github.com/ChurchApps/FreeShow/assets/91175275/dc7fd3e9-dc80-40a8-b1e6-27da19de51a8)

Please help me out.
Thank you

**Comment by vassbo** [comment]
Hi, I'm not sure what has happened here. Have not had this issue before.
Have you tried restarting? Could you provide a screen capture so I can try to figure out what might have happened here?

**Comment by JoJo26josh** [comment]
Hi,
Yes i had restarted lot of times. and i reinstall 2 times but this issue didn't went..

https://github.com/ChurchApps/FreeShow/assets/91175275/e14d4773-5324-472f-bfef-ea6e75a102e3

This screen capture..👆

Thank you.

**Comment by vassbo** [comment]
Thanks. Will see if I can figure something out.

**Comment by JoJo26josh** [comment]
Hi
Can u find the solution pls help me out...

Thank you .

**Comment by vassbo** [comment]
I have not been able to reproduce this problem. Can you try creating a new output in the "Outputs" settings and delete the previous one, does that make any difference?

**Comment by JoJo26josh** [comment]
Hi 
Thank you for the suggestion...
I tried it and now it's working.
I appreciate your time .
