### ISSUE TITLE
1.1.6 Crashes on launch on Mac when NDI is enabled

### ISSUE THREAD

**Issue by jzongker** [ChurchApps/FreeShow#531]
A user called reporting this and Micheal was able to reproduce the issue on his Mac.  The current workaround is downgrading to 1.1.5.  it doesn't crash if NDI is disabled

**Comment by StvBradly** [comment]
Having the same issue with M2 Mac mini. So older version doesn't have this issue? How do I download 1.1.5?

**Comment by vassbo** [comment]
It's because NDI did not support the new arm64 build. Should be fixed in the dev version: https://github.com/ChurchApps/FreeShow/issues/512#issuecomment-2111083932
