### ISSUE TITLE
Template Media is not working.

### ISSUE THREAD

**Issue by TPaulManohar** [ChurchApps/FreeShow#534]
Hi FreeShow App Team,

We created a new template with added media image from pixabay. In template it showing the background Image, but when we applying that template to project it only shows text not background Image on output screen.

<img width="1439" alt="Screenshot 2024-05-20 at 4 36 13 PM" src="https://github.com/ChurchApps/FreeShow/assets/24794328/c10ac79e-4192-4ee9-8b15-06535e743ada">

macOS: Sonoma 14.5
Model: M2
FreeShow Version: 1.1.6

Thanks,
Paul.

**Comment by vassbo** [comment]
Should be fixed in the next update. :)

**Comment by TPaulManohar** [comment]
Thanks for confirmation
