### ISSUE TITLE
"New Collection" Bible Versions do not move to other chapters together

### ISSUE THREAD

**Issue by Robmendez1** [ChurchApps/FreeShow#535]
I am currently selecting two different downloaded bible versions, and adding them as new collection, one is in spanish, one is english, but when I try to use the new bible collection to display scripture, the two versions do not move together. Also the main display is not refelecting the scripture template, its as if one bible version is much larger than the other no matter what changes I make to the template. One bible text is much larger than the other, and they two bibles are on different books of the bible.
<img width="835" alt="Screenshot 2024-05-20 at 3 13 22 PM" src="https://github.com/ChurchApps/FreeShow/assets/170363624/a1c749d8-c763-4b80-a319-3f92165daddf">
<img width="286" alt="Screenshot 2024-05-20 at 3 12 59 PM" src="https://github.com/ChurchApps/FreeShow/assets/170363624/bc06b41d-899f-4cd5-b375-acf42c70e6d8">

**Comment by vassbo** [comment]
Thanks, will check it out!
Have you by any chance applied a custom template to the output (in the "Styles" settings)?

**Comment by Robmendez1** [comment]
These are my current style settings, do you think that applying a custom template would have been part of the problem or were you implying that a custom template can help me achieve the two bible versions displaying correctly? Thank you for working on this amazing software by the way. Very much appreciated by many
<img width="848" alt="Screenshot 2024-05-20 at 8 13 17 PM" src="https://github.com/ChurchApps/FreeShow/assets/170363624/136f4953-813c-498d-ad57-5949cf9a0285">

**Comment by Robmendez1** [comment]
Yes you are right, that did fix the issue of text size, but having two bible versions with a new collection still do not move to different books together but it will move to the same number chapter and verse while stuck in Genesis. This means that the second bible stays on genesis while the first bible is in a different book. Eg. second bible is in Genesis 5:5 while the first is in Luke 5:5, hope this makes sense to you and it might be user error again so thank you for any help you can provide. Thank you again
<img width="292" alt="Screenshot 2024-05-21 at 4 39 29 PM" src="https://github.com/ChurchApps/FreeShow/assets/170363624/6dd4d030-b730-4c8d-9091-62d0ae0e7f11">

**Comment by vassbo** [comment]
Great! It's a bug, that should be fixed! :)

**Comment by vassbo** [comment]
Do you still have this issue in the latest version?

**Comment by Robmendez1** [comment]
Hey this issue is resolved, thank you so much for your help. I know it is a lot of work getting all of these bugs fixed but we appreciate it. Have a blessed day!!! So far for my churches needs, its doing all we need and even more.

**Comment by Robmendez1** [comment]
Is there a way to store bibles locally, so we wont have to depend on wifi or internet connection to display verses? If so that would be amazing but havent figured it out yet, thank you

**Comment by vassbo** [comment]
Great! You can't download the Bibles offered by Bible.API, but you can import your own offline .XML Bibles by importing from supported formats like "Zefania".
