### ISSUE TITLE
 Freeshow 1.6 Download Error

### ISSUE THREAD

**Issue by Jakethewhite** [ChurchApps/FreeShow#536]
Freeshow will not download 1.6 on Ventura 13.6.7 only can download 1.5 and it will not update when you reload app as the info on 1.6 pop up shows.

**Comment by thebiblelover7** [comment]
@Jakethewhite Could you provide more information on the errors? Are you able to download Freeshow manually from the releases? What are your system specs?

**Comment by vassbo** [comment]
I guess that's because verison 1.1.6 does not have a dmg build (because of the arm64 version), but the next version should work fine. In the meantime you can download it manually from freeshow.app!

**Comment by Jakethewhite** [comment]
There's literally a DMG build on the website for it

**Comment by vassbo** [comment]
Does that work? The next update should have a .dmg for both the x64 and the arm64 version. This one was just for arm64, and all the previous ones were for x64.
