### ISSUE TITLE
ACTION FOR STAGE DISPLAY LAYOUTS

### ISSUE THREAD

**Issue by SKU003** [ChurchApps/FreeShow#537]
I'm trying to find the action on clicking on one of my shows like music, in the way that it changes the type of stage layouts for specific parts. Like in ProPresenter, where I would like to show the countdown and the action where it triggers a stage layout that just shows the time and the countdown to the service and then when I click on the first slide it changes the stage layout for the worship team to use. And couldn't find instruction on the website if that feature is there or not.

**Comment by vassbo** [comment]
At the moment you can right click any stage layout, and choose to move all connections to that layout.
