### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Mpagi-Paul** [ChurchApps/FreeShow#538]
You can add an option to display two bible versions on the same screen, add more editing features for customizing how scripture should look on the screen.
The easyworship data base import doesn't work well.
Online song search takes too long to an extent of not working

**Comment by vassbo** [comment]
The first two you can do: https://github.com/ChurchApps/FreeShow/issues/236#issuecomment-1683423643

Please send the database not working to dev@freeshow.app

The search should be working again in the next update.
