### ISSUE TITLE
[HELP] Some .WAV file is not playing in Audio Tab

### ISSUE THREAD

**Issue by hanshinelee** [ChurchApps/FreeShow#539]
I humbly seek your assistance with an issue I am facing. I have added WAV files to my show in FreeShow, but it seems the software is not recognizing these particular files. The playback time is displayed as 0 seconds, and they do not play when I press the play button. Other WAV files are recognized and play correctly, but these four specific files are not working. I would be incredibly grateful if you could provide a solution to this problem.
<img width="1470" alt="스크린샷 2024-05-24 오후 1 40 04" src="https://github.com/ChurchApps/FreeShow/assets/35419194/3e1ac5c3-c041-4cf0-9bdc-55ddac6313bb">
![스크린샷 2024-05-24 오후 1 40 04(2)](https://github.com/ChurchApps/FreeShow/assets/35419194/b793863f-1215-4ed1-8d37-763e6922a056)
<img width="1191" alt="스크린샷 2024-05-24 오후 1 41 54" src="https://github.com/ChurchApps/FreeShow/assets/35419194/17a38571-fe4b-4160-8da3-16118c35029c">
![스크린샷 2024-05-24 오후 1 42 58](https://github.com/ChurchApps/FreeShow/assets/35419194/6b6c9ad5-ef37-4338-8c6e-e2e6598bbfc9)
![스크린샷 2024-05-24 오후 1 43 11](https://github.com/ChurchApps/FreeShow/assets/35419194/dc91a12e-77aa-4d1d-be2b-16027c4386e5)
![스크린샷 2024-05-24 오후 1 43 21](https://github.com/ChurchApps/FreeShow/assets/35419194/892dcf6f-4eb3-4c52-9724-2d20f688eddb)
![스크린샷 2024-05-24 오후 1 43 40](https://github.com/ChurchApps/FreeShow/assets/35419194/f2632e21-8edc-471c-8031-22596c2f3274)

**Comment by vassbo** [comment]
You can try renaming them using just english characters just to check if that's the problem. If they still does not work, they might be encoded in an unsupported format.

**Comment by vassbo** [comment]
I managed to find the issue thanks to this: https://www.reddit.com/r/freeshowapp/comments/1czcr8x/comment/l5m6vio/
