### ISSUE TITLE
[Feature Request] Multilingual Songs

### ISSUE THREAD

**Issue by zefanja** [ChurchApps/FreeShow#540]
In our church we have slides with 2 or 3 languages. Right now you can have multilingual songs in FreeShow ([mix languages in text mode and separate slides by newline](https://preview.redd.it/multilingual-songs-v0-n33d9cfdha2d1.png?width=723&format=png&auto=webp&s=05c27109cfae244b481e50ccf00a4645eb672fa4)).

The issue is, that all the languages have the same style so it is hard to distinguish them.

## Idea
* Create a template with multiple textboxes and style them.
* in text mode use some kind of markup to tell the parser which textbox to use, e.g.

```
[Vers]
![tb1]Licht dieser Welt, 
du strahlst in unsrer Nacht auf,
![tb2]Light of the world,
You stepped down into darkness
![tb3]ดุจความสว่าง พระองค์เข้า
มาในความมืดมิด
```

**Comment by vassbo** [comment]
A textbox parser might be a good idea, you can easily style them if they are in different textboxes.

**Comment by vassbo** [comment]
In the next version you will be able to input/edit textboxes like this:
```
[Vers]
[#1]
Licht dieser Welt, 
du strahlst in unsrer Nacht auf,
[#2]
Light of the world,
You stepped down into darkness
[#3] ดุจความสว่าง พระองค์เข้า
มาในความมืดมิด
```

**Comment by zefanja** [comment]
Great! Thank you!

**Comment by noah-sheldon** [comment]
Hi @vassbo 

Thanks for the translation support in 1.27

I want to be able to add lyrics in tamil/tanglish(tamil in english)

currently i add the song as

[Verse]
எங்கள் நடுவிலே அசைவாடுகின்றீர்
ஆராதிப்பேன் ஆராதிப்பேன்
செயல்படுகிறீர் இந்த இடத்திலே
ஆராதிப்பேன் ஆராதிப்பேன்
engal naduvilae asaivaadukinteer
aaraathippaen aaraathippaen
seyalpadukireer intha idaththilae
aaraathippaen aaraathippaen

English meaning
"You are moving among us
I will worship, I will worship
You are working in this place
I will worship, I will worship"

Hence translation is not helping us there. 

We want to sing it in the local language but the letters are in English.

This is a simple song with  lyrics in Tamil/English/Tanglish
https://tamilchristiansongs.org/lyrics/vazhi-seibavar-way-maker-benny-john-joseph/

**Comment by vassbo** [comment]
You can import the different languages into different textboxes with this formatting: https://github.com/ChurchApps/FreeShow/issues/540#issuecomment-2252198076
And use templates to position/update it however you would like!

**Comment by noah-sheldon** [comment]
Thank you, understood 🙂
