### ISSUE TITLE
help help freeshow app crash upon startup 

### ISSUE THREAD

**Issue by dinoPPPBEMS** [ChurchApps/FreeShow#541]
freeshow app crash upon startup 
im using mac mini 2 with freeshow 1.16. latest download

**Comment by vassbo** [comment]
Have you downloaded the correct version? Please try the x64 zip version if you installed the arm64 version previously.

**Comment by dinoPPPBEMS** [comment]
Hi i tried uninstall again and reinstall the zip version but still fail. Previously was running well for few weeks but this time cant run, always crash upon at startup -------- Original message --------From: Kristoffer Vassbø ***@***.***>Date: Sat, 25 May 2024, 6:41 pmTo: ChurchApps/FreeShow ***@***.***>Cc: dinoPPPBEMS ***@***.***>, Author ***@***.***>Subject: Re: [ChurchApps/FreeShow] help help freeshow app crash upon startup  (Issue #541)
Have you downloaded the correct version? Please try the x64 zip version if you installed the arm64 version previously.

**Comment by vassbo** [comment]
Okay, did you have NDI turned on previously? It is not supported on the ARM64 architecture. Can you try running the app via the command line, and send a screenshot of any errors you get?
https://github.com/ChurchApps/FreeShow/issues/389#issuecomment-1925688711

**Comment by halrobertson** [comment]
Same issue here, 8GB M1 Mac Mini, Sonoma. 1.15 worked fine. Auto updated to 1.16 and crash on start. Every time. Downloaded the ARM version, x64. Same issue. Uninstall and reinstall 1.15, works fine.

**Comment by halrobertson** [comment]
Here's my crash report.
[Freeshow 1.1.6 Crash Report.pdf](https://github.com/ChurchApps/FreeShow/files/15505879/Freeshow.1.1.6.Crash.Report.pdf)

**Comment by vassbo** [comment]
@halrobertson Do you have NDI enabled?

**Comment by halrobertson** [comment]
I have used the NDI output in the past, but it is currently disabled.

**Comment by vassbo** [comment]
Okay, 1.1.6 is the first build for ARM, the previous versions have been running using the Intel architecture. I guess previously it has worked fine because the Intel build was converted in a way, but NDI should be supported natively on both architectures in the next version. I think this is the issue causing the crash.

**Comment by dinoPPPBEMS** [comment]
Is there any fix fr this? Can i revert to 1.15 at the moment?-------- Original message --------From: Kristoffer Vassbø ***@***.***>Date: Fri, 31 May 2024, 11:43 pmTo: ChurchApps/FreeShow ***@***.***>Cc: dinoPPPBEMS ***@***.***>, Author ***@***.***>Subject: Re: [ChurchApps/FreeShow] help help freeshow app crash upon startup  (Issue #541)
Okay, 1.1.6 is the first build for ARM, the previous versions have been running using the Intel architecture. I guess previously it has worked fine because the Intel build was converted in a way, but NDI should be supported natively on both architectures in the next version. I think this is the issue causing the crash.

**Comment by vassbo** [comment]
You can revert for now, the fix should come in the next update.

**Comment by halrobertson** [comment]
When I reverted, I had to go into Settings and disable auto updates. Otherwise, on next boot, the 1.1.6 version would launch. Just a tip...

**Comment by dinoPPPBEMS** [comment]
Thanks for the tip!

**Comment by dinoPPPBEMS** [comment]
Awesome, thanks for the update!
