### ISSUE TITLE
Importing powerpoint issue

### ISSUE THREAD

**Issue by JD821** [ChurchApps/FreeShow#547]
I have tried some PowerPoints of songs that we already use at church, and it doesn't create any slide, is there a minimum Office version required for this to work? Im using Microsoft Office 2016

**Comment by vassbo** [comment]
The PowerPoint importer is not the best at the moment, I guess it works best for newer versions.
Will try to update it sometime.
Related: https://github.com/ChurchApps/FreeShow/issues/491
