### ISSUE TITLE
Display scaling (Windows 11 Pro) conflicts with FreeShow understanding of window resolution

### ISSUE THREAD

**Issue by mark-epstein** [ChurchApps/FreeShow#548]
Running v1.1.6, but this issue existed on the previous version as well.

I have barely begun to scratch the surface of this software. However, just opening it up and trying to go through a few menus I immediately run into a problem:

I have two displays:
1 - 3840 x 2160
2 - 1920 x 1080
I have the 4k display (#1) scaled in Windows to 250%.

FreeShow seems to think that my second monitor is actually a higher resolution than it is.
![image](https://github.com/ChurchApps/FreeShow/assets/80222240/07b77474-3f59-41f7-9d55-332fe0ec0448)

If I use the "Identify screen" tool, it always draws the box around the 4K display correctly. But it will draw the box around display 2 in accordance with the higher resolution that it thinks the display is, so the box is off the screen, well overlapping display #1.

![image](https://github.com/ChurchApps/FreeShow/assets/80222240/b3e3d0e9-7c07-4b6a-8df5-83d2b1d260f9)

Further, if I turn on Present mode, the slide that should be limited to the confines of display 2, far overlaps display 1 (coincident with where the identify indicated the edges of the display were.

IF I set my 4k display scaling to 100%, both displays work as they should, but everything is tiny on my 4K monitor and I cannot read anything.

**Comment by vassbo** [comment]
Thanks, I'll check it out. Did you try restarting the application after the display scaling was changed? That resolved the issue for me.

**Comment by mark-epstein** [comment]
> Thanks, I'll check it out. Did you try restarting the application after the display scaling was changed? That resolved the issue for me.

I did try restarting, to no avail. The only fix that ever seemed to work was to turn off scaling, and that takes effect immediately without restarting FreeShow.
