### ISSUE TITLE
Sync issue with scriptures

### ISSUE THREAD

**Issue by pvdl** [ChurchApps/FreeShow#550]
Scripture text is not synced between two (or more) computers.

PC A:
Select or make a new Show
Go to Scripture
Select some text
Select 'New show' (bottom right)
Scripture text is added to your current show.
Save and sync.
What  happens: in cache.json you find an ID (reference) with the scripture text

PC B:
Open FreeShow
Sync
Go to your show where the scripture text is added.
You see 'Unnamed'

What  happens:
In `cache.json` on PC A you find an ID (reference) with the scripture text. But this file is not synced to PC B.
Only the reference ID is synced, but this reference ID points to 'nowhere'.

**Comment by pvdl** [comment]
Version 1.1.6
Related: https://github.com/ChurchApps/FreeShow/issues/457

**Comment by vassbo** [comment]
Thanks. Closing as this is related to the other issue you linked. :)

**Comment by pvdl** [comment]
Please reopen.
Issue still exists in v1.1.7
