### ISSUE TITLE
Templates with multiple textboxes applied to show with only one textbox

### ISSUE THREAD

**Issue by odlg** [ChurchApps/FreeShow#554]
In earlier versions of FreeShow, applying a Template to a show would add the number of textboxes in the template. That is not the case with 1.1.6 and dev.  The only way I can find to add the textboxes is to manually add a textbox to each slide in the show and then apply the template again to position them, etc. Is there an easier way?

**Comment by vassbo** [comment]
Will fix. Related: https://github.com/ChurchApps/FreeShow/issues/534
