### ISSUE TITLE
Parts of OpenLP lyrics missing after import

### ISSUE THREAD

**Issue by lof747** [ChurchApps/FreeShow#558]
Take the following songs exported from OpenLP in XML format as example, the show file is missing chorus and ending. Did I do something wrong? 

```
<?xml version='1.0' encoding='UTF-8'?>
<song xmlns="http://openlyrics.info/namespace/2009/song" version="0.8" createdIn="OpenLP 3.1.1" modifiedIn="OpenLP 3.1.1" modifiedDate="2024-06-06T03:56:51">
  <properties>
    <titles>
      <title>10000 Reasons</title>
    </titles>
    <copyright>Hillsong</copyright>
    <verseOrder>c v1 c v2 c c v3 c c e e</verseOrder>
    <authors>
      <author type="words">Matt Redman and Steve Angrisano</author>
      <author type="music">Matt Redman and Steve Angrisano</author>
    </authors>
  </properties>
  <lyrics>
    <verse name="c1">
      <lines>Bless the Lord, o my soul, o my soul<br/>Worship His holy name<br/>Sing like never before, o my soul<br/>I'll worship Your holy name</lines>
    </verse>
    <verse name="v1">
      <lines>The sun comes up, it's a new day dawning<br/>It's time to sing Your song again<br/>Whatever may pass and whatever lies before me<br/>Let me be singing when the evening comes</lines>
    </verse>
    <verse name="v2">
      <lines>You're rich in love and You're slow to anger<br/>Your name is great and Your heart is kind<br/>For all Your goodness, I will keep on singing<br/>Ten thousand reasons for my heart to find</lines>
    </verse>
    <verse name="v3">
      <lines>And on that day when my strength is failing<br/>The end draws near and my time has come<br/>Still, my soul will sing Your praise unending<br/>Ten thousand years and then forevermore</lines>
    </verse>
    <verse name="e1">
      <lines>Sing like never before, o my soul<br/>I'll worship Your holy name<br/>Jesus, I will, worship Your holy name<br/>Worship Your holy name</lines>
    </verse>
  </lyrics>
</song>
```

Show file
`["1e5de699667",{"name":"10000 Reasons","private":false,"category":"openlp","settings":{"activeLayout":"9ca8031e5de","template":"default"},"timestamps":{"created":1717646671980,"modified":1717654027013,"used":1717654014149},"meta":{"title":"10000 Reasons","author":"Matt Redman and Steve Angrisano","artist":"Matt Redman and Steve Angrisano","CCLI":"","copyright":"Hillsong"},"slides":{"ca8031e5de6":{"group":"Chorus","color":"#f525d2","settings":{},"notes":"","items":[{"style":"top:120px;left:50px;height:840px;width:1820px;","lines":[{"align":"","text":[{"style":"font-size: 100px;","value":"Bless the Lord, o my soul, o my soul"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"Worship His holy name"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"Sing like never before, o my soul"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"I'll worship Your holy name"}]}],"align":"","auto":false}],"globalGroup":"chorus"},"a8031e5de69":{"group":"Verse","color":"#5825f5","settings":{},"notes":"","items":[{"style":"top:120px;left:50px;height:840px;width:1820px;","lines":[{"align":"","text":[{"style":"font-size: 100px;","value":"The sun comes up, it's a new day dawning"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"It's time to sing Your song again"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"Whatever may pass and whatever lies before me"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"Let me be singing when the evening comes"}]}],"align":"","auto":false}],"globalGroup":"verse"},"8031e5de699":{"group":"Verse","color":"#5825f5","settings":{},"notes":"","items":[{"style":"top:120px;left:50px;height:840px;width:1820px;","lines":[{"align":"","text":[{"style":"font-size: 100px;","value":"You're rich in love and You're slow to anger"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"Your name is great and Your heart is kind"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"For all Your goodness, I will keep on singing"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"Ten thousand reasons for my heart to find"}]}],"align":"","auto":false}],"globalGroup":"verse"},"031e5de6996":{"group":"Verse","color":"#5825f5","settings":{},"notes":"","items":[{"style":"top:120px;left:50px;height:840px;width:1820px;","lines":[{"align":"","text":[{"style":"font-size: 100px;","value":"And on that day when my strength is failing"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"The end draws near and my time has come"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"Still, my soul will sing Your praise unending"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"Ten thousand years and then forevermore"}]}],"align":"","auto":false}],"globalGroup":"verse"},"31e5de69966":{"group":"","color":null,"settings":{},"notes":"","items":[{"style":"top:120px;left:50px;height:840px;width:1820px;","lines":[{"align":"","text":[{"style":"font-size: 100px;","value":"Sing like never before, o my soul"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"I'll worship Your holy name"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"Jesus, I will, worship Your holy name"}]},{"align":"","text":[{"style":"font-size: 100px;","value":"Worship Your holy name"}]}],"align":"","auto":false}]}},"layouts":{"9ca8031e5de":{"name":"Default","notes":"","slides":[{"id":"a8031e5de69"},{"id":"8031e5de699"},{"id":"031e5de6996"}]}},"media":{}}]`

**Comment by vassbo** [comment]
I'll check it out.

**Comment by TPaulManohar** [comment]
Same Issue We also facing. Few lines are missing.
