### ISSUE TITLE
[Feature request] Displaying group sequence in stage view

### ISSUE THREAD

**Issue by lof747** [ChurchApps/FreeShow#559]
Requesting feature to have group sequence display in stage view, or as a dynamic variable then have a free textbox to enter dynamic variable. This is similar to how OpenLP stage view where it displays sequence of a song on the top of the stage view.

![image](https://github.com/ChurchApps/FreeShow/assets/4714051/8d778324-5d19-4cbd-beb3-654ccd641c10)

**Comment by vassbo** [comment]
Would be nice,
