### ISSUE TITLE
Interface wouldn't show up

### ISSUE THREAD

**Issue by leonardo4tan** [ChurchApps/FreeShow#560]
> Hi, great piece of software. The software was awesome.

I've encountered a problem with the software. The User Interface just wouldn't show up on my Mac. The app icons show the app icon itself and the output icon but, it only shows the output without the UI. It first shows the loading intro interface but just gone after the loading finished. The output works though.
<img width="192" alt="Screenshot 2024-06-08 at 10 55 41" src="https://github.com/ChurchApps/FreeShow/assets/48441827/f444ff8b-6bd8-446b-ba7f-6da32dd79a58">

I've been using this software on 2 devices; a Macbook (MacOS Sono 14.5) and a PC (Windows 10). I've been connecting them with the backup data with Google Drive. Both with the integrated drive API and just basically just put the data folder to the cloud storage. I can open it in my PC with the data intact but, it just wouldn't run on my mac. I already reinstall it few times with the version 1.1.6 and the newest one 1.1.7. I tried restarted the device, deleted the data from the cloud but still wouldn't work.

Please Help! Cheers! God Bless!

**Comment by vassbo** [comment]
Thanks, this is a known problem on macOS, I hope this will be fixed. I have no idea why this happens.

**Comment by vassbo** [comment]
If you want, you can try deleting the FreeShow data on your mac here: `~/Library/Application Support/FreeShow/`
This should reset the program, and you can try loading in the data from the drive again afterwards.
Let me know how it goes.

**Comment by leonardo4tan** [comment]
<img width="791" alt="Screenshot 2024-06-20 at 16 10 04" src="https://github.com/ChurchApps/FreeShow/assets/48441827/cc510ab2-7d54-4cb7-ab9f-edca0567f63e">
Weirdly that folder does not exist in my hard drive.

Meanwhile, I found a solution by making it fullscreen using the top menu.

**Comment by vassbo** [comment]
Okay, no worries. Probably stored in another place. I'm glad you found a solution! :) Maybe the window has a tiny size, I'll try to add a minimum size, and we'll see if that makes a difference.

**Comment by vassbo** [comment]
Looks like this is fixed in version 1.1.8!
