### ISSUE TITLE
Output screens not working in the new update

### ISSUE THREAD

**Issue by abhishikthraj** [ChurchApps/FreeShow#561]
The output screens and styles are completely messed up in the new update. 

The first issue is that, apart from my primary output screen, my other output screen and stage view output screen is blank. 

The second issue is, I have the app installed on a different laptop, in that I'm able to view the output screens but the styles and the output screens are messed up. I've been getting a different style than the selected style for the output screens. The background colour is different but the over-ridden template looks fine

**Comment by vassbo** [comment]
I've been trying to recreate this issue, but I can't figure out the issue.

Here's my understanding of your issue:
- On one laptop the second and third (stage) outputs are not showing anything.
- On another laptop the background color is not the one set in the selected style.

Please try to remove your current outputs and styles, and create new ones. Does this fix the issue, or is it still broken?
If that does not work, please describe the issue more clearly.
