### ISSUE TITLE
Possible to Bold Chorus Only?

### ISSUE THREAD

**Issue by mlavio829** [ChurchApps/FreeShow#569]
Hi,
I can't seem to find a way, but wondering if there is a way in Templates to create the Chorus part of the song in bold and the verses in regular font?

**Comment by vassbo** [comment]
You actually can, as long as you don't have any templates set as output styles.
What you can do is set a template on the whole show first, then drop another template on just the Chorus slide, that way all the Chorus slides will be different to the rest.

This would have to be done for each show so I guess maybe not the best solution, I'm guessing there should be an option to set template for each group in "Groups" in the settings, to auto set the slide template if the group has a template.

What do you think?

**Comment by mlavio829** [comment]
That definitely works however going through over 300 songs might take a long time.
An option to set the template for each group (i.e. chorus group) would be quite helpful if possible.
