### ISSUE TITLE
How to deaktivate Loop-Funktion?

### ISSUE THREAD

**Issue by RitterWacko** [ChurchApps/FreeShow#570]
How can I deaktivate the Loop-Funktion and save it. Everytime I play the video the Loop-Funktion is activated again.

**Comment by vassbo** [comment]
Please go to the show "Media" tab on the right to turn off looping.
![331797397-b7595f4f-3f85-4846-92ef-4193438705aa](https://github.com/ChurchApps/FreeShow/assets/17619496/9aafd6af-8e4d-4c13-b44d-c36444ca8964)
