### ISSUE TITLE
The video should stay on the last frame

### ISSUE THREAD

**Issue by RitterWacko** [ChurchApps/FreeShow#571]
How can I manage to have the video stay on the last frame and not to fade out?

**Comment by vassbo** [comment]
I don't see any good use case for this, could you explain why this feature would be necessary? :)
What you can do, is to add an image of the last frame after the video, and set the "Next after media finished" action on the video.

**Comment by RitterWacko** [comment]
I use this feature all the time with PlayBackPro, PVP, ProPresenter, QLab...
For example, I had a show where all Speakers got an animation with their names when they enter the stage. The last frame of the animation, had to stay on the screen until we switched to their Powerpoint presentation.
Sure you can capture an image of the last frame but if you have to do this for 10-15 videos a few minutes before showstart, the you will find that this is a very nice feature ;-)

**Comment by vassbo** [comment]
Okay, I see. Should be able to implement it in a way. :)

**Comment by RitterWacko** [comment]
That would be great. 
Thanks for all your work you put in this Software!
