### ISSUE TITLE
SongSelect CCLI Integration

### ISSUE THREAD

**Issue by Marsipulami** [ChurchApps/FreeShow#572]
Is it possible to make an integration with the SongSelect database from CCLI?

It would be a huge enhancement in my opinion and would for sure convince me of this software rather than buying a tool like ProPresenter.

Thanks and God bless
Nathan

**Comment by jzongker** [comment]
I think this depends on #501 .  I'll look into their API when working on that.

**Comment by mlavio829** [comment]
This would be a huge help!

**Comment by jzongker** [comment]
I just sent a PR for #501 .  I requested access to the Song Select API and received the response below.  I've followed up asking if there is a replacement API we can use and am waiting to hear back.

![image](https://github.com/ChurchApps/FreeShow/assets/1447203/b84b9e46-a14e-4e58-9a52-d0f412539f1a)

**Comment by jzongker** [comment]
Had a few rounds of follow up with CCLI customer service.  It appears that ProPresenter has a special arrangement and SongSelect is not available for other platforms.  I'm going to close this issue until CCLI (hopefully) changes their position.  The only option for now would be to copy/paste lyrics into FreeShow manually:


_Thank you for the quick response. Is there a new API to replace it? What's the current method for software that wishes to integrate SongSelect?_

`There are currently no plans to replace the current API that we are on right now. We will definitely make an announcement if, or when we decide to start the program back up again.`

_Renewed Vision is stating they have migrated ProPresenter to a new API you provided in order to continue to offer SongSelect. Is that API not available to other presentation software?_

_https://support.renewedvision.com/hc/en-us/articles/16717107843987-Update-about-CCLI-and-ProPresenter_

`Yes, that is correct in that we migrated to a new API sometime last year, and in order for Renewed Vision to connect with the new API they had to create a new version of their software. Currently, the old and new API's are not available for other presentation software as stated below.`

**Comment by Marsipulami** [comment]
Thanks for trying. Hoping they will change their view on this.
in the meantime, keep up the good work

**Comment by gwonamfromkoradai** [comment]
First of all, thank you for the incredible work on this program! I love how simple you have made the front end, and this software has been something I have sought for many years.

I don't know anything around whether there are legal reasons this wouldn't work, but as Open LP has integrated with Song Select / CCLI, is it possible to simply adapt [some of the python files ](https://gitlab.com/openlp/openlp/-/tree/master/openlp/plugins/songs/lib?ref_type=heads) which link to Song Select? There probably is a reason that I am missing why this wouldn't be possible, but I wanted to ask. I would be willing to work on a plugin if this made sense, but there's probably some reason why this hasn't been done.

**Comment by vassbo** [comment]
Looks like they have mimicked the front end of SongSelect with user login, and grabbing the data that way.
I think it should be fine as this would be accessible to the user anyway.

@gwonamfromkoradai If you would like to work on a plugin for Node.js we can integrate, that would be nice.

**Comment by gwonamfromkoradai** [comment]
> Looks like they have mimicked the front end of SongSelect with user login, and grabbing the data that way. I think it should be fine as this would be accessible to the user anyway.
> 
> @gwonamfromkoradai If you would like to work on a plugin for Node.js we can integrate, that would be nice.

Yeah, that’s what I figured. Sounds good! I’ve started working on tweaking the code, so far login is working but I might need to make a basic UI to search for songs.

**Comment by mlavio829** [comment]
This would be huge if this could work!

**Comment by comebacktomorrow** [comment]
I haven't had much to do with free show, but I was just looking into this myself and came across this thread. Is this new?
https://documenter.getpostman.com/view/604633/TzseGkmA
I see that it has a reporting API, so I'm thinking it's newish?

**Comment by vassbo** [comment]
@comebacktomorrow It might look new, but it's not. And we don't get access!
https://github.com/ChurchApps/FreeShow/issues/776

**Comment by joschua8** [comment]
There is no news, is there? Are there any ways to help with this? FreeShow would be perfect for us, if it had the integration. Thank you for your amazing work!

**Comment by gwonamfromkoradai** [comment]
@joschua8 I made a standalone song search program which I was hoping to integrate into freeshow, but life has gotten away from me. If anyone else is willing to integrate, that might work, but I don't suspect I will be able to integrate it further for a few months. 

[Here is the stand-alone program](https://github.com/gwonamfromkoradai/SongSelectSave). I make make it downloadable as a single dmg to make it more accessible but for now that's as far as I've gotten.

**Comment by joschua8** [comment]
@gwonamfromkoradai Very cool that you've taken this on board. Unfortunately, I'm also busy for the next few months, otherwise I'd look into it. Maybe I'll get around to it someday.

**Comment by hiyjinx** [comment]
i assume both you guys are still busy with life lol

**Comment by maximilianbiebl** [comment]
I’ve actually been working on something related to this.

I continued developing the original Python project by @gwonamfromkoradai and turned it into a tool that downloads lyrics from CCLI SongSelect and formats them for use in presentation software, including FreeShow.

Repo:
https://github.com/maximilianbiebl/ccli_downloader

Thought I’d share it here in case it’s useful to someone.

**Comment by gwonamfromkoradai** [comment]
> I’ve actually been working on something related to this.
> 
> I continued developing the original Python project by [@gwonamfromkoradai](https://github.com/gwonamfromkoradai) and turned it into a tool that downloads lyrics from CCLI SongSelect and formats them for use in presentation software, including FreeShow.
> 
> Repo: https://github.com/maximilianbiebl/ccli_downloader
> 
> Thought I’d share it here in case it’s useful to someone.

That's amazing!! Going to check it out now
