### ISSUE TITLE
(Feature Request) Scripture editing

### ISSUE THREAD

**Issue by Zack762x39** [ChurchApps/FreeShow#573]
I'd like to be able to edit a single verse and it edits the whole bible like on video psalm. My church can be fast paced with scripture and I can't really use freeshow for scripture cause I gotta edit each verse to make it seeable and for the background during service. Unless it's there and I can't find it, I'd love for there to be an option for that and I'd appreciate it so much!

**Comment by vassbo** [comment]
You can do that by editing the existing scripture template, or create a new template and set one in the right of the "Scriptures" tab. And if you want even more control, you can also click "New show" in the bottom right, to be able to tweak even further. Hope this makes sense!
