### ISSUE TITLE
{META_TITLE} tag behaves strangely

### ISSUE THREAD

**Issue by jitzerttok51** [ChurchApps/FreeShow#574]
When I apply a template like in the image below, the main song text becomes the title and the song title comes in place of the song text. 
I've seen this only recently on 1.1.7 but strangely when I downgraded to 1.1.5 the bug was still present. 

Best regards,
Nikolay
 
![image](https://github.com/ChurchApps/FreeShow/assets/20264815/63d3c2c1-ab3e-425f-bd93-a749f2ee3b12)

**Comment by jitzerttok51** [comment]
Also in text edit mode I can see only this:
![image](https://github.com/ChurchApps/FreeShow/assets/20264815/44da267f-0e38-4995-8444-3ae26e230aff)
There should be text here not only {meta_title}

**Comment by vassbo** [comment]
For the first problem, please try clicking on the template again (clicking the same template multiple times will move around the textbox text content).

The second one I will try to fix. :)

**Comment by jitzerttok51** [comment]
Thanks for the quick response
For the second problem, I can also see in the edit window that songs have a second textbox with {meta_title}. I think this should disappear when the template is changed. Also, why are templates applied to the actual song/show. I thought it was only like a theme of some kind, so it should not change the original content?
