### ISSUE TITLE
macOS Sequoia - FreeShow Won't Launch

### ISSUE THREAD

**Issue by mlavio829** [ChurchApps/FreeShow#575]
Hello,
I know it is just in Developer Beta, however, FreeShow does not launch in macOS Sequoia. 

<img width="508" alt="Screenshot 2024-06-12 at 9 10 14 AM" src="https://github.com/ChurchApps/FreeShow/assets/9010174/92d17f9f-da90-4740-a367-589287117714">

**Comment by vassbo** [comment]
I guess we just have to wait a bit, to see how the support for Electron is.

**Comment by mlavio829** [comment]
Agreed. It did eventually let me open but seems buggy.

**Comment by vassbo** [comment]
In pre-release 1.2.5 I have updated the Electron version, it might be better here.
