### ISSUE TITLE
ProPresenter Japanese/Chinese character convertion (GB2312)

### ISSUE THREAD

**Issue by johnanan1990** [ChurchApps/FreeShow#577]
Hi! been testing and enjoying FreeShow so far but it has a bit of trouble handling special characters on import from ProPresenter.

Here's how the original looks
<img width="931" alt="Screenshot 2024-06-13 at 15 44 14" src="https://github.com/ChurchApps/FreeShow/assets/172576919/5a269884-f052-443f-9900-b97415de6473">

Here's how it looks after importing into freeshow
<img width="1159" alt="Screenshot 2024-06-13 at 15 43 48" src="https://github.com/ChurchApps/FreeShow/assets/172576919/7b104cca-d1fa-480a-aa48-8db43118f958">

**Comment by vassbo** [comment]
All ProPresenter songs are stored in base64 format, meaning all chararters have to be converted into just 64 characters, meaning special characters have to be encoded like this as shown in your example: `\'d7\'a3\'b8\'a3\'a4\'ce\'b1\'ad`.
This specific unicode encoding is of type GB2312, but should be decoded to UTF-8 (祝福の杯).

We will need to redo the way text is decoded sometime, but this will not be prioritized.
Maybe extracting the bytes, and using this: https://www.npmjs.com/package/text-decoder

**Comment by johnanan1990** [comment]
Sorry for the late reply! Thanks for looking into it!

I think I understand, appreciate the detailed explanation! 

Thank you!
John

**Comment by vassbo** [comment]
I could not figure out a working solution. I tried [iconv-lite](https://www.npmjs.com/package/iconv-lite) as well as [text-decoder](https://www.npmjs.com/package/text-decoder), but they could not properly decode even the raw bytes as GB2312 unfortunately, so it might be a different unusual format. But either way I'm closing this now as the imported text can be replaced manually.

**Comment by AngangGuo** [comment]
Will this link helps?
https://greyshirtguy.com/blog/pro7fileformat1/

**Comment by vassbo** [comment]
Unfortunately not @AngangGuo!
