### ISSUE TITLE
Urlencoded file names on the interface

### ISSUE THREAD

**Issue by gyuris** [ChurchApps/FreeShow#578]
Description: File names that contains non English characters are displayed urlencoded:
- on background layer
- on music layer?
- on the playlist.

Step to reproduce:
1. Add an image to FreeShow with non English characters, for example: "Háttér"
2. Sent it to background layer. It displayed as "H%C3%A1tt%C3%A9r".
![background image name urlendoded](https://github.com/ChurchApps/FreeShow/assets/847982/1ae03206-ef66-4c84-a788-98f326812558)

1. Add an MP3 music file to FreeShow with non English characters.
2. Create a playlist with these files.
3. See the content of the created playlist.
![playlist urlencoded](https://github.com/ChurchApps/FreeShow/assets/847982/ed1762d0-c680-42b9-afad-2ca3e415da5d)

Affected version: v1.1.7

**Comment by vassbo** [comment]
Fixed: https://github.com/ChurchApps/FreeShow/issues/565
