### ISSUE TITLE
Truncated OpenLyrics import

### ISSUE THREAD

**Issue by gyuris** [ChurchApps/FreeShow#579]
Currently the OpenLyrics/OpenLP importer only parses the first `<lines>` tag in a `</verse>` tag.  

For example this a valid OpenLyrics:

```xml
<verse name="v1">
  <lines>Some lyric</lines>
  <lines>Some other lyric</lines>
  <lines>An another lyric</lines>
</verse>
```
The importer only imports the content of the first `<lines>` tag: `Some lyric`.

Explanation: OpenLP normally creates only one `<lines>` tag per` <verse>` but puts an other `<lines>` tag if there is a [conditional verse break ](https://docs.openlyrics.org/en/latest/dataformat.html#split-verse) (`<lines break="optional">`) But it is not mandatory that a new `<lines>` tag indicates a verse break.  Even each new line can be a new `<lines>` tag (without `<br>`).

Please iterate over `<lines>` tags during OpenLyrics import.

A real test file : [Kanadai mise.zip](https://github.com/user-attachments/files/15844171/Kanadai.mise.zip)

**Comment by vassbo** [comment]
Great! Thank you.
