### ISSUE TITLE
the books of the Bible are not translated into Portuguese

### ISSUE THREAD

**Issue by uoshitopires** [ChurchApps/FreeShow#581]
The books of the Bible remain in English even if you download a Portuguese version. Is there a way to resolve this?

**Comment by vassbo** [comment]
The imported book names are the same as in the .xml file (meaning the are in english in your downloaded file), so you will have to edit the names in the .xml file, and import again if you want to change them!

**Comment by wagnersong** [comment]
como faço isso?

**Comment by Phantom-Matt** [comment]
> como faço isso?

Abre os arquivos .xml que provavelmente estão na pasta "Documentos/FreeShow/Bibles" do seu usuário em um editor de texto básico e usa a função "Localizar e substituir". Acho que essa é a maneira mais "fácil" para fazer essa possível tradução.

**Comment by Phantom-Matt** [comment]
> The imported book names are the same as in the .xml file (meaning the are in english in your downloaded file), so you will have to edit the names in the .xml file, and import again if you want to change them!

@vassbo  There's a case where that does not happen in that exact order: when the books in the .xml don't come with names (in case of a Beblia version that I have, they come on number). In that case, the "/src/frontend/converters/bebliaBible.ts" takes care of renaming, using the content from lines 100-167 to switch every name. After switching the names on there, I finally got the names of the books fully translated.

Changing 

![before-change-on-bebliaBible](https://github.com/user-attachments/assets/2756282b-008b-42de-ad61-7ebe94c6d295) 

to 

![after-change-on-bebliaBible](https://github.com/user-attachments/assets/d46701ed-2b90-4a57-92c3-2ca40ac324f9)


Problem is, changing the src for every language would require some time and a lot more lines on this file. Also, the final user most likely would not try to download source files and edit them. So, would be possible to enable a way to modify each book name from inside the program?

**Comment by Vitlyr** [comment]
Is there any possible way to change the font to arial or something to make different languages more accessible?

**Comment by vassbo** [comment]
@Vitlyr Yes, you can edit the "Scripture" template.

**Comment by vassbo** [comment]
I decided because it's so common that the XML files does not include the proper book names, that there should be a built in way to rename the books after all, but only for local scriptures if the book names are in English!
