### ISSUE TITLE
Memory leaks?

### ISSUE THREAD

**Issue by odlg** [ChurchApps/FreeShow#582]
If you leave FreeShow running for some days and then starts using it, it is crawling slow and takes lots of CPU power.  Restarting it fixes the speed and CPU usage immediately.  Could perhaps be some memory leaks?

**Comment by vassbo** [comment]
Probably! I will be trying to optimizing the code, to hopefully reduce this issue.

**Comment by odlg** [comment]
1.1.8 is significantly faster to start and also faster just after startup. Also the dev branch some days ago did not suffer from the slowdown.
