### ISSUE TITLE
Link to Bible.api not working

### ISSUE THREAD

**Issue by Racer6711** [ChurchApps/FreeShow#583]
Hi

I am new to Freeshow.  Setting up for my church.

I have it all working except that the Scripture Module doesn't open properly.

Looks like it isn't connecting to Bible.api???
![Freeshow Error](https://github.com/ChurchApps/FreeShow/assets/72370150/132c8dcf-8378-4105-ae3a-bcdd6c439a9d)

Any ideas on what is wrong?

Do I need to open a hole in my firewall?

Thanks!!!

**Comment by vassbo** [comment]
I have found the issue, and it should be fixed for the next version. You can use an offline bible in the meantime.

**Comment by Racer6711** [comment]
Brilliant!

 

Thank you.

**Comment by hoga2443** [comment]
I'm using version 1.1.9 on Windows 10, and the issue seems to remain.  I don't get a spinning wheel, or any response, when I click on the Scripture tab.  FreeShow stops responding, and the only resolution is to close the application.

**Comment by vassbo** [comment]
It's another bug @hoga2443 : https://github.com/ChurchApps/FreeShow/issues/630
