### ISSUE TITLE
Universal Backgrounds

### ISSUE THREAD

**Issue by Timothy-Rocha** [ChurchApps/FreeShow#587]
Hello! It would be awesome if there was a way to set a universal video or still background that applies to scripture and songs that overrides other backgrounds. For example, our flow involves having a welcome slide or sermon slide up whenever the preacher is speaking. When a verse is mentioned, we use the search in scripture to pull up the verse on demand (we don't receive the verses beforehand so scripture is put up on demand in real time instead of creating a slideshow where we can apply a background). What ends up happening is that scripture uses whichever media was last playing as a background. At the moment, the workaround I've found is selecting the background media first, then searching up the scripture, but this isn't ideal for speed reasons. If there could be a master background that takes priority, that would be awesome. We do prepare songs in advance, but having to set the background for each song isn't as convenient as simply applying a master background that applies to all text elements with a background in that session. 

![image](https://github.com/ChurchApps/FreeShow/assets/173066531/7300f713-4c12-4107-a3f7-4845392a8ed2)

Note: I do see that there is an option for a background in the styles setting that does set a universal background for songs and scripture (assuming songs aren't assigned another background already), however, it only supports stills and we also run into the issue where it uses the last played media as background instead of using the background added in the styles settings page. 

It's good that selecting media from the sections panel clears all and displays just the media, but it is troublesome when it comes time to put up a verse. It also doesn't loop automatically when selected from the sections panel.

If it's possible to achieve this using functions or templates that could work for me as well. I just haven't seen a way to add a video background to a template or find a way to use a function to select the video background automatically when pulling up a verse. Thanks for the help!

**Comment by vassbo** [comment]
Great suggestions!

**Comment by vassbo** [comment]
In the next version you can set videos in the output style, and set media backgrounds on templates.

**Comment by Timothy-Rocha** [comment]
Awesome! Thanks for update.
