### ISSUE TITLE
Media item transition between slides

### ISSUE THREAD

**Issue by MrShinyBoots** [ChurchApps/FreeShow#588]
Hi there - apologies if I have missed a setting but I have tried to tinker but cannot get the behaviour I want without a workaround. 

I want to create a template with a set place for a piece of media to be static in a song (chord charts) however when I use the media item - even when transitions are set to none and fade time set to 0.0 the media fades in. one workaround I have found is using an overlay - the problem is I will have to make a new overlay for each song I wish to do this for.

While my work around functions it is frustrating to have media refuse to not fade but also to have to create an overlay for each individual song.

essentially I would like a media widget that acts as an overlay rather than a standard overlay - this would mean I would not have to create then engage each overlay per song and I could just do it from the show edit window, by creating a template and loading the chord chart for the relevant song.

edit: i should note this "overlay media type" should only apply to the current "show" i.e song - the other overlays apply to every show in a project.

many thanks

**Comment by vassbo** [comment]
Please note that the "Text transition" should affect the "Media" item, and not the "Media transition". Does it work for you if the "Media" item has no transition, or would it be better to have some sort of "Show overlay" that always is active on the current show?

**Comment by MrShinyBoots** [comment]
Hi there, 

thank you for the quick reply, yes both text and media transitions were set to 0.0 / none, it may be a bug however I have tried it on arm64 1.5 and 1.6 (1.7 bug already mentioned in another issue means I can't test 1.7 on arm64) however I have tested 1.7 on windows. all of these exhibit the same issue. 

whilst this may be a fixable bug, as I'm using the same image for each slide in a song I thought a "show overlay" item would be less clicks for any user wanting to do a similar thing, set up a template then add your image once per song - this avoids the standard overlay issue of it being applied to every song in a presentation.

if it would be helpful for me to record a video of the issue I have encountered I could do that.

many thanks

**Comment by vassbo** [comment]
Okay, thank you. I will work on the way transitions work, to hopefully resolve this issue. But this feature might also be added sometime.

**Comment by vassbo** [comment]
By the way, if you want you should be able to create an overlay with your image, right click and select "Place under slide", then drag it on the first slide of a show. And even set a slide action on the last slide to clear. I guess this should be fine in your case.
