### ISSUE TITLE
Present and next slide’s text is displayed simultaneously

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#592]
Present and next slide’s text is displayed simultaneously for several seconds when transitioning within a show.

On investigation:
- The poor performance is not limited to slide transitions.
- Just switching between global app settings pages is particularly slow.
- Memory usage is exceptionally high and spikes to >3GB when switching between app settings pages (for example).
- Was first noticed on V1.1.6, but still occurs on V1.1.7.
- Often occurs on Win11, but cannot be reproduced on Win10.
- Closing and restarting the app resolves the issue, at least partially, so as to improve display of slide transitions.

**Comment by vassbo** [comment]
Related: https://github.com/ChurchApps/FreeShow/issues/463
Will update the way transitions work to hopefully resolve this issue.
