### ISSUE TITLE
Import ppt as pdf

### ISSUE THREAD

**Issue by dunyel** [ChurchApps/FreeShow#595]
![IMG_0206](https://github.com/ChurchApps/FreeShow/assets/173221890/84f3c582-2f08-4456-89de-f1efcfce353d)
Im trying to import a powerpoint as a pdf, but it says its not supported on linux on my macbook. Which linux software do i need to download

**Comment by vassbo** [comment]
The message means that PDF import does not work on Linux.
It should work on mac, but we have had some others reporting that it does not work all the time. So if nothing happens after a few minutes, then it probably does not work.

You can use an online PDF to JPG converter, and just drag in the images.
I do have on the TODO list to update the PDF importer if I can find a better solution.
