### ISSUE TITLE
Timers fail to start after starting a show via slide action

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#597]
Timers fail to start in a show after the show is started via a slide action.

_Start timers on active slide_ functions correctly when the show is activated manually, but is ineffective after the show is started from a slide action.

However, _Stop active timers_ functions correctly under both conditions.

**Comment by colanct** [comment]
The reported behaviour is unchanged in v1.1.9

**Comment by vassbo** [comment]
Okay, probably working sometimes, but not always.

**Comment by colanct** [comment]
The same behaviour (timer does not start) occurs when a show is started from a calendar event.

**Comment by colanct** [comment]
This issue remains unresolved in v1.2.0

The scenario is:
* Show B, Slide 2
   - has an overlay containing a timer.
   - has a slide action to start timer on active slide.
   - when the slide is played in sequence or is clicked on, the timer starts as expected.

* Show A, Slide 3
  - has a slide action to start Show B
  - when this Show A Slide 3 is played, Show B is started and sent to the output as expected.
  - the overlay on Show B, Slide 2 is displayed as expected.

* However, the timer on Show B Slide 2 is not started when Show B Slide 2 is output.
* Although Show B has been started and is outputted as expected, app focus remains on Show A.
* If  Show B is given focus by selecting it from the LH Project panel, the counter starts.

So, it seems that the timer does not start unless the show containing the slide with the timer has focus in the centre panel.

**Comment by vassbo** [comment]
Thanks for specifying! I have fixed this as well now.

**Comment by colanct** [comment]
I'm pleased to confirm that this is fixed in v1.2.1.
Thank you.
