### ISSUE TITLE
Automatic sync changes displayed content in Show/Edit panel

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#599]
_Automatic cloud sync_ is invoked on every autosave cycle.

On completion of  automatic sync, the item displayed on the centre panel is changed.
- When in _Show_ mode:  the selected and displayed Show is replaced with the FreeShow home / splash screen.
- When in _Edit_ mode:  the selected and displayed slide is deselected and _No slide selected_ is displayed.

The output/presentation is not affected.

**Comment by vassbo** [comment]
Should not sync when saving unless the app is about to close. I have fixed this now. :)

**Comment by colanct** [comment]
Thank you.
