### ISSUE TITLE
Provide a method to exit a continuous show loop

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#600]
At present, a show that loops continuously (due to the _Go to start slide_ action) can only be exited manually.  There seems to be no method to exit automatically.

A method to automatically exit the loop on a timer or media event would allow more use-cases.  Such a method would need to allow selection of timer finished or media finished, as a looping show could include both media (e.g. audio playlist) and a timer (e.g. countdown).

**Comment by colanct** [comment]
Aah, good. Looking forward to seeing how you did it.

**Comment by vassbo** [comment]
👍 You can set "Schedule action" in the calendar at any date/time to clear. Or trigger an action when a video or timer has ended.
