### ISSUE TITLE
Not able to delete a certain song

### ISSUE THREAD

**Issue by David-TLCC** [ChurchApps/FreeShow#604]
I don't know what caused it but realized that there are some songs I cannot delete or edit.

I am using google cloud fuction. It is seen in every PC that is linked (4 different PC - All windows)

One song's name changed to a series of alphabet and number by itself 'c84fcacbe31' and another one "Because of your love" 
When I delete, rename, edit these files and save, then somehow it came back and be reset loading from the cloud.

Any idea how to solve this issue?
<img width="1067" alt="20240622_144527" src="https://github.com/ChurchApps/FreeShow/assets/147236894/da8542f1-f715-463a-b201-911c467e79e9">

**Comment by vassbo** [comment]
This is due to the cloud sync. I need to implement a way to know if a file has been deleted. At the moment when you delete a file it will just be downloaded again, because it think the file in the cloud is new.

**Comment by ip4368** [comment]
Is it possible to actively delete it from cloud and now wait for it to sync?

**Comment by vassbo** [comment]
At the moment you have to delete it from the cloud and all computers, because if you remove it from the cloud it thinks the show on device is new and uploads that. I guess we will have to replace the show data in the cloud with e.g. "deleted" when a file is deleted on one computer, so it knows that and can delete the local files as well.

**Comment by David-TLCC** [comment]
According to the advices above, I deleted the "Shows_Content.json" file on google, while freeshow is running on a PC. Then, deleted the songs I don't need on freeshow and saved. This created new "Shows_Contents.json" file.

Thx

<img width="1036" alt="20240625_103533" src="https://github.com/ChurchApps/FreeShow/assets/147236894/e04faf2e-a37f-45da-b2d9-9e2deba0df20">
