### ISSUE TITLE
no auto clear background

### ISSUE THREAD

**Issue by byersbd** [ChurchApps/FreeShow#607]
I use a Linux based operating system and with the new 1.1.7 update I can no longer use the auto clear back ground option on my slides if you changed how to do so I could use the pathway to enable that option if not I would either like to have to add the background to any slide I want background on or for you to re-enable the option to have that background auto cleared or maybe it is just a problem with the Linux version app image and the scroll has been disabled on the option list of slide actions I don't know but I would very much like the problem to be resolved thank you
![Screenshot from 2024-06-22 11-45-40](https://github.com/ChurchApps/FreeShow/assets/173559451/d78798ff-8899-4330-91ac-3d6337d6fa5b)
This is an attached screen shot of what I am talking about notice there is no slide bar to scroll down for more options as there was in the past again thank you for your time

**Comment by vassbo** [comment]
This has moved to the "Start action". You can also create a clear action in the "Functinos" drawer tab that can just be dragged on to any slide if you set this often. :)
