### ISSUE TITLE
Issues saving

### ISSUE THREAD

**Issue by byersbd** [ChurchApps/FreeShow#608]
I am using Linux Mint and I am having issues with free show not saving and the only way to close it is to cancel the save and exit I would really like this issue to be fixed on 1.1.7 so I can began saving again thank you oh this is now a persistent problem.

**Comment by vassbo** [comment]
When you press CTRL+S does it not say "Saving..." in the bottom right corner? And when closing does it also not save??
You can turn on the "Always display popup before closing" in the "Other" settings, if that helps.

**Comment by byersbd** [comment]
The system says saving but when I go to exit it still brings up if I wish
to save or not then when I click save it does not and the program remains
open the only way I can close it is by clicking do not save and quit but I
do want to save and quit ps this same problem persist on windows platform
as well

**Comment by vassbo** [comment]
If a message says "Saved!" after pressing CTRL+S you are good to close the program.
You are on v1.1.7, right? Getting any errors in the console when you click "Save & Quit" and nothing happens?

**Comment by byersbd** [comment]
There is no message that says saved only a message that says saving but as
as if it never finishes no errors though and yes on the Linux version I
have the latest update

**Comment by vassbo** [comment]
Okay. Do you have cloud sync enabled?

**Comment by byersbd** [comment]
No the process would take some coordination to set up because I run three
different churches off your software and this is a problem across the board

**Comment by vassbo** [comment]
Okay, I have not experienced this issue before. Maybe there is something wrong with one of your files, causing it to not save.
You can try to do "Backup everything" and send the files in over a compressed file to this email: **dev@freeshow.app**

**Comment by vassbo** [comment]
Do you still have this issue if you update to 1.1.8?
