### ISSUE TITLE
MIDI Action is working properly.

### ISSUE THREAD

**Issue by TPaulManohar** [ChurchApps/FreeShow#609]
Hi Team,

MIDI action is not working properly, It not sending accurate signals. And there is no particular Tab or option called MIDI Manger that which midi signal has created or assigned.

And, after created MIDI Signal it shows on slide **Remove: Send MIDI Signal** or **Remove: undefined**, but what we created it didn't shows that particular action name or details.
![Screenshot (4)-1](https://github.com/ChurchApps/FreeShow/assets/24794328/99a393ff-528a-420c-9977-9a965ee8753d)

![Screenshot (5)-1](https://github.com/ChurchApps/FreeShow/assets/24794328/732336bd-c86d-497a-832d-c0d6a49c6a72)

Please fix this issue.

Thanks,
Paul.

**Comment by vassbo** [comment]
Fixed the "Activate on MIDI signal" not working. What do you mean by "not sending accurate signals"? In my testing all the values were correct.

**Comment by TPaulManohar** [comment]
Not accurate means, 
In slides i created a action-Activate MIDI Signal -> c-2 key for a first slide.

4slide i created another action-Activate MIDI Signal -> c#-2 it not sending even how times I click that slide.

3slide when I click it took E-3 midi signal, even i didn't  create any action-Activate MIDI Signal   how it sending that midi signal.

6slide i created another action-Activate MIDI Signal ->  d-2, it not sending any signal even i tried multiple times.

This what I'm saying it is not sending accurate signal.

Thanks,
Paul.

**Comment by vassbo** [comment]
Okay, thanks. Should be better in the next version.
