### ISSUE TITLE
Hanging on splash screen after upgrading to v.1.1.7

### ISSUE THREAD

**Issue by dantyndall** [ChurchApps/FreeShow#614]
@vassbo, just updated to the latest version. Encountered an issue though were FreeShow would just hang... tried rolling back to the previous working version (1.1.6), and encountered the same issue. I only solved it by removing %APPDATA%/freeshow. It's working now, but just letting you know if anyone complains about it.

**Comment by dantyndall** [comment]
Actually... I'm back to having problems again. FreeShow crashed, and wouldn't start again (stuck on the splash screen)... so I removed the %APPDATA%/freeshow folder again... and now it's locking up on "Updated shows".

**Comment by vassbo** [comment]
Hi, thank you. Can you please send over the "error_log.json" file in the %AppData%/freeshow file (If it has any new content)?
Please send to this mail: dev@freeshow.app

**Comment by dantyndall** [comment]
It's actually hanging on the splash screen again--and no error_log.json is being produced.

**Comment by vassbo** [comment]
Do you encounter this in 1.1.8?

**Comment by dantyndall** [comment]
Sorry for not getting back to you--had a rough day at work on Tuesday due to the unexpected shutdown of one of our HPCs, and then was terribly sick yesterday. 1.1.8 fixes the problems! Impressive that you were able to fix it without me sending any files along. Thanks! :D
