### ISSUE TITLE
Max lines for scripture

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#617]
Would it be possible to add in the ability to set the line count for scripture?

I know that in the scripture settings you can set it to be 1 verse per slide, but there are times that some verses just get to be way too long to look good on a single slide and gets even worse if you try to have a lower thirds version as the text will just overflow the textbox and not show the top and bottom of the text. Daniel 3:15 is a good example of this.

I know you can set a line count in a style that can be applied to the output, but as far as I can tell that does not affect scriptures, and I don't see any other setting to set one.

As far as I can tell, the only way to fix this is to do it manually by splitting the slides.

![image](https://github.com/ChurchApps/FreeShow/assets/73187905/61550b1d-d94e-4a0c-9e44-6f3375f22f48)

**Comment by vassbo** [comment]
You can use auto size.
