### ISSUE TITLE
Cloud sync media not syncing

### ISSUE THREAD

**Issue by lof747** [ChurchApps/FreeShow#619]
Hello,

Please correct if the following statement is correct: I think it is by designed that cloud sync is only for lyrics and layout, but the media is a local file system. 

If it is correct, then I would recommend updating the FreeShow Docs saying media is not part of cloud sync, and provide alternate way to sync media. This is especially useful in cross platform environment, e.g. our main computer is Mac but we have the need for worship leaders to pre-create lyrics at home and they are using Windows computer, we found the background is not synced (it is referencing Mac path instead of Windows path).

If it is incorrect, can you advise what log file / config file you require to troubleshoot this further please?

Thanks

Felix

**Comment by vassbo** [comment]
Hi, this is correct.
https://freeshow.app/docs/data#cloud-storage

Will try to integrate it at some point.
But right now you can use any provider to sync the media, like this one: https://freefilesync.org/

Here is the trick: As long as both of your media folders are added in the drawer, and you have set up drive sync for the shows, it will automatically find any matching media file with the same name when it's set as a slide background, regardless of the root path!
