### ISSUE TITLE
FreeShow 1.1.9 Not Displaying on Main/Edit Screen

### ISSUE THREAD

**Issue by halrobertson** [ChurchApps/FreeShow#624]
M1 Mac Mini, 8GB, Sonoma 14.5. 1.1.7 was working fine with the exception of slide timings getting wonky over time.

Installed 1.1.9 today and it will start, but it only shows the Output screen. Taskbar shows it launched, but all I see is my desktop. Clicking around, etc, no change. Deleted and re-installed 1.1.7, all is well again.

**Comment by vassbo** [comment]
Does it look like this?: https://github.com/ChurchApps/FreeShow/issues/560
