### ISSUE TITLE
Problems with the stage output

### ISSUE THREAD

**Issue by Nestor63** [ChurchApps/FreeShow#626]
Many times it does not connect to the IP address.

**Comment by vassbo** [comment]
Please check out this troubleshooting: https://freeshow.app/docs/connecting#troubleshooting

When it does not connect, is it always from another device? Please try connecting from a browser on the same computer as the program, does it have the same problems, or does it work then?

**Comment by Nestor63** [comment]
The problem is when I want to use another device, sometimes it works and
sometimes it doesn't. On the same computer it works fine so far.

**Comment by vassbo** [comment]
You can try with a wired connection, that should be more stable.
