### ISSUE TITLE
Audio Bug on 1.1.9

### ISSUE THREAD

**Issue by Acetoua** [ChurchApps/FreeShow#627]
Whenever I play something with audio or the audio itself it just hangs.

**Comment by vassbo** [comment]
Do you mean it don't clear? Please set the "Audio fade duration" to something above 0, that will work.

**Comment by Acetoua** [comment]
Hello, I mean it just hangs. The UI just hang. Well if I click the clear all it stops but the display hangs it doesn't show anything on the Presentation when I click any shows or videos. It didn't do this when it was 1.1.7. I haven't try it on other devices though.

**Comment by vassbo** [comment]
Okay, can you please send the "Log file" in settings<"Other" to dev@freeshow.app

**Comment by vassbo** [comment]
Thanks! It's the correct file. I think I can track down the issue now.

**Comment by Acetoua** [comment]
Hi! just following up on this bug. Should I re-install the app or am I the only one having this issue?

**Comment by vassbo** [comment]
This is probably a specific issue that occurs sometimes, but it might be fixed in the next version.

**Comment by vassbo** [comment]
Hi, is this fixed in this prerelease?
https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.0

**Comment by Acetoua** [comment]
Its okay now. Thank you!
