### ISSUE TITLE
2021 M1 Pro Sonoma 14.5 app nonresponsive

### ISSUE THREAD

**Issue by superfuture88** [ChurchApps/FreeShow#628]
Besides the info in the title, I have a secondary monitor that I'm using with the MacBook Pro screen open. The secondary monitor is my primary. Just downloaded version v1.1.9. First open and there was no window. Nothing in the File/Edit menus to start a new project or open a new window. Closed and relaunched the program. Got a window. Could click through library tabs and was able to click "New Folder" and name the folder. Was also able to click "New Project" but after that, no buttons seemed to work. I could still click through tabs but nothing was in the "Libraries". No images, no scripture options, Overlays, etc. Buttons for Edit, Show and Stage did not work. Several shutdowns and restarts don't seem to change anything. On the last restart, the window opened but was about 300x300. Very buggy all around. Excited for the possibility of the software, though.

**Comment by superfuture88** [comment]
Immediately after posting, played with the 300x300 window (expanded and started clicking on options) and the features became present. Was able to add a song, edit fonts, click between view modes, etc. However, when I clicked the scripture tab, things froze again and became unresponsive, so maybe the bug is there.

**Comment by vassbo** [comment]
Okay, the arm64 might be unstable because of electron. You could also try if the x64 version is more stable.
