### ISSUE TITLE
Text not Showing on version 1.1.9

### ISSUE THREAD

**Issue by ralphievolt** [ChurchApps/FreeShow#629]
I tried version 1.1.9 both on MacOS and Windows 11 and they have the same issue.
Test seem not showing like below when in Show tab
<img width="434" alt="Screenshot 2024-06-29 at 1 12 32 PM" src="https://github.com/ChurchApps/FreeShow/assets/5282658/63fec871-62b9-44c8-b89a-2525913bd4a8">

on edit tab here's how it looks
<img width="604" alt="Screenshot 2024-06-29 at 1 14 31 PM" src="https://github.com/ChurchApps/FreeShow/assets/5282658/f8261805-e444-4078-b6c4-b45f749a9992">

**Comment by ralphievolt** [comment]
but on the projected screen this will show the text.

**Comment by ralphievolt** [comment]
<img width="1709" alt="Screenshot 2024-06-29 at 1 18 36 PM" src="https://github.com/ChurchApps/FreeShow/assets/5282658/b777abd5-868e-48d9-b767-bc0fdec35516">

**Comment by vassbo** [comment]
I can't recreate this issue.

**Comment by ralphievolt** [comment]
Look at the arrange item on the right panel
<img width="1709" alt="Screenshot 2024-07-01 at 11 52 44 AM" src="https://github.com/ChurchApps/FreeShow/assets/5282658/112bf91a-27f7-46c7-90a2-ee0f2988c198">
<img width="1710" alt="Screenshot 2024-07-01 at 11 52 53 AM" src="https://github.com/ChurchApps/FreeShow/assets/5282658/c5fa70a2-8e8b-479c-9210-f10086bc53a6">

I changed the arrangement and it look like this. btw, I copied these two items from a previous slide. Hope this helps
