### ISSUE TITLE
Let us add text into templates

### ISSUE THREAD

**Issue by JovanPlayzz** [ChurchApps/FreeShow#632]
we should be able to add text into templates so like i can add like the song title and stuff. or add like a switch that makes the text become lyrics or be just text thats shows into every slide that has that template on.

![image](https://github.com/ChurchApps/FreeShow/assets/149248224/f197f3f2-6113-4e28-b1a5-a706d932697b)
![image](https://github.com/ChurchApps/FreeShow/assets/149248224/9d1d088a-fc09-4ff8-be98-a3da5be72e64)

**Comment by vassbo** [comment]
You can do that. :) Right click, choose "Dynamic values", choose e.g. "show_name".
