### ISSUE TITLE
RemoteShow Not Working (1.1.9)

### ISSUE THREAD

**Issue by Mhouse01** [ChurchApps/FreeShow#633]
While attempting to control a Project in RemoteShow in update (1.1.9) it states that there is, “no show selected” and only one of the shows is working and will not show me different slides when I change out of that show.

https://github.com/ChurchApps/FreeShow/assets/174251312/479c91d8-e75d-422b-b63f-e358987e4602

**Comment by vassbo** [comment]
Okay, thanks.

**Comment by vassbo** [comment]
Do you still have this issue in the latest prerelease?: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.0

If you do, could you open the remote on the computer, and right click and inspect, go to console, try the same thing as the video, and let me know if you get any errors in the console.
