### ISSUE TITLE
Output and Styles and Stages

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#634]
1.1.9 (Linux)

Outputs are no longer following the resolution set in a style and seem to default to 1920x1080. Everything else does seem to follow the style set for the output. 

Stages seem to no longer be getting current and next text, but only when set as an output. When looking at the edit screen or in a browser it works as it should. And for some reason stage show output was turned off but it was still showing up as a display, when I then turn on the output option it then creates another stage output and shows it as well.

I'll double check this at home on my windows 11 machine and see if it does the same. I don't recall seeing this there.

EDIT: Found out that the source field on the Stage settings was not set, not sure when that got changed, but setting it to the main display out got it back.

Though the Main output is still not following the resolution I want in the style I have set. Still tinkering to see if I messed something up

![image](https://github.com/ChurchApps/FreeShow/assets/73187905/8c4912b6-2833-4547-9b2b-40103fe5f239)

**Comment by SPN09** [comment]
1.1.9 (Windows)

Hi, I have the same issue of retaining 1920x1080 on the outputs, instead of the resolutions I have set in settings.

For me it only appeared when setting more than 1 output, after which the issue persisted.
Going back to 1 output or even resetting the app and import previous settings did not work! (Backup made before the issue rose up)

Reinstalling version 1.1.7 circumvented this issue!

**Comment by TPaulManohar** [comment]
Hi @vassbo ,

I tried v1.1.9 to created Output with 1080x1920 for Instagram Vertical resolution but it take 1920x1080 resolution, Here we used styles but it not following what we set in style. It follows the 1920x1080.

And we tried on v1.1.6 it working as expected even in v1.1.7 also not working.

**Comment by TPaulManohar** [comment]
@vassbo  Here, please let me know, how the resolution works in styles, we are expecting the output screen should be 1080x1920. If I set 1080x1920 resolution on styles and enabled NDI on Output with selected style name which we created, But it not modified.

We checked in v1.2.0 and v1.1.9.


Here what I did is i created a template with added text and change the size to 1080x1920 then I readjust it to fit the 1080x1920, after I selected this template to styles and at output I selected the style then I achieved.

This how the procedure we need to follow here.

Let us know

Thanks,
Paul

**Comment by vassbo** [comment]
Hi, I'm pretty sure you have to change the output dimensions to properly change the NDI resolution. (The style is for setting the aspect ratio in the editor, and previews)
Go to "Outputs", then click "Choose screen", click the button to manually change the position, and enter the 1080x1920 size here.
