### ISSUE TITLE
Custom "Run Action" continues to execute after been removed from slide

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#636]
Removing a custom "Run action" from a slide removes the Run Action flag from the slide, but the underlying action is not removed and continues to execute.

**Comment by vassbo** [comment]
What do you mean it continues? Does it still start the action when the slide is clicked, or when something else is triggered?

**Comment by colanct** [comment]
The custom action continues to be executed whenever the slide is clicked/played, despite the whole "Run action" having been removed from the slide.  

In my test case: the action is set to Clear audio; Activation is set to Activate when timer is ending. The function behaves as expected when a slide - on which the Action was placed - is played.  However, the custom action still occurs after the action is removed from the slide, as if it was never removed.

**Comment by vassbo** [comment]
This works as expected. Setting custom activation on an action it will make it activate regardless of having it on a slide or not, you can set a slide action to enable/disable the action!

**Comment by colanct** [comment]
Okay, thank you. I'll retest accordingly.
