### ISSUE TITLE
Trigger condition for "Run action" with multiple actions is effective for only the first action

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#637]
Custom "Run actions" defined to start multiple actions on a custom activation/trigger execute the first defined action when the trigger occurs, but the second action executes immediately when the slide is played.

**Comment by vassbo** [comment]
Could you explain further? I added one "Run action" (with multiple triggers) to a slide, that worked. And I set "Custom activation" on that, and all the actions in the single action were triggered.

**Comment by colanct** [comment]
My reported issue was probably mainly due to my misunderstanding of enabling, triggering, run action, and toggling of custom actions, which you partly clarified in #636.

Now that I have a better understanding, I've retested using the below custom action, with a Toggle action for it placed on a slide.  It functions mostly as expected.  While testing, I found:

1.	Toggling actions changes the Enabled status in the defined action in the drawer.  So if the action was defined with Enabled deselected, it becomes defined with Enabled set to selected.  If the app is closed before the action is toggled for a second time (to revert to its original state), the action is saved with the Enabled state toggled.  So, the next time the show is played the sequence is inverted.  As I see it, toggling an action should not alter the saved defined action.

2.	Although action 4 (in my example) is effective in toggling the action, so that the action is disabled for subsequent slides, it does not alter the Enabled status of the action. This is confirmed when the action config is viewed in the drawer. When the action is toggled again, it is out of sequence. 
However, when, instead of action 4, a stand-alone toggle action is applied to the following slide, the Enabled status is changed, as evidenced in the app drawer.

4.	After action 4 in my custom action executed, none of the timers can be restarted.  In the drawer, they appear to be reset, show as playing, but do not decrement.  The app has to be closed and reopened to recover.  This does not happen when a stand-alone toggle action is applied to the following slide.

5.	Custom actions dragged and dropped from the drawer do not function or display correctly. 

6.	Adding the action Stop active timers to my custom action, appears to do nothing.

![image](https://github.com/user-attachments/assets/2b37e8ea-240d-4836-9f9c-80b15a2a718a)

**Comment by vassbo** [comment]
1. Users can manually enable/disable actions so it makes sense that this will be changed. But you can set the toggle state to on/off (using the checkbox) to ensure it's set to what you need it to be (in your screenshot it will always be set to "on").
2. You need to choose an action to be toggled using the dropdown (this can't be the same action that triggers it!
3. This is because you have not set an action to toggle, but I will fix this "freeze" error!
4. I'll fix this behaviour.
5. Same reason as point 3.

**Comment by colanct** [comment]
Thank you. 

I'm still finding the UI confusing when adding a Toggle action to a custom action. In particular, the behaviour of the toggle switch and the removal of the selected action when the switch is enabled.  

Please clarify the intended behaviour when:
1. Adding a Toggle action without selecting an action to toggle. I've assumed the toggle applies to the action being edited, as it can be saved without defining the action.
2. The switch is enabled and the selected action to toggle is removed.

**Comment by vassbo** [comment]
You should always select an action to toggle when choosing "Toggle action", but it's set to "-" by default so no action is accidentally toggled. If you don't select any action, or the selected action does no longer exist then it will do nothing! (I will fix it so it does not freeze in this case)

**Comment by vassbo** [comment]
I see, this is a bug. Will fix this as well.

**Comment by colanct** [comment]
Ah, good; thank you.

Then, is my understanding of the intended function of the switch now correct?

- **When Off/deselected:**  selected function will be toggled (Enabled status will be inverted).
- **When On/selected:** selected function will be enabled, irrespective of its present state.

If so, consider amending the text "_Action will toggle if checkbox is unchanged_" to be dependant on the state of the switch, and keep it visible.  For example:
When switch is off/unselected/default display "Action will be toggled"
When switch is on/selected: "Action will be enabled"

**Comment by vassbo** [comment]
If the checkbox is **unchanged** it will toggle the value (as the text explains), but if it's set to on OR off again (deselected), the action will be set to on OR off accordingly!

**Comment by colanct** [comment]
Ah, now I understand; thank you.

The confusion is partly because once the switch has been cycled from the default, it is not possible to tell if the action will be toggled or if it will be set to Off, and there is no way to restore the default without starting again (which is probably why the selected action is being removed).

Anyhow, thank you for your help.
