### ISSUE TITLE
Guidance on use of custom "Run action" feature

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#638]
The new custom "Run action" function will be particularly useful, thank you.  Please provide guidance on the following:

1. Is there a way to play a selected slide?  At present, it seems a slide can be selected (by name or index), but that action does not play it.
2. Selecting a slide by name (as shown in the json) does nothing,  Does the name need to be formatted/encoded in some way?  Using the slide index seems fine.  
3. Where do users get slide names?  Names of slides in the project may not always be unique.
4. What is the purpose of Start action > Toggle action?

**Comment by vassbo** [comment]
1. An action can play a slide by name or index on the currently selected show, that should work. You might have to set an action to change the show also. But you can also right click a slide if you want a specific show and slide, and use the activate by MIDI signal. This uses MIDI, but you can use an action to send that MIDI signal and route it back using e.g. MIDI loop.
2. It selects the first slide in the currently selected show with a matching name. If you have the group name e.g. "Verse 1", you can type "ver" and it will play that slide.
3. It's the name that's on the slide. This can be renamed to something unique.
4. This is only useful if the action has a "Custom activation", so you can turn on/off the action if you just want to do something specific for that show when e.g. the timer has ended.

**Comment by colanct** [comment]
Thank you; that helps.  I'll experiment with a MIDI loop.
I've logged issue #641 re not finding the specified slide name.
