### ISSUE TITLE
Bible stuck in Genesis in v1.1.9

### ISSUE THREAD

**Issue by r3troseer** [ChurchApps/FreeShow#639]
Scripture gets stuck in Genesis; opening Luke 2:3 displays Genesis 2:3 on the screen. This issue persists even after restarting the app and trying both the OpenSong and Zefania formats. However, reverting to version 1.1.7 fixes the issue

**Comment by vassbo** [comment]
Yep: https://github.com/ChurchApps/FreeShow/issues/630
