### ISSUE TITLE
Bug or feature? Powerpoint slides without styling

### ISSUE THREAD

**Issue by soph-os** [ChurchApps/FreeShow#64]
When importing a powerpoint presentation it uses the text from the slides but puts it in a template. My expected behaviour is: the original powerpoint presentation with all styling/layout is imported as-it-is.

Did I miss some options during the importing?

Platform: Win11 Home - 10.0.22621 Build 22621

**Comment by vassbo** [comment]
This is actually a feature, because many have song lyrics in PowerPoint. But you can export the PowerPoint to PDF, and import the PDF to get all the styles.

**Comment by soph-os** [comment]
Ok, good to know :)
It would be a nice addition when you could decide during import whether to keep the style or just import the text. Useful for sermons&&

**Comment by vassbo** [comment]
Yes, it would be nice. And maybe sometime. 😄 But that will require me to include the OpenOffice converter inside of the program. It's a lot of work to convert all the styles correctly.

It's almost as easy to just use the default PowerPoint exporter, or use an online PPTX to PDF converter.

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/491
