### ISSUE TITLE
When useing the Stage Display words get stuck and do not clear

### ISSUE THREAD

**Issue by mbyrdLCS** [ChurchApps/FreeShow#642]
https://github.com/ChurchApps/FreeShow/assets/65249159/8e7760c7-85c0-4246-9832-a41385b8feca

**Comment by abhishikthraj** [comment]
@mbyrdLCS sorry, this might not be relevant but I liked your backgrounds. Can you let me know where can I find them

**Comment by mbyrdLCS** [comment]
I am not for sure this is a screen recording from a church that I am helping.

**Comment by abhishikthraj** [comment]
Oh ok no problem
