### ISSUE TITLE
OpenLP song import does not work when xml file has no newlines

### ISSUE THREAD

**Issue by FelixHeppner** [ChurchApps/FreeShow#643]
Because of the way the version tag in xml files is removed before conversion to json the importer does not work (anymore) with files without newlines. At least quelea church projections software  generates OpenLP xml files without newlines when exporting the songs from database.  There is  commented section to handle this is the code with an off by one index error. I fixed this locally and it works just fine.

**Comment by vassbo** [comment]
Thank you!
https://github.com/ChurchApps/FreeShow/pull/644
