### ISSUE TITLE
I'd like to change the name of the Bible

### ISSUE THREAD

**Issue by HippoC-KR** [ChurchApps/FreeShow#645]
I added the 'XML' Bible file I received from the internet to the program as 'beblia.com ', 
and I tried to change the arrowed part of the screenshot to Korean, 
but I couldn't figure out which source to modify in '%AppData%/freeshow'.
I'd like to know how to modify that part.
![books name](https://github.com/ChurchApps/FreeShow/assets/174556922/6e5a455e-8296-404f-a854-ea30ee909ae5)

**Comment by vassbo** [comment]
Open your documents folder, go to FreeShow>Bibles, then open the version saved here.
And search for the book names and change them. Then open the program, and you should see the changes.

**Comment by malidejan** [comment]
> Open your documents folder, go to FreeShow>Bibles, then open the version saved here. And search for the book names and change them. Then open the program, and you should see the changes.

Is it possible that instead of Genesis 1:1 it would be Genesis 1,1. So instead of ":" to use ",".

**Comment by HippoC-KR** [comment]
Thank you so much, the problem has been solved!
