### ISSUE TITLE
Scriptures: chapter, verses separator

### ISSUE THREAD

**Issue by malidejan** [ChurchApps/FreeShow#646]
In Scriptures is it possible that chapter and verses are separated with comma instead of colon?
For example instead of Genesis 1:1 that it would be Genesis 1,1.

I know it can be edited but interested if it can be changed in settings or somewhere.

Picture 1 (with colon):
![image](https://github.com/ChurchApps/FreeShow/assets/171418673/c5810e89-0736-42b7-a8af-86eecad767c5)

Picture 2 (with comma):
![image](https://github.com/ChurchApps/FreeShow/assets/171418673/4a029015-9fc7-47a8-8669-e9bcde0d6322)

**Comment by vassbo** [comment]
I don't think this is common enough for it's own option in the program, but if you really want to, you will be able to change this in the next version, by finding the app data location, opening the **settings_synced.json** file, searching for the `scriptureSettings` key, and adding `referenceDivider: ":"`

**Comment by malidejan** [comment]
Thanks. It works in v1.2.0.
