### ISSUE TITLE
Import song: clipbord or text file

### ISSUE THREAD

**Issue by malidejan** [ChurchApps/FreeShow#647]
If last punctuation mark in line/row is comma, it does not import that punctuation mark to the song. See example 1.
But if the last punctuation mark is anything else than comma, then that punctuation mark it is imported to song. See example 2.

There is no problem if comma is anywhere between the line, it just the problem when it is at the end of line/row.

Example text 1:
[Chorus]
Moje srce kliče iz vse moči,
"Bog, velik si! Bog, velik si!"

Result of import 1:
![image](https://github.com/ChurchApps/FreeShow/assets/171418673/b33ce084-25ff-4d20-9fb5-28cd05e9680e)

Example text 2:
[Chorus]
Moje srce kliče iz vse moči:
"Bog, velik si! Bog, velik si!"

Result of import 2
![image](https://github.com/ChurchApps/FreeShow/assets/171418673/eea54a84-f535-4576-b626-585156cb2407)

**Comment by vassbo** [comment]
Auto formatting is enabled by default. So you have to turn off "Format text" in the "New show" popup.

**Comment by malidejan** [comment]
I did turn "format text" off (picture below)

![image](https://github.com/ChurchApps/FreeShow/assets/171418673/aedb22e9-0ba8-4f08-9c12-b8918c1a64e1)

Jet when I import via clipboard or txt file/songs (around 800 of them) there is still no comma in the first row/line.

For this clipboard text example:

[Chorus]
Moje srce kliče iz vse moči,
"Bog, velik si! Bog, velik si!"

Result of import:
![image](https://github.com/ChurchApps/FreeShow/assets/171418673/d7d94035-890b-4f7f-872f-2bff00387f75)

It should be like this:
![image](https://github.com/ChurchApps/FreeShow/assets/171418673/36bec0ed-2cdf-407a-9db3-1adca3f677c5)

Interestingly is that the issue as said is only if the last character is a comma, but for example, if I put one space after a comma it does import the comma.
What am I doing wrong?

**Comment by malidejan** [comment]
> Auto formatting is enabled by default. So you have to turn off "Format text" in the "New show" popup.


I did turn "format text" off (picture below)

![image](https://github.com/ChurchApps/FreeShow/assets/171418673/aedb22e9-0ba8-4f08-9c12-b8918c1a64e1)

Jet when I import via clipboard or txt file/songs (around 800 of them) there is still no comma in the first row/line.

For this clipboard text example:

[Chorus]
Moje srce kliče iz vse moči,
"Bog, velik si! Bog, velik si!"

Result of import:
![image](https://github.com/ChurchApps/FreeShow/assets/171418673/d7d94035-890b-4f7f-872f-2bff00387f75)

It should be like this:
![image](https://github.com/ChurchApps/FreeShow/assets/171418673/36bec0ed-2cdf-407a-9db3-1adca3f677c5)

Interestingly is that the issue as said is only if the last character is a comma, but for example, if I put one space after a comma it does import the comma.
What am I doing wrong?

**Comment by vassbo** [comment]
I'll check it out.

**Comment by vassbo** [comment]
This should be fixed in this prerelease: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.0
