### ISSUE TITLE
Showing Song Verse Number and Refrain (Chorus)

### ISSUE THREAD

**Issue by BogenhofenMedia** [ChurchApps/FreeShow#649]
Hi, I have a suggestion, would be nice to show automatically the Number of the Verse and the Refrain (like in the picture)
I did it now manually to show how it look like.

![number-verse](https://github.com/ChurchApps/FreeShow/assets/98317242/e548ea11-c016-4447-92be-4274c9fdc111)

![refrain-verse](https://github.com/ChurchApps/FreeShow/assets/98317242/95f4ba00-197f-4a3e-917d-4841304d0373)

![number-verse Kopie](https://github.com/ChurchApps/FreeShow/assets/98317242/f12c2e0a-cf98-4aab-953a-3e9c82628cb2)

Thank you so much for your great work. God bless you.

**Comment by vassbo** [comment]
It already assigns a number automatically based on the amount of e.g. verses in the song, and you can change the default names in the "Groups" settings. As you see in your image, there are 4 slides called "Verse" and the program assigns a number to each individual slide e.g. the 3rd verse is called "Verse 3".

Is this what you meant?

**Comment by BogenhofenMedia** [comment]
What I would like, it's to show the number from the Verse or the Refrain on the output presentation. (like in the picture, the number on the right is not showing, so I manually edited the slide to add a textbox with the number) But it would be nice to have it automatically. Maybe an option in the setting where we could activate to show or not to show the number and the refrain on the output presentation. (also to be able to change the style like for the metadata in the styles setting)

![number-verse-a](https://github.com/ChurchApps/FreeShow/assets/98317242/23c54748-8147-4d84-8ef2-ef65bb31ffd9)

**Comment by vassbo** [comment]
You can right click a textbox, choose "Dynamic values", and click "slide_group". This will show the current group name.

**Comment by BogenhofenMedia** [comment]
Thank you so much, I did not know we could do that. 

I have another question about the textbox with the Dynamic values.

I have here on this slide 4 lines. My settings are set up to show 2 lines.

![Screenshot 2024-07-15 185439](https://github.com/user-attachments/assets/737cb8aa-2a44-4a84-97f3-c0a0a558c8d1)
![Screenshot 2024-07-15 190108](https://github.com/user-attachments/assets/d8c86f44-fadc-4202-afe8-6e1025b6ba13)

In the first 2 lines, we can see the "slide_group" in this case "Refrain". But for the other last 2 lines (from the same slide), "Refrain" is not shown. It is possible to always show the textbox?

![Screenshot 2024-07-15 185652](https://github.com/user-attachments/assets/6cbff76f-c43f-4af6-b1d1-000d06b3585b)
![Screenshot 2024-07-15 185716](https://github.com/user-attachments/assets/7ff20a5a-9b17-4197-82df-093cc585d538)

**Comment by vassbo** [comment]
Great! I can fix this.
