### ISSUE TITLE
When drag/dropping media, show appropriate icon

### ISSUE THREAD

**Issue by jzongker** [ChurchApps/FreeShow#651]
Users can drag and drop into the project pane, show slides or edit tab, but not other areas like the drawers and details pane.  We should have the drop icon indicate which areas are and are not droppable.

**Comment by vassbo** [comment]
Dragging & dropping inside the program does change the cursor, and it show a message on areas that accepts dropping. I don't think we can change the cursor when dragging files from the computer!

**Comment by vassbo** [comment]
Dropping is now visually only allowed in drawer navigation areas that supports it.
