### ISSUE TITLE
FreeShow freezes when I select the scriptures option.

### ISSUE THREAD

**Issue by odlarhg** [ChurchApps/FreeShow#652]
When I select the scriptures option it doesn't show any scripture and the app freezes. How can I solve that?

I am using the latest version available on your download site.

**Comment by jerm00** [comment]
use the workaround @vassbo mentioned in #630 or downgrade to version 1.1.7. if you downgrade, make sure you undo the "fix" modifications made to the .json file, otherwise 1.1.7 won't load (at least it didn't for me this morning on the linux version)

**Comment by odlarhg** [comment]
Thank you so much,

I did what you recommended and now the writing option works.

Thank you so much.
