### ISSUE TITLE
Significant Performance Lag

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#653]
Hello All, thanks for the continued development of the app; I'm super excited to see where it will go, and I'm working on transitioning my church to FreeShow. However, every time I run the app, the performance on it is so slow that I don't think it will be reliable enough to use for slideshows at church. When I look at demos of others on the issues, it's not as slow, and so I'm wondering how to make it faster.

Here's How to Replicate; get three outputs running, each with auto size on. Then, load in a multi-slide song, and cycle through them using the arrow keys. For me, it takes at least two seconds for all of them to start to change. Then, try clearing all the outputs. This usually takes 30s to a minute.

Details: I'm on a M1 MacBook Air running MacOS Sonoma, and I'm using FreeShow 1.1.9

**Comment by jzongker** [comment]
@Dcanadian I'm looking into this.  There is some slowdown with multiple displays, especially when playing videos on each, but I haven't seen it to that extent before.  Do you know what resolution these three displays are at?

**Comment by TPaulManohar** [comment]
Even we also facing same Performance Lag and some times it stucks when shows runs. If we add Pictures as background to Slides it stuck and output display will take 30s or more. If there is not background then output display shows less than 30s. However app need to optimise and should be reliable.
