### ISSUE TITLE
Scriptures Quick Search

### ISSUE THREAD

**Issue by JoJo26josh** [ChurchApps/FreeShow#655]
Hello Free show 

Creating a "Scriptures Quick Search" feature for easy reference to verses would greatly benefit anyone looking to quickly access specific passages. This feature could be designed to allow users to search by keywords, phrases, or specific references (like book name, chapter, and verse number). Additionally, it could include thematic searches to help users find verses faster.

Incorporating user-friendly features like auto-suggestions and filters (e.g., by version of the scripture, such as KJV, NIV, etc.) would enhance the usability. Moreover, providing options for bookmarking and saving searches could make the tool even more convenient for regular users.

Thank you,

**Comment by vassbo** [comment]
This already exists, try pressing the search icon, or CTRL + F to quickly search for a verse. Or you can search for content at the bottom in the "Scripture" tab. Is this what you were thinking?

**Comment by JoJo26josh** [comment]
Hello Vassbo,
Yes that what i were looking for.
I never knew this feature already exists! This made me easier.
Thanks for saying...
