### ISSUE TITLE
Issues with syncing over the cloud

### ISSUE THREAD

**Issue by janyboy951** [ChurchApps/FreeShow#657]
Hello, 

I'm running into an issue where the cloud sync is not working with my latest changes. 

1. On my very first laptop, i setup the cloud keys and synced everything to google cloud. 
2. I then used the exact same keys to sync the cloud data on another computer. 

the problem i'm having is that any time I delete a shows, I'm unable to save those chages to the cloud. It looks like whatever is in the cloud is always getting registered as the latest changes. Would you let me know how i can resolve this?

## Example 
The current list of items in shows are as follows
<img width="678" alt="image" src="https://github.com/ChurchApps/FreeShow/assets/154772034/b28158f6-ebed-4de8-ae5b-754acc4894db">

I deleted two of the shows 
<img width="678" alt="image" src="https://github.com/ChurchApps/FreeShow/assets/154772034/028e8d3b-5012-4ce2-b39b-1015ab708e75">

When i click save, it downloads the latest copy from google drive
<img width="1508" alt="image" src="https://github.com/ChurchApps/FreeShow/assets/154772034/ef4c19dc-5325-431f-b04f-960719cbb53c">

Please find a screenshot of the latest version of my cloud settings 
<img width="1508" alt="Screenshot 2024-07-08 at 4 20 48 PM" src="https://github.com/ChurchApps/FreeShow/assets/154772034/5b7e5d97-9aa5-49ee-a0f9-6d8b87765b4d">

Would you let me know if i'm doing something incorrectly?

Best regards,

**Comment by vassbo** [comment]
This issue should have been resolved in version 1.1.9, are you using this version?

**Comment by vassbo** [comment]
Please try this again in the latest prerelease: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.0
You might have to reset the sync, and add the key file again.
