### ISSUE TITLE
Text Box too big for 4:3 display

### ISSUE THREAD

**Issue by GiantManBat** [ChurchApps/FreeShow#659]
I have my slides set to 4:3 to be compatible with our projector screen. When Freeshow generates text boxes, they are still set for 16:9 resolution and so hang over the canvas of the slide and get cut off. I have to go in to every slide and manually resize the text boxes each time to fix it.

**Comment by vassbo** [comment]
You can use templates to change the textbox style, either applying to each show, or set a custom style template in the settings for this specific screen that will override the output textboxes. Does this help?
