### ISSUE TITLE
The software crashes when removing a timer layer.

### ISSUE THREAD

**Issue by thirdybobiles** [ChurchApps/FreeShow#661]
The software freezes after deleting a timer item layer in the stage view.

**Comment by thirdybobiles** [comment]
Addition. When the timer was ongoing and I tried to remove the layer of it on stage view, it freezes and stopped functioning.

**Comment by vassbo** [comment]
I can't reproduce this issue. Can you provide more details, or send the error log file found by clicking "Open log file" in the "Other" settings?

**Comment by vassbo** [comment]
Does this issue still exist in version 1.2.1?
