### ISSUE TITLE
The cloud saving is very bad

### ISSUE THREAD

**Issue by Beniamin137** [ChurchApps/FreeShow#662]
I saved everything in cloud on the main pc and on my personal pc doesnt change anything that i do on the main pc. I do have all the song from the main pc but they are not in their folders

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/657

**Comment by vassbo** [comment]
Try resetting & setting up the sync again on the second computer when the next verison comes out.
