### ISSUE TITLE
A Few Bugs

### ISSUE THREAD

**Issue by kwagloben** [ChurchApps/FreeShow#663]
Please anytime multiple verses of scriptures are selected to create a new show the app crashes, and also I have been trying to figure out a way to crop media files but it seems the feature is not available

**Comment by jzongker** [comment]
Thanks for the report.  

The first is a known bug that will be fixed on the next release.  #630

On the second, once you add media to a slide, you can change the fit to "Cover" in the right pane under the Media tab.  Then adjust the size of the box to crop it as desired.
