### ISSUE TITLE
Scriptures not loading / crashing the Freeshow App

### ISSUE THREAD

**Issue by Acoustician1981** [ChurchApps/FreeShow#667]
I have a newly installed version of freeshow and the songs are great - I loaded them in from openlp with no issue at all. 
The version I have is 1.1.9.
I cannot, however, get the scriptures section to work - I cannot import anything and the drawer is empty. Also, the buttons then become unresponsive once I click on the scriptures drawer. I've tried a few times but to no avail.

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/630
