### ISSUE TITLE
Subcategories in the shows

### ISSUE THREAD

**Issue by odlarhg** [ChurchApps/FreeShow#668]
Hello

Thank you for your effort and time invested in FreeShow. FreeShow has been a great help and blessing to our ministry.

I want to suggest a functionality for FreeShow. It would be very useful if subcategories could be created. For example, being able to create a subcategory by author in the song category and within that subcategory being able to include some more subcategory. That would make it easier to find a song to use in a project.

The subcategories would help a lot to organize the presentations. They could be organized by Pastor, by topic, by event, etc.

I would greatly appreciate if you could consider adding subcategories.

Blessings.

**Comment by vassbo** [comment]
I don't think "subcategories" are necessary, but possibly a tag/filter system that could use the metadata to e.g. filter songs by artist/custom tag etc.
