### ISSUE TITLE
Modifying a duplicated show also changes the original regardless of where it is located

### ISSUE THREAD

**Issue by turtureanu** [ChurchApps/FreeShow#673]
When trying to **duplicate** a show, the show does appear to duplicate itself, but when editing either the original or the duplicated one they share the changes. When trying to rename the duplicate, the original gets renamed as well, internally it appears FreeShow doesn't actually duplicate the .show file.

When creating a new show with the same name (**independent of project**, i.e. the original could be in another project) the file that shows up is renamed to `<show name> $n`, where `$n` is a number that starts at 2 and gets increment if we create a new show with the same name again. Internally this is a different file, which is the correct. The problem is that this happens regardless of it being in another project altogether.

Maybe it would be a better idea to create project subfolders in FreeShow/Shows instead of putting everything in one place:
```
FreeShow/
└── Shows/
    ├── ProjectName1/
    │   └── ShowName1
    └── ProjectName2/
        ├── ShowName1
        └── ShowName2
```

In this case there could be duplicates (`ShowName1`) that don't sync changes between themselves. Syncing could then be implemented manually (by e.g. hard linking them).

I'm not sure this is the desired behavior and I would like at least there to be an option to choose between syncing changes between duplicates or not.

Screencast showcasing the issue:
[FreeShow-Duplication-issue.webm](https://github.com/user-attachments/assets/d8867a54-4976-462b-8456-babef2eb705f)

- OS: Ubuntu 24.04 LTS x86_64
- FreeShow version: using preview-window branch on commit 2980f41 

- [x] I am willing to open up a pull request to solve this

**Comment by vassbo** [comment]
You are duplicating the project reference to the show, this is just a "link" to the actual show that you can find in the drawer. Please open the "Shows" drawer tab, and duplicate it from there!
