### ISSUE TITLE
Border radius is not implemented

### ISSUE THREAD

**Issue by turtureanu** [ChurchApps/FreeShow#675]
There is a border radius option in the settings
![image](https://github.com/user-attachments/assets/c12ded59-da01-4552-852f-a088baa5abba)

When trying to change it nothing happens.

In the console I get the following error:
![image](https://github.com/user-attachments/assets/81cc5f37-8e28-4145-b767-cb06a85fbcbf)

I don't think this is implemented yet, and should at least be temporarily removed (or commented out) from the settings: https://github.com/ChurchApps/FreeShow/blob/3309835d9157cbea63e75d4e1c397b5c3a8b9c44/src/frontend/components/settings/tabs/Theme.svelte#L112-L115

I assume this is because there is no such property in /src/frontend/components/settings/tabs/defaultThemes.ts and it doesn't seem to change the variable in public/global.css: https://github.com/ChurchApps/FreeShow/blob/3309835d9157cbea63e75d4e1c397b5c3a8b9c44/public/global.css#L43

- OS: Ubuntu 24.04 LTS x86_64
- FreeShow version: using dev branch on commit 3309835

**Comment by vassbo** [comment]
I see, this is because you have a custom theme. I will fix this. You can select the "Default" theme, and then you should be able to change it!

**Comment by turtureanu** [comment]
You are right, thank you!
