### ISSUE TITLE
[Feature Request] Make it possible to set a slide as a default background

### ISSUE THREAD

**Issue by funnysloth** [ChurchApps/FreeShow#677]
It would be very nice to be able to set a slide as default background that is shown when pressing "Esc" button. Right now it can be set in Settings only by importing some media.
Would appreciate it.

**Comment by vassbo** [comment]
You can probably set up a custom action that will activate a specific show whenever a slide/background is cleared.
Go to "Functions"->"Actions", create a new one, set the "Custom activation" to e.g. "Activate when slide is cleared" and set the action to "Start show" and create your custom slide here. Does that work for you?

I think adding this to the settings will be more confusing than good. You could also just create a custom image based on the slide if you wanted to.

**Comment by funnysloth** [comment]
Yeah, that'll work, thanks a lot
