### ISSUE TITLE
v1.2.0 freezes when creating a new scripture show with 1 verse per slide

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#678]
v1.2.0 freezes when creating a new scripture show using _Scripture_ template and _Max verses per slide_ = 1.

**Comment by vassbo** [comment]
I can't reproduce this issue. Are you able to send the error log file in the "Other" settings, "Open log file"?

**Comment by colanct** [comment]
Attached as requested [error_log.json](https://github.com/user-attachments/files/16328904/error_log.json)

**Comment by colanct** [comment]
Seems it's the _Verses on individual lines_ toggle that triggers the issue.

**Comment by colanct** [comment]
This is unresolved in v1.2.1.
Freeze occurs when creating a scripture with:
- Max verses per slide >1
- Verses on individual lines = On

**Comment by vassbo** [comment]
Got it, thanks. Managed to find it.
