### ISSUE TITLE
wrap slides text

### ISSUE THREAD

**Issue by DLumen07** [ChurchApps/FreeShow#681]
Is there a way to extend a slide content to another slide? for instance I'm displaying a Bible verse or a song that has a lot of words in it with a big font size considering old readers, instead of fitting it all in a single slide why not wrapping it up to another slide?

**Comment by vassbo** [comment]
Right click the slide, choose "Format", click "Split in two".

It's also possible in the editor to put the caret anywhere on the text, and hold ALT+ENTER to split in two.
