### ISSUE TITLE
Allow "video countdown" to be shown over videos on displays

### ISSUE THREAD

**Issue by frederickjh** [ChurchApps/FreeShow#682]
Hello,
I see that there is a "Video countdown" available for use on the stage display.
Would it be possible to make this available for other displays as well?

The use case is that someone at our church makes a video countdown of the announcement slides, but we like to add the video countdown over the video (so the pastor knows how much time is left before we start). The church's live stream is started with the countdown video. Currently we do this in VLC and use the "Time" plugin to show the video countdown.

Thanks for considering this!
Frederick

**Comment by vassbo** [comment]
In the next version you will be able to show video time/countdown in the output using "Dynamic values".

**Comment by vassbo** [comment]
Yeah, I guess that would nice.

Right click any textbox, select "Dynamic values" and choose e.g. "video_countdown"!
