### ISSUE TITLE
v1.2.0 - Dragging show slide between shows does not copy layers

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#683]
In v1.2.0, when dragging a show slide to another show, the slide is added to the show, but the overlays are not copied.

**Comment by vassbo** [comment]
You can

**Comment by colanct** [comment]
This is unresolved in v1.2.1.  

When dropping, slide text is retained, but
 - background is lost
 - test box formatting is changed.

**Comment by vassbo** [comment]
Everything except background/audio were working fine, this is now fixed for the next release.
The textbox formatting is changed because you have set a custom template on the show.
