### ISSUE TITLE
Random slides not showing on stage view (versions 1.1.9 and 1.2.0)

### ISSUE THREAD

**Issue by thirdybobiles** [ChurchApps/FreeShow#685]
I’m not sure if someone has already noticed this issue. I’ve seen it before in version 1.1.9 and now in version 1.2.0. It randomly shows the next slide as invisible. The only solution is to remove the text and paste it again for it to show up.

Here's a demo
https://github.com/user-attachments/assets/6ee6b469-20e9-4ff9-9a2f-129d4150f89d

Here's the error log if it could help
[error_log.json](https://github.com/user-attachments/files/16366028/error_log.json)

**Comment by vassbo** [comment]
Please try out this preview build: https://filetransfer.io/data-package/wlrwuLdR
Does it work here?

**Comment by thirdybobiles** [comment]
It works on this one!
