### ISSUE TITLE
Background Video Flashing

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#686]
Testing Version 1.2.0. 

Not sure if I changed something in settings, but Motion backgrounds are periodically flashing in and out. Desktop will show for a split second, if you have another output layered behind the main output, that shows through as well. 

It mainly shows when changing slides, if slide is left long enough it might be flashing on the loop to restart the background.

So, far does not seem to affect picture backgrounds or slides without a background, just ones that have video background.

Edit:
Once it starts into the flashing, sometimes removing the video does not remove it and a refresh of the screens does not remove it. Also, after clearing the screen and turning off the projection. The main window will the momentarily flash as well. Though this is not ongoing, just 1 flash and done.

Edit 2:
Seems it is happening after making changes to the display settings within FreeShow, 2 that I changed was outputs style selection and which screen the outputs when to. Then after a few restarts' things start working as they should...

**Comment by vassbo** [comment]
Can you please try this test version, to see if it's fixed here: https://filetransfer.io/data-package/pTl4FxXu
If not, are you able to send a screen recording of the issue?

**Comment by Bagel94** [comment]
Yeah, I'll try doing that when I can get back to my computer.

**Comment by Bagel94** [comment]
@vassbo So, I tried everything I did before to get it to replicate the issue again and so far, I have not been able to get it to happen again. If it does start doing this again, I'll make sure to grab a video of it.
