### ISSUE TITLE
No resources

### ISSUE THREAD

**Issue by wabrice** [ChurchApps/FreeShow#687]
I copied the AppImage to my Arch Linux computer. There are no Bibles. All of the fields seem to hang like they are waiting for input somewhere. Are there resource files that I need to download and install? Any config files that need tweaking?
I would really like for this to work well.
One church I attend uses Easyworship. The annual costs are a lot for a small 25 person congregation.
Another church uses PowerPoint simply because the minuscule budget does not allow for anything else.
Thanks for any help.
The two churches are both using Windows,

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/630#issuecomment-2239042706
