### ISSUE TITLE
Clear Background Start action disappearing

### ISSUE THREAD

**Issue by sidcurtis7684** [ChurchApps/FreeShow#690]
See attached GIF.  When you right-click a slide and add the Slide Action > Clear Background option, then left click either back on that same slide or another slide then back to the original one, the Clear Background option disappears. Tested in version 1.2.1
![2024-07-25 13-05-17](https://github.com/user-attachments/assets/0b09ccfd-48c6-4a62-b214-8787a91ae304)

**Comment by vassbo** [comment]
Thank you! Will get this fixed.

**Comment by vassbo** [comment]
This is caused when there is more than one output, so it works fine if you just have one output.

**Comment by vassbo** [comment]
I managed to fix it for the next version! Happened to "Clear background" & "Clear overlays".

**Comment by sidcurtis7684** [comment]
Thanks again Kristoffer!  So, it'll be fixed in v1.2.2?

**Comment by vassbo** [comment]
Yes, there is a prerelease available: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.2
