### ISSUE TITLE
Arch Linux Wayland

### ISSUE THREAD

**Issue by wabrice** [ChurchApps/FreeShow#691]
I have had issues getting Freeshow to work on my Arch Linux machine.
Stable 1.1.9 nothing worked. I installed 1.2.0 - Bible works but not much else.

Arch Linux, like many distros, is or has changed over to the Wayland compositor. I know that some applications were developed with frameworks that are not yet compatible with Wayland, only X11.

On a hunch, I restarted with X11 instead of Wayland. Freeshow works fine now, just get to get familiar with it.
Which version of the gtk libraries does Freeshow use?

**Comment by vassbo** [comment]
Okay, glad you found a solution. I'm pretty sure Electron is still on GTK3.
Here's the status for version 4 support: https://github.com/electron/electron/issues/33690

**Comment by vassbo** [comment]
I have heard that version 1.2.1 might work on Linux Wayland, is this correct?

**Comment by odlg** [comment]
Another solution might be to add `--ozone-platform=wayland` as command line parameter.
