### ISSUE TITLE
[Feature request] Start/Stop present from remote device 

### ISSUE THREAD

**Issue by MiragePresent** [ChurchApps/FreeShow#692]
Hello!
I wanted to request adding a new button on the remote control device that start and stops presenting to external screen. 
The use case is next: 
I present from one computer. Sometimes I have to switch between Keynote and FreeShow because FreeShow output goes on the top of Keynote presentation I must stop presentation from computer

This button is only in desktop app
<img width="156" alt="Screenshot 2024-07-26 at 7 32 47 PM" src="https://github.com/user-attachments/assets/db2266c0-2ad8-433b-9e9b-d192c9a3e3ba">

Maybe it could be added as a new button next to "Clear all" so when presenting it's two buttons the clear all and "Stop presenting". When not presenting it's "Start presenting" or "Present"
![Screenshot 2024-07-26 at 7 38 25 PM](https://github.com/user-attachments/assets/80f4cbfd-1abe-42c7-8310-8b65702b79b1)

**Comment by vassbo** [comment]
I recommend going to the "Outputs" settings and turning off "Always on top". This will allow Keynote to display on top of the FreeShow output. Does that work for you?

**Comment by MiragePresent** [comment]
@vassbo Thank you. I haven't seen that in the settings. That should work
