### ISSUE TITLE
Delete slide vs Delete group

### ISSUE THREAD

**Issue by MiragePresent** [ChurchApps/FreeShow#693]
I probably don't know how to remove individual slides from a show or it's broken

![output](https://github.com/user-attachments/assets/80f18bcf-b049-48dc-afca-ce429f310837)

As you can notice the group name is the same so it deletes whole group. Maybe it makes sense to have separate buttons for "Delete group" and "Delete slide"?
(As you can notice I use unique name for each slide as workaround but maybe it can be solved the other way)

**Comment by vassbo** [comment]
There are two buttons: "Delete slide" & "Remove group". The first will delete the slide in the group (deletes the whole group as well if there are no slides left in the group), and the second button will remove just the slide group placed in the layout (this is what you need).

The whole point of the groups are so you can add e.g. a chorus that can be reused multiple times, and if one is changed all the others are changed as well. You can also add multiple slides with the same name e.g. "Verse" and if they are unique the program will automatically assign a number to them: e.g. "Verse 1" & "Verse 2". One single group can have multiple "child" slides as well!

I have made an example for you (see the image):
- Here you can see on the right that for all these slides there are only 6 groups. You can simply click and drag in more as you want to use them)
- As you can see the "Chorus" and "Bridge" have a child slide as well.
- If you want a group to be unique, just right click and click "Duplicate", so you can change the content without changing all the other groups.
- The verse slides are all called just "Verse", but the program assigns a number to them.

![bilde](https://github.com/user-attachments/assets/7845a7bb-4e87-4792-b1ce-bd7666480448)

Hope this makes sense! :)

**Comment by MiragePresent** [comment]
@vassbo Thank you for explanation!
I'll definitely read it a few times to refresh in memory. 

Another reason I started using unique names for groups is I noticed once that the program rearranged the sequence after "Quick lyrics". If I notice it again I'll record it and report.
Thank you for rapid reply, btw
