### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by imelcher** [ChurchApps/FreeShow#694]
Mac OS 150 Beta (24A5298h)

Not sure if I am doing this right or not, but I am not able to delete shows, slides or anything across the app. 
I can delete text boxes but that is about it.

**Comment by vassbo** [comment]
Not sure, the OS is pretty new so we'll just have to wait a bit for the Electron support!
Probably related to this: https://github.com/ChurchApps/FreeShow/issues/575
