### ISSUE TITLE
It is not possible to sort shows by name

### ISSUE THREAD

**Issue by odlarhg** [ChurchApps/FreeShow#695]
Hi,

It is not possible to sort shows by name. I can sort by creation date, by modification date, but not by name.

Regards,

Aldo

**Comment by vassbo** [comment]
The default show sort is "Name", and you should be able to select that in the context menu:
![bilde](https://github.com/user-attachments/assets/613d85c0-f006-460e-92cb-15f2d12ede1d)

Let me know if you can't find it.
