### ISSUE TITLE
Motions background freezes after upgrade to new version

### ISSUE THREAD

**Issue by odlarhg** [ChurchApps/FreeShow#699]
Hello

After updating to the new version, the motions videos freeze momentarily during their execution. The video does not look continuous, it has small freezes during its execution. I have just updated yesterday to the new version and before updating the video was running normally.

I am using the same computer. My computer has Core i5 8th gen, 16gb RAM.

Thanks for your help.

**Comment by jzongker** [comment]
Could you let me know if you're running a single output or multiple screens?

**Comment by odlarhg** [comment]
Hello

I am using an Epson powerlite x36+ projector to project the lyrics and my laptop screen.

**Comment by odlarhg** [comment]
Hi

Attached is a sample of the video playing as a background in FreeShow and the same video playing with the Windows 11 media player.

As you can see, the execution speed is very different.

Before updating I had version 1.1.9 installed, in that version the video played correctly in FreeShow, but after the update it no longer plays correctly.

I am running these video samples using only my computer screen.

https://github.com/user-attachments/assets/98ed5376-4b5d-49ef-a496-9f3585fc1ae1
https://github.com/user-attachments/assets/16b51197-f36f-43f3-90d4-971860b30cfc

**Comment by vassbo** [comment]
Thanks @odlarhg. Can you please try this preview build and let us know if it's better: https://filetransfer.io/data-package/T5OlByGl

**Comment by vassbo** [comment]
I noticed that it's fine until the video loops. Then it starts to stutter until the video is paused and played again!
