### ISSUE TITLE
Incorrect slide action is removed from slide

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#703]
When selecting a slide action to be removed from a slide that contains multiple slide actions, the action removed is not the selected action.  It seems that the lowest displayed action is deleted irrespective of which action is selected for removal.

**Comment by vassbo** [comment]
Got it fixed, thanks! You can also right click and choose "Remove layers" to remove the correct ones at the moment.

**Comment by colanct** [comment]
Thank you.
