### ISSUE TITLE
UI issues when adding "Start show" to a custom action

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#704]
When adding **_Start show_** after the first **_Start action_** to a custom action via the Functions drawer > Actions > New action, one of two issues occur, depending on what actions were selected previously.

1. **_Start show_** pre-selects a show name that cannot be changed.  The UI functions correctly by opening the list of show names, but the selected show from the list is not applied. The pre-selected show name seems to be the one that was last selected successfully in a previous operation.

2.  The **_Select show_** dialogue does not allow a selection to be made. Attempting to select a show name from the list causes the Select show dialogue to close and reopen momentarily.  This recurs if the dialogue is closed manually and the custom action is reopened via the Edit button.  The only way out is to delete the whole custom action.

**Comment by vassbo** [comment]
Thanks. I can't recreate this issue. Anything more specific you can think of that may cause this issue?

**Comment by colanct** [comment]
I've setup a test on another synced Win 10 PC.  The same issues occur on that PC, bearing in mind that it is synced with the PC used for my initial testing.  I could un-sync and clean it if that will help.

**For issue 1 above**, I've subsequently found that it occurs after
- Creating an action with action 1 set to Start Show, and successfully selecting show name AAA from the list.
- Changing Start action 1 to something else (_Select project by index_, in my test case).
- Adding **_Start show_** as Start action 2.

Show name AAA (that was selected previously) is populated immediately and can't be changed.  


**Issue 2 above** occurs (for example) when:
**_Start action 1_** is set to **_Select project by index_**.  Action 1 functions fine on it's own.
**_Start action 2_** is set to **_Start Show_**

Once **_Start Show_** is selected, the show name can't be picked from the list.

**Comment by vassbo** [comment]
Okay perfect, thank you. I'm able to track down the issue now! :)
