### ISSUE TITLE
Add option to define Google Drive folder manually on initial cloud sync setup

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#705]
Add the option to define Google Drive folder manually on initial cloud sync setup.  
At present the **_Set main folder manually_**  field is not exposed until after the first sync.  

It appears that one or more folders (maybe from deletions) are being created via the API.  When FreeShow syncs it typically finds one of those folders first and syncs to it incorrectly.  The folder id must then be changed manually.  This is problematic because a sync to the incorrect folder has already occurred.

These Drive folders cannot be viewed or deleted via the Drive UI as they are owned by the API account and not shared.  The UI shows only one shared folder.

A work-around would be to allow the folder to be set manually before the initial sync.  This would, at least, prevent contaminating the main synced content.

If there is some way to prevent the creation of folders via the API, or to delete them automatically, that would be much better. 

This issue seemed to start occurring on recent releases (maybe after addressing the file deletion issue).  On earlier versions, FreeShow always found and synced to the correct Google folder (probably because there was only one shared folder).

**Comment by vassbo** [comment]
I added an option to enter a custom folder ID on sync setup.

The API account does not have access to any other folders than the ones you have "shared" it with, so if you create a new main folder, you need to make sure the shared access to the previous is removed, then you can delete the folder, and make sure it's deleted from the trash as well.
