### ISSUE TITLE
cambiar en automatico el conteo en stage ¿se puede?

### ISSUE THREAD

**Issue by icadsm** [ChurchApps/FreeShow#706]
recién estoy utilizando el software, me parece genial. dentro de las funciones que usamos esta el conteo para los tiempos del servicio para cada parte del evento en ese orden de ideas con la opción de iniciar al colocarlo con una diapositiva funciona pero lo que sucede es que como las letras de canciones también son diapositivas entonces al momento de enviar las letras el contador del tiempo de las alabanzas se desaparece de la pantalla que tengo destinada para el escenario que es independiente al stage view del programa ya que la tengo con una salida independiente por NDI el asunto es que usando el stage view del programa funcionaria pero tocaría ir después que termine cada sección del evento a eliminar el conteo del pasado y colocarle el nuevo y luego ir a los temporizadores y darle iniciar al que sigue y parar al que terminó. no se si habra una forma de automatizar el inicio y terminación de cada conteo.

**Comment by vassbo** [comment]
So you would like a better way to manage countdowns on the stage display? I think I can add a stage item that uses the active countdown instead of a specific one, is this what you meant and need?

**Comment by icadsm** [comment]
@vassbo Yes, What I want is a way in which I can set each countdown of each event of my service to run without having to manually go to the timers tab first to play what comes according to the event that is happening in the service and second then go to the stage and place the one that I set to play. If there is any way to do this without affecting the songs or biblical texts that are also slides, it would be great. That is the only thing I have not been able to do with your software. For the rest, it would only be to work more on the stability of the program since sometimes when modifying a song the program would freeze.

**Comment by vassbo** [comment]
Great! In the next update you will be able to add a stage layout item that will automatically show the active timer regardless of which one it is. Also you can add a "Timer" item to a normal slide, this will start the timer when the slide is triggered, different slides can be scheduled to play automatically at any day in the "Calendar" tab!

**Comment by icadsm** [comment]
> ¡Genial! En ​​la próxima actualización podrás agregar un elemento de diseño de escenario que mostrará automáticamente el temporizador activo sin importar cuál sea. También puedes agregar un elemento "Temporizador" a una diapositiva normal, esto iniciará el temporizador cuando se active la diapositiva. ¡Se pueden programar diferentes diapositivas para que se reproduzcan automáticamente cualquier día en la pestaña "Calendario"!

If it were possible to send more than one slide at a time without affecting what is appearing on the stage it would be great, since for example I know that if a timer is placed on a slide it will activate and start automatically, but what happens in the case of churches that set a time for the songs? This time will no longer be seen on stage since as soon as the lyrics of the songs, which are also slides, begin to be sent, then the timer will stop appearing.

**Comment by vassbo** [comment]
Not sure I understand you, but you can right click a slide/item & choose "Bind to" to prevent them from appearing in the stage display & you can also set actions on a slide to change the stage display layout, so this should be doable!

**Comment by icadsm** [comment]
> Not sure I understand you, but you can right click a slide/item & choose "Bind to" to prevent them from appearing in the stage display & you can also set actions on a slide to change the stage display layout, so this should be doable!

that is what I want to tell you, and if I have done it as you indicate but at the time of sending them due to the fact that in the scenario it is configured that the text of the current slide appears, that causes that once the praise time counter is sent but then the lyrics begin to be sent, the counter is removed and only the lyrics of the songs appear since both the counter and the lyrics of the songs are slides. With respect to the functions, I have tried it but it is not working very well, it does not perform the action assigned to it.

**Comment by vassbo** [comment]
Please, could you send a screenshot/recording so I can better understand the issue?

**Comment by icadsm** [comment]
> Please, could you send a screenshot/recording so I can better understand the issue?
Thanks, I've solved it, I did the following:

I created a slide for each counter, to the first I added the time before starting the service, then to the next I put the time of the praise in that order, to the first I put the action to start the active counter in it and change the style of the stage, to the second I inserted the action first to stop the active counters, second to start the active counter and third to change the style of the stage and on the stage I have several styles created according to the time of the service. This way it is working but it would be good if it could be automated a little more.

I have another question and it is regarding the Bible, the first thing is that I have added several versions of the Bible and in one of them I added a * at the end of the biblical verse, I don't know if there is a way to fix it, I am using the NTV, TLA, RV1960, NVI versions. In the RV1960 version it doesn't happen to me but in the others it does, I brought them from Holyrics. I would also like to have the same banner style that I had in Holyrics for the Bible with CCSS. I tried bringing the CCSS from Holyrics but it didn't work. I will attach an image of how I have it in Holyrics.
<img width="2013" alt="CCSS TEXT Biblico" src="https://github.com/user-attachments/assets/006de981-95db-4019-95c5-df185ef9daeb">

Check out the ccss: 


}

.image-custom {

}

.music_slide {

}

.text_slide {

}

/*transparent background, and aligned to the left*/
.text-custom {
  background-color: #ffffff00 !important;
  text-align: left !important;
}

.bible_slide {
  background-color: #f6f6f6;/*background color*/
  color: #101010;/*font color*/
  display: block;
  border-top-right-radius: 40px;
  border-bottom-left-radius: 25px;
  font-size: 42px;
  padding-left: 30px ;
  padding-right: 25px ;
  padding-top: 10px;
  padding-bottom: 10px;
}

 .bible-header-custom {
   /*https://cssgradient.io/*/
   /*you can change the gradient color of background, and replacing it in the following two lines*/
   background: rgb(0,16,56);
   background: linear-gradient(100deg, rgb(0, 86, 211)40%,  rgb(29, 116, 255));
   color: #f6f6f6;/*font color*/
   display: inline-block !important;
   border-radius: 100px 100px 100px 100px;
   padding-left: 30px;
   padding-right: 30px;
   padding-top: 10px;
   padding-bottom: 10px;
}
/*animation*/
:root {
    --animation_out_delay: 300;
}

@keyframes nome_da_animacao_de_entrada {
    from {opacity: 0.0}
    to   {opacity: 0.9}
}

@keyframes nome_da_animacao_de_saida {
    from {opacity: 0.9}
    to   {opacity: 0.0}
}

.text-custom span {
    animation-name: nome_da_animacao_de_entrada;
    animation-duration: 0.2s;
    animation-fill-mode: forwards;
}

.animation_out {
    animation-name: nome_da_animacao_de_saida;
    animation-duration: 0.2s;
    animation-fill-mode: forwards;
}

**Comment by vassbo** [comment]
I made a template for you, with that syle. (Please rename the extension from .json to .template, I had to rename to upload here on GitHub). Go to File>Import>Template, then you can change the scripture template to this one.
[Bible Verse.json](https://github.com/user-attachments/files/16518883/Bible.Verse.json)

**Comment by icadsm** [comment]
> Glad you figured it out.
> 
> I made a template for you, with that syle. (Please rename the extension from .json to .template, I had to rename to upload here on GitHub). Go to File>Import>Template. After it's imported you can change the scripture template to this one. [Bible Verse.json](https://github.com/user-attachments/files/16518883/Bible.Verse.json)

Great, it worked for me but there is no way to have the small Bible quote at the top with the blue gradient and below the content of the Bible quote as I showed you in the screenshot?

**Comment by vassbo** [comment]
It should look like this, does it not, try messing around with the template?
![bilde](https://github.com/user-attachments/assets/445cc963-5d8d-455c-9b16-a6bba0e20170)

Also you should limit the "Max verses per slide" to 1 or 2 to prevent very small text.

**Comment by icadsm** [comment]
> Debería verse así, ¿no es así?, intenta jugar con la plantilla. ![imagen](https://private-user-images.githubusercontent.com/17619496/355892066-445cc963-5d8d-455c-9b16-a6bba0e20170.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDY4MzcsIm5iZiI6MTcyMzA0NjUzNywicGF0aCI6Ii8xNzYxOTQ5Ni8zNTU4OTIwNjYtNDQ1Y2M5NjMtNWQ4ZC00NTVjLTliMTYtYTZiYmEwZTIwMTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE2MDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MmNiZTNlOTBmNzJkZjM5ZjkwZTdhYzUyODRkNjBlYmYwNjU0M2M2ZjE0NjY0MTE2NGQ5YTVlYWY5YjU2NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gic9QnjKylwPodKbzKHoYtyjyMdMlcYNiuvfplZNouU)
> 
> También debes limitar el "Máximo de versículos por diapositiva" a 1 o 2 para evitar texto muy pequeño.

No, it looks like that, it doesn't look so rounded, what happens is that for the auditorium screens I send it in a large size and with a background image. I'm going to try the maximum number of verses per slide.

**Comment by vassbo** [comment]
You can tweak the CSS if it does not look how you want.
![bilde](https://github.com/user-attachments/assets/fb465f25-03df-42ba-82f3-0a3dcc628dbb)

**Comment by icadsm** [comment]
> You can tweak the CSS if it does not look how you want. ![bilde](https://private-user-images.githubusercontent.com/17619496/355897139-fb465f25-03df-42ba-82f3-0a3dcc628dbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxNTQxNzYsIm5iZiI6MTcyMzE1Mzg3NiwicGF0aCI6Ii8xNzYxOTQ5Ni8zNTU4OTcxMzktZmI0NjVmMjUtMDNkZi00MmJhLTgyZjMtMGEzZGNjNjI4ZGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDIxNTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkODJmMmY5NjY3ZDkxYmYzZGQ0ODMzNTAwMjc2ZWFmMjY0Mjc0MTViMDkxZjRiOTZmNDYwZjlmMTljNzFlYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PbcxD_EmUwDoPzBhgvlr0w62FzR_wxD_ckmZIsG7_ak)


Sorry for the trouble on my part, I would like to know if it is possible for the Bible reference and the version to appear on a single line and not below it as it appears because I already discovered that if I remove the version, it appears as you showed in your image, also if you could specify if in the CCSS the space where the text of the Bible verse appears as well as where the reference book appears are independent? so that I can modify the one I am trying to leave on a single line without a single line break... thank you.

**Comment by icadsm** [comment]
> Glad you figured it out.
> 
> I made a template for you, with that syle. (Please rename the extension from .json to .template, I had to rename to upload here on GitHub). Go to File>Import>Template. After it's imported you can change the scripture template to this one. [Bible Verse.json](https://github.com/user-attachments/files/16518883/Bible.Verse.json)

Sorry I don't understand much would it be something as is this: 

       "style": "background-color: rgb(221 221 221 / 1);border-radius: 0 30px 0 30px;height: 139.08px;left: 50.00px;top: 907.97px;width: 1820px;padding:15px;",
            "type": "text",
            "lines": [
                {
                    "align": "",
                    "text": [
                        {
                            "value":  [reference]
                            "value":  [version]
                            "style": "text-shadow:0px 0px 0px #000000;color:#000000;"
                        }
                    ]
                }
            ],
            "auto": true,
            "autoFontSize": 101.03515625,
            "actions": {}
        },
        {

**Comment by vassbo** [comment]
No CSS, look at the image I sent in that message, you need to change it in the bottom right of the Scriptures section in the drawer.

**Comment by icadsm** [comment]
> No CSS, look at the image I sent in that message, you need to change it in the bottom right of the Scriptures section in the drawer.

Ok, I already did it my friend, thank you very much, but I had to update to 2.4 because the previous one didn't allow it. I thought that in this one they would include the automation of the timers for the stage in this update.

**Comment by vassbo** [comment]
Okay, nice. It is there, you need use the "First active timer" stage item, as I mentioned earlier.

**Comment by icadsm** [comment]
> Okay, nice. It is there, you need use the "First active timer" stage item, as I mentioned earlier.

Ok, I'll try to do it. I still have to deal with the Bible versions. I use the following ones:
NIV
NTV
TLA
RV1960
Where can I get them? Because I tried using the ones I had in Holyliric and only RV1960 worked for me. In the others there is a change in the scriptures, for example, from one verse after the period, a * appears and in some cases they replace letters with characters like ?¡

I appreciate all your help and the software is really cool, very complete.

**Comment by vassbo** [comment]
Hi, thank you! :)

I can't do anything about the ?¡ characters, you probably have to search the web for more:
Here is a good place to find some: https://www.ajaytheceo.com/digital/bibles

**Comment by icadsm** [comment]
Hello, thank you for sending me the link although it is not in Spanish so I still have the same problem, on the other hand I wanted to tell you that I'm trying the latest update and so far it's going very well, could you please add an option to automatically change the stage style without using a slide? What happens is that usually in worship we have the following items:
Current slide text
Next slide text
Clock
Timer

Then in the sermon we would only have:
1. Title of the moment of worship that would be sermon
2. Clock
It would be good to be able to have an automatic change of these two styles without using a slide, it would also be good to add a function to be able to start and stop the timers automatically. There is already the option that on the stage only the first one that is activated is shown, that's great. Now it would be good to have a more practical and faster way to stop and start the timers without having to use a slide.

**Comment by vassbo** [comment]
Great!

You can manually change the stage layout by going to "Stage" & right clicking any of the layout and pressing "Move all connections to this". This can also be done in the Functions>Actions tab by creating an action that does it and clicking that.

This can even be automated by time in the "Calendar" tab.

**Comment by icadsm** [comment]
the new update 2.7 have an mistake, in the bible template the options autosize it's not working good  when it put an verse short it is seen very small and when it put an verse large it come out the screen. also I would like if its possible add the new way for search the verse biblic and new way of go the verse and verse when it is read. I go to show that in a video belog...


https://github.com/user-attachments/assets/8a075d0d-c3f0-42e1-ad92-6580dc8f3546

**Comment by vassbo** [comment]
Try changing the "Text fit" in the scripture template: 
![bilde](https://github.com/user-attachments/assets/bda36bcd-3a52-4535-962b-d946784ca4a3)

I'll see about the grid, but it's actually much quicker to press search (Ctrl+F) and type in the book/chapter/verse!

**Comment by vassbo** [comment]
![bilde](https://github.com/user-attachments/assets/bd448ad6-d586-4142-a163-046df2d962d6)

**Comment by icadsm** [comment]
> ![imagen](https://private-user-images.githubusercontent.com/17619496/368098793-beefc838-69c9-497a-b802-561e11a1ec71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODg2NzYsIm5iZiI6MTcyNjU4ODM3NiwicGF0aCI6Ii8xNzYxOTQ5Ni8zNjgwOTg3OTMtYmVlZmM4MzgtNjljOS00OTdhLWI4MDItNTYxZTExYTFlYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE1NTI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNjZkYjBmNjhjZTMxZDEyMDE4ZWE5MjFlNDc2MTg2Zjc2MzcxOTc2NzhmYzBhZDI1Njg0MDMwZGQ0NWY4YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ju4Vhcw1r_WGfuuzZyHt5ygKiRVLW3riHRWjCf5vFNU)

Have you integrated this feature into the current version of the program?

**Comment by icadsm** [comment]
> I'll see about the grid, but it's actually much quicker to press search (Ctrl+F) and type in the book/chapter/verse!

Maybe not just the grid, but it might be faster to go through and search for Bible verses. In the example I sent you, just by typing, it starts to search for the quote. If I press the ESC key, I exit that pop-up window. It even tells me how many chapters and books the book has. I thought it was a good function, that's why I shared it with you. In fact, there's also the option to go through verses by pressing the arrow keys on the keyboard.

**Comment by vassbo** [comment]
Try creating a new template in the latest verison. I can't recreate this issue!

The grid will come in the next verison, but in the current version you can already search the Bible for content or use the arrow keys to change verses!

**Comment by icadsm** [comment]
> Intente crear una nueva plantilla en la última versión. ¡No puedo recrear este problema!
> 
> La cuadrícula vendrá en la próxima versión, pero en la versión actual ya puedes buscar contenido en la Biblia o usar las teclas de flecha para cambiar versículos.

ok, good but the grid it's not so important as the function search quickly with only type in the keyboard as I was show you in the video. for example if I want to search John 3:16 instead of Press the ctrl + F  and type John 3:16 in the bar the search, would be better and fast that the moment I type in my keyboard John 3:16 the software show in the Popup the result of the search, as the show in the video that I sent it. 

because the way the search whit the bar I thinks so not bad, but I thinks that way that I show in the video would be more quickly. At least for us in my church it is faster to do it that way.

**Comment by vassbo** [comment]
In the early versions it did search directly from inputs, but that was more confusing than helpful. Also pressing letter keys on the keyboard is reserved for triggering slide groups & actions. There's not much time loss by doing the shortcut. I don't think there's a better way to do it. It should be very fast how it is at the moment.

**Comment by icadsm** [comment]
> En las primeras versiones, se buscaba directamente desde las entradas, pero eso era más confuso que útil. Además, presione las teclas con letras del teclado que están reservadas para activar grupos de diapositivas y acciones. No se pierde mucho tiempo al hacer el ataque. No creo que haya una mejor manera de hacerlo. Debería ser muy rápido como está en este momento.

ok i understand, there is only one way to do it and it is having the independent bible module i think that is what the program we were using does, however i understand that the keys are intended for the shortcuts something that is very good. but i speak to you from our experience using the program what is difficult for us is the search for the texts since some time is always lost when searching with the shortcut and more so going to the search bar more because to have a successful search you still have to write the accents of the name of the book if it has an accent this is something that makes the search a little slower perhaps if there was no need to write the accents it would be faster also having a history of the scriptures that have already been placed would be very itul since in our case on Sundays we have several services and so after the first one in the second going to the history the search would also be faster. in reality the program is super useful and very good it would only be good if you could add and improve that part of the program if possible it would be cool. Thank you very much for always being attentive and responding. Please excuse my English, which is a bit bad. Greetings and blessings from Colombia.

**Comment by icadsm** [comment]
hello sorry I know that the problem I told you about with the auto-size of the bible, you told me that you couldn't do anything and that I should try deleting and recreating another one, well I did and the same thing continues with the error now, inquiring a little about doing tests I realized that when I place it as my default template that way it works correctly but I don't have it that way because in my live broadcasts I have a template for the bible with css that when in settings within the style that I have for the signal that I send by ndi to the transmission computer it happens that when I tell it to overwrite the bible with the CSS template that I have, it shrinks the text reference just as I show you in the video, that is why in the face of that problem the solution was to place the css template by default and within the style that I have for the screens that I have in the church then place that it overwrites with the template that I created for it but it turns out that doing it that way gives the error that I mentioned regarding the autosize of the biblical texts.

https://github.com/user-attachments/assets/5c924982-c67e-459b-a12d-6345cff85606

**Comment by vassbo** [comment]
Okay, thanks. Now I can probably reproduce this and fix it, let me see what I can do.

**Comment by icadsm** [comment]
> Okay, thanks. Now I can probably reproduce this and fix it, let me see what I can do.
Thank you, would it be possible to have a history of all the Bible verses played during the service? Another question, could the software be integrated with planning center?

**Comment by vassbo** [comment]
I will see.

**Comment by vassbo** [comment]
Btw. the template issue should be fixed here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.8-beta.1

**Comment by icadsm** [comment]
> Por cierto, el problema de la plantilla debería solucionarse aquí: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.8-beta.1

Yes sir, thanks a lot! already I install that version yesterday at moment everything okay! I hope you can put it history of verses biblic. there some way for hidden background my computer because when I send the lyrics of the songs with transparency of NDI, the background of my computer appears and if I deactivate the transparency of NDI in the video of my cameras, the lyrics appear but when they come out, it opaques the video to black quite a bit.

**Comment by vassbo** [comment]
The background does not appear with the transparency if you properly receive the NDI signal in e.g. OBS. It only appears if you record the output screen with another software as you don't need to do because it's NDI.

**Comment by icadsm** [comment]
> El fondo no aparece con transparencia si recibes correctamente la señal NDI en, por ejemplo, OBS. Solo aparece si grabas la pantalla de salida con otro software, ya que no es necesario hacerlo porque es NDI.

thats correct, on obs work  ok. but I spaeking about the signal send to atem blackmagic for the screen`s  in the church. in the atem we do a lumakey that remove black color and only leave the color white of letters but whit FreeShow its no doing because leave the image of cameras oppacity low its as not would remove the color black. I was try removing the options transparency in the output, but happen what I told you about the error that the black color leaves, so if I active the transparency in the output whit NDI my wallpaper appears which is my logo in white more the letters that I sending.

**Comment by vassbo** [comment]
I know it's possible to key out the black background properly with the right settings, so you have to tweak some more and see how it goes. I can't help you here.

**Comment by icadsm** [comment]
Hi, I have seen that in the new updates you have incorporated a new function for controlling PowerPoint. I would like to know how it works because when importing a PowerPoint, the photos or backgrounds are not included, only the text is included. I don't know if it does this or if it is possible to also include the animations that the PowerPoint file has.

**Comment by vassbo** [comment]
Drag & drop a powerpoint file into your project.

**Comment by icadsm** [comment]
> Drag & drop a powerpoint file into your project.

Awesome! But what it actually does is project from the same PowerPoint, that is, it does not leave the presentation controls in FreeShow. It would be good if it left them and to be able to have independence from the presentation within FreeShow in case a biblical text has to be projected, it can be sent and not lose the order in which the PowerPoint presentation was going.

**Comment by vassbo** [comment]
In that case just import the powerpoint as images, that's what you should do if there are no important animations on the presentation. The is not so much flexebility the way it's done, but it ensures the correct layout & animations if they are needed on a live stream.

**Comment by icadsm** [comment]
@vassbo in the versions 1.2.9 Official and 1.3.0 beta it's not working the outputs NDI.

**Comment by vassbo** [comment]
Should work. Try creating a new output, and turn NDI on there. (Make sure to remove the old output) Does that make any difference?

**Comment by icadsm** [comment]
> Should work. Try creating a new output, and turn NDI on there. (Make sure to remove the old output) Does that make any difference?

I did as you told me but it doesn't work, in my case the official version 1.2.9 stopped working since in the beta it was working without problems.

**Comment by vassbo** [comment]
NDI is working, I tested it. Also no one else that are using NDI have reported this issue (yet).
So I'm pretty sure something has changed on your side!

Make sure the NDI receiver is receiving from the correct FreeShow output!

**Comment by vassbo** [comment]
You just said that NDI outputs were not working, and now you are saying that it works without problems!??

What's not working if it's not the NDI??
Maybe if you send some screenshots of the issue I can help you?

**Comment by icadsm** [comment]
> You just said that NDI outputs were not working, and now you are saying that it works without problems!??
> 
> What's not working if it's not the NDI?? Maybe if you send some screenshots of the issue I can help you?

Sorry, it must be my English that isn't that good, what I mean is that the NDI outputs work without problems when using them with other programs that I use during the church service. On the other hand, in FreeShow they are not working well in the latest updates, that was the reason why I wrote to you. Then, in my last comment, I told you that I did as you told me "I deleted the NDI outputs and created them again" but the NDI outputs still do not work in FreeShow, that is why when I noticed that in version 1.2.9 beta they do not work, it seems to me that it could be a problem with the latest updates, however, you told me that no one else has reported errors with NDI, to which I respond in my last comment that I understand that no one else has reported this error to you and that I will continue working with version 1.2.9 Beta, which is in my case where the NDI outputs are still working.

**Comment by vassbo** [comment]
Okay, thanks for the clarification!

**Comment by icadsm** [comment]
Hi friend, two questions, the first:

Can it be integrated with Planning Center?

The second is:
Can it be integrated with QLab to automate the lyrics of the songs with the sequences?

**Comment by vassbo** [comment]
Not sure. See this: https://github.com/ChurchApps/FreeShow/issues/333#issuecomment-1848955899

You might be able to integrate with QLab using MIDI cues, but I can't help you with that.

**Comment by vassbo** [comment]
Try out the Planning Center integration in the latest pre-release: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.6-beta.1
Docs: https://freeshow.app/docs/faq#planning-center-integration

**Comment by vassbo** [comment]
Nice! It will import the service program with any lyrics/media. But do you need the times? I feel like the times often don't match 100% and if it's all in order, then it should not matter.

**Comment by icadsm** [comment]
> ¡Genial! Importará el programa de servicio con cualquier letra o archivo multimedia. Pero, ¿necesitas los tiempos? Siento que los tiempos a menudo no coinciden al 100 % y, si todo está en orden, entonces no debería importar.

I understand, it would be great if it imported the times of each moment of the worship that we define within Planning Center since that way everything would be synchronized.

**Comment by icadsm** [comment]
Hey @vassbo  in the latest version the triggers that I had configured to start the counters and change the scenario at the same time stopped working. Currently, it only changes the scenario but does not start the counter.

**Comment by vassbo** [comment]
@icadsm Try removing them and adding them back in, they seem to work just fine.

**Comment by icadsm** [comment]
> [@icadsm](https://github.com/icadsm) Try removing them and adding them back in, they seem to work just fine.

hey, I try removing them and adding them back in, but not work just fine. only work fine leaving only one function or shortcut, for example, to start the timer, but I added the 3 in the order I had them:

1. change the scenario
2. stop all timers
3. start timer by ID.

That's where it's not working like it did before.

**Comment by vassbo** [comment]
You probably need to add a "Wait" action of 1 second between 2 and 3.
