### ISSUE TITLE
Change filename of x64 Mac release

### ISSUE THREAD

**Issue by thebiblelover7** [ChurchApps/FreeShow#709]
The current x64 mac release has the file name of `FreeShow-1.2.1-mac.zip`. I would recommend to change this file name to `FreeShow-1.2.1-x64-mac.zip` to make it clear that this is an x64 release. This would also fix ChurchApps/FreeShowWeb#10 .

**Comment by vassbo** [comment]
This name is automatically assigned by electron builder, and I don't think we can easily change the name for just this one file, so I'm letting it stay for now.

**Comment by thebiblelover7** [comment]
I found this when searching it up: https://stackoverflow.com/questions/40549421/retrieve-or-specify-output-file-name-in-electron-builder

A line would have to be added somewhere below https://github.com/ChurchApps/FreeShow/blob/bfe8678c11e0848de11dc2c1c420510a479a19f6/package.json#L51-L54

Something like:
```json
    "build": {
        "forceCodeSigning": true,
        "appId": "app.freeshow",
        "artifactName": "FreeShow-${version}-${arch}-${os}.${ext}",
        "productName": "FreeShow",
```

I tried to build it on my computer, but it failed for other reasons (I'm not very experienced at node)

**Comment by vassbo** [comment]
Okay, I'll see what I can do.

**Comment by thebiblelover7** [comment]
Thanks @vassbo !

**Comment by thebiblelover7** [comment]
Should be done now by commit bccb8df. Thanks! This probably fixes ChurchApps/FreeShowWeb#10, but it should be double checked.

**Comment by thebiblelover7** [comment]
Looking at the releases now, I think they should be in the format "FreeShow-${version}-${os}-${arch}.${ext}" because currently it is not possible to know what file is for what operating system (unless you know that .deb is for Linux, .exe is for Windows, etc.)

Maybe I'm being too picky... but I think the little things matter to make the project look, if not be, more professional.

**Comment by vassbo** [comment]
I see, could be nice, but I didn't want the file names to be too long, and most people will download from the website and they are already sorted by OS here, so I don't think it's necessary.

**Comment by thebiblelover7** [comment]
Ok. Sounds like a good compromise.
