### ISSUE TITLE
Add Unsplash Photo API to Media Tab in Drawer

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#710]
This is a feature that I've been wanting for a long time, and that would be really useful across the board. Unsplash has an amazing free API (that's super simple to implement) for their photo database and search functions. I think if we added it to the media tab as a source of photos for slide backgrounds, it would simplify and streamline the process of getting media for a slide background a lot. What do you all think? Is that something possible to add?

[https://unsplash.com/developers](https://unsplash.com/developers)

**Comment by vassbo** [comment]
Would be possible. You can already get images/videos from Pixabay in the "Media" tab.
