### ISSUE TITLE
Display Alignment Issues - V1.2.2

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#711]
Testing version: 1.2.2 - Windows 10 - 

After around either update 1.1.7 or 1.1.9 or whenever the option to align the output to display was added. Outputs have been doing what is happening in this image.

![image](https://github.com/user-attachments/assets/288f27ec-722e-445f-8191-b6e4ebf58e45)

Now, this only seems to happen after a new display is connected to the computer or the display settings have changed, and the program seems to retain its previous output settings. Once you re-align the outputs to the display, restarting to program does keep those settings as long as it is the same display, and that display has not moved around with in the windows display settings. (Ex. changing the virtual location of the display, such as from the left to right side, or top to bottom, or changing it so display tops or bottoms are aligned)

In the past this seemed to be an automated process when clicking the present button, that it would fit itself to the display. Is it possible to get it back to that?

This is really just an annoyance to portable setups that may not always be used in the same location. If your computer is in one location with the same display, it's fine and doesn't seem to be a problem.

**Comment by vassbo** [comment]
I'll check it out. Should be automatically aligned correctly.

**Comment by Bagel94** [comment]
This was my screen setup before I took the screen shot: Photo1
![image](https://github.com/user-attachments/assets/ce5b1822-de6c-4cb0-a41d-1686aee9c93c)

This is what I changed it too and it created the issue: Photo2
![image](https://github.com/user-attachments/assets/da154934-4b7c-4da8-8952-4a855143eea2)


In the entail post photo, the output display is correct in its size and position based off of photo1 but due to moving display 2 down so that the displays are bottom aligned per photo2, FreeShow kept the settings from the last known position.

**Comment by vassbo** [comment]
Quick question: Would it work for you if the "Align with screen" button saves the resized state? I guess then you would just have to click that once after e.g. the Windows alignment is changed.

The output window will only automatically align if there is just one output & one screen, but it should not do that if there is multiple to not mess up special cases.

**Comment by Bagel94** [comment]
That could possibly work.
