### ISSUE TITLE
Shortcut keys bug (v1.2.1)

### ISSUE THREAD

**Issue by thirdybobiles** [ChurchApps/FreeShow#715]
The shortcut keys are either non-functional or have a delayed response when recognizing the keys. Restarting and reinstalling the application has been attempted, but the issue remains unresolved. The software was not lagging.

**Comment by vassbo** [comment]
Have not experienced this myself. What keys are you pressing, and how long does it take before the action is executed?

If it's the arrow keys, try pressing the arrow buttons under the preview, do you get the same amount of delay here?
![bilde](https://github.com/user-attachments/assets/3545bc64-6f96-4486-a2a9-acc781092e1f)
