### ISSUE TITLE
Slide groups changing after editing the text

### ISSUE THREAD

**Issue by funnysloth** [ChurchApps/FreeShow#717]
We have a problem with slide groups. We're adding multiple slides of same groups and firstly it shows in a correct order - for example, first slide is "verse"  and the next one is "verse 2". But when we edit the text of the slide the group changes with the following number. 
Steps to reproduce:
1. Create a song show with 2 verses
2. Edit the text of the group "Verse 2" slide

Expected result: the group remains the same - "Verse 2"
Actual result: the group changes to "Verse 3"

**Comment by funnysloth** [comment]
Yeah, I forgot to mention that it only reproduces with multiple layouts in the song. And it probably makes sense. But what if I want to split the lyrics of the slide into 2 slides? We use a text editor to add one empty string, but it changes the slide group.

**Comment by vassbo** [comment]
Right click the slide, "Format">"Split in two". Or place the caret anywhere on the text, hold ALT and press ENTER.

**Comment by funnysloth** [comment]
got it, thanks
