### ISSUE TITLE
Text pasted into a song via the Text edit view is not retained

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#719]
Text pasted into a song via the Text edit view is not retained.
The pasted text displays correctly until the view is changed, whereafter it is lost.

**Comment by colanct** [comment]
Hmm.  This is not as straight forward as it appeared initially.

The problem occurred multiple times recently on a Win 11 PC and was reproduced consistently on a Win 10 PC.

There is no problem when editing a newly created song.

However, the issue occurs consistently when editing some previously created shows.  I didn't create them, so I don't know the history,
For those, all text additions, not only when pasting, are not retained.
Also, for each problematic song, the background image, applied to the first slide, is not removed after selecting _Remove Background._
Songs where the background can be removed do not exhibit the issue.

The first slide is an inserted title slide.  Perhaps the way it was created is problematic.  
I can export and send the song as a project, if that will help.

**Comment by vassbo** [comment]
Okay, please send the song, that would be helpful! :)

**Comment by colanct** [comment]
I've attached [Colan Test - All Glory be to Christ.json](https://github.com/user-attachments/files/16494514/Colan.Test.-.All.Glory.be.to.Christ.json) as an example of a problematic song.

Another consideration is that both PCs are cloud synced.  Recently created test songs that do not exhibit this issue, have not been synced or edited by another synced device.

**Comment by colanct** [comment]
Will the fix be effective for existing shows, like the attached example, or will those need to fixed manually?

**Comment by vassbo** [comment]
It will work for all existing shows, yes. :)

**Comment by colanct** [comment]
Ah, good; thank you.
