### ISSUE TITLE
Cannot Download x64 version for macbooks with Intel processors. 

### ISSUE THREAD

**Issue by Pauix30** [ChurchApps/FreeShow#722]
I tried downloading the x64 version for MacBooks with Intel processors, but when I click on x64, nothing happens. However, when I tried downloading the ARM64 version, it downloaded successfully, but since my MacBook has an Intel processor, it is not compatible and doesn't work. What could be the problem?

**Comment by vassbo** [comment]
Please go here: https://freeshow.app/downloads
https://github.com/ChurchApps/FreeShowWeb/issues/10
