### ISSUE TITLE
Can I somehow make it so bible's chosen starting and ending verse is shown?

### ISSUE THREAD

**Issue by funnysloth** [ChurchApps/FreeShow#726]
Hey, have a question about scripture slides. We want to be able to make it so that when we choose a verse range from the bible to see the range on each slide. For example, If I choose Mathew 1 chapter and verses 12-20, we want to see _Mathew 1:12-20 (current verse(s)_) on each slide> Is it something that can be done?

**Comment by vassbo** [comment]
Okay, so instead of e.g. Matthew 1:12-15, Matthew 1:15-18 etc. it always shows Matthew 1:12-20?!

**Comment by vassbo** [comment]
In the next version you can turn off this option to always show the full selection:
![bilde](https://github.com/user-attachments/assets/c0d62408-13e1-4030-a7cc-51e33ed5ff61)

**Comment by funnysloth** [comment]
thanks

**Comment by funnysloth** [comment]
will it be in 1.2.4?

**Comment by vassbo** [comment]
Yes.
