### ISSUE TITLE
v1.2.3 Songs show background Could not load

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#727]
v1.2.3 songs with background attached to the first slide show **_Could not load_** on all subsequent slides.
Slide 1 background remains correctly visible for all subsequent slides on the output.

**Comment by vassbo** [comment]
Thanks, I'm not able to recreate this issue for some reason. I place a background on the first slide and all the other previews loads fine. Does this happen with all shows & backgrounds?

**Comment by colanct** [comment]
It's happening on new and pre-existing songs once an image is dropped onto a slide.

For a new empty show, where slides are created by dropping an image onto the centre panel, it is fine when adding new slides via right click (i.e. subsequent slides load the preview background successfully)   However, once the background is replaced on one of those slides by dropping an image onto the slide, subsequent slides show _Could not load_.

Also, it takes about 5 seconds for the replacement background image to be shown on the slide on which it was dropped, which makes it seem that the action was unsuccessful.

**Comment by vassbo** [comment]
Okay, it does not work if the media is not cached.

**Comment by colanct** [comment]
Is this a bug?
I've not used any new media since moving from v1.2.1 to v1.2.3.  So, if the cache is gone, that must have been caused by the install.

If the media folder needs to be opened to invoke the caching, I've done that, but the problem persists.  All subsequent slides still show _Could not load_.

**Comment by vassbo** [comment]
It was a bug that I managed to fix now, the cache is not changed by any installation.
Should work fine again in the next version. :)

**Comment by colanct** [comment]
Ah, good.  Thank you.
