### ISSUE TITLE
v1.2.3 Background processes continue after closing app

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#728]
After closing each v1.2.3 instance, a WIn 10 background process remains for each instance.

After opening and closing the app three times:
![image](https://github.com/user-attachments/assets/c09a1277-2db6-42eb-b880-5b01b6d4a6f0)

**Comment by vassbo** [comment]
Tried fixing it, without any luck, might be a problem with the current Electron version! I'll see how it is when I update Electron.

**Comment by vassbo** [comment]
Looks like Electron 31 did the trick! That will be version 1.2.5 if everything goes to plan.

**Comment by colanct** [comment]
Ah, good. Thank you.

**Comment by colanct** [comment]
Confirmed; issue no longer occurs in v1.2.5.
