### ISSUE TITLE
Multi language Bible Collection is not working.

### ISSUE THREAD

**Issue by TPaulManohar** [ChurchApps/FreeShow#729]
We tried to show the multiple scripture language, but it not working. 

We used collection to merge two language bible, but it still loading it not showing both language bible it only showing one language. As  we followed this
https://github.com/ChurchApps/FreeShow/issues/236#issuecomment-1683423643
and tired but it not working or us.
 
 App Version: 1.2.1, 1.2.2, 1.2.3, even in 1.1.6 also we tried but it not working.

**Comment by vassbo** [comment]
I'm guessing this might be related to the API.Bible not loading at all sometimes, regardless of it being a collection?! I'll see if I can find out more. Should be more reliable using local scriptures, and that should work fine with collections as well as long as your template has three textboxes.

**Comment by vassbo** [comment]
I found the problems, it should work in the next update.

**Comment by vassbo** [comment]
Fixed now in version 1.2.4!

**Comment by TPaulManohar** [comment]
Thanks @vassbo for Fixing fast.. Eagerly wait for 1.2.4.

**Comment by TPaulManohar** [comment]
Its working in v1.2.4 
Thanks @vassbo for fixing

**Comment by escyvtt** [comment]
Collection is greyed out when trying to create a multi scripture language

**Comment by vassbo** [comment]
@escyvtt Do you have screenshots and more info?
