### ISSUE TITLE
Issue with song "New Layout"

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#730]
Noticed in V1.2.2 - Linux Mint, V1.2.2 & V1.2.3 - Windows 11

Sunday morning, we need to do a new layout for a song that we had already did. I didn't catch it before service, but during the service I clicked on the song that had 2 layouts, then when I clicked on the first slide it would not send any of the slides to the outputs. The only way to get it to go was by pressing the space bar.

Songs with the default layout when created do not have this issue.

https://github.com/user-attachments/assets/c282320d-b54b-437a-972b-5a8540d5d994

**Comment by vassbo** [comment]
Thanks. I can't recreate this. Can you send over the "Change My Heart" song, there's probably an error in it. Then I should be able to fix this.

**Comment by Bagel94** [comment]
Do I just export that song? And then where do I send it to?

**Comment by vassbo** [comment]
You shoud be able to find it in the Documents/FreeShow/Shows folder (probably called "Change My Heart.json"), or something like that. You can just drag it into the comment box here on GitHub, or send it here dev@freeshow.app

**Comment by Bagel94** [comment]
In the Shows folder, the only file extension is .show, is that the right one, or should see if there is a .json?

**Comment by vassbo** [comment]
Yeah, sorry. You can rename a copy to .json (or just send it on mail)

**Comment by Bagel94** [comment]
Awesome, here ya go!

[Change My Heart, Oh God.json](https://github.com/user-attachments/files/16560114/Change.My.Heart.Oh.God.json)

**Comment by vassbo** [comment]
The first slide referenced a background file that didn't exists, that's why it did not work, but it will work in the next update! :)

**Comment by Bagel94** [comment]
In the mean time is there a way to remove the reference?

**Comment by vassbo** [comment]
I guess you just can apply a background to the slides with this issue, and remove it again.

**Comment by vassbo** [comment]
@Bagel94 I just released the fix actually, so you can update to version 1.2.4! :)
