### ISSUE TITLE
Screen is blank

### ISSUE THREAD

**Issue by katrinarusli** [ChurchApps/FreeShow#731]
<img width="1440" alt="Screenshot 2024-08-08 at 2 21 40 PM" src="https://github.com/user-attachments/assets/0e382a6a-2b20-4286-a685-516466d03c1e">
Every time I open FreeShow, it's been showing this blank screen, and I haven't been able to do anything. I recently downloaded it about a week or two ago, so I should have the most recent version. I need the program ready for tomorrow, so any help would be greatly appreciated.

**Comment by vassbo** [comment]
Is it better if you update to this prerelease (Should be more stable): https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.3
If not I'm not sure what might be the problem, if updating does not fix it you can try deleting all the app .json files that might be located here: `~/Library/Application Support/FreeShow/` This will delete the application data, but not your shows (songs).

**Comment by vassbo** [comment]
This might have been fixed in 1.3.0-beta.1 as it is similar to this: https://github.com/ChurchApps/FreeShow/issues/872
