### ISSUE TITLE
cannot drag and drop media, cannot create slide from media

### ISSUE THREAD

**Issue by wpd2012** [ChurchApps/FreeShow#733]
cannot drag and drop media to make it as a backround of the slide or even create a slide.

**Comment by vassbo** [comment]
I need more context on when this happens, this works fine when I just tested it in version 1.2.4.

**Comment by wpd2012** [comment]
ohh i see, I tried it and everything seems to work fine... so I searched why this happened...
Bug happens when you drag a scripture to create a slide... then media wont work

**Comment by vassbo** [comment]
Thank you, I managed to fix the issue for the next version.
