### ISSUE TITLE
CMD+Z Undo after changing group shortcut freezes GUI

### ISSUE THREAD

**Issue by Socapexxx** [ChurchApps/FreeShow#734]
I added a new global group, hit enter and it shot to the bottom of the list, as expected, sorted alphabetically.
In my haste, I didn't see it had done that, and changed the shortcut for the top group. Not really knowing what I had done, I hit CMD+Z to undo, and to my surprise, it appeared to do it. It then showed up with "[object Object]" in the shortcut field, and now nothing in the GUI is responsive to any mouse clicks.
![image](https://github.com/user-attachments/assets/2d1a7e8a-9000-4d4b-b660-ef24ba8e36cd)
Quit and reopened, and still nothing is responsive. Crashed within a few seconds. Finished for the night so I haven't tried anything further

Macos 14.6, MacBook pro m2 pro

Crashlog: https://pastebin.com/UhFv8AZi

**Comment by vassbo** [comment]
Thank you, I will fix this! :)

**Comment by vassbo** [comment]
I managed to fix it for the next version, if it still freezes in the current version you can find the `settings_synced.json` file in the app data location (often `~/Library/Application Support/FreeShow/` on Mac) and remove the entries in `groups` that looks off.
