### ISSUE TITLE
Suggestion: One Output per Monitor

### ISSUE THREAD

**Issue by thirdybobiles** [ChurchApps/FreeShow#736]
I suggest implementing a feature where only one output is displayed on a secondary monitor. Currently, two outputs appear on the same screen, even when the NDI transparent window option is activated. Additionally, I would like the stage monitor to be the sole display without showing anything else on any other screens.

**Comment by vassbo** [comment]
You probably can do this, let me try to explain:
- If you want to use multiple outputs, but only want one to show up you can turn on the "Invisible" option when NDI is enabled. Or alternatively you can set the X/Y coordinates of the window manually to something outside the secondary monitor.
- If you just want to show the stage display do the same thing in the last step, you can also right click the output buttons above the preview and enable "Hide from preview" if you just want the stage display in the preview. (The stage display is linked to the output content, so you need at least one output active.)
