### ISSUE TITLE
Use number keys to show slides

### ISSUE THREAD

**Issue by CMGbR** [ChurchApps/FreeShow#738]
Hi there,

thanks for the amazing work you are doing with this software! :)

If have a question / feature request:
The slides in the slide view are numbered. Is it possible (or would you maybe consider making it possible) to dispaly slides by pressing the coresponding number keys as it is in SongBeamer? That would be a great feature for us who are used to that.

Thanks and blessings,

Kornelius

**Comment by vassbo** [comment]
Hi, thank you! This is possible, but have you considered setting and using the shortcut keys in settings>Groups? To be able to quickly go to specific groups instead of slides with e.g. "C", "V" & "B".

**Comment by vassbo** [comment]
I added a toggle in the "Groups" settings for the next version if you want to use this, `Play slides with number keys`. It has a timeout of 0.3s so you can press more number keys, e.g. 1+5=15.

**Comment by CMGbR** [comment]
Oh wow, thank you so much!! That was extremely quick! I didn't know about the group shortcuts but it's very amazing to have both options now! Thank you!
