### ISSUE TITLE
[Bug Report] {Freeshow being laggy}

### ISSUE THREAD

**Issue by brian4926** [ChurchApps/FreeShow#740]
If I click something in freeshow, it will take 3-4 seconds to respond.

**Version**
 - OS: [MacOS M1 Pro]
 - FreeShow Version: [1.2.4]

**Comment by vassbo** [comment]
Please give more context, is it related to this?: https://github.com/ChurchApps/FreeShow/issues/708#issuecomment-2260626296
If so you can try that solution.

Also did you try the previous version, was it better here?

**Comment by hyiten** [comment]
1.2.1 on the M1 is not laggy. 1.2.4 is really laggy.
on 1.2.1. The video background playback is stuttering.

**Comment by vassbo** [comment]
I will be adding a toggle to turn back on hardware acceleration in the next version. I guess that might improve the performance, but might make the videos stutter.

**Comment by vassbo** [comment]
Try pre-release 1.2.5: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.5
I hope it's better here, I also added an option to toggle Hardware Acceleration in settings>"Other", try toggling to see if that's better!
