### ISSUE TITLE
Long Load Time for Shows with a lot of Slides

### ISSUE THREAD

**Issue by Jesuite** [ChurchApps/FreeShow#742]
**Describe the bug**
When ever a show with a lot of slide loads it takes quite a while to load which should be expected with more slides but the issues is in the church use case if a song needs to be displayed very quickly and who ever is singing starts from maybe the bridge which is a slide located further down the delay of the loading slides would be undesirable.

**Reproducing**
Just try loading a show with a lot of slides for example the song Refiner by Maverick City, then try scrolling down.

**Screenshots (Optional)**

**Version (Optional)**
 - OS: Windows
 - FreeShow Version: 1.2.4

**Additional context**

**Comment by vassbo** [comment]
I'll see if it's possible to reduce the time. But have you considered using keyboard shortcuts? If you want to show the bridge, just press "B", or "C" for chorus, this can be tweaked in the "Groups" settings.

**Comment by Jesuite** [comment]
Sure I'll definitely incorporate shortcuts into my flow, just thought to bring up the loading times.
