### ISSUE TITLE
Adding a "Slide LABEL" or "Slide NOTE" to slides

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#744]
Is there a way to add a customizable "LABEL" or "NOTE" to slides when you right click on them just like you could with "Groups" and add an editor button into the "Settings" folder just like you can with "Groups"?

**Comment by vassbo** [comment]
Yes, go to "Edit", then "Slide" on the right, and type any note for the slide. If you need something more reusable, just use groups.
