### ISSUE TITLE
Stage display "Always on top" error

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#746]
Stage display is "On Top" when you press "Present" but in the Settings under Outputs, Always on top is disabled

**Comment by vassbo** [comment]
Try turning the toggle on and off again. Does that fix it? It works for me.

**Comment by kinghamr** [comment]
It does not work for me

**Comment by vassbo** [comment]
Okay, try turning off and on the whole stage display output then, does that work?
