### ISSUE TITLE
Enable/Disable Output button for Stage

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#747]
Is there a way to add an "Enable/Disable" button for Stage?

**Comment by vassbo** [comment]
This is possible. I can't have it like the other outputs enable/disable buttons because that will be confusing (because it has it's own enable/disable in stage), so how would that work? Maybe hide the stage output window when the stage layout is disabled with right click?

**Comment by kinghamr** [comment]
When I try to present it shows both screens so I can’t even see the
software window

**Comment by vassbo** [comment]
I see. You can press "Choose screen" to change the position, also I hope you get the "Always on top" fixed so you can turn that off!

**Comment by vassbo** [comment]
Closing as I figured this is probably not needed, if you use stage with NDI turn on "Invisible window", otherwise just turn off the main stage output in "Stage">"Slide">"Output screen"
