### ISSUE TITLE
Template error: Bullets

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#748]
When you click on "Bullets" actual bullets "• " are being added to the slides under the Bullets template and they won't go away when you go to a different template, and you need to edit the whole show to remove all of them

**Comment by vassbo** [comment]
This is intentional, and you can just press Ctrl+A (select all slides), right click "Format">"Find & replace text", then replace "• " with "" to easily revert the change. But I'll see if I can auto remove them!

**Comment by kinghamr** [comment]
Thanks!
