### ISSUE TITLE
Applying Styles automatically to slides

### ISSUE THREAD

**Issue by kinghamr** [ChurchApps/FreeShow#750]
Is there a way to add Styles automatically for either Notes, Bible Verses, Announcements or Songs when detected without having to have a preset or manually change them by having the first slide be set for "Style X" then bible "Style Bible" etc?

**Comment by vassbo** [comment]
Not sure what you mean exactly, but you can apply a template per slide in the "Edit">"Slide" (or with drag and drop), then that single slide will update automatically when the template changes. You can also create different output styles, and create slide actions to automatically change styles!
