### ISSUE TITLE
Paste in a text box fails

### ISSUE THREAD

**Issue by joelgraff** [ChurchApps/FreeShow#751]
When pasting text copied form another slide onto a slide that has text already, the paste function works, but inserts the copied text above where I place it, typically in the middle of the existing text on the slide.

To reproduce: Import a song and switch into edit mode.  Copy text from one slide and select another.  Use SHIFT+Enter to adda  blank line or two, then paste the copied text.  No matter how many blank lines I add, the copied text is always pasted near the end of the text that already exists, typically at a point around 25 characters from the end of the previous text.

(I will add a screenshot when I have time if needed.)

Bug exists identically in both Windows and Linux versions, currently running the latest (and previous) release.

Refer to issue #470, which appears to be the same bug, but has been closed.

**Comment by vassbo** [comment]
Thanks, looks like it works fine when not using SHIFT, and just pressing Enter a few times! I'll fix this.

**Comment by joelgraff** [comment]
Gotcha.  Bad / good habit I've developed, I guess.  I can't trust Enter to work as expected in a text input, as it may be captured to do something else within the application.  Shift-Enter / CTRL-Enter is the "safe" way to add line breaks in a text box in my mind.  Maybe I've just been doing this too long...

**Comment by vassbo** [comment]
I see. I decided to prevent Shift+Enter to make things simple, because of the way Chromium adds line breaks as `<br>` and not `<span>` when holding Shift, that breaks some things, but I guess that's fine because the "safe" way will just do nothing in this case and users can expect normal "Enter" to be safe I guess.
