### ISSUE TITLE
Auto-capitalization for song lyrics

### ISSUE THREAD

**Issue by joelgraff** [ChurchApps/FreeShow#754]
Provide an auto-capitalization feature for song lyrics.  This might include the start of every line and for pronouns and names referring to God or Jesus.  This would simply apply the capitalize action to imported song lyrics automatically, either on import or as a template option.

**Comment by vassbo** [comment]
Settings>"Other">"Capitalize words"!

**Comment by vassbo** [comment]
Currently capitalizing "Jesus" & "Lord" by default. I did include God also by default, but removed it again as Norway and some other coutries uses the word "god" meaning "good" (so we don't wanna capitalize that by default)

**Comment by joelgraff** [comment]
Nice!  Using a textbox for customization is perfect.  Thanks!
