### ISSUE TITLE
[Feature Request] Add stage layout switching per display

### ISSUE THREAD

**Issue by thebiblelover7** [ChurchApps/FreeShow#758]
**Describe the feature**
It would be nice to be able to switch which stage layout is showing on which display. The usecase is this: when we were on ProPresenter, we had multiple stage layouts. When showing image slides, we would have a macro that would automatically switch to that stage layout, and when we had song lyrics, it would automatically switch to the song stage layout. 

As of the current version, the only way to do that is to disable the stage output for one layout, enable it on another, and set the right output screen. (quite complicated)

This would probably require a reworking of how stage layouts are set. Stage layouts should probably be setup from the output settings with a toggle to make them a stage output. Then, a panel could be added to the main view to choose the stage layout for each output (much like ProPresenter).

<img width="394" alt="Screenshot 2024-08-16 at 1 34 22 PM" src="https://github.com/user-attachments/assets/c2ac8f04-b949-4fb6-886f-73dacb1b51ce">

**Comment by Bagel94** [comment]
Would this work for what you are trying to replicate?

Under "Stage" create another stage and add the elements you want it to display.

Then on the slides where you want it to change, right click the slide, choose "slide actions", "start action", then choose "Change stage layout by ID"

**Comment by thebiblelover7** [comment]
I was trying to do it through a physical output, as that is our use case and is currently not possible.

**Comment by vassbo** [comment]
You can do this with the actual stage displays yes. But actual stage outputs are only assigned to one output, so if you want to do this you should use "Mirror" items, like explained here: https://freeshow.app/docs/mirrors#stage-display-in-output-window

**Comment by vassbo** [comment]
We need a better way of dealing with stage outputs in general!
