### ISSUE TITLE
[Bug Report] Current slide text output does not update if first non-stage output is disabled

### ISSUE THREAD

**Issue by thebiblelover7** [ChurchApps/FreeShow#760]
**Describe the bug**
If the first non-stage output is disabled, the stage outputs' current/next slide text will not update with the updated slide.

**Reproducing**
Disable the first non-stage output, then change the slide. The stage output current/next slide text will not update.

**Screenshot**
<img width="487" alt="Screenshot 2024-08-16 at 2 35 05 PM" src="https://github.com/user-attachments/assets/7a46a45a-cd25-438d-8b8a-829415a9cb32">

**Version (Optional)**
 - OS: MacOS
 - FreeShow Version: 1.2.5

**Comment by vassbo** [comment]
This is because the stage display is always linked to the first output if no output is set, so you should probably set a specific output in Stage>"Slide">"Source output".

**Comment by thebiblelover7** [comment]
Is it possible for the stage display to not be linked to any output, for example, if I don't want to show something to the audience, but just for the stage? I think that would be a nice feature to add.

**Comment by vassbo** [comment]
Right click a textbox, choose "Specific outputs", click "Stage".
