### ISSUE TITLE
[Feature Request] Add Text size down/up option to text boxes

### ISSUE THREAD

**Issue by thebiblelover7** [ChurchApps/FreeShow#761]
**Describe the feature**
It would be very nice to have an option to resize the text in a box (like auto-size) but with more granularity. I think ProPresenter's method of doing this is really great. It might even improve performance when using auto-size.

![image](https://github.com/user-attachments/assets/bc28d0c1-72a2-405d-87af-cbba029ebf3f)

**Comment by vassbo** [comment]
I have added two new auto size options for the next version:
1. Shrink to fit: Text is set font size by default, but can shrink if the text does not fit in the textbox. (default)
2. Grow to fit: Text will grow to fill the entire textbox, but maximum the set font size.

![bilde](https://github.com/user-attachments/assets/2725b788-3c40-44ea-9568-c787c92ade0c)

**Comment by thebiblelover7** [comment]
@vassbo Could we add this to the stage view as well?

**Comment by vassbo** [comment]
Why do you need the text to not be large in the stage editor?
