### ISSUE TITLE
Bug Report: FreeShow App Using 104% CPU and Slowing Down

### ISSUE THREAD

**Issue by noah-sheldon** [ChurchApps/FreeShow#762]
Describe the bug
The FreeShow application is consuming 104% of CPU resources, leading to significant slowdowns in its performance. This makes the app almost unusable during the periods when CPU usage spikes.

Reproducing
Steps to reproduce the issue:

Launch the FreeShow app.
Perform any typical task (e.g., import a file, start a presentation, or edit a slide).
Monitor CPU usage through Task Manager (Windows) or Activity Monitor (MacOS).
Observe that the CPU usage spikes to 104% or higher.
Note the slowdown in app responsiveness.

Screenshots (Optional)
<img width="832" alt="Screenshot 2024-08-16 at 18 59 08" src="https://github.com/user-attachments/assets/ce87af7c-1fb3-4401-a6d0-9a81ffbadba2">

Version (Optional)
<img width="472" alt="Screenshot 2024-08-16 at 19 03 00" src="https://github.com/user-attachments/assets/5f0b0749-ae68-4e4e-bb5c-153433d30a69">

OS: 
<img width="487" alt="Screenshot 2024-08-16 at 19 03 09" src="https://github.com/user-attachments/assets/2947f3bc-9693-4c3c-ae4c-3e8987c06040">

FreeShow Version: 1.2.4
Additional Context

<img width="555" alt="Screenshot 2024-08-16 at 19 04 14" src="https://github.com/user-attachments/assets/a405663b-0dbb-4b3f-a6bd-dc9a52cb9c6f">

**Comment by noah-sheldon** [comment]
Thanks @Dcanadian . 

I reset the settings, reinstalled the app - didnt touch the settings this time. 

It was smoother and better now. 

This is the metrics at the moment.

<img width="971" alt="Screenshot 2024-08-17 at 00 47 26" src="https://github.com/user-attachments/assets/b474c402-d951-42b3-b7ec-d4a76017b5b7">

**Comment by wpd2012** [comment]
Also an issue for Mac FreeShow Version: 1.2.5 ,
after sometime it freezes the app, probably some kind of memory leak

**Comment by thebiblelover7** [comment]
@noah-sheldon Have you made sure that you are not using any captures in your show? Check out the examples here: https://github.com/ChurchApps/FreeShow/issues/708#issuecomment-2260626296

**Comment by abhishikthraj** [comment]
Facing the same issue on Windows 10

**Comment by TPaulManohar** [comment]
Need optimizing here for CPU utilization. It taking lot of CPU resources.

**Comment by thebiblelover7** [comment]
Can reproduce on M2 Mac Mini on a fresh install with no changes whatsoever. The UI is slow and laggy.

**Comment by vassbo** [comment]
Please in v1.2.5 go to settings>"Other" and toggle "Disable hardware acceleration", does that make things better?

**Comment by TPaulManohar** [comment]
Hi @vassbo,

What I identified here is, when we updated from 1.2.4 to 1.2.5, Mostly same CPU Utilization slight difference, even we enable or disable "Disable Hardware acceleration".

I tested on different CPU Processors in running with Windows Machine
Intel i5-5200 CPU values are 80% to 100% - 2.95Ghz Speed. 
AMD Ryzen 5 3600 CPU Values are 40% to 80% - 3.94Ghz Speed.

And what I identified again here is when toggle is enable "Disable hardware acceleration" CPU utilization is increasing. When toggle is disable "Disable hardware acceleration" graphic card utilization is increasing to almost 50%. I'm using Dedicated 4GB nvidia graphics card. 

Where is happening is fetching content from Pixabay and Unsplash to load the content.

Thanks,
Paul.

**Comment by Jesuite** [comment]
Hi @vassbo,

I'm not sure how useful this might be but if you have sometime you could check it out and see if it could help with FreeShow's performance. https://brainhub.eu/library/electron-app-performance.

Thanks,
Jay.

**Comment by vassbo** [comment]
Please try this version, it should be more optimized: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.6-beta.1

**Comment by Jesuite** [comment]
Yeah been messing around with the beta it's a lot more optimized. You're doing really fantastic work man, God Bless You!

**Comment by noah-sheldon** [comment]
Looks and feels stable

**Comment by TPaulManohar** [comment]
@vassbo Yes, we tested 1.2.6-beta version be lot more optimized. And one more  I found in lower speed processor(2.20GHz) it take more CPU Utilization. Compare to previously it running good with 50% to 80% when disabled "Disable hardware acceleration"
