### ISSUE TITLE
Chord Pro Import

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#763]
- OS: Windows 11
 - FreeShow Version: 1.2.4
 
Was testing out the Chord Pro import to try using chords in the stage view, but when you import a .cho file and it has the {key: } tag, this tag is then set as the first slide and is marked as verse 1. everything else imports as it should.

**Screenshots (Optional)**
![image](https://github.com/user-attachments/assets/5f3f2658-c538-4dae-ad48-781d79f1413f)

 - OS: Windows 11
 - FreeShow Version: 1.2.4

**Comment by vassbo** [comment]
I added a check to move this to the notes, if it has {}
