### ISSUE TITLE
[Feature Request] Auto fit text to slide preview

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#764]
EDIT: never mind, I totally forgot that Max auto size text was added. and everything works as it should

It would be nice if the program could auto size the text to fit all inside the slide preview when looking at the grid layout. If you don't split slides, it's too much text. See screen shot.

The immediate fix is of course to either split the slide or turn on auto size, but then that auto resize effects the output, which is not the desired result.

![image](https://github.com/user-attachments/assets/ec4bea4d-a944-4e2f-8263-37b7352890e5)

**Comment by vassbo** [comment]
I think this will be implemented as a better way of dealing with this: https://github.com/ChurchApps/FreeShow/issues/761
