### ISSUE TITLE
[Bug Report] Interface freezes/slow response

### ISSUE THREAD

**Issue by MiragePresent** [ChurchApps/FreeShow#765]
**Describe the bug**
Hello!
The interface started to response with a delay. Same applies to video backgrounds, they look like 5-10fps.
The logs are full with the next error: 
```
The play() request was interrupted because video-only background media was paused to save power. https://goo.gl/LdLk22
```
The link gives a code fix only. Is there anything I can do to fix the problem? 

**Reproducing**
Probably video backgrounds

**Screenshots (Optional)**
Pay attention to how hover effect is trying to catch up the cursor
![slowinterface](https://github.com/user-attachments/assets/9eab01ce-a0a8-4a43-9027-9af1d29471cb)

**Version (Optional)**
 - OS: MacOS
 - FreeShow Version: 1.2.4

**Additional context**
Log file:
[error_log.json](https://github.com/user-attachments/files/16645756/error_log.json)

**Comment by thebiblelover7** [comment]
Have you double checked this is not related to https://github.com/ChurchApps/FreeShow/issues/708#issuecomment-2260626296?

**Comment by vassbo** [comment]
Thanks! Will continue here: https://github.com/ChurchApps/FreeShow/issues/762
