### ISSUE TITLE
Javascript Error: EPERM Operation Not Permitted (Dropbox issue?)

### ISSUE THREAD

**Issue by mlavio829** [ChurchApps/FreeShow#766]
Hi,
I had a problem where I was using Dropbox but something got messed up. 
I removed Dropbox, and uninstalled FreeShow. After reinstalling FreeShow (Windows) I get this error: 

<img width="377" alt="Screenshot 2024-08-17 at 8 25 47 PM" src="https://github.com/user-attachments/assets/e956613b-4d27-4c6a-b698-9b3e5553b349">

Where are the preferences being saved in Windows on FreeShow? 
I tried removing the AppData\Local\Programs\FreeShow and reinstalling but it still gave the error.
I was able to get create a new Windows User Account, reinstall under that account and it worked successfully on the new user but the one I was using before still doesn't. This leads me to believe there is a preference that it is remembering somewhere. What do I need to delete to get it working under the original Windows User account?

**Comment by vassbo** [comment]
The settings should be in `%AppData/freeshow`, but you can check the "Data location" in settings>"Other" and see where that's pointed, also make sure "Save user settings at 'Data location'" is turned off if you don't need it.
