### ISSUE TITLE
[Feature Request] In Triggers need to Button style.

### ISSUE THREAD

**Issue by TPaulManohar** [ChurchApps/FreeShow#770]
In Triggers Tabs, Instead of tile style need button style must more handy to click to operate that which we are clicking. 

And need some animation that we clicked.

![Triggers-1](https://github.com/user-attachments/assets/8733db1e-c07f-4ae9-951e-5eb20521d826)

I hope this improvement can add in next release.

Thanks,
Paul.

**Comment by TPaulManohar** [comment]
@vassbo Thanks for added Button style to triggers. Can you enhance visualization more for this feature.

**Comment by vassbo** [comment]
I think the visuals are nice, what specifically are you thinking about?

**Comment by TPaulManohar** [comment]
@vassbo Specifically, What I'm looking is how the Bitfoucs Companion buttons looks like. Edge of buttons needed to smooth(rounded edges).

And one more is not to display the Value of that trigger. When we click Edit option then only it should show the value of that button.

Most of the UI need to be rounded edge then it can look more beautifully. Please imagine from your side as well.
![Renewed_Vision_ProPresenter7](https://github.com/user-attachments/assets/bf736ed3-00ac-40d7-b04b-7ca2bdcf417f)

I hope this will  implement.

Thanks,
Paul.

**Comment by vassbo** [comment]
Please change the theme to set border radius in the app (I will add it to the triggers): 
![bilde](https://github.com/user-attachments/assets/9c505593-d8de-453d-b802-9634d830c8c7)

Also showing the info could be nice, but I can remove that.

**Comment by TPaulManohar** [comment]
Hi @vassbo ,

I found that "Border radius" in the theme. It looks good to me.

Please add the same thing to the triggers as well.

**Comment by TPaulManohar** [comment]
@vassbo ,

I used the Border Radius as "15" In windows title bar also reflect with same border radius. I think Title Bar and Title Bar button should be like as normal. 

In Triggers When buttons increased it not showing the button names even we scroll up. Please have a look.
![Freeshow trigger1](https://github.com/user-attachments/assets/e67f7372-99f1-4563-b3d2-ed8cd1670605)
![Freeshow trigger2](https://github.com/user-attachments/assets/213a61ef-634a-4820-bd84-6180481fe229)


Please have a look fix this.

Thanks,
Paul.

**Comment by vassbo** [comment]
@TPaulManohar I can fix this.
