### ISSUE TITLE
[Bug Report] {Moving Slides arround}

### ISSUE THREAD

**Issue by LevinsJacobs** [ChurchApps/FreeShow#771]
**Describe the bug**
When I drag and drop slides, it works fine. However, when I try to move those slides around, the entire application crashes. Also the slides don't rearrange. 

**Reproducing**
Open FreeShow.
Drag and drop slides into the workspace.
Attempt to move the slides within the workspace.
Observe that the software crashes and fails to move correct slides when rearranging.

**Version (Optional)**
 - OS: MacOS 14.5
 - FreeShow Version: v.1.2.4
 
**Additional context**
The issue occurs specifically when rearranging slides after dragging and dropping them into the workspace.

**Comment by vassbo** [comment]
Please try this in pre-release 1.2.5, and let me know if it is better here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.5
