### ISSUE TITLE
Proxy Server 

### ISSUE THREAD

**Issue by KelvNganga** [ChurchApps/FreeShow#772]
I kindly request the ability to enable proxy settings for users connected to the internet through a proxy server. Some features, like online song lyrics and Bible search, cannot work unless the proxy settings are enabled. Once this feature is put into consideration and implemented, it should be set in such a way that users can manually set the proxy server or automatically detect system settings.

**Comment by vassbo** [comment]
Closing as this can be done on a system level.

Also if you need to control FreeShow using WebSocket/REST API you can do that by enabling it in the "Connection" settings!
