### ISSUE TITLE
[Bug Report] YouTube Video Embed doesn't work on FreeShow 1.1.4

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#774]
**Describe the bug**
Every time you try to embed a YouTube video in the Media/Online/Add button, you get a "No Video ID" error. I've tried just the video ID, and I've tried Vimeo as well. Something just isn't working.

**Reproducing**
Go to the media tab in the FreeShow drawer, and select "Online," then try to add a YouTube video from a link.

**Version (Optional)**
 - OS: MacOS Sonoma 14.4.1
 - FreeShow Version 1.1.4

**Comment by thebiblelover7** [comment]
Can you try it on v1.2.4?

**Comment by vassbo** [comment]
Have you done it like this, it works fine for me with both the ID and the entire path!:
![bilde](https://github.com/user-attachments/assets/1b968b2a-7a16-455a-bca3-a61c44b9d541)
