### ISSUE TITLE
[Feature Request] CCLI Auto Reporting integration

### ISSUE THREAD

**Issue by snowcondor** [ChurchApps/FreeShow#776]
It would be good to integrate the new CCLI auto-reporting.

It appears that as of around August 2024, CCLI are working directly with developers in bringing this feature to as many presentation platforms as possible. Here's the promotion page. https://au.ccli.com/auto-reporting/ Are we able to contact CCLI to start this process?
It is a big selling point for some churches. This is one feature that I've looked for myself as we find it inconvenient to report our song usage. Hopefully this can be incorporated.

**Comment by vassbo** [comment]
Apparently this was an old API, and we got the same response as here: https://github.com/ChurchApps/FreeShow/issues/572#issuecomment-2163179642

Apparently they might have bought [Presenter](https://www.worshiptools.com/en-us/presenter), and want to stop newer presentation softwares from benefitting from SongSelect/CCLI integration, to gain more users and revenue by the looks of it.

**Comment by snowcondor** [comment]
Thanks for your response @vassbo. Please forgive my little rant. 😄 It seems very strange to me that it's no longer available as their website has a big banner at the top of it that says "NEW! Auto-reporting is here." Has this banner been there for a while? The auto-reporting page itself has a good handful of other presentation solutions indicated on it too. It just seems rather counter-intuitive to me that they'd still be promoting it. 

Well, let's hope they come to their senses. 😄 I wonder if it's possible to create a competitive alternative to CCLI to support all the programs they are abandoning. 😜

**Comment by vassbo** [comment]
Yeah, no worries! It has probably been there for a while. I think they will update it now as we mentioned it.

Someone's gotta make a better solution available for everyone!

**Comment by vassbo** [comment]
Linking this as it can be used for reporting: https://github.com/ChurchApps/FreeShow/issues/883
