### ISSUE TITLE
[Bug Report] Bold Letters not showing up or colors

### ISSUE THREAD

**Issue by MonteC24** [ChurchApps/FreeShow#780]
Each time we select bold, italic or underline and save and then fresh it doesn't update to the live screen or even try changing color it shows in the show tab but not on the screen.

**Reproducing**
add new slide, textbox, type whatever and then try to use bold or different color

**Version (Optional)**
 - FreeShow Version: [e.g. 1.2.4]

**Additional context**
help please
![Screenshot 2024-08-25 122042](https://github.com/user-attachments/assets/ed2964d7-cd81-4198-b58d-b7a3e5eb1af1)

**Comment by vassbo** [comment]
I'm guessing you have set a custom output style with a template, please check that in the "Styles" settings.
![bilde](https://github.com/user-attachments/assets/19e815ea-e762-499f-80e6-374d4b5b6abc)
