### ISSUE TITLE
Is it possible to add the orientation in which a transition is executed?

### ISSUE THREAD

**Issue by odlarhg** [ChurchApps/FreeShow#781]
It's a great feature to be able to add transitions to text and media. Is it possible to add the orientation in which a transition should enter or exit?

For example, the SLIDE transition could run from right to left, from left to right, from top to bottom, or vice versa. I know that not all transitions can have this type of feature, but for those that can, it would be useful to be able to configure this feature.

**Comment by vassbo** [comment]
Should be doable. I want to rework the way transitions work very soon.
