### ISSUE TITLE
[Feature Request] Books name - french language

### ISSUE THREAD

**Issue by Mattcod3** [ChurchApps/FreeShow#783]
Hiiiii,

I have imported a French Bible XML file, but even though the app is set to French in the settings, the book names still appear in English.
It would be great if the book names could be displayed in French and other languages.
It would be even better if people could keep the app language in English and change only the book names to the desired language.

![books language](https://github.com/user-attachments/assets/aa010084-61ab-42e4-a763-2eea8dd1c61a)

Thank you so much for the amazing work you're doing and for creating such an incredible app! I truly appreciate all the effort and dedication you've put into it. Keep up the great work!

**Comment by vassbo** [comment]
Thank you! :) I also responded to your email.

The XML files contains the book names, not the program, so you need to add them here yourself if they are not there.
The books might be stored in English in the file, or they might be missing the name entirely.

To add them edit the XML file, and add a `name=""` attributes to the `book` tags, like this: `<book name="Genesis" ..`.
