### ISSUE TITLE
[Feature Request] Variably Darken Background Beneath Text

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#785]
**Describe the feature**
When adding backgrounds beneath text, often the photos are slightly too bright for the white text I use in my use case. It would be great to have a feature to add a variable overlay above backgrounds. That way you can make the whole image darker (with a black one), or brighter (with a white one). The ability to add these backgrounds hopefully should be really simple to implement, I think.

For future development of this feature, I'd love to have gradient overlays and vignette-style overlays.

I have very little experience with coding, but if I can be of any assistance, please let me know.

**Comment by vassbo** [comment]
Right click the image, press "Edit", choose "Filters" and turn down the brightness!

Or you can set a background filter per slide even if you would like to.

Alternatively you can create an overlay with a semi transparent black textbox filling the entire screen & choose the "Place under slide" option from the context menu.
