### ISSUE TITLE
[Bug Report] Scipture Tab keeps on loading

### ISSUE THREAD

**Issue by dksandimas** [ChurchApps/FreeShow#787]
**Describe the bug**
The scripture tab just keeps on loading until forever

**Reproducing**
Open Freeshow and go to Scripture tab

**Screenshots (Optional)**
<img width="1094" alt="Screenshot 2024-08-29 at 6 22 41 PM" src="https://github.com/user-attachments/assets/c57f6776-1dfe-407b-82b9-65c4d415987d">

**Version (Optional)**
 - OS: macOS Sonoma
 - FreeShow Version:  1.2.5

**Comment by vassbo** [comment]
You probably selected the wrong format when importing, try choosing another format. If none work, please send the file you used so I can check it out: dev@freeshow.app.

**Comment by dksandimas** [comment]
Hi @vassbo , it goes to all the default versions too. Even in the Windows version even if I didn't import any scripture.

**Comment by vassbo** [comment]
The first file in the image is a local file, so the problem here is an error in the file itself.

For the default API Bibles that's a different issue, I see we are getting an error 503 (Service Unavailable), so it might be temporarily down.

**Comment by dksandimas** [comment]
Okay got it. Might need to check the file that I have imported. 
I got the xml file from this page -> https://github.com/Beblia/Holy-Bible-XML-Format/blob/master/EnglishNASBBible.xml

**Comment by vassbo** [comment]
I imported your file, and it worked perfectly. It's Beblia, so you need to choose that option.
