### ISSUE TITLE
Mac OS X v10.11.6 compatibility

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#790]
Is FreeShow v1.2.4 compatible with Mac OS X v10.11.6?
I'm trying to install it onto a (very) old i5 MacBook Pro, but the dmg cannot be mounted.

**Comment by vassbo** [comment]
Unfortunately not, support for macOS 10.11 & 10.12 was dropped in Electron 20, all the FreeShow versions prior to 1.2.5 uses Electron version 21.

**Comment by colanct** [comment]
Thank you.
