### ISSUE TITLE
Allow for song translation

### ISSUE THREAD

**Issue by kbradshaw390** [ChurchApps/FreeShow#793]
I absolutely love this platform. And I love the fact that you can quickly import lyrics from the internet, meaning that the people in your church can simply add to the church planner a link of the exact version of the song from that they want from google and we can paste the lyrics in. I think this is genius.

But sadly there is just one feature that this software is missing from allowing it to replace pro presenter in my church and if you could add this then I would switch in a heartbeat.

The feature that would help us is that we have lots of Ukranians in our church and we like to display two languages alongside each other, for example like this.
![Screenshot 2024-08-31 at 21 34 08](https://github.com/user-attachments/assets/98bf4d64-2391-4749-8d6c-d82b7190af45)

(Also we make sure that these Ukranian lyrics do not show up in the live stream, as this would leave our live stream lower thirds too cluttered)

We simply take our lyrics and put them straight into google translate and then paste them over to pro presenter. The ability to do this ESPECIALLY with your quick and easy method of just pasting lyrics in would work wonders in our church and make our Sunday morning 100x quicker.

Thank you very much,

Keep up the good work

P.S Also love the PDF import!

**Comment by vassbo** [comment]
In the next version FreeShow has integrated Google Translate, with 248 languages to chooes from. Just click one button, select the language, and press "Translate". It will automatically translate the textboxes and add new ones. You can also add multiple languages.

![bilde](https://github.com/user-attachments/assets/66e6d651-63df-4f56-b97a-f0d49fd1fa11)

**Comment by vassbo** [comment]
You can try it out here @kbradshaw390: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.7-beta.1
![bilde](https://github.com/user-attachments/assets/409a0358-3654-4aaf-9031-5b6306bd7121)
