### ISSUE TITLE
[Bug Report] Transparent Images

### ISSUE THREAD

**Issue by SemicolonUnexpected** [ChurchApps/FreeShow#794]
**Description**
Transparent images render incorrectly, not allowing visibility of the background or any other media behind.

**Reproducing**
Create a slide, change the background to something other than black. Place media in the background. The transparent images seem to be broken or unsupported

**Screenshots (Optional)**
![image](https://github.com/user-attachments/assets/9d2a0d63-6d63-43eb-9924-9f4a2aed2794)
![image](https://github.com/user-attachments/assets/ec17c432-d819-4519-a306-e8e31886d369)

**Comment by vassbo** [comment]
The image preview thumbnails are saved as JPG, I guess it makes sense to change this to PNG so it supports transparency.
