### ISSUE TITLE
[Bug Report] Transitions inconsistent to settings

### ISSUE THREAD

**Issue by SemicolonUnexpected** [ChurchApps/FreeShow#795]
**Description**
The transition continues to fade when the background changes, even though it has been set to none

**Reproducing**
Create two slides, with different coloured backgrounds, and place some media in the centre. Change all transitions to "None", including in the media itself, the slides, and in the output section of settings. Switch between slides. The fade animation still plays 

**Screenshots**
A zip file containing a video showcasing the above steps
[Recording 2024-09-01 092711.zip](https://github.com/user-attachments/files/16828054/Recording.2024-09-01.092711.zip)

**Comment by SemicolonUnexpected** [comment]
Just to note, you can get around this at the moment by setting the background to a plain image, however this is not an elegant solution, especially when working with multiple computers and having to transfer media manually for now.

Really appreciate FreeShow. Great work so far!

**Comment by vassbo** [comment]
Thanks, I'll check it out.
