### ISSUE TITLE
[Feature Request] Livestream to outside of obs


### ISSUE THREAD

**Issue by Mitsuolevel** [ChurchApps/FreeShow#797]
.

**Comment by Mitsuolevel** [comment]
It would be really nice to get some kind of stream to youtube/Facebook feature obs and freeshow is really bogging down my small churches PC we use for streaming

**Comment by Mitsuolevel** [comment]
Yea, I'll mess with it next week. It would still be nice to have something in freeshow that can output to youtube or Facebook in software

**Comment by vassbo** [comment]
Looking more into we would need to convert the video stream to H.264 and audio to AAC, then package to FLV that can be sent via RTMP, I don't think it would perform a lot better than just recording and streaming with OBS, and it would make the app size a lot larger. So until streaming platforms like YouTube supports the modern browser standard WebRTC (YouTube do, but only for webcams), I'm gonna close this.
