### ISSUE TITLE
Motions freeze during show execution

### ISSUE THREAD

**Issue by odlarhg** [ChurchApps/FreeShow#798]
Hello

After updating to the latest version (1.2.6), I have problems with slow playback of background videos. Sometimes the execution of the slides freezes completely and freezes the show.  The same thing happened to me in previous versions and you very kindly corrected it, but the problem has reoccurred again.

I appreciate your help

My basic computer configuration

Processor: Core i5 8th generation
RAM:  16 Gb
Video Memory: 4 Gb

**Comment by vassbo** [comment]
Not sure what the problem could be, I did update the Electron/Chromium version.
Is there any difference if you go to settings>"Other" and toggle this?
![bilde](https://github.com/user-attachments/assets/5cdd7bc6-75a8-47ef-b961-85986d9b133c)

**Comment by vassbo** [comment]
Does this happen right away after startup, or does it happen after playing multiple videos?

**Comment by vassbo** [comment]
Is it still as bad in the latest pre-release?: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.7-beta.1
