### ISSUE TITLE
Bugs with NDI output resolution

### ISSUE THREAD

**Issue by Yttrium-tYcLief** [ChurchApps/FreeShow#799]
**Describe the bug**
This is sort of two separate bugs, but they both relate to NDI resolution:

1. **Freeshow does not seem to let you change NDI resolution whatsoever.** No matter what is set in Outputs > NDI > Display mode, a 1920x1080 feed will be sent.
2. **The resolution Freeshow sends NDI feeds at, and composites at, is modified by the Windows display scale.** When the Windows display scale is set to 125%, Freeshow will composite (render) and encode at 2400x1350.

**Version**
 - OS: Windows 10
 - FreeShow Version: 1.2.6

**Additional context**
While NDI Studio Monitor confirms the resolution being sent is 2400x1350, it's important to note this is NOT simply Freeshow compositing a 1080p feed and then getting confused by the Windows display scale, upscaling it by 25%, and then sending that as NDI. It is actually compositing at 2400x1350. I can use a high-resolution image as my entire slide content, capture the NDI feed, and then compare the NDI feed to a 1920x1080 version of the image, scaled bilinearly up to 2400x1350. The resolution difference is pretty obvious.

**Comment by vassbo** [comment]
I actually think this might not be a bug. The "Display mode" I think is related to the Blackmagic being enabled (I guess you have tested that build), so creating a new output should remove the extra settings.

The NDI uses the actual resolution if the output window, so if you click "Choose screen" you can click a window to change the NDI resolution to that window size, or manually setting a resolution here. I guess you should check and update the value if the screen resolution has changed.
