### ISSUE TITLE
Unable to add the new bible from api.bible

### ISSUE THREAD

**Issue by patrick-hui** [ChurchApps/FreeShow#801]
![image](https://github.com/user-attachments/assets/bd216a1c-0427-4278-9e62-facbabc9feb3)

I would like to ask how to add a new bible from API.Bible? I cannot find any place to enter the API code. I am using Fedora 40 and the v1.2.6 Appimage packaging.

**Comment by vassbo** [comment]
The list should load automatically, do you have network connection? Please try again a few times.

**Comment by patrick-hui** [comment]
I am sure that the internet connection is not a problem. I tried different platform (e.g. Win 11, MacOS and Linux) and the result were same (same as the picture attached)

**Comment by vassbo** [comment]
All right, thanks. I managed to figure it out. I recently changed the way the key was stored and I still had it stored in the old way on my PC, that's why it still worked, I never updated the check in the import list, but that's fixed now!

**Comment by vassbo** [comment]
Should work here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.7-beta.1

**Comment by patrick-hui** [comment]
> Should work here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.7-beta.1

Awesome! I can see the list of bibles now. Thank you so much!
