### ISSUE TITLE
[Feature Request] Quality of Life Editing and Workflow

### ISSUE THREAD

**Issue by taavidayo** [ChurchApps/FreeShow#803]
**Describe the feature**
First thank you so much for the development of this app. I'm wanting to switch over from propresenter, but there's a couple quality of life improvements that I've been having a bit of a tough time with.

First is the ability to click multiple items on a show and move them with an arrow key. For example if I have two text elements, I would like the ability to move them together and even snap into positions based off their new center point. Not being able to do this and not being able to adjust them with arrow keys make editing for our slide operators cumbersome. They now have to click through and use the X and Y values to make quick pixel perfect adjustments. There are times when the arrangement is near perfect but just need to make a quick adjustment, and what should take one second now is a lot more clicks.

Second is the ability to see transparency in the preview. I understand it will show in the real show, but again, for the slide operators this has made it difficult when working with multiple PNG elements especially when they are working at home with no second output.

Third is that I think the FreeShow logo is taking up some valuable space for a search feature. I realize that there is the search feature in the bottom but that feature searches a new context given the category that it's in. If we could get a dedicated hot key for being able to look up just shows would be helpful in a spontaneous environment.

Thank you again. Really excited about the potential for this app and hoping to make the switch officially soon!

**Comment by thebiblelover7** [comment]
I absolutely agree with all these ideas! The first one is also a very important one for us.

Maybe this issue should be split into three different issues....

**Comment by vassbo** [comment]
I'll definetly improve on the first one.

The second one has been fixed with this issue: https://github.com/ChurchApps/FreeShow/issues/794

Fro the third one I guess a "Quick search" - simular to CMD+Space on mac would do the trick, I guess it could be used for many things. We probably don't need a UI element for it but maybe clicking the logo could bring that up?!

**Comment by TPaulManohar** [comment]
Yes, absolutely first one should be improved. It save lot of time.
