### ISSUE TITLE
[Feature Request] Improvements in workflow Features 

### ISSUE THREAD

**Issue by TPaulManohar** [ChurchApps/FreeShow#804]
1. In Scripture Tab needed Mouse right button option as: Add to Project
When we select bunch of bible verses then we can right click on mouse there should be option called "Add to project". Instead going to bottom conner clicking "New Show"

2. Export Items - > Options Needed for Template, Overlays, Actions, Triggers, Variables.
Export Items-> In my sense when we need to export entire freeshow project(Shows, Templates, Overlays, Actions, Triggers, Variables)to backup computer that can help very handy. Instead of going to template and export particular template, overlay. Here there is no option to export for Functions.
when exporting from File -> Export-> there it need to shows option to select what they need to export.
<img width="1440" alt="Freeshow Export" src="https://github.com/user-attachments/assets/5c431191-3309-4ee1-bcaa-63d076e277b1">

3. Collection of Bible-> Search option needs to works
After created collections of bible, search option is not working, but in single bible search option is working(Exodus 1:1-5)

4. Edit Tabs -> For Fonts Search option need to search the fonts.
In Edit tab, When we need to change particular fonts which we like, there needed find option for particular font. Right now we are scrolling as alphabetical order. 

Thanks,
Paul.

**Comment by vassbo** [comment]
I'll see about number 1, maybe just add "New show" into a context menu here.

If you want to make a full backup you can go to settings>Other>Backup. The exporting is used to export shows in various formats. I'll see if this can be changed in a way.

I can fix nr. 3 & possibly add nr. 4.

**Comment by vassbo** [comment]
I'm not able to recreate the collection search not working, works fine in my tests. What scriptures are you using?

**Comment by TPaulManohar** [comment]
I used collection zefania XML and NKJ which is preloaded with Freeshow.

**Comment by vassbo** [comment]
@TPaulManohar You should probably only create a collection with just API Bibles or just local Bibles, I think I will prevent creation of both as it is some extra work to maintain.

**Comment by TPaulManohar** [comment]
@vassbo Actually, The Bible which we use XML local bible that was Zefania Standards Format Bible which we imported.

**Comment by TPaulManohar** [comment]
@vassbo  Thanks for taking our request, I'm so happy that you fixed as soon as possible. It can improve Freeshow App more and more

**Comment by vassbo** [comment]
You can try it here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.7-beta.1
Try creating a collection with e.g. two Zefania Bibles, or at least two XML Bibles instead of the one from Bible.API, that should work.

**Comment by TPaulManohar** [comment]
@vassbo , I will check and let you know.
