### ISSUE TITLE
[Bug Report] Cannot Import PDF Files

### ISSUE THREAD

**Issue by Acetoua** [ChurchApps/FreeShow#808]
I cannot import pdf files. It just add the title and not upload any of the pictures.

1st I edit on my powerpoint then save it via pdf, then I import it but it doesn't push through. It just create a show with nothing on it.

**Screenshots (Optional)**
![image_2024-09-08_124634087](https://github.com/user-attachments/assets/53a15b8d-8ffa-4e1a-82aa-ac5e742f935d)

**Version (Optional)**
 - OS: Windows
 - FreeShow Version: 1.2.6

**Additional context**
What I do in the meantime is I lower my version to 1.2.4 then import pdf. Then after it is imported I update the version to 1.2.6 and you can see on the picture these are the icons. The one with the pdf icon on it has no pictures.
![image](https://github.com/user-attachments/assets/b0b2102a-b307-4c52-9d01-83db44272a37)

**Comment by Acetoua** [comment]
![image](https://github.com/user-attachments/assets/f2808ffd-42e0-4105-b6c1-7f341b7fe808)
Here you can see what I import on the 1.2.4 version

**Comment by joelgraff** [comment]
+ 1 for this.  I just get an empty screen when doing PDF drag / drop.  Drag/drop on pptx files just leaves me with a "loading" message (sorry, I know that's a separate issue).  I'm running 27.1 beta 1, Win10.

**Comment by MrDogeBro** [comment]
I also am experiencing the same problem with v1.2.6. I tried to bring in a PDF export of a Google Slides presentation earlier today and it created a show with nothing in it. Even when I clicked the convert to images button, it said converting, but it didn't work and did nothing.

**Comment by vassbo** [comment]
All the PDFs I have tested currently works fine, can someone please send over a PDF file that's not working here: dev@freeshow.app, so I can find the issue?

As for the PPTX, I need more info (requested here: https://github.com/ChurchApps/FreeShow/issues/491#issuecomment-2337190664)

**Comment by vassbo** [comment]
I actually found the issue, newly added items did not have the path to the file, only previously added items.

**Comment by Acetoua** [comment]
It works now! Thank you so much!
