### ISSUE TITLE
[Feature Request] {Ndi,hx camera feed input desktop ndi }

### ISSUE THREAD

**Issue by jabeztechs** [ChurchApps/FreeShow#809]
[Feature Request] {Ndi,hx camera feed input desktop ndi  capture input, vmix output to freeshow,Bible show ndi to freeshow,and we'll done on the output ndi love the update it keep growing,

**Comment by vassbo** [comment]
Thanks! Go to "Media">"Screens">"NDI"! Does this work?

**Comment by jabeztechs** [comment]
Once in church will check ,in drawer right most time I cheek camera,would like it as ndi source or something in that line

**Comment by vassbo** [comment]
Okay, did you get them to show up in another supported program?

I can't do that, but you should be able to find the ones you need in XML!

**Comment by jabeztechs** [comment]
> Thanks! Go to "Media">"Screens">"NDI"! Does this work?

I see it but crash on version 1.2.7-beta.2 freeapp will just close up
