### ISSUE TITLE
Verse numbers option overrides the automatic grow-to-fit Bible text adjustment

### ISSUE THREAD

**Issue by Ichthys88** [ChurchApps/FreeShow#813]
**The option to display verse numbers overrides the automatic grow-to-fit Bible text adjustment**

When I use the "grow to fit" option in the scripture templates to fit the Bible text and turn on verse numbers, the entire Bible text fits to the verse number size ignoring the auto-size setting set in the template.

**Image 1: Presenting the Bible verses without the verse numbers**
![FreeShow1](https://github.com/user-attachments/assets/b9bd0b9f-4485-4bcc-b597-b065e6b296af)

**Image 2: Presenting the Bible verses with verse numbers**
![FreeShow2](https://github.com/user-attachments/assets/52f43ee1-50ea-430a-862d-b240cab7b3bd)

 - OS: Fedora Linux 40 (KDE Plasma) x86_64
 - FreeShow Version: v1.2.6 and v1.2.7-beta.1

If this bug can be corrected and add an option to make the verse number automatically adjust to the parameters in the scripture template, that would be helpful.

**Comment by vassbo** [comment]
Thanks, I managed fixed this.
If auto size is enabled, the verse size will act as a percentage, meaning a size of 50 will be 50% of the actual text.
