### ISSUE TITLE
Can't edit transition method

### ISSUE THREAD

**Issue by Akoli1** [ChurchApps/FreeShow#815]
I am unable to edit the transition methods, both text and media. They're set to fade by default and it's really inconveniencing me as I experience delays, more so the media. When I want to change theme between verses in a song, it delays and really sucks. I think they should be set to default 'None' because as it is, when I try to click other options, it doesn't respond and save

**Comment by vassbo** [comment]
This is where you change the global transition:
![bilde](https://github.com/user-attachments/assets/849db8bf-c31d-4ca0-8b24-27830147db23)

I see that you tried changing it in "Styles", which can be changed for each output! That works after you change at least one other value, but I'll fix the bug you encountered so you can set it here by default as well!
