### ISSUE TITLE
[Feature Request] Add support for images and text on stage layouts

### ISSUE THREAD

**Issue by thebiblelover7** [ChurchApps/FreeShow#817]
**Describe the feature**
It would be really nice to be able to add labels and images to the stage layouts. Having basically all of the options for normal slides available would be really neat

Currently, you are only able to add components such as current slide text, current output, next slide, etc. No static ones as far as I can tell.

**Comment by vassbo** [comment]
You can do this!

Firstly by using variables for easy output of custom text.
Secondly you can basically use any item like "Media" and select a specific output for it to only show up in "Stage" (and use "Current output" in stage).

**Comment by thebiblelover7** [comment]
But what if I don't want to make variables for the text, as it doesn't have to change? It would make it so much simpler if I could just add a text box to the stage layout

**Comment by vassbo** [comment]
What would be the use case for this? A variable is like a custom textbox, not a lot of extra steps.

**Comment by thebiblelover7** [comment]
For us, we use it for labels for what the stage components are. They are completely static. We label if there is a timer on the screen, or if the current time is shown, so that we do not have to explain to our presenters what each item on the stage screen means.

**Comment by vassbo** [comment]
In that case just use the built in "Labels" made for that!
![bilde](https://github.com/user-attachments/assets/c080ee6b-e028-4050-8c35-e617dfff7876)

**Comment by thebiblelover7** [comment]
@vassbo But then you can't customize it at all, not to change the name, or font-size or color or anything....

I honestly think that this issue/enhancement is a lot bigger than just being able to add images and text to stage layouts. The stage editor has sadly lagged behind the normal slide editor, which is a bit annoying. For example, there are no auto-size options (like "shrink-to-fit", etc.), the labels differ from the slide editor to the stage editor. It would be really nice if we could use practically the same editor for both. I don't see any reason for us not to be able to add images, text or set options like auto-size on a stage layout.

**Comment by vassbo** [comment]
I can probably add an option to change the label color.

For the stage editor I have tried adding the options that would be needed. You would definetly not need all of the normal "Items". As for the auto size I guess the point of the stage display is for the text to be big so the people at the stage can see it, so would there be a need for "Shrink to fit"??

You mentioned the editors should be the same, but that can't work as the stage has elements like "Current slide text", "Current slide", "Next slide", "Current output", etc. that would not be needed normally, and as I mentioned the stage does not need all the normal items.

Currently all stage items can only be added once as they are only needed once, I think this is an easy way to toggle on/off stage elements. But if textboxes/images should work they would need to be different, as they should be added multiple times.

But this is my thoughts at the moment, hope it made sense, if you can think of a good way to make the stage work more like the normal editor let me know.

**Comment by vassbo** [comment]
I see that the "Text" section in the stage textbox tools could need an update at the moment.

**Comment by thebiblelover7** [comment]
It would be nice to just be able to use a normal slide editor. Then you add a new option to stage text boxes that allows you to make it fill the text with a variable, e.g., "Current Slide Text", "Next Slide Text", etc.
The same principle could be used for images: create a rectangle on a stage layout and then set the *fill* to be "Current Slide" or "Next Slide", etc.

Hopefully that idea makes sense. It is basically the same idea that ProPresenter uses for its stage layouts. That way, you can have more customizability while not really compromising its usability.

**Comment by vassbo** [comment]
This should come in 1.4.0!

**Comment by thebiblelover7** [comment]
Let's goo!! I'm excited!
