### ISSUE TITLE
Output Zoom

### ISSUE THREAD

**Issue by Blackio123** [ChurchApps/FreeShow#820]
Will it be possible to make the PDF pic Larger or smaller so that way when I'm presenting a pdf book and the text is too small i can just enlarge it?

**Comment by vassbo** [comment]
Next update you can zoom in the "Draw" page:
![bilde](https://github.com/user-attachments/assets/fc18082f-559f-4e92-9c93-ca3c26abffe8)

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.8-beta.1
