### ISSUE TITLE
[Bug Report] Startup and Save Command Performance Issues

### ISSUE THREAD

**Issue by johnjairus10** [ChurchApps/FreeShow#822]
**Describe the bug**
The application experiences significant performance issues both during startup and when executing the save command.

1. **Startup:** The app takes an unusually long time to open. The delay is noticeable and affects the overall user experience, causing frustration.
2. **Save Command:** The save operation is extremely slow. It can cause the program to hang or become unresponsive, rendering it unusable for extended periods.

**Version (Optional)**
 - OS: Windows 10 22H2
 - FreeShow Version: v1.2.7

**Additional context**
- We have been encountering this issue for some time, and it persists even after updating to the latest version.

**Comment by vassbo** [comment]
Hi, in my testing the startup & save is just a few seconds, but I guess that you might have a lot of shows/data. Can you go to settings>"Other">"Backup everything", and send the files to dev@freeshow.app so I can see what can be improved? :)

**Comment by johnjairus10** [comment]
Hi! Unfortunately, we couldn't back up everything as the app became unusable, requiring us to uninstall and reinstall it to restore functionality.

After the reinstall, it appears the immediate issues have been resolved. However, I’ve sent you the files from the app data folder that I managed to copy before uninstalling, which may assist in debugging the original issues.

Additionally, I’ve included the problematic show file that caused the program to hang #823.

Many thanks!

**Comment by vassbo** [comment]
@johnjairus10 Got the email yesterday, but you need to allow read access to the attached drive files.

**Comment by vassbo** [comment]
Probably related to this: https://github.com/ChurchApps/FreeShow/issues/823

**Comment by vassbo** [comment]
The main problem here was the history.json log file storing some edits from the problematic show, causing it to exceed 280 MB. I will implement a check to prevent this as well.
