### ISSUE TITLE
[Bug Report] Application Hangs When Presenting a Certain Show

### ISSUE THREAD

**Issue by johnjairus10** [ChurchApps/FreeShow#823]
**Describe the bug**
The application hangs when attempting to present a specific show. This issue necessitates forcefully exiting the program and prevents presenting of the slide.

- The problematic show file has grown to approximately 80MB in size, which is significantly larger than usual.
- It appears that previous edits are being saved into this file, leading to its large size.
- The hanging issue only occurs when presenting this particular show.

**Version (Optional)**
 - OS: Windows 10 22H2
 - FreeShow Version: v1.2.7

**Additional context**
- We were able to temporarily resolve the issue by deleting the problematic show and its file, and creating a new show from scratch.
- Please investigate if the feature storing previous edits is causing this issue and if it can be disabled or optimized.
- Clarification on whether storing previous edits is intended behavior would be appreciated.

**Comment by vassbo** [comment]
This is not related to previous edits, but if you are able to send over one problematic file as well I want to check out why it's so slow! (https://github.com/ChurchApps/FreeShow/issues/822#issuecomment-2352065717)
