### ISSUE TITLE
[Bug Report]  "Split in two" does not split scripture text

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#825]
**_Split in two_** on scripture slides creates a new slide, but does not split the text.  The metadata text box is copied, but scripture text box is blank on new slide.  
The _Split in two_ feature functions correctly in songs.

 - OS: Windows 10
 - FreeShow Version: 1.2.7

**Comment by vassbo** [comment]
You can turn on "Verses on individual lines" for it to work, but I'll see if I can improve this! :)

**Comment by mwb9aa** [comment]
@vassbo 
I know you closed this, but I still see the same behavior with version 1.2.9. Split in two works for songs, but not for scriptures. I have used 1.2.7, 1.2.8, 1.2.9 Beta, and the release version of 1.2.9. They all had the same behavior to original poster listed.

I did uninstall each version before installing the new one.
I also removed my config folder before installing FreeShow 1.2.9, and all my settings were gone (as expected), but my configured outputs were the same. I suspect there are some app settings somewhere else, but I can't find them.

I am running Windows 11.

I cannot find a setting "Verses on individual lines". I did try Output->Styles->Lines->1. Nothing seemed to change. (The output screen flashes, but displays the same thing as before.)

**Comment by vassbo** [comment]
@mwb9aa You are probably not referring to this fixed issue!
![bilde](https://github.com/user-attachments/assets/7133c9f2-ee02-4f28-b720-748744b27969)

If you select at least two scripture verses you will get that option on the right side:
![bilde](https://github.com/user-attachments/assets/007ce564-68b9-42c6-bd2f-90ef9b5e5a0c)

Scriptures from the drawer uses these settings and does not work with the "Lines" style setting, but you can click "New show" to convert to a show that works. (If you have "Verses on individual lines" on)
