### ISSUE TITLE
[Bug Report] Scripture slide text and metadata content swap positions when clicking Apply to All after editing an Item.

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#826]
When clicking on _Apply to all_, after editing a scripture slide Item (like backdrop filter), the change is made, but the scripture text and metadata positions are swapped.  Clicking on _Apply to all_ for a second time restores the fields to their correct positions.

 - OS: Win 10
 - FreeShow Version: 1.2.7

**Comment by colanct** [comment]
Similar behaviour of cycling the position of scripture text and metadata between the two text boxes on the slide occurs when clicking on a scripture template in the Templates drawer when a scripture show has focus.

**For example:** 

- A Scripture show is created using the _Scripture_ template (2 text boxes).
- New scripture has focus.
- Click on same Scripture template in Templates drawer.
- Scripture text and metadata text positions are swapped.
- Clicking again on the template swaps them again.
- For templates with more text boxes, the rotation includes all text boxes.

**Comment by vassbo** [comment]
@colanct Will fix the first bug. Second statement is a feature, not a bug!

**Comment by colanct** [comment]
Thank you.

Regarding the feature to cycle text content position from the Templates drawer: 
it would be more intuitive and less confusing if the text position did not change on the first click of an alternative template (or when reapplying a previously disconnected template to a show).  So, first click would simply change the template.  Subsequent clicks would cycle the text position. 

It's not a significant problem once a user is aware of the feature, but is otherwise quite confusing.

**Comment by vassbo** [comment]
Makes sense. Haven't though about that!
