### ISSUE TITLE
Have you considered a version of FreeForm to use on the iPad?

### ISSUE THREAD

**Issue by odlarhg** [ChurchApps/FreeShow#828]
Hi,

I have used my iPad to remotely control presentations in FreeShow, but I would really like to have an iPad version.  I think it would be very useful for us to be able to control all the functions of FreeShow from an iPad.

Regards,

**Comment by vassbo** [comment]
Maybe a web version at some point that can be used on tablets as well, but not an iPad version unfortunately.
