### ISSUE TITLE
[Bug Report] Cannot Create Folders in Media or Audio in 1.2.7

### ISSUE THREAD

**Issue by Chiller-74** [ChurchApps/FreeShow#829]
**Describe the bug**
When trying to link a new folder to either the media tray or audio tray nothing happens. However, when rolling back to 1.2.6 it works as expected.

**Reproducing**
attempt to create a new folder in the media tray or audio tray while running 1.2.7.

**Version**
 - OS: Windows
 - FreeShow Version: 1.2.7

**Comment by vassbo** [comment]
I'll fix this, but you can bypass the issue at the moment with drag/drop from the file exporer!
