### ISSUE TITLE
[Bug Report] {"Unnamed" on delete}

### ISSUE THREAD

**Issue by SemicolonUnexpected** [ChurchApps/FreeShow#832]
https://github.com/user-attachments/assets/66b1776b-c72f-43ab-bf1e-364b1f84f9bf

**Describe the bug**
When you delete a show from the projects section, it leaves an "Unnamed" show as an artefact.

**Expected behaviour**
The show completely vanishes from all projects in which it originally was

**Comment by vassbo** [comment]
I can probably update this behaviour, but this was done so you could undo the deletion of the show without losing the reference in the project. And also if I remove it I should only remove it on the active project, and not any other projects!
