### ISSUE TITLE
How to import icon SVGs

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#833]
Is there a trick to import icon SVGs?
When I click _Import SVG from clipboard_, nothing happens, despite the SVG being on the clipboard.

**Comment by vassbo** [comment]
If you have an SVG file you need to copy the text content, not the file.
Just tested it seems to work, if you still can't get it please send your clipboard.

**Comment by vassbo** [comment]
Great! The custom icons can be found & added via the "Edit" tab:
![bilde](https://github.com/user-attachments/assets/99a9633e-1a82-4acb-8e7a-87850d38fa33)

They are not added to the category selection if that's where you tried as I don't think they are needed there.

**Comment by colanct** [comment]
Aah, thank you; I now see what the issue is.  
I wasn't aware that there are slide item icons.  Those are successfully added and edited as you describe above.
The issue is that there seems to be no way to select an added icon for categories in drawer category panels, after selecting Change icon.
![image](https://github.com/user-attachments/assets/4d4c25a9-bcdc-4973-9f2f-95abb0d1f3d2)

This is a luxury feature that may not be worth spending time on, if it's not a quick fix.  If it's not simple, perhaps the Manage icons button at the bottom of the Icon selection pane could be hidden when invoked from the drawer.
