### ISSUE TITLE
[Feature Request] Cloud sync improvements

### ISSUE THREAD

**Issue by gkiibzmultimedia** [ChurchApps/FreeShow#834]
The cloud sync is working fine, but when there are multiple users working in freeshow, the last one close the app will replace the files in the cloud causing the works from the previous users to be gone.

Is it possible to append the files instead of replacing them when freeshow synching to the cloud?

What is "Media path ID" for in the Cloud setting page?

**Comment by vassbo** [comment]
This is true, but only for changed projects etc. not shows as they are updated by the latest version. The way this works at the moment makes it hard to do as we would need a timestamp tracker on each element. But if you only experienced this issue with projects I might be able to do something about it?

If the "Media path ID" is set to the same on two computers that means the exact media paths are the same (e.g. if an external drive is used), but in most cases they are different that way the different paths will be auto located and stored at the media path location for the current computer.

**Comment by chanx** [comment]
yes, maybe the project settings need improvement, cannot store in one json file. perhaps save to data folder with separate file for separate project? so if one not edit the same project file at least they won't get error. just suggestion.

**Comment by jerm00** [comment]
I was thinking about this the other day, what about a cloud sync using a traditional sync app (I use Nextcloud self host, but google drive, Dropbox, onedrive and etc) so that it monitors changes for you? You wouldn’t need to implement the change monitoring and file locking part at least.

**Comment by vassbo** [comment]
@jerm00 That works for mediam and would work for shows, but the projects etc. are stored in one file, so it won't help on that issue.

**Comment by gkiibzmultimedia** [comment]
> This is true, but only for changed projects etc. not shows as they are updated by the latest version. The way this works at the moment makes it hard to do as we would need a timestamp tracker on each element. But if you only experienced this issue with projects I might be able to do something about it?
> 
> If the "Media path ID" is set to the same on two computers that means the exact media paths are the same (e.g. if an external drive is used), but in most cases they are different that way the different paths will be auto located and stored at the media path location for the current computer.

yes, only with projects.
