### ISSUE TITLE
[Bug Report] Cannot add a folder to drawer

### ISSUE THREAD

**Issue by M-Ryba** [ChurchApps/FreeShow#839]
In the most recent version (1.2.7) when trying to add a folder nothing happens after selecting it with the file explorer window. It works with the version i used before (1.1.6).

**Reproducing**
1. Open the drawer
2. select eg. Multimedia tab
3. click New folder
4. Select the folder
5. _**Folder is not added**_

**Version**
 - OS: Windows
 - FreeShow Version: 1.2.7

**Comment by vassbo** [comment]
There is a workaround: https://github.com/ChurchApps/FreeShow/issues/829#issuecomment-2352078556
