### ISSUE TITLE
[Bug Report] Google Slides generated PDF not working with FreeShow

### ISSUE THREAD

**Issue by OrangeCoding2021** [ChurchApps/FreeShow#840]
Upon downloading slides as a pdf from Google Slides and opening them in FreeShow, the program freezes. Buttons change as you hover over them but are not working.

 - OS: Windows 10
 - FreeShow Version: 1.2.7

Potential workaround:
Downloading as powerpoint from slides. Opening in Powerpoint. Then saving as a PDF creates a pdf file that FreeShow reads fine at first

**Comment by OrangeCoding2021** [comment]
Found the log file. This is the error
"version": "1.2.7",
			"active": {
				"window": "main",
				"page": "show",
				"show": {
					"id":pdf location,
					"type": "pdf",
					"index": 4,
					"data": {
						"viewports": [
*Null repeated for length of pdf*						]
					}
				},
				"edit": {
					"type": "show",
					"slide": 0,
					"items": [],
					"showId": "pdf location"
				}
			},
			"drawer": {
				"active": "media"
			},
			"type": "unhandledrejection",
			"source": "See stack",
			"message": "Cannot read properties of undefined (reading 'width')",
			"stack": "TypeError: Cannot read properties of undefined (reading 'width')\n    at Object.c (file:///C:/AppData/Local/Programs/freeshow/resources/app.asar/public/build/bundle.js:19:1534487)\n    at Object.c (file:///C://AppData/Local/Programs/freeshow/resources/app.asar/public/build/bundle.js:19:1534975)\n    at Object.p (file:///C://AppData/Local/Programs/freeshow/resources/app.asar/public/build/bundle.js:19:1537110)\n    at ze (file:///C://AppData/Local/Programs/freeshow/resources/app.asar/public/build/bundle.js:1:6547)\n    at Ee (file:///C://AppData/Local/Programs/freeshow/resources/app.asar/public/build/bundle.js:1:6182)"
		}
	]

**Comment by vassbo** [comment]
Thank you. I managed to fix this!
