### ISSUE TITLE
[Bug Report] New folder not added to the list in Media and Audio tabs

### ISSUE THREAD

**Issue by groaking** [ChurchApps/FreeShow#841]
**Describe the bug**
Clicking the "New folder" button in Media and Audio tabs opens a folder selection dialog. However, upon selecting a folder and closing the dialog, the selected folder does not get added to the list of folders to be scanned in the Media and Audio tabs.

Surprisingly, dragging a folder from the file explorer directly into the folder list successfully adds the folder to the list.

**Reproducing**
1. Go to "Media" or "Audio" tab
2. Click the "New folder" button at the lower left corner
3. Create a new folder or select any existing folder
4. Click "Open" in the folder selection dialog
5. The dialog gets closed, but the list does not display the folder that is just selected

**Screenshots (Optional)**
Not applicable.

**Version (Optional)**
 - OS: Windows and Linux
 - FreeShow Version: 1.2.7

**Additional context**
Not applicable.

**Comment by vassbo** [comment]
There is a workaround: https://github.com/ChurchApps/FreeShow/issues/829#issuecomment-2352078556
