### ISSUE TITLE
Scripture search prefix

### ISSUE THREAD

**Issue by odion-cloud** [ChurchApps/FreeShow#843]
**Prefix for scripture search**
I love this software the best ever created for presentation, please can we get prefix of scripture easy search like the one on easy worship, makes it easy and fast to search scripture.

**Comment by chanx** [comment]
i think freeshow already has this feature, just enter the first few letters of the bible book name, and it will be autocompleted.

**Comment by mwb9aa** [comment]
It does. From the documentation:

[Search](https://freeshow.app/docs/scripture)

Start searching (CTRL/CMD + F) to quickly select any verse in the bible, it will auto complete the book name. Can be like this: "John 1:1-4", or like this: "Genesis 1:1-2+5", then press ENTER to show in output.
