### ISSUE TITLE
[Bug Report] Media Drawer Loading Slow

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#848]
**Describe the bug**
Since, i think, Version 1.2.6-Beta or 1.2.6 the media drawer has been loading super slow, to the point where it just freezes up the program and all the thumbnails have the little loading icon. 1.2.8-beta so far has been the worst at it.

I don't know if I have to many Video Backgrounds or what, but it used to not be a problem. If I open task manager, I can see that it is using almost 2.5 GB of memory and increasing. Does this across three separate devices all varying in performance.

**Reproducing**
Not really sure how to reproduce this, other than try having a folder with a lot of media in it. 

**Version (Optional)**
 - OS: Windows 10 & 11
 - FreeShow Version: [1.2.8-Beta]

**Additional context**
Not sure if it makes a difference or not, but I have about 16 folders of motion backgrounds totaling about 15 GB.

**Comment by vassbo** [comment]
I found a bug related to the folder preview, that probably is related. But I'll also try to optimize this further.

**Comment by vassbo** [comment]
How is it here?`: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.8-beta.2

**Comment by Bagel94** [comment]
This seems much better!

My desktop loads the previews fairly fast, though my laptop is slower on the load, but that's to be expected since it's not as powerful as the desktop.
