### ISSUE TITLE
[Bug Report] Freeshow goes over the maximum lines in formatting section.

### ISSUE THREAD

**Issue by UserDefaul** [ChurchApps/FreeShow#849]
**Describe the bug**
Sometimes, depending on the song I will get more lines than the limit I put. I set the limit to two lines, but I have gotten up to 5 lines on a slide.

**Reproducing**
OS: Windows 11
Version: v1.2.8-beta.1

Create a new show, name it Oceans, and select the auto-searched lyrics for Oceans (Where feet may fall) Then make sure formatting is turned on and set it to 2 lines per slide. You will see that almost every slide has more than two lines.
**Screenshots (Optional)**

https://github.com/user-attachments/assets/71ced59b-199c-4996-8323-6e5e95d42561

**Comment by vassbo** [comment]
The lines count for "line break"/"enter", not line wrapping if one line is very long, make sure this is not the case?!

**Comment by vassbo** [comment]
Looks like it's working as expected. You can turn on "Text on one line" to prevent the auto wrapping:
![bilde](https://github.com/user-attachments/assets/b59c14e3-c2f0-490d-9a97-18e1d36ee0ac)

This should work well with auto size.
