### ISSUE TITLE
[Feature Request] more text animations

### ISSUE THREAD

**Issue by gkiibzmultimedia** [ChurchApps/FreeShow#850]
are there other text animations (not transitions) besides scrolling and size change in freeshow?

**Comment by vassbo** [comment]
What do you have in mind?

**Comment by gkiibzmultimedia** [comment]
> What do you have in mind?

I am just checking if there are another already available besides those two.

anyway, I found it is more convenient to create the lyrics animation in other platform such as Canva and save it as video with plain black background.
but, I can't still work out how to filter that black background in freeshow properly.
I have tried with css mix-blend-mode: color-dodge;, it is working but the edges of the letters doesn't seem sharp enough.
can you advise how to do it properly please?

**Comment by vassbo** [comment]
Okay, there are not many text animations at the moment, if I were to add more, I need to know what should be added.
Doing it in Canva is a good solution.

FreeShow does not offer video greenscreen tools, so the best you can do is CSS mix I guess, or a transparent GIF.

**Comment by gkiibzmultimedia** [comment]
which CSS mix should work for greenscreen?
can freeshow render transparent video?

**Comment by gkiibzmultimedia** [comment]
right now, I use CSS mix-blend-mode: screen; to remove the black background.

**Comment by vassbo** [comment]
If the video is encoded in HEVC (H265) with support for transparency, it should work.

If not, the trick you used about CSS mix-blend-mode propably the best you can do with a non transparent video.
