### ISSUE TITLE
[Feature Request] Require confirmation before activating Stop Presentation.

### ISSUE THREAD

**Issue by jquyatt** [ChurchApps/FreeShow#851]
**Describe the feature**
Right now, the Start/Stop Presentation button is right next to the Settings button up top. This makes it easy to accidentally stop the presentation while in the middle of a show. 

**Proposed UI change**
When user clicks the Start/Stop Presentation button, a small tab drops down below the button that can confirm the action before initiating.

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.8-beta.2

**Comment by jquyatt** [comment]
Thanks so much for including this! I think the current interaction is a little confusing without any descriptive indicators near the button, only the notification at the bottom right of the screen saying "Click again to confirm". Here's my proposal:

When the “Stop Presentation” button is clicked, a small drawer or panel pulls out directly below it, asking the user “Are you sure?” with Yes (Red) or No (Neutral) options. This keeps the interaction contained within the button area and also decreases the likelihood of an accidental double-click in the same spot.

**Comment by vassbo** [comment]
No problem. :)

I get it, but I think people understand how it works after a couple of uses. The thing is in the cases people need to hide the output window quickly (to give another window focus) especially in tense moments, I actually think a dropdown with two options will be more confusing in some cases.

If a user accidentally double clicks I don't think it's a big of a deal as the button can just be clicked again to display the window.
