### ISSUE TITLE
[Bug Report] Unable to batch import .pro (ProPresenter 7) files

### ISSUE THREAD

**Issue by leonwcl95** [ChurchApps/FreeShow#852]
**Describe the bug**
Whenever I tried importing batches of .pro files, it will show up an importing with correct icon to click on but never actually imported anything into my Shows. I can import 1 by 1 files but nothing more than 5 in my case. Error shown in screenshot below.

**Reproducing**
CTRL+i / Files>Import, Select ProPresenter & Select more a batch of .pro files.

**Screenshots (Optional)**
![Screenshot 2024-09-26 145829](https://github.com/user-attachments/assets/39931b35-f56f-4a18-823a-81325ee08213)
Once I click the button, it would appeared nothing was imported.

**Version (Optional)**
 - OS: Windows 11
 - FreeShow Version: [1.2.7]

**Additional context**

**Comment by vassbo** [comment]
I'm guessing it's a few of your .pro files with issues. Can you please send the files to dev@freeshow.app so I can fix it? :)

**Comment by leonwcl95** [comment]
sure, I will send the .probundle since it's probably easier. :)

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.8-beta.2
