### ISSUE TITLE
Add an option to place the Bible quote and Bible version below the Bible text in stage mode

### ISSUE THREAD

**Issue by Ichthys88** [ChurchApps/FreeShow#855]
Add an option to place the verse reference and verse version below the Bible text in stage mode without having to go to the "Combine with text" option in the scripture menu

I've been testing FreeShow and found an important feature that should be included in the stage mode, which is the ability to place the verse reference and version below the scripture text, without needing to go through the Scripture menu by activating the "Combine with text" option, thus altering the layout of the scripture projection.

Image 1: Shows the default way Freeshow displays the biblical text in stage mode
![Image 1](https://github.com/user-attachments/assets/96fa8a8e-0969-4e58-933d-4070ba4a0d47)

Image 2: Shows the way I found to place the quote and the version below the biblical text, but it alters the layout in the projection of the biblical text (This is by going to the "Combine with text" option in the Scripture menu).
![Image 2](https://github.com/user-attachments/assets/bf214d0a-e1f7-4a7e-aa97-850c499ff0d1)

If you add an extra option on the "current slide text" element that does that or if you add an option to add the scripture text and the scripture reference in a separate textbox's, as well as in the scripture templates, that would be very helpful.

**Comment by mwb9aa** [comment]
+1 I would like it also. This is one of the things that prevents me from switching to FreeShow. There may be a couple of others, and I will open a report for each of them, after I verify it is not my installation. (I think I installed the program while several other programs were also running and had control of monitors.)

**Comment by vassbo** [comment]
I think this should do (comming next version):
![bilde](https://github.com/user-attachments/assets/d6b893d6-b2d7-4149-b79b-62fb08ebcc88)
