### ISSUE TITLE
Is it possible to draw boxes and other geometric figures in presentations?

### ISSUE THREAD

**Issue by odlarhg** [ChurchApps/FreeShow#858]
Is it possible to draw boxes and other geometric figures in presentations?

I want to add boxes to portions of text within the slides of a presentation. Is it possible to do so? Something similar to what can be done in a PowerPoint presentation. If it is possible, how can I do it? If Freeshow does not have this function at the moment, is it possible for you to add it?

thank you

Aldo

**Comment by vassbo** [comment]
You can add icons in the "Items" tab:
![bilde](https://github.com/user-attachments/assets/40db7cdd-372f-4f9c-a4d6-7b9c9520dbd6)

If you need just a rectangle or a circle you can also use a normal textbox and set a background color & border radius.
