### ISSUE TITLE
[Bug Report] Excessive CPU  usage

### ISSUE THREAD

**Issue by becerrapedro4** [ChurchApps/FreeShow#860]
**Describe the bug**
When I opened the program, the CPU usage shot up to 100%

**Reproducing**
just openning and using freeshow with no lirycs, programs or anything else setted up.

I have an all in one computer.
with an intel core i3 10th gen processor
8gb ram

**Version**
 - OS: Windows 10
 - FreeShow Version: 1.2.7

**Additional context**
When running the program I heard my PC fan running faster, which led me to see what was causing this abnormal behavior.

**Screenshots**
![Sin título2](https://github.com/user-attachments/assets/ea58f7cd-b4ce-4357-bfd5-060d4fb86cbb)
![Sin título](https://github.com/user-attachments/assets/1c173f1a-e6e7-494e-98dd-2dbae17cd353)

**Comment by vassbo** [comment]
Please check the CPU usage in the latest version an let me know if it's better: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.8-beta.2

**Comment by NikolasGregor** [comment]
make sure you have hardware acceleration disabled in freeshow settings because i had the same problem with a very powerful computer
