### ISSUE TITLE
Overlays no longer editable on MacOS 15

### ISSUE THREAD

**Issue by KaterTom80** [ChurchApps/FreeShow#861]
Hi There,
i updated to MacOs15 - now, if try to edit my overlays, nothing happens, when i click on edit. 
Version of FreeShow is 1.2.7
Any idea?

**Comment by vassbo** [comment]
Try right clicking the overlay with ctrl+trackpad, and then click "Edit".
Something is wrong with the two finger trackpad click on mac if that's what you where using!?

**Comment by KaterTom80** [comment]
Yes, i use the trackpad with two finger click. 
Thank you, ctrl+trackpad works. 

I think this is a problem by macos sequoia. So i open a bug request at apple. Thank you so much for freeshow - a awesome software.
