### ISSUE TITLE
[Bug Report] Advance slide timer not operating

### ISSUE THREAD

**Issue by insprittian** [ChurchApps/FreeShow#862]
Hello from New Zealand! 

Great work on FreeShow, it has some great features out of the box. I am attempting to set it up to replace our current presentation software, but I'm having one main issue as detailed below.  

I've attempted to follow the documentation and select the clock icon and set a next slide timer, but after I apply to all and select the first slide, it doesn't progress to the next one and there is no progress bar underneath the clear functions like I see on the tutorial video. 

Have tried with images and standard text slides, select clock icon, set a duration and select apply to all. Select the first slide and it isn't progressing to the next.

Can add a video of the issue tomorrow.

 - OS: Windows 10
 - FreeShow Version:1.2.8-beta.2

Went to the beta to resolve the issue with importing PDF's showing up as blank.

**Comment by vassbo** [comment]
Thanks. A video could be nice. I can't recreate the issue, works fine in my testing.

You can also try right clicking a slide and setting "Slide actions">"Next slide timer" does that work?
You should see a clock icon with the duration at the top left on the slide if it works.

Holding down the ALT key will prevent any timer/background from playing, make sure this is not your issue.

**Comment by insprittian** [comment]
Hi @vassbo,

Video [here](https://drive.google.com/file/d/1mnRKQ3nT-OoaO8BhiUvBbDZYQm8okjOC/view?usp=drivesdk), hopefully it is of some use. 

Tried the next slide timer and had the same result. The clock icons are where they should be, but the slides never proceeds to the next. 

Ensured the alt button wasn't engaged also. 

Obviously I'm the only one with this issue, so must be something funny with our setup, but strange that it's the only feature that isn't working as expected.

**Comment by vassbo** [comment]
Thanks, I see the issue, you have two Stage outputs!
The "Audience" output should be a normal output, as next slide timer only work when played on a normal output.
