### ISSUE TITLE
[Bug Report] Virus Scanner detecting a virus in latest download for Windows: FreeShow-1.2.8-x64.exe

### ISSUE THREAD

**Issue by greggbhill64** [ChurchApps/FreeShow#865]
**Describe the bug**
Virus Scanner detecting a virus in latest download for Windows: FreeShow-1.2.8-x64.exe

**Reproducing**
download. try to install...

**Screenshots (Optional)**
![image](https://github.com/user-attachments/assets/0c9dfd24-e865-46a4-8f0a-3038f5ae0db3)

**Version (Optional)**
 - OS: Windows 10
 - FreeShow Version: 1.2.8

**Additional context**

**Comment by NikolasGregor** [comment]
False alarm

**Comment by NikolasGregor** [comment]
try with malwarebytes I think is false alarm

**Comment by vassbo** [comment]
I'm pretty sure it's the PowerPoint controller cousing the false alarm, as it needs to spawn system shell and execute commands. But as long as you make sure to download from the official website or here from GitHub you are good!
