### ISSUE TITLE
Quick Start Guide does not display text in light themes

### ISSUE THREAD

**Issue by Ichthys88** [ChurchApps/FreeShow#866]
While I was testing Freeshow, I found that when I put the light theme and started the quick start guide, it did not show me the text...

https://github.com/user-attachments/assets/6662e0a1-ba6f-466d-a66c-aa5d162baa7f

As I see, the color of the boxes that are in the background of the guide text do not adapt when the text color is black, it would be convenient for these boxes to follow the secondary color of the theme (in this case pink), in order to avoid these visual inconveniences.

**Version:**
 - OS: Fedora Linux 40 kde 
 - FreeShow Version: 1.2.8 AppImage x86_64

**Comment by vassbo** [comment]
Just set the text to always white for the guide: https://github.com/ChurchApps/FreeShow/releases/tag/v1.2.9-beta.1
