### ISSUE TITLE
Changes in Slide designs

### ISSUE THREAD

**Issue by Anuser28** [ChurchApps/FreeShow#867]
Issue is I have edited the slides in the edit tab, implementing text and various images through media but when switching to the show tab the designs of the slides completely change and then it is a struggle to go back to get the originally designed slides

https://github.com/user-attachments/assets/f47f0f58-db2e-4bc7-a35a-36a5dc623352

**Comment by vassbo** [comment]
You have set a template on the show, meaning the show will update with the template style.
To set a custom layout make sure you have removed the template by opening the "Templates" drawer tab, and clicking this button:
![bilde](https://github.com/user-attachments/assets/014c3f3e-8e3d-42c7-8969-6f4336ad2891)

**Comment by vassbo** [comment]
Also make sure there is no slide templates:
![bilde](https://github.com/user-attachments/assets/80ef397a-6401-4180-859c-909374afcb3a)
