### ISSUE TITLE
[Bug Report] NDI Output transparent background for Lower Thirds Lyrics

### ISSUE THREAD

**Issue by wwcfshj** [ChurchApps/FreeShow#870]
Does freeshow allow transparent background for song lyrics for NDI output to OBS?

I have enabled the NDI option and Enable Transparency in the settings, but after receiving the feed from my OBS laptop, it still has the video background. Any steps I'm missing on this?

**Comment by vassbo** [comment]
What OS are you on? And how are you receiving the NDI content with OBS?

**Comment by wwcfshj** [comment]
> What OS are you on? And how are you receiving the NDI content with OBS?

The Freeshow program is running on Windows 11, whilst the OBS is running on Mac OS Sequoia, I am receiving the NDI straight from the Output section of Freeshow where the option to Enable NDI is turned on.

**Comment by vassbo** [comment]
The content should be transparent in that case?!

If you mean you want to hide any videos/images, you can do that by applying a custom output style with the "Background" layer disabled!
![bilde](https://github.com/user-attachments/assets/fb268e26-297f-4d7d-b513-7dccb4219978)

**Comment by gkiibzmultimedia** [comment]
Hi
I have the same issue. The background is not transparent.
I use NDI Webcam to capture the NDI content which is then used as video capture device in OBS.
Please advise.

**Comment by vassbo** [comment]
@gkiibzmultimedia Have you enabled "NDI" and the "Transparent" option in the settings?
If you have you need to receive the signal directly from OBS, you can't go via another capturer.
![Image](https://github.com/user-attachments/assets/2aecc2d2-514c-48f8-b236-4588d13e6d46)

**Comment by gkiibzmultimedia** [comment]
Yes, both are enabled.
How to receive it directly?  There is no NDI source in OBS.

**Comment by gkiibzmultimedia** [comment]
I got it work now for Primary output.
It does not work for Stage output.

**Comment by vassbo** [comment]
@gkiibzmultimedia Nice, I never implemented that for the stage output, but will do that.
