### ISSUE TITLE
[Feature Request] "Audio is starting/ending" action

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#871]
**_Next on media finished_**   is not working for audio but is fine for video.

v1.2.9,beta 1
Win 10

**Comment by vassbo** [comment]
Did you add the audio file to the slide with the "Next on media finished" action?
Works fine in my testing.

**Comment by colanct** [comment]
No; I attached the audio file to a previous slide in the same show.  Several slides are shown after starting the audio.  My intention is to show the last slide until the audio ends (assuming similar logic to an active timer).  

_Next on media finished_ is functioning correctly when applied to the same slide that starts the audio.

As _Next on media finished_ was unsuccessful, I tried a custom action, but found there is no _Custom activation_ for audio ending, like there is for video and timer ( _I thought I'd seen it there before - maybe until the _Next on media finished_ was introduced_).

Thank you.
