### ISSUE TITLE
[Bug Report] My screen is blank

### ISSUE THREAD

**Issue by LouangeRevelation** [ChurchApps/FreeShow#872]
**Describe the bug**
My screen remains blank despite all the updates I've downloaded.

**Reproducing**
Freeshow had previously frozen, and I used Ctrl+Alt+Del.

**Screenshots (Optional)**
See the screenshot attached.

**Version (Optional)**
 - OS: Windows
 - FreeShow Version: 1.2.8

**Additional context**
I've already followed these steps https://github.com/ChurchApps/FreeShow/issues/731.

![Capture d'écran 2024-10-05 221834](https://github.com/user-attachments/assets/ee247906-e7f0-44d1-8186-686feffefd22)
![Capture d'écran 2024-10-05 222052](https://github.com/user-attachments/assets/6b425e34-c0d2-4cbb-bc03-0d5a53e71dd2)

**Comment by vassbo** [comment]
Thanks. Please navigate to `%AppData%/freeshow` and send the `error_log.json` file. :)

**Comment by LouangeRevelation** [comment]
Hi,

Thank you for your reply,

Please, find attached the file requested.

Thank you in advance for your help,

Kind regards.

Gaëlle

**Comment by vassbo** [comment]
You can't attach files in the GitHub email directly. But you can send to dev@freeshow.app

**Comment by LouangeRevelation** [comment]
Ok, here's the file 
[error_log.json](https://github.com/user-attachments/files/17364586/error_log.json)

**Comment by vassbo** [comment]
Do you still have this issue in this version?: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.1

**Comment by LouangeRevelation** [comment]
The issue is solved, thank you very much! :)))
What should I do if the software freezes again? 
Also, I've noticed that updates are done automatically on Mac but on PC I have to download the new versions each time; is this normal?

**Comment by vassbo** [comment]
Awesome! The same issue should not come back, but if something similar happens please let me know with a new issue here on GitHub. :)

I'm pretty sure you need to right click and install as administrator for the auto updates to work on Windows!
