### ISSUE TITLE
[Bug Report] Media (Video) cuts off when tweaking a slide while it is playing on loop

### ISSUE THREAD

**Issue by PettyRJ** [ChurchApps/FreeShow#873]
**Describe the bug**
When a video media file is playing on loop, the video abruptly ends due to the following things involving slides: putting up, adjusting, editing, taking down, and transitioning between slides

**Reproducing**
1. Playing a video media on the loop feature (especially videos over 30 seconds)
2. Putting on a slide to overlay on that of the video media, treating the media as a background for the playing slide.
3. Adjust, Edit, Take Down, and/or Transition between slides; this will eventually end the video with the looping feature still on

**Version (Optional)**
 - OS: [MacOS (M1 Pro Chip)]
 - FreeShow Version: [e.g. 1.2.8 and Before]

**Comment by vassbo** [comment]
Thanks. I can't reproduce with the steps you provided, are you able to send a screen recording of the issue?
