### ISSUE TITLE
[Bug Report] Images in the template should not Redraw with every slide

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#880]
See video bellow.
I'm trying to put a logo on the top right of the screen, but the logo is redrawn with every slide transition.( See the video GIF bellow)

![ezgif-4-9206ed6ce5](https://github.com/user-attachments/assets/dd532802-180e-4272-b373-d8b32ca617f2)

Another bug that can be seen on this same video:
The auto-scale of the font should not be visible on the slide show. Currently, the text spawns with a size then resizes after a split second.

**Comment by vassbo** [comment]
This is more of a limit to the way transitions work, but you can right click the image item and set the transition to "None" to resolve this issue. Changing the transition duration should also help with the auto size issue.

**Comment by vassbo** [comment]
I found & fixed the auto size issue. Only happened when using a custom scripture template in the output style.
