### ISSUE TITLE
[Bug Report] Media still shows on output, despite template not having the media

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#881]
I have set a template for a separate output, which will be a lower third in OBS. The template and the output work fine, but even though the template doesn't include the logo on the top-right, it is still seen on the OBS output:

![image](https://github.com/user-attachments/assets/d1c309c6-49cb-45ba-a68c-78e21da20101)

**Comment by vassbo** [comment]
The templates will not remove any items, just add new ones & re-style them. To fix this you should have the show template without media item and set the "Primary" output to use the "Scripture" template!

Alternatively you can create an overlay that you lock to the output, or apply the overlay to the "OBS Scripture" template & remove the overlay layer in the "OBS" output style!

**Comment by yurividal** [comment]
Thanks, right clicking the image, and selecting "Specific Outputs" and selecting the Primary one.
