### ISSUE TITLE
[Bug Report] Inconsistent application of theme

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#884]
Hi again, and sorry for reporting so many issues in the last 24 hours. I'm still learning the software, and I am quite excited about all the features, and want to help it keep improving. 
I'm not sure if this is a bug, or intended behavior. Fell free to ignore me if i'm being a pain.

I noticed that when I apply a theme to a scripture, if i click the theme again, it inverts the position of the text with the refference. (See video bellow). Is this intended? If so, is there a way to lock a certain text box to always show the text, and one to always show the refference?

Also, notice how the refference in slides 2 and 3 doesn't get resized, where the one on the first slide does. I believe this one is definetly non-intentional.

https://github.com/user-attachments/assets/50ced6b2-c541-4589-81c6-097a36280122

**Comment by vassbo** [comment]
No problem! This is intentional behaviour: https://github.com/ChurchApps/FreeShow/issues/741#issuecomment-2287946556

**Comment by yurividal** [comment]
Thanks. 
Perhaps having a way to lock this would be nice. I'm thinking that it can be quite confusing for someone with less experience with the software.
Also, any considerations on this part?

> Also, notice how the refference in slides 2 and 3 doesn't get resized, where the one on the first slide does. I believe this one is definetly non-intentional.

**Comment by vassbo** [comment]
I'll see.. What about changing it to only shift around the items when the "shift" key is held down?

Probably related to this: https://github.com/ChurchApps/FreeShow/issues/878
