### ISSUE TITLE
[Bug Report] Searching Scripture Returns No Results

### ISSUE THREAD

**Issue by jzongker** [ChurchApps/FreeShow#887]
**Describe the bug**
Searching for any text within scripture always returns no results

**Reproducing**
- Click on the Bible drawer
- Click the search icon
- Enter a keyword
- Press enter

**Screenshots (Optional)**
https://github.com/user-attachments/assets/cf6b54cd-bcc7-4be9-86cc-71562c6ac565

**Version (Optional)**
 - OS: Windows 10
 - 1.2.9

**Comment by vassbo** [comment]
Thanks! Probably related to the API, local bibles work fine at least. (And the normal book/chapter search)
