### ISSUE TITLE
The "Grow to fit" option for the Scripture quote in Scripture templates does not work

### ISSUE THREAD

**Issue by Ichthys88** [ChurchApps/FreeShow#888]
When I go to edit a Scripture template, activate "Auto size" and choose the "Grow to fit" option for the "Meta" box (where the Scripture quote and the Bible version appear), the font size is set to 800 and does not fit to the margin of the box...

https://github.com/user-attachments/assets/94198193-508a-4eae-bb16-0746feb177f8

If you could fix this bug, that would be helpful.

**Version (Optional)**
 - OS: Fedora 40 kde 
 - FreeShow Version: 1.2.8, 129-beta.1 & 1.2.9 (Appimage)

**Comment by vassbo** [comment]
I think this should have been fixed in 1.2.9 but another issue caused it to not show up at all in my testing.
I fixed it for the next version! :)

**Comment by vassbo** [comment]
Should work better here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.1
