### ISSUE TITLE
[Bug Report] The Import function from PPTX files in FreeShow misorders the slides upon import.

### ISSUE THREAD

**Issue by AnPhan90** [ChurchApps/FreeShow#890]
The Import function from PPTX files seems to have an issue; the slides, after being imported into FreeShow, are not arranged in the same order as in the original PPTX file.

File/Import/Choose Powerpoint file

**Screenshots**
<img width="1119" alt="Screenshot 2024-10-11 at 22 53 41" src="https://github.com/user-attachments/assets/2e08a472-20c6-4b06-886a-e251bff6d911">
<img width="1393" alt="Screenshot 2024-10-11 at 22 54 42" src="https://github.com/user-attachments/assets/a4a48345-3375-453d-abf5-8a36e723f92a">

**Version**
 - OS: MacOS
 - FreeShow Version: 1.2.9

**Comment by vassbo** [comment]
Thanks. Can you send an example of a .pptx file that's not working to dev@freeshow.app?

**Comment by AnPhan90** [comment]
Here is the .pptx file I used. The Windows version has the same bug as the macOS version.

[TrinhChieuCoDoc-2410288204004193.pptx](https://github.com/user-attachments/files/17364791/TrinhChieuCoDoc-2410288204004193.pptx)

**Comment by vassbo** [comment]
Should work here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.1
