### ISSUE TITLE
[Feature Request] {Pop Up Output Window}

### ISSUE THREAD

**Issue by Kernowa** [ChurchApps/FreeShow#891]
Could there be an option to have a separate native output window for the output. I know there are the connection options over the LAN but it would be good to have a pop up window that is running native on the operating system for performance reasons. This could be an option on the outputs tab called 'Display in Window'

**Comment by vassbo** [comment]
The default output window is a native OS window?!
Settings>"Outputs">"Add"

Not sure I get what you mean, but hope this helps.

**Comment by Kernowa** [comment]
Thanks. Spotted it. On a side note the software is really slow and choppy despite using a pretty powerful Windows computer. Is there a solution to this?

**Comment by vassbo** [comment]
Great! Please check this out to make sure you do not have capture enabled that can slow down things: https://github.com/ChurchApps/FreeShow/issues/708#issuecomment-2260626296
