### ISSUE TITLE
[Bug Report] Merge/Split bible verses breaks template

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#892]
When there is a verse that is too short, sometimes it makes sense to merge it with the previous or next vserse.
Currently, trying to merge 2 verse slides breaks template completely:

![image](https://github.com/user-attachments/assets/161e4088-1998-478a-ae58-99b461147a9f)

![image](https://github.com/user-attachments/assets/43a6a082-72a5-46f8-aa22-e67c97ce0c0e)

Similartly, when there is a bible verse that is too long for a single slide, sometimes it makes sense to split it into 2 slides.
Trying to split a big verse into 2 slides doesn't currently work for bible verses. It simply replicates the slide.

**Comment by vassbo** [comment]
This was caused by the media item, but I found the issue:
`a.type || "text" === "text"` should have been `(a.type` || "text") === "text"` to only get text items! 😅

**Comment by yurividal** [comment]
@vassbo
FYI, splitting works fine in songs (it's usually split half-half), but splitting a Bible verse, currently only spawns a blank slide after the original slide.

**Comment by yurividal** [comment]
@vassbo 

FYI, splitting still doesn't work as expected, if you have selected "1 verse per slide"

![image](https://github.com/user-attachments/assets/5d1289e2-3b45-42ea-86c5-57b36c900cf1)


Before split:
![image](https://github.com/user-attachments/assets/74f9376b-e104-4f53-8cf4-056a7409bc84)


After right-click -> format -> split in two:
![image](https://github.com/user-attachments/assets/b65e069e-af8e-4b64-9069-8468c418c823)


The verse number goes to one slide, the entire text goes to another.

**Comment by vassbo** [comment]
@yurividal That's expected, it has to be split by the "text" difference when all the text is on one line (To split two verses correctly).

You can turn off the verse numbers to get it correct, but I don't think people split just one verse in two.

And if you want to, you should use ALT+ENTER to split it where you want to anyway.

Hope this makes sense!

**Comment by yurividal** [comment]
Perfect. Makes sense.
