### ISSUE TITLE
[Bug Report] {Text/Media layer malfunctions}

### ISSUE THREAD

**Issue by Idrisate** [ChurchApps/FreeShow#893]
Fail to play video/text template .
also texts layers and overlay malfunctions/mis calculate positions when editing after it's applied to a slide .
Text does not change colour/background after it is duplicate from a particular slide or template.
--Window 11 OS--

**Comment by vassbo** [comment]
Please provide some screenshots/more context as I'm unable to understand/locate the issue.

**Comment by Idrisate** [comment]
> Fail to play video/text template . also texts layers and overlay malfunctions/mis calculate positions when editing after it's applied to a slide . Text does not change colour/background after it is duplicate from a particular slide or template. --Window 11 OS--

Video explanation file is 12mb and upload accept only 10mb max so I sent it on mega link https://mega.nz/file/5kJ0wQ5B#O-mO70fp8ACo73X-Doz_V0GEOBHOLvDeOWeJys2T1ZQ

_ Also I like to ask for an option for NDI inputs 
_Also improve the icon box since shapes can't be stretch to fill/fit 
_Additional option to Add a visibility option just like ProPresenter for slide action ;time to show/time to hide ....when a slide/video/etc is triggered to hide-this-and-show- automatically see pic.
![Slide_1](https://github.com/user-attachments/assets/26563272-fdc4-4778-9521-c110c258c45a)
![Slide_2](https://github.com/user-attachments/assets/eac24896-a817-4be6-bbcc-60fadfaa1249)
![Slide_3](https://github.com/user-attachments/assets/d7751bc3-2c99-43d0-9a4f-2f163ab61e47)
![Slide_4](https://github.com/user-attachments/assets/6acd15fc-6831-43d7-be84-49a66ca6da79)
![Slide_5](https://github.com/user-attachments/assets/bd538cf4-1fdd-4ff8-951a-5a6600fd0afd)
![Slide_6](https://github.com/user-attachments/assets/b5412581-5478-41bf-8c31-3cfe84b80e00)
![Slide_7](https://github.com/user-attachments/assets/6ec72821-0867-44c1-8002-4e7a4f4923bd)
![Slide_8](https://github.com/user-attachments/assets/945ed67a-9ee0-4065-8b6a-eed2f5279bf9)
![Slide_9](https://github.com/user-attachments/assets/d1ffc9e3-bea8-4b02-85b5-0a85823e2fa5)
![Slide_10](https://github.com/user-attachments/assets/aad801b4-a3e3-4cf4-a731-d1f010051ad0)
![Slide_11](https://github.com/user-attachments/assets/c962c262-a383-4976-b884-53cf55654b30)
![Slide_12](https://github.com/user-attachments/assets/5fe46cff-2505-42fa-8e4f-03b1fe8f8e85)
![Slide_13](https://github.com/user-attachments/assets/190b52e4-a04e-4f46-93e5-2b0209ae6517)
![Slide_14](https://github.com/user-attachments/assets/a9a1f688-433a-4f5a-8fed-3780a32c6eff)
![Slide_15](https://github.com/user-attachments/assets/288d8cb7-d0a1-4bc8-9619-c3dd3f8b8d70)
![Slide_17](https://github.com/user-attachments/assets/8f730909-5d22-4669-87d1-edc254718842)
![Slide_18](https://github.com/user-attachments/assets/77bb9022-cb3f-40df-953f-045961ba705c)
![Slide_19](https://github.com/user-attachments/assets/84b22cd1-b9ac-4348-a07a-0bb97cf39a67)
![Slide_20](https://github.com/user-attachments/assets/16213a85-e31c-427e-88f6-23b08dc31e4d)
![Slide_21](https://github.com/user-attachments/assets/255dd44e-0a35-4bb6-8313-390882de7c88)
![Slide_22](https://github.com/user-attachments/assets/4a6957c1-4d06-405d-b2ae-7460c18d74a5)
![Slide_23](https://github.com/user-attachments/assets/cb5e90ee-06fa-4ffa-8324-67bf4a38aace)
![Slide_24](https://github.com/user-attachments/assets/252667fe-87ef-491d-abc3-a5c3db4a522a)

**Comment by Idrisate** [comment]
> Fail to play video/text template . also texts layers and overlay malfunctions/mis calculate positions when editing after it's applied to a slide . Text does not change colour/background after it is duplicate from a particular slide or template. --Window 11 OS--

https://github.com/user-attachments/assets/def625a4-0ef6-4d16-becb-a88ea5c7d17a

**Comment by vassbo** [comment]
- NDI inputs: Media>Screens>NDI
- If you need a square/circle you can use a normal textbox, and fill it with an "Item" background color!
- Right click the textbox to set show/hide timers, or to choose "Specific outputs". You can also use actions in the drawer for more custom behaviour. Let me know if you need a special action not already there. (In that case please let me know the use case, example: why would you need to show the specific item when a video input is active?)

Thank you for the video.
- First of all you it looks like the issue is related to text "Line" background, and not "Item" background. Could you send me the .show(.json) file of the show with this issue, as I can't recreate it.
- Secondly the media item plays fine, it's only a thumbnail in the preview, but not in the actual output! I'll see if I can change this behaviour.
