### ISSUE TITLE
[Bug Report] Some ProPresenter file can't be uploaded

### ISSUE THREAD

**Issue by Rares006** [ChurchApps/FreeShow#895]
**Describe the bug**
sometimes when I want to import a .pro file, the application cannot import it. This does not happen with every file, but only with some of them

**Reproducing**
I select Import -> ProPresenter -> I select the file and nothing happens

**Comment by vassbo** [comment]
Please send an example file that's not working to dev@freeshow.app and I'll check it out!

**Comment by vassbo** [comment]
Fixed here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.1

**Comment by Rares006** [comment]
Thank you!Pe 17 oct. 2024, la 14:42, Kristoffer Vassbø ***@***.***> a scris:﻿
Fixed here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.1
