### ISSUE TITLE
[Feature Request] Video input

### ISSUE THREAD

**Issue by Rares006** [ChurchApps/FreeShow#896]
**Describe the feature**
I would like to select a webcam to have it like a live background at my presentation

**Comment by Phantom-Matt** [comment]
Hi. Not a developer of the project but I can say that what you are asking is (probably) already implemented.

Just go to the lower dock "**Media**" (or just press Ctrl+2) and click on "**Cameras**". If your PC is connected to a video input device (like a webcam, for example) it will be there.

For example, on my program there is:

![Captura de imagem_20241013_232543](https://github.com/user-attachments/assets/25c03af0-f54c-49e2-8121-37f2e4397016)

I hope it helps.

**Comment by Rares006** [comment]
Thank you!Pe 14 oct. 2024, la 10:10, Kristoffer Vassbø ***@***.***> a scris:﻿
Closed #896 as completed.
