### ISSUE TITLE
[Feature Request] Planning Center

### ISSUE THREAD

**Issue by Rares006** [ChurchApps/FreeShow#897]
**Describe the feature**
If it's posible I like to have an Planning Center integration like on ProPresenter. 

**Additional context**
[https://www.youtube.com/watch?v=u6HLUpSaqZw](url)

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/333#issuecomment-1848955899

**Comment by Rares006** [comment]
Thank you!
