### ISSUE TITLE
[Feature Request] Recently used projects

### ISSUE THREAD

**Issue by Bagel94** [ChurchApps/FreeShow#899]
**Describe the feature**
Currently FreeShow loads the last project that was used locally. Would it be possible to have FreeShow load the most recent project created whether that was created local or was brought in during a sync?

This feature would be tremendously helpful for volunteers that aren't the ones getting things setup and then them having to locate the newest service project.

**Comment by vassbo** [comment]
I see that is could be helpful and this works in cases like this, but what if multiple people are working on different up & comming projects and a different project to the pne you need/last used is active, I guess that would be confusing.

I think I should add list of "last used projects" that opens on startup if more than one project is used within one week!
What do you think?

**Comment by Bagel94** [comment]
That's a far better solution than I had suggested!! I think that would work out well.

**Comment by vassbo** [comment]
Try it out: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.1

**Comment by Bagel94** [comment]
Started trying out the beta. 

Not seeing where the recent projects are. Is it a dropdown list, a folder somewhere, or a popup after syncing? Does the project need to be created within this beta version to show up on another PC with this beta version, or does is matter the version?

Currently my Desktop is on this 1.3.0.beta1and Laptop is on 1.2.9.

**Comment by vassbo** [comment]
When you open a project from this version going forwad the program will store the last used time.
If you open at least two projects, then save & close, then reopen you should see "Recently used" projects on the left side on startup!

**Comment by Bagel94** [comment]
Okay, I'll get my laptop updated and continue testing it out.

Thanks!

**Comment by Bagel94** [comment]
The feature works great! Though was thinking more along the lines of "Recently Created" instead of "Recently Used". That way if projects weren't created locally, you could then see a populated list of things that were created to choose from.

Unless I didn't do something correct. In the current form it does not pick up if something new is created. Only if that show was presented.

Which would mean we would need to create our project, present it and then when you get to say, church, then it would show up. 

Scenario 1, Currently this is how the list works:
1. Create show offsite, say at home.
2. Present the project at.
3. Save and sync.
4. Arrive at church, open and sync
5. List now has the show only because it got presented.

Scenario 2, The thought process is this:
1. Create show off site, say at home. Or onsite the day before (though in this case it should just open the last saved project)
2. Save project and sync.
3. arrive at church, open FreeShow and Sync.
4. List now has all the most recently made projects. Whether it's 1 or 5, however many have been created by other groups.

If you forget to do step 2 of Scenario 1, the list then becomes irrelevant since it won't pull in that show you created. Thus, still making you have to go back through whatever project organization you do to find the most recently created shows.

Now I know it's probably common to present things before actually using them in a service to see if things look how they need to, but I do also know there has been times we've not had to double check how things look thus not presenting until service time. Which often times, leads to just checking out how it looks before service starts and not at home.

**Comment by vassbo** [comment]
The project will be storing the used date when creating it as well so you shouldn't need to present anything, it should show up regardless (but you might have to close/reopen the program again after the projects have been synced for them to show in the list, I'll fix that.)

**Comment by Bagel94** [comment]
Ahh, okay! Didn't notice that since I was just focusing on if it would show up straight from a sync a close.
