### ISSUE TITLE
[Feature Request] Can any one help me to add a Telugu bible into freeshow . There is no xml file for Telugu BSI bible to download and add to freeshow software.please help.

### ISSUE THREAD

**Issue by dinusam111** [ChurchApps/FreeShow#903]
**Describe the feature**
A clear and concise description of what you would like too add/change.
Optionally describe why this feature is needed.

**Additional context**

**Comment by dinusam111** [comment]
please help to add telugu BSI bible into free show

**Comment by vassbo** [comment]
See this: https://freeshow.app/resources#scriptures
