### ISSUE TITLE
[Bug Report] Black screen on MacOS

### ISSUE THREAD

**Issue by RayMac1976** [ChurchApps/FreeShow#906]
Every time i open Freeshow on my MacBook Air M1 it automatically opens to a black screen. Even after i force close it and reopen, same thing happens! help

**Comment by yurividal** [comment]
Its probably set to auto start slide show.
Right click on the blank screen, see if you get an option to close the show.
You can also try to press command + O

The, go to setting, and disable "Activate output screen on startup"

**Comment by RayMac1976** [comment]
the activate output screen on startup is disabled yet its still doing it

**Comment by yurividal** [comment]
Are you able to collect the log file?
Should be in the data folder.
In windows it defaults to "C:\Users\user\Documents\FreeShow", i'm not sure what the location is on macOS

**Comment by vassbo** [comment]
I don't think the error log has any logs of this issue..
@RayMac1976 Did you make any changes to some settings, or did this happen when you installed for the first time?
Sounds a bit similar to this other issue, you can try the fix he got working:
https://github.com/ChurchApps/FreeShow/issues/450#issuecomment-2028477215

**Comment by vassbo** [comment]
Closing until further information/reproducing is provided.
