### ISSUE TITLE
The manual save (Ctrl+S) does not sync to cloud

### ISSUE THREAD

**Issue by gkiibzmultimedia** [ChurchApps/FreeShow#912]
The manual save (Ctrl+S) does not sync to cloud.
When manual save is done right before closing the application, it won't ask the user whether to save the project or not, hence it won't sync to the cloud.

**Comment by vassbo** [comment]
Are you using 1.2.9? It should sync when closing regardless of saving right before or not.

**Comment by gkiibzmultimedia** [comment]
it seems not.
can you make it also sync when it is saved manually please?

**Comment by gkiibzmultimedia** [comment]
yes, 1.2.9

**Comment by vassbo** [comment]
I got it fixed! It worked when closing right after save if the dialog was turned off, but not when the close dialog was enabled!

I can't make it sync when saving every time, because it was like that previously, but that just caused lots of lag in the process and discouraged users to save often.

**Comment by gkiibzmultimedia** [comment]
if the dialog is turned off, it does syncing to the cloud when closed but it never ends

**Comment by gkiibzmultimedia** [comment]
![image](https://github.com/user-attachments/assets/4a9d407c-f935-4379-b371-ee498b2ee735)

**Comment by vassbo** [comment]
Strange.. Can you send over the error log in settings>Other>"Open log file"?
