### ISSUE TITLE
[Bug Report] Reordering songs in a playlist duplicates all songs

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#914]
**Describe the bug**
When dragging a song in a playlist to reorder the sequence, all songs in the playlist are duplicated.

**Version (Optional)**
 - OS: Win10
 - FreeShow Version: 1.2.9

**Comment by vassbo** [comment]
Thanks. Apparently only when dropping outside of the song list, so just make sure to drop it onto a song.

**Comment by colanct** [comment]
Thank you.  Indeed, that is the case.
