### ISSUE TITLE
[Feature Request] Dynamic Value that shows order of slides, and highlights current one

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#915]
Hi again.
I spoke to our music group last night, and one of the features they really like from OpenSong is that we have a small indicator in the bottom of the slide that shows the order of all the slides and highlihts the current one.
This way, they always have a quick refference as to what verse comes next, and when to go to chorus.

This is what it looks like on the bottom of the slide:

![image](https://github.com/user-attachments/assets/2e404b03-53d5-462c-a1a1-c2499c09d6df)

Would be amazing if we could have this in FreeShow, probably implemented as a variable, or dynamic value.

**Comment by vassbo** [comment]
![bilde](https://github.com/user-attachments/assets/ecdb1f23-7e05-44f3-b832-b0af49370717)

**Comment by yurividal** [comment]
Hi @vassbo 

I tried using the % Progress, but it doesn't behave the same way.

First of all, on mine, it always stays as 0/0

But even if it was working fine, wouldn't it just show a number? like, 2/5 , 3/5 etc?

What I am trying to achieve is something more like

V1, Chorus, V2, **Chorus**, V3

Where the current slide is highlited (bold, or underline), and the rest of the slide order is shown.

**Comment by yurividal** [comment]
![image](https://github.com/user-attachments/assets/d7972394-0d82-488b-96b5-296eb1f41e95)

**Comment by vassbo** [comment]
Should probably be used with an overlay. Worked fine in my testing. It will always show the progress of the outputted show.
Let me know if you get it working and why. Maybe if you have multiple outputs that causes issues?

![bilde](https://github.com/user-attachments/assets/d4adc898-276f-4d4e-be4f-e8d9b2a5e51a)

**Comment by yurividal** [comment]
Ye,s it works. I didn't realize there was the option inside the Profress item, to pick type groups.

![image](https://github.com/user-attachments/assets/0480c914-9736-4dea-ab2d-baedc3069b03)


Some minor improvements could be made if you want. The ability to select some tags to be ignored in the list, (like "Tag" and Outro, in my example) would be nice. Also, it seems that when 2 slides have the same group tag, one is shown, then when you go to the second item in the same group, you get a number 2 popup

https://github.com/user-attachments/assets/3f5bf08a-ce73-4386-9811-e26646b60340

**Comment by vassbo** [comment]
I changed it so a number 1 also appears when the first slide in a group with multiple "child" slides is active.

Also you will be able to "hide" slide groups in the progress by disabling the slides in the layout.
So if you have e.g. a "Tag" group you can just disable the slide, and click manually to present.
Or better, do as shown in the image to hide it but not disable keyboard interaction:
![bilde](https://github.com/user-attachments/assets/3fb728c4-9d40-44e5-98b1-fde3000e5df4)

**Comment by yurividal** [comment]
I'm sorry, i don't think i understand what you mean. 
"So if you have e.g. a "Tag" group you can just disable the slide, and click manually to present."

Will the slide still be visible on the screen? The idea is for the slide to be seen in the main screen, but just the actual lyrics slides be listed in the Progress Bar.

**Comment by vassbo** [comment]
A disabled slide works like a normal slide, but the arrow keys will skip it.

What's new is that disabled slides will also now not be visible in the "Progress" list, as you wanted a way to "ignore" groups in the list.

**Comment by yurividal** [comment]
Gotcha... 👍
Why not just add a checkbox here?, something like "Show in progress calculation"

![image](https://github.com/user-attachments/assets/76b0904c-d5c8-47d2-9914-0c1bad62ab01)

**Comment by vassbo** [comment]
Because it won't be used that much, so that would add more confusion as to what that setting does.

**Comment by yurividal** [comment]
I understand that it could cause confusion if put in that global settings.
What about if you put it inside the "% Progress" menu options? Somethig like checkboxes for groups to ignore from the progress calculations?

![image](https://github.com/user-attachments/assets/57f28588-da9b-47a1-8add-8829771173ba)

I'm just trying to think of a more automated and global way of doing it, instead of manually hiding them in every song.

**Comment by vassbo** [comment]
That would not work as these settings are and should be per item, and not globally.
But I'm thinking maybe if the group has a name that starts with **~** e.g. "~Tag", then it should be ignored.

**Comment by yurividal** [comment]
Yeah, that would work! I can easily edit all the tags in all the songs with a script to add the ~

**Comment by yurividal** [comment]
@vassbo did you only apply thr ~ logic to title and outro or to all the groups?
I'm trying to use ~License, but it still shows in the list. 
~Tag and ~Outro seem to be fine! =)

**Comment by vassbo** [comment]
Should work with all groups with "~" at the start, but I can check that out.

**Comment by yurividal** [comment]
You are right. I just had to reimport my song, and the License tag changed to ~License
Perfect, thank you brother

**Comment by yurividal** [comment]
@vassbo I figured out why the L wasn't  hiding for me, but the ~T was.
As you can see in the video bellow, it seems like changing the Value of the "License" group doesn't affect the actual shows, where the T and the C do.
Check out the video bellow. 
I have a T (Title) slide, and a L (License) slide.
I rename both groups to "T Test" and "L Test", when i go back to the show, you can see that the T updated, but the L didn't.


https://github.com/user-attachments/assets/49dc3615-bb09-48c6-a175-ef25cbfd721f

**Comment by vassbo** [comment]
Not sure how you applied the L to that slide, but renaming to the same name does not work. You need to apply the global group (right click>Change group>select the correct group) - it should also be yellow in your case if it's applied correctly.

**Comment by yurividal** [comment]
The L was part of the Opensomg import. I didn't add it manually. It's the license.

**Comment by vassbo** [comment]
Right, that's the reason. It's a custom group not a global group.
The easiest way to change it is to press "Toggle global groups" on the right side, and just drag in your "~License" to the center of the "L" slide! That way it will use the global group.

**Comment by yurividal** [comment]
Ok, that makes sense.
I ended up writing a python script that replaced the string in all .show files

**Comment by yurividal** [comment]
@vassbo 
The implementation of the slide numbers in the %Progress is still a bit confusing. 
Check out this example:

![image](https://github.com/user-attachments/assets/f7d0d935-407f-4790-92c4-e16e82226154)


The show as:
![image](https://github.com/user-attachments/assets/4ea6b7fb-140d-442d-a5fe-5890232f6527)
and 
![image](https://github.com/user-attachments/assets/3c5cb1e6-499e-478d-8638-14018611d65f)

Which makes it look like Verse 11 and then 12.

Suggestions:
1) Consider just the Verse number. In this case, both would show just V1 (Preffered, as its all part of the same VERSE)
2) Add some sort of separator, like a ".", So it would show V1.1 then V1.2

**Comment by vassbo** [comment]
Updates: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.1-beta.1

You can keep "Verse" as the group, but still get your V1 V2 progress if you want.
![bilde](https://github.com/user-attachments/assets/dc41e527-62a5-46f6-a436-48dd6e781e9b)

**Comment by yurividal** [comment]
awesome! Thank you, @vassbo

**Comment by yurividal** [comment]
@vassbo stupid question: where do i find this toggle that you posted on your screenshot?

**Comment by vassbo** [comment]
In the slide progress item editor:
![bilde](https://github.com/user-attachments/assets/b12dac1c-5f6b-4956-8227-a5a0bab766e7)

**Comment by yurividal** [comment]
Thanks. Found it.
By the way, the "sub index" feature seems to be a bif broken. It does it sometimes, sometimes it doesn't.

https://github.com/user-attachments/assets/2f482039-5301-4d02-be1e-98dd4f2bbeb9

On the video, you can see the "intro" sometimes shows .1 sometimes doesn't, even when i go back a slide.
It also doesm't always respect the "one letter mode"

**Comment by vassbo** [comment]
Okay, I think it works fine as long as not both are one at the same time.
You said earlier that you preferred not having the sub indexes anyway so just leave that off.

**Comment by yurividal** [comment]
Yeah, not a specific issue for me. Just thought I'd report it anyway to let you know. Thanks!

**Comment by vassbo** [comment]
Looking into it I could not recreate it, so I guess actually you don't have the same style on all if your "Progress" items! You probably just turned on "One letter mode" on the first slide!
