### ISSUE TITLE
Slide Action/Start action/Change stage layout by ID

### ISSUE THREAD

**Issue by DennisKVBC** [ChurchApps/FreeShow#916]
Having a problem with Slide Action/Start action/Change stage layout by ID.  My stage screen has 2 layouts, songs and sermon. If I go in thru Settings/Outputs/stage TV/Stage layout, I get my 2 choices and when selected, the stage screen works properly.  If I use Slide Action/Start action/Change stage layout by ID, it shows my 2 layouts.  If I select "songs" or "sermon" I get the small icon on the slide (Sermon or Songs).  When I click on that slide, the stage layout does not change.  Using 1.2.9.  Didn't use this feature in previous versions.

**Comment by mwb9aa** [comment]
I noticed the same thing and got it to work by creating an action in the function tab and then dragging that action to the slide.

**Comment by vassbo** [comment]
It works just fine, I think you are mixing two different actions!
- "Change stage layout by ID" will change all stage connections to a specific stage layout (not outputs)!
- "Change stage output layout" will change the stage layout in a specifc stage output!

I removed the first stage layout from the slide actions list to remove confusion, but you will still be able to drag&drop onto a slide as @mwb9aa mentioned!

**Comment by DennisKVBC** [comment]
Thanks.  I'll give it a try when I get to church later today.

Dennis
________________________________

**Comment by DennisKVBC** [comment]
Thanks.  I'll give it a try when I get to church later today.

Dennis

________________________________

**Comment by csafarjr** [comment]
I created actions using the steps above for each stage layout and added them to my slides. But, the action is not updating my stage view (physical output) as it won't change the stage layout I have set in settings > outputs > stage.

**Comment by csafarjr** [comment]
Nevermind, I figured it out. Instead of using change stage layout by id, I needed to use change stage output layout.
