### ISSUE TITLE
[Bug Report] "Remove group" and "Delete slide" sometimes swap functions

### ISSUE THREAD

**Issue by Phantom-Matt** [ChurchApps/FreeShow#917]
In some instances, editing a show or a song bring this weird behavior where clicking on "Remove group" removes only a single slide while clicking on "Delete slide" wipes out an entire group. Honestly, I tried to reproduce the error in a freshly open window, but had no sucess.

At least, I got some footage.
https://github.com/user-attachments/assets/013b7376-32a8-4c4a-87d9-50b82d6bd826

**Version (Optional)**
 - OS: Linux
 - FreeShow Version: 1.2.9 
_(Later, I'll try on 1.3.0-beta.1)_

**Comment by vassbo** [comment]
Looking at the footage this looks like the correct behaviour.

First you pressed "Delete slide", that will delete the slide from the group, as there is only one slide in your "—" group, it will also delete the group.
Secondly you pressed "Remove group", and that will only remove the selected instances of the group from the layout, which in this case was the middle slide.
