### ISSUE TITLE
MIDI Select Project Item by Index and Ableton Live 11

### ISSUE THREAD

**Issue by mwb9aa** [ChurchApps/FreeShow#918]
**Describe the bug**
Ableton Live seems to broadcast a note or message with no velocity. If the Show has an action in the Function tab of Select Project Item by Index with MIDI control selected for that action and velocity set to any value (e.g. 0, 1, 2, etc.), then every time Ableton Live stops, FreeShow navigates to the first item of the Show (index 0).

**Reproducing**
1. Create an action
2. Start Action #1->Select project item by index
    Activate by MIDI Signal->On
    MIDI Input->Name of Midi output such as FreeShowControl
    Velocity->0 (or any number)
3. No other controls seem to make a difference, but they do need to match the output MIDI properties for channel and note
4. Play the MIDI note in Ableton Live, press Stop in Ableton Live

**Screenshots (Optional)**

**Version (Optional)**
 - OS: Windows-latest
 - FreeShow Version: 1.2.9
 - loopMIDI 1.0.16
 - Ableton Live 11 Intro 11.3.35

**Additional context**
I really appreciate the work you are doing. I did look at issue 338 (https://github.com/ChurchApps/FreeShow/issues/338) and 508 (https://github.com/ChurchApps/FreeShow/issues/508). I have tried this on two different Windows 11 machines running the same software and have the same result. Using MidiView, pressing the stop button in Ableton produces the HEX value B0 7B 00, where the digit after B represents the channel (channel 1 is index 0). The velocity is 0 and the message is All notes off Channel _x_.

I think the relative code might be in the export function receiveMIDI(ms) of midi.ts (line 88 at the time of this writing). However, I'm not seeing what code would create the issue unless maybe Ableton sends some non-standard code and the stop command velocity _is_ undefined?

Please let me know what I can do to help you troubleshoot. I believe this is the last piece of the puzzle before my church adopts this software. Thank you for all of your hard work.

**Comment by vassbo** [comment]
Let me know how it behaves here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.2
