### ISSUE TITLE
[Bug Report] Clicking on a song lyrics show slide while a slide with video is playing doesn't stop/clear the video

### ISSUE THREAD

**Issue by vicholz** [ChurchApps/FreeShow#920]
**Describe the bug**
Clicking on a song lyrics show slide while a slide with video is playing doesn't stop/clear the video. The video keeps playing in the background with the song lyrics over it. This happens even if you add an overlay to the song lyrics.

**Reproducing**
1. Create a show with a video slide.
2. Create another show with song lyrics.
3. Add both shows to a project.
4. Click on the slide with the video.
5. Click on the slide with the song lyrics - video continues to play even if song lyrics have and overlay.

**Screenshots (Optional)**

**Version (Optional)**
 - OS: Windows
 - FreeShow Version: 1.2.90

**Comment by vassbo** [comment]
This is intentional. FreeShow uses a layer system:
- Background media
- Slide content (text)
- Overlays
- Audio

So they won't affect each other, unless you use a slide action to clear playing videos!
