### ISSUE TITLE
[Feature Request] Make backspace (or delete) button `Remove` item and shift+delete to `Delete`

### ISSUE THREAD

**Issue by vicholz** [ChurchApps/FreeShow#921]
**Describe the feature**
There is no quick and easy keyboard shortcut to remove shows without deleting them from projects. You can use the `Delete` button but that deletes items completely from FreeShow which I don't think should be the default behavior. It would be great to be able to `Remove` items without deleting them using the `Backspace` button on the keyboard or to change the `Delete` button to remove without deleting, and `Shift+Delete` to actually delete with a confirmation prompt.

**Comment by vicholz** [comment]
> You can use `Backspace` to remove a show from the project, this will not delete it! If you delete a show from the drawer (the whole application) it will also be removed from any project!
> 
> A project is used to order shows/media files in a selected order, often for one time use. If you want to hide a show from the "Shows" drawer, you can right click the show in the project and choose "Private".

Thank you for your quick response @vassbo. There was no `Backspace` tip like there is for `Delete` on the right-click menu and pressing `Backspace` or `Delete` after clicking on a show does not do anything. I just figured out that you have to select it by CTRL/CMD clicking it or drag selecting it (or several) then `Backspace` and `Delete` buttons works. My worry is that someone may accidentally right-click and select delete and end up completely removing a reusable show or song. Maybe it would be safer to only allow complete removal/delete from the lower shows/media panel? Just a thought.

Thanks for the tip. We reuse the same project because we follow the same layout/pattern and only change songs and text we  display. It is less work to swap out just the 3-4 shows we need to change than to create a whole new project from scratch each time.

**Comment by vassbo** [comment]
I see. If you accidentaly delete a slide/group you can press CTRL/CMD+Z to undo the action!

For your project you should have one "TEMPLATE" project ready made that you just duplicate each time and add your 3-4 songs.
Or of course just remove the shows from it, and add the new ones.
