### ISSUE TITLE
[Feature Request] Ability to import a ProBundle

### ISSUE THREAD

**Issue by kb9gxk** [ChurchApps/FreeShow#923]
I have been working with ProPresenter 7 presentation and would like to migrate it to FreeShow.  I made the presentation a few years back and it's for when I'm doing some training.  Having the ability to import newer presentations would be needed.

**Comment by vassbo** [comment]
You should be able to extract it as .zip and import all the .pro files from it!

https://github.com/ChurchApps/FreeShow/issues/225
