### ISSUE TITLE
[Bug Report] Changing Bibles resets the results

### ISSUE THREAD

**Issue by chalamministries** [ChurchApps/FreeShow#924]
**Describe the bug**
When changing to a different bible, results reset to Genesis 1

**Reproducing**
Look up scripture using KJV, then change to a different bible. 

**Version (Optional)**
 - OS: MacOs
 - FreeShow Version: 1.2.9

**Additional context**
Not sure if it is because of the type of Bible I've imported. It appears to happen regardless of which bible switched to

**Comment by vassbo** [comment]
Seems to only happen when changing from an API Bible to a local Bible right after the book/chapter is changed. Got it fixed!
