### ISSUE TITLE
[Feature Request] [UI Improvement] Chorus slides shouldn't have numbers.

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#926]
This is a minor improvement.
The whole point of a "Chorus" in a song is that it repeats multiple times throughout the song. 
Having Chorus(1), Chorus(2) Chorus(3) etc... doesn't make sense, and may cause confusion. 
Perhaps, consider removing the numbers when a specific slide is used more than once. 
Maybe it doesn't even make sense to have it in verses either, but that one is debatable.

![image](https://github.com/user-attachments/assets/77c680b3-a917-4dfb-bc37-b65431aee408)

**Comment by vassbo** [comment]
This is not a group number, it's a group counter!

It's the same for all groups, if you have two unique groups they will be named: "Verse 1" & "Verse 2" / "Chorus 1" & "Chorus 2"
If you have more of the same group they will get a index/count number: "Verse 2 (1)" & "Verse 2 (2)" / "C (1)" & "C (2)"

**Comment by vassbo** [comment]
Do you think this is better than the parentheses?
![bilde](https://github.com/user-attachments/assets/bfb0a7d7-c2c5-469e-be49-cb583503e006)

**Comment by yurividal** [comment]
Yes, indeed this format makes more sense. How will it show in the %Progress bar?
Will the counter also be hidden?

**Comment by vassbo** [comment]
What do you think, should it be hidden? If not it will show with parentheses.

**Comment by yurividal** [comment]
I believe it should be hidden. It's a chorus, it's not relevant to the projection if it's the first, second or third time it is displayed
