### ISSUE TITLE
[Bug Report] Media Transition

### ISSUE THREAD

**Issue by aJaaaang** [ChurchApps/FreeShow#927]
Transitioning from media 1 to media 2 have a short pause (or I think restarted media) then the transition.

Steps:
Put 2 medias in the presentation area.
Apply the 2 slides with any transition.
Select any of them and click another slide with different media.

Below is the video demonstration of the bug:
https://drive.google.com/file/d/1Y6GTPzM-_rAHLxegpNgBHGxCBN2KjHOd/view?usp=sharing

 - OS: Windows 11 x64 intel CORE i7 10th Gen
 - FreeShow Version: 1.2.9

**Comment by aJaaaang** [comment]
Same also with the 1.3.0 beta2

Windows 11 x64 intel CORE i7 10th Gen

**Comment by vassbo** [comment]
I don't get the same issue in beta.3.. Is only the preview, or the output as well?

**Comment by vassbo** [comment]
Closing until it can be reproduced.

**Comment by aJaaaang** [comment]
> I don't get the same issue in beta.3.. Is only the preview, or the output as well?

Yes the same as the output. I can't reproduce it yet since I have my HDMIs used on our church. Since, we have the new version I'll try it and see if there's an issue about it.
