### ISSUE TITLE
[Feature Request] Allow full settings to be synced

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#930]
I'm trying to have the entire AV team to have the same freeShow environment on their own computers.
Currently, i have tried google drive, and also i have tried syncing the full data folder.
But, even with the entire data folder being synced, the Song categories, the templates, and most settings are not synced.

Do i need to sync the %appdata% folder too to accomplish this? 

A simpler way to get full sync would be nice, unless i'm doing something wrong and this is already possible...

**Comment by yurividal** [comment]
Original PC:

![image](https://github.com/user-attachments/assets/cc8421d6-1ac3-4d79-a8f4-c2a3658687f3)


New PC with same data folder, synced from google drive:

![image](https://github.com/user-attachments/assets/f2aeb38f-ca99-47a4-b34f-87c453c8e937)

**Comment by yurividal** [comment]
Thanks. I ended up doing this.
It initially overwrote all my setting on both computers. luckily I had a backup and I was able to replace it.

Maybe, for the future, you might consider a welcome wizard on the first run that allows the user to point to an existing location, and it won't overwrite on the first run?

**Comment by vassbo** [comment]
Great! It should not override anything on first toggle, but the program will automatically take a backup for you when you toggle this so it should be fine!
