### ISSUE TITLE
Put the search input in a conspicuous area 

### ISSUE THREAD

**Issue by macdelacruz** [ChurchApps/FreeShow#931]
It's hard to notice the search input for the shows. Every time I ask someone to use Freeshow I always have to tell them how to search the shows. I know that this search works across all objects including templates, media, and scripture. Maybe you can adjust the width/alignment of the Search icon and text OR make the input field always visible without having to click "Search", add a placeholder text and tooltip to it that says "Search shows, scriptures, etc."

<img width="956" alt="Screenshot 2024-10-25 234128" src="https://github.com/user-attachments/assets/beaa00de-22ae-4f51-a4d2-66033d18a976">

**Comment by vassbo** [comment]
I find it strange how poeple don't see it, have experienced that myself as well. As it is global across the drawer I don't see any better way to put it!

For the first two years the search bar was always active as the big expanded area, but people didn't see it when it was like that either, I'm sure the way it has an icon now is better than it was:
![bilde](https://github.com/user-attachments/assets/1f02cc3a-d83c-4213-b16d-2894fa4c2536)

CTRL+F works for people familiar with that. I'm sure moving it to the left side will not help noticeable with the issue.

Also for smaller screens it's better the way it is now, as the drawer tabs might fill almost the entire width:
![bilde](https://github.com/user-attachments/assets/b23b51cf-12e0-4a2f-b7db-760f3d57eee8)

I think I should include it in the "Quick start guide" at least, but for now I don't see any better placement for it!
