### ISSUE TITLE
[Bug Report] Ableton PLAY/STOP function triggers first SHOW on FreeShow

### ISSUE THREAD

**Issue by tansimson** [ChurchApps/FreeShow#934]
We are using two laptops during our church services. First laptop is for FreeShow for lyric projection and second laptop for backing tracks and sending MIDI signals/triggers to first laptop using Ableton. However, when I trigger the PLAY/STOP button on ABLETON either using the SPACEBAR or LMOUSE click it triggers the first show item in the project on FreeShow.

Upon checking what MIDI signal is being received from Ableton's PLAY/STOP it shows "Incoming: Control Change on ch. 5 with CC#:123 (0x7B) and value:0 (0x00)".

Gears/Devices:
 Laptop 1 (receiving MIDI)
 - Acer on Windows 11
 - rtpMIDI and Bonjour for midi network
 - FreeShow Version: [1.2.9]

Laptop 2 (sending MIDI)
- Macbook Pro on Big Sur
- Ableton 11
- Audio Midi network

I haven't set any MIDI ACTION on FreeShow for the said MIDI signal. Does FreeShow have internal action for the said MIDI signal?

**Comment by mwb9aa** [comment]
@vassbo fixed the problem for me in release 1.3.0-beta.2. I used loopMIDI on the same machine. rtpMIDI is made by the same person, and operates the same. I have even been able to use both at the same time.

FreeShow has some default MIDI actions, but you do need to "enable" them by opening the Drawer, clicking on the Function tab, then create a new action. 

[1.3.0 Beta 2](https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.2)
[1.3.0 Beta 3](https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.3)

**Comment by vassbo** [comment]
Try the latest beta as @mwb9aa linked!

https://github.com/ChurchApps/FreeShow/issues/918
