### ISSUE TITLE
[Feature Request] Customizable Keyboard Shortcuts

### ISSUE THREAD

**Issue by pipocoding** [ChurchApps/FreeShow#936]
It would be nice to be able to set and change keyboard shortcuts.

**Comment by mwb9aa** [comment]
@pipocoding 

Would you please provide more information? What shortcut keypress(es) are you wanting? What do you want the shortcut to do? You can change the keyboard shortcut for navigating various slide groups and declare a keyboard shortcut for Actions.

Settings->Groups->Group shortcut

Drawer->Function tab->Action->Edit / New action->Activate by keypress

**Comment by yurividal** [comment]
I have requested this a few weeks ago, but at the time, it was rejected.

Details here: https://github.com/ChurchApps/FreeShow/issues/900

**Comment by mwb9aa** [comment]
@pipocoding @yurividal 

If you are on Windows, you can use AutoHotKey to capture a shortcut and forward it to FreeShow. For example, AutoHotKey could capture an up arrow and send a left arrow to FreeShow. For someone who doesn't want the behavior, just pause or close AutoHotKey.

MacOS has a similar program, karibiner maybe?
