### ISSUE TITLE
[Bug Report] Powerpoint Import as a Media not function probably

### ISSUE THREAD

**Issue by MichaSchumacher** [ChurchApps/FreeShow#937]
**Description**
I wonder if it's possible to load the PowerPoint slides automatically when I click start in FreeShow. I found it complicating to load my presentation in PowerPoint first for FreeShow to recognize it.

**Reproducing**
For reproducing, do not load a presentation on PowerPoint and try to start the PowerPoint presentation on FreeShow. This causes the error "No presentation loaded." 

**Screenshots**
<img width="1440" alt="Bildschirmfoto 2024-10-26 um 15 46 29 (2)" src="https://github.com/user-attachments/assets/6e5ac3af-e5d2-4349-9edb-7a1145806164">

<img width="573" alt="Bildschirmfoto 2024-10-26 um 15 52 03" src="https://github.com/user-attachments/assets/2f89ec72-25ed-47c3-9036-8ddbe389a742">

<img width="629" alt="Bildschirmfoto 2024-10-26 um 15 56 33" src="https://github.com/user-attachments/assets/9aa93dbe-ef7c-404b-9b9d-0f07504cf5a1">

**Version**
 - OS: MacOS Sequoia 15.1
 - FreeShow Version: 1.2.9

**Additional context**
When I try again, sometimes the PowerPoint home screen loads, but the presentation doesn't, and in the window of the PowerPoint home screen, I can select nothing.

Thanks for your product and your help

**Comment by vassbo** [comment]
Can't do much about this, more of an issue with the controller package: https://github.com/rse/slideshow

If it's still slides without animations you should convert the slides to images and import it that way, much more reliable.

**Comment by MichaSchumacher** [comment]
Oh okay, i understand. Is this only on Mac a problem?--Gesendet mit der GMX Mail AppAm 28.10.24, 08:26 schrieb "Kristoffer Vassbø" ***@***.***>:

Can't do much about this, more of an issue with the controller package: https://github.com/rse/slideshow
If it's still slides without animations you should convert the slides to images and import it that way, much more reliable.

**Comment by vassbo** [comment]
I think this is Mac only yes, but I'm sure Windows also has some different issues.

**Comment by MichaSchumacher** [comment]
Ok thanks--Gesendet mit der GMX Mail AppAm 28.10.24, 10:39 schrieb "Kristoffer Vassbø" ***@***.***>:

I think this is Mac only yes, but I'm sure Windows also has some different issues.
