### ISSUE TITLE
[Bug Report] Bibles freeze the app

### ISSUE THREAD

**Issue by jayye-jpg** [ChurchApps/FreeShow#938]
**Describe the bug**
The scripture loads for searching, but when selecting to show, it blocks FreeShow from doing anything anymore. Cannot click away from the verse or even the panel for Scripture, or do anything in the app - but the buttons react.

**Reproducing**
Load a bible, preview shows
Click any verse (or search a verse and click) - no responses other than button presses and depresses.

**Version (Optional)**
 - OS: macOS 14.6.1
 - FreeShow Version: 1.2.9

**Additional context**
[Bibles.zip](https://github.com/user-attachments/files/17534513/Bibles.zip)

**Comment by mwb9aa** [comment]
@jayye-jpg 

Please see my [response](https://github.com/ChurchApps/FreeShow/issues/935#issuecomment-2439819977) to another issue. It may be related. It appears I had a file corruption in one of the json files. Deleting the file allowed the program to work normally again.

**Comment by yurividal** [comment]
@jayye-jpg any chance you can submit a video of the issue?

**Comment by jayye-jpg** [comment]
> @jayye-jpg any chance you can submit a video of the issue?

Okay, I’ll do my best! I left that location, but I have a setup at home that I’ll try to replicate and get a screen recording. Also, I ended up resetting the whole software, and I’m mid-rebuild.

**Comment by jayye-jpg** [comment]
> @jayye-jpg
> 
> Please see my [response](https://github.com/ChurchApps/FreeShow/issues/935#issuecomment-2439819977) to another issue. It may be related. It appears I had a file corruption in one of the json files. Deleting the file allowed the program to work normally again.

Okay so in order to reset the software on the Mac, I had to do something similar! I’ll report back if that did resolve it and I’ll up your reply! Thanks!
