### ISSUE TITLE
[Bug Report] Removing a background from a template only works after restarting freeshow

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#940]
If you set a background image or video for a template and apply it to certain shows, then remove the background from the template, the background is still shown on the shows.
Even if you change the template and re-apply the template to the shows, they will still appear with the background image.
The only way to solve this is to close freeshow and reopen. 
I think the backgound image is somehow getting stuck in the cache.

(Beta3 - Windows 10 and Windows 11)

**Comment by vassbo** [comment]
The template backgrounds will apply a background to the first slide in a show, but not remove backgrounds as templates should not affect existing backgrounds.

Is the background still there after removing it from the show?
![bilde](https://github.com/user-attachments/assets/59688b54-2c16-4f3c-a23a-e30d300e2f2e)

**Comment by vassbo** [comment]
I changed it, so if changing from a template with the same background as the selected - to a new template with no background, the background will also be removed!
