### ISSUE TITLE
[Bug Report] {Stage Display Text Formatting Malfunctioning on Online Viewer}

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#941]
**Describe the bug**
The Stage Show display (Stage View shown on an IP) isn't working properly.

❓ If any kind of autosizing is applied to the regular, text-only slides for display at the front, then large, multi-line text gets cropped in stage view. (See ScreenShot 1) Once auto-size is disabled, and slide text is restricted to a global font size, then there are no issues. However, this removes the of usability of autosize in presentations requiring stage view.
🧠     I think that this problem occurs due to the fact that the stage view uses the same font-size numbers as the regular displays instead of resizing for display purposes. Thus, if the text at the front is resized to fill the text box on the slide, then that same font size is applied to the smaller text box on the stage view slide - thus rendering the text unusable. A simple reload oftentimes will do the trick, but that shouldn't be necessary.
✅    @vassbo, are you able to implement a "Shrink to fit" autosize feature for stage view similar to that used on the regular slide/template editor? That way, regardless of text size in the regular slides, text will be displayed correctly in stage view. This would allow the auto size features in the regular slide editor to work properly across the app.

**Reproducing**

1. Create a text only slide (ideally song lyrics) and ensure that some slides have more lines than others.
2. Enable auto size features in the slide editor for the song.
3. Create a stage display with a "current output" text box of smaller size than on your output slides.
4. In a web browser, navigate to the IP of your machine, and select the relevant port to access stage show.
5. As you advance through slides in the FreeShow app, watch and see how the text is cropped for some slides with more lines.
6. Be inspired to write a long GitHub bug report 😁 

**Screenshots**
<img width="1440" alt="ScreenShot 1" src="https://github.com/user-attachments/assets/3b138679-5dee-470d-b278-f9a4348ae528">

**Version (Optional)**
 - OS: macOS sequoia 15.0.1
 - FreeShow Version: 1.2.9

**Comment by vassbo** [comment]
It's fixed in the latest pre-release!
https://github.com/ChurchApps/FreeShow/issues/910
