### ISSUE TITLE
[Bug Report] {Online StageView text is not displaying correctly}

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#942]
**Describe the bug**
❓ When displaying any text with or without a background in the online StageView (accessed through IP), the font seems broken, and is not displayed correctly. (Please refer to ScreenShot 2)

🧠 Perhaps FreeShow is overprocessing the text due to mirroring text from the "Current Output" multiple times instead of displaying the information. I'm thinking that could cause the text to fall apart as the image, and not the information output is resized for stage view twice (once for the app output, and once more in online output).

✅ If I'm right about the cause of the issue, you might want to rethink the "Current Output" option in the stage view editor. You may want to display different layers with a similar processing workflow as the regular outputs. Instead of just mirroring the flat output of the slide, you may want to re-render text from base information instead of mirroring pixels. This might cause extra processing leg, but could be worth it to ensure text fidelity while displaying.

**Reproducing**
Display a slide that contains a text layer and view it in the online StageView.

**Screenshots**
<img width="1440" alt="ScreenShot 2" src="https://github.com/user-attachments/assets/58762f6b-67da-4731-a8dd-275ea4dd35fa">

**Version (Optional)**
 - OS: macOS Sequoia 15.0.1
 - FreeShow Version: 1.2.9

**Comment by vassbo** [comment]
First of all make sure you try it on the latest pre-release: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.3

Secondly, in the stage website make sure to CTRL+SHIFT+R to refresh the website and clear the cache.

Thirdly, is it a font only issue? Is the size wrong or just the font rendering? If it's just the rendering it must be a browser issue and not something I can fix unfortunately.
