### ISSUE TITLE
Stage View Not Displaying Some Content

### ISSUE THREAD

**Issue by Dcanadian** [ChurchApps/FreeShow#943]
### Description
I've made a Stage View for my church's setup to display the current output slightly smaller to include the "System Clock" and "Progress" indicator. (See ScreenShot 1) Unfortunately, I've discovered that the "Current Slide" option for stage displays will not display the current output all the time. Things like YT videos, screens, or video inputs won't display. (See ScreenShot 2) 

### Question
A while back in Issue #708 , there was an issue with using "Current Output" in the presenter view. Is that issue fixed now? I'm wondering if it will wreck the system again if I try it.

### Reproducing

1. Try to play a YouTube video or display system screen or video in current output.
2. Create a Stage View with "Current Output" present.

#### ScreenShot 1
<img width="1552" alt="ScreenShot 1" src="https://github.com/user-attachments/assets/00ecd3f5-4207-486a-a2cd-cd93de811b6a">

#### ScreenShot 2
<img width="1552" alt="ScreenShot 2" src="https://github.com/user-attachments/assets/d8161565-1fb2-4caa-81aa-060e17925798">

### Version
 - OS: macOS Sequoia 15.0.1
 - FreeShow Version: 1.3.0-beta3

**Comment by vassbo** [comment]
Not sure if the performance is better for the "Current output".

But I'll try my best to fix the media issue (The "Current slide" should show a thumbnail only, not any full videos).
