### ISSUE TITLE
[Bug Report] Transitions are output when None are selected

### ISSUE THREAD

**Issue by colanct** [ChurchApps/FreeShow#944]
For some slides, but not all, a transition is applied to the output even though all transition options are set to None.

Win10
FreeShow V1.3.0-beta.3

**Comment by yurividal** [comment]
@colanct 
Any chance you can get a video of the issue, to make it easier to understand what you are reporting?

**Comment by vassbo** [comment]
Probably related to this: https://github.com/ChurchApps/FreeShow/issues/939

**Comment by colanct** [comment]
Appears unlikely to be related to #939.

Here's an example of what I'm seeing:
Slide 1 - All transitions set to None
Slide 2 - Text = None; Media In = Slide; Media Out = Spin.
Slide 3 - All transitions set to None
When Slide 1 transitions to Slide 2:  Slide 1 spins out (unexpectedly) and Slide 2 slides in (as expected).
When Slide 2 transitions to Slide 3:  No transition is visible. I expect slide 2 to spin out.

Unless I'm misunderstanding the logic, I'm wondering - given the inconsistencies - if changes to the transition settings are not replacing previous settings fully.

I have other cases where all transitions on three consecutive slides are set to None, yet the first two show in and out transitions.

**Comment by vassbo** [comment]
Okay. Here is the transition order, please check that none of these are set to "spin":
- Global transition
![bilde](https://github.com/user-attachments/assets/a06ced3f-f728-4b3f-998b-6131d09a1619)
- Style transition
![bilde](https://github.com/user-attachments/assets/ef773ad9-a2d5-4429-9bfc-bff54b5bafcc)
- Slide transition
![bilde](https://github.com/user-attachments/assets/900e9bde-2d66-4660-966b-05b6cdb9892d)
- Item transition
![bilde](https://github.com/user-attachments/assets/25fc8635-f8ad-4a25-a318-94fc87fb7224)

**Comment by colanct** [comment]
Thank you.  I checked each.  None are set to Spin.
I have no _Items_ in my test slides;  just  backgrounds.

Will it help if I send the show file?

**Comment by vassbo** [comment]
I don't think that will help.
Do your media transitions look like this?
![bilde](https://github.com/user-attachments/assets/1b5516fb-b523-486e-b899-305e1a29a1fb)

**Comment by vassbo** [comment]
You said "all transition options are set to None", but apparently you did have custom slide transitions not set to none, I get it now. The transitions for the next slide overrides the previous!

**Comment by colanct** [comment]
No. 
This is what's at the Slide level

![image](https://github.com/user-attachments/assets/6fde5404-13a0-488c-ac53-b604c3a06a01)

**Comment by vassbo** [comment]
Yeah, I managed to fix it. I thought all transitions were set to none as you said first.

**Comment by colanct** [comment]
For "all transition options are set to None", I was referring to all the options on a specific slide, not for all the whole show.

**Comment by colanct** [comment]
Thank you.
Please clarify the intended behaviour, particularly if there is any overriding or inheriting.  
My expectation is that if everything at the slide-level is set to _None_, then that setting takes precedence at the slide level.  Is that correct?

**Comment by vassbo** [comment]
Correct.

**Comment by colanct** [comment]
Ah, good; thank you.
Please clarify the function of the _Between_ setting on _Text transition for current slide_, and why it is only available for text?  I'm having difficulty working it out.

**Comment by vassbo** [comment]
Between will only trigger if a slide is already outputted when clicking a slide.
Meaning you can e.g. set in/out to "Fade" and between to "None".
So if will only fade when clicking the initial slide and clearing, but not when changing from one text to another.

**Comment by colanct** [comment]
Just to confirm my understanding: when you say _changing from one text to another_, would that be the case when song lyric text is shown against a background applied to only the first slide of that show, and then only the text being changed on subsequent slides?

**Comment by vassbo** [comment]
It only applies to the "slide" layer.

Here's a tip to know:
- If no slide is outputted, the "In" will trigger when changing slide:
![bilde](https://github.com/user-attachments/assets/fc2e2163-9a3d-4f43-8134-ba43d6c90911)
- Else the "Between" will trigger, unless the slide layer is being cleared, then it's "Out":
![bilde](https://github.com/user-attachments/assets/518a99f8-7d5d-474c-9862-4d558da87575)

**Comment by colanct** [comment]
Aah; thank you.  That helps.

**Comment by vassbo** [comment]
Test it out: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.0-beta.4

**Comment by colanct** [comment]
Yes, it's fixed; now the transitions function logically.
Thank you for your quick response.
