### ISSUE TITLE
Edit show groups in RemoteShow

### ISSUE THREAD

**Issue by Rares006** [ChurchApps/FreeShow#945]
**Describe the feature**
I would like if is possible to put in the RemoteShow the option to see the structure of the song and to can edit.

**Additional context**
Each worship leader sings the songs with a slightly different structure, and they would like to be able to see the song structure in advance and modify it if necessary, so that they can see correctly what is displayed on the stage screen.

**Comment by mwb9aa** [comment]
I think you are saying that you would like to make a new arrangement and be able to manipulate the song arrangement a clicking in the group area and duplicating groups and changing their order and the slides area mimics the group area. I would like that as well.

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.2-beta.1

**Comment by Rares006** [comment]
It works perfectly on a PC, but could you adapt it so that the structure can also be edited from a tablet or phone?

**Comment by vassbo** [comment]
@Rares006 You can do that. Just hold and drag the group!

**Comment by Rares006** [comment]
Still not working this way either.[https://share.icloud.com/photos/0019k3Y1GqQOJKBSsU8QOLpsg](https://share.icloud.com/photos/0019k3Y1GqQOJKBSsU8QOLpsg)

**Comment by Rares006** [comment]
It works the same for me as it does on safari.

**Comment by vassbo** [comment]
@Rares006 It's an Apple issue that I can't do anything about unfortunately!
https://stackoverflow.com/a/54429501/10803046

**Comment by mwb9aa** [comment]
@vassbo  and @Rares00, 
I went to the stackoverflow link, then to the code pen from the original question. Drag and drop works on my Apple iPhone 13 running iOS 18.1.1 in both mobile and desktop versions of the code pen. Long press (touch and hold for about a second), then the element becomes draggable. Letting go of the element drops it in its place. I will try to remember to test this with FreeShow later today.

**Comment by vassbo** [comment]
Okay thank you. Looks like `style="-webkit-user-drag:element;"` might fix it? I'll add that, but can't test it.

**Comment by Rares006** [comment]
I can test it. Tell me when you add that

**Comment by vassbo** [comment]
Added in the latest update: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.2

**Comment by Rares006** [comment]
it still doesn't work

**Comment by Rares006** [comment]
I think this can help. 
![IMG_1141](https://github.com/user-attachments/assets/43ed4d65-bfc1-436d-ab96-d97c273619b0)
![IMG_1142](https://github.com/user-attachments/assets/69f32444-f341-4de1-8427-6c576f16aa5c)
<script src="http://bernardo-castilho.github.io/DragDropTouch/DragDropTouch.js"></script>
