### ISSUE TITLE
[Bug Report] Beta Version - Scripture Resize

### ISSUE THREAD

**Issue by chalamministries** [ChurchApps/FreeShow#949]
**Describe the bug**
Text resizes when using the arrows to scroll throught scripture

**Reproducing**
Pull up scripture by double clicking. Auto resize happens before it pushes to screen. GOOD. But click the left or right arrows to scroll through the scripture. It pushes to screen before it resizes.

**Version (Optional)**
 - OS: Mac OS
 - FreeShow Version: 1.3.0-beta.4

**Comment by yurividal** [comment]
Is this still happening on latest Beta 4?

Seems to be the same issue reported here: https://github.com/ChurchApps/FreeShow/issues/910

It should have been fixed.

Can you please update to version beta 4, and send a video of the issue still happening? I'm not questioning you, just trying to understand if it's the same issue I was having.

**Comment by vassbo** [comment]
Can't reproduce, looks to be working as it should. I only see your described behaviour in the scripture preview in the drawer, but that's expected.
Try changing the transition duration to see if that helps, but I could not see this issue even when the transition was set to none.

**Comment by yurividal** [comment]
@vassbo i was able to reproduce this in 1.3.0
It works fine in the main output. But, this is what it looks like on my OBS (lower third) output. Note how the text resizes after being displayed. 

https://github.com/user-attachments/assets/7412d9e9-ce60-4c75-8ee8-cad39314772b

**Comment by vassbo** [comment]
I see, I tried with a second output. Now I also see it for some reason. I'm sure it only happens in a specific scenario.

**Comment by vassbo** [comment]
Apparently a delay of 200ms was not enough (sometimes), had to be 400ms.
