### ISSUE TITLE
[Feature Request] New Show From Entire Bible Chapter

### ISSUE THREAD

**Issue by chalamministries** [ChurchApps/FreeShow#950]
**Describe the feature**
You can right click on a verse and choose New Show and it creates a slide with just that verse (s) but I think it would be great to right click on the chapter we are in, and do the same thing.

**Comment by yurividal** [comment]
That seems like a good idea. Currently, I do Ctrl-A to select all verses, then new show.

Would save 1 click and 2 key-presses. =)
