### ISSUE TITLE
[Feature Suggestion] Use Semantic Versioning

### ISSUE THREAD

**Issue by yurividal** [ChurchApps/FreeShow#951]
This is just a suggestion, to make it easier to understand versions and updates, since this project is under heavy development.

Using [semantic versioning](https://semver.org/) makes it easier for people to identify updates and how crytical they are.

Basically it means major.minor.patch

Major - Big Changes to the app behavior, look or API

Minor - New Features are available, or any braking changes are implemented.

Patch - Bug Fixes and performance improvements

As I said, this is only a suggestion. It would put this project more in line with most of the modern FOSS out there.

Example: I believe the next release would be 1.30.0 since it includes quite a lot of new features (as seen in the beta changelogs)

🤓

**Comment by vassbo** [comment]
I'll see what I do.
The next is going to be 1.3.0!
