### ISSUE TITLE
[Feature Request] {import your own text fonts}

### ISSUE THREAD

**Issue by dtrio-nbl** [ChurchApps/FreeShow#954]
**Describe the feature**
An option to import text fonts would be a great feature to add so it doesn't limit us to just the default fonts.

**Comment by Phantom-Matt** [comment]
By my understanding, FreeShow always grabs the fonts that are installed on system, so, if you wish to import your own text font, just install in your system for all users (I tested on Windows11 and a linux distro; both worked)

**Comment by mwb9aa** [comment]
Installing the font on the system works for me too.

**Comment by vassbo** [comment]
@renarena That is a bug on some Linux systems. I can't do much about that with the new font system. Related to this: https://github.com/ChurchApps/FreeShow/issues/1119

You can use CSS to type in any the font name
