### ISSUE TITLE
I cant use my media completely

### ISSUE THREAD

**Issue by JOSHUA29092003** [ChurchApps/FreeShow#955]
whenever i try to use media only web camera opens, there is no options for other medias
![Screenshot 2024-11-01 010434](https://github.com/user-attachments/assets/8330e1fc-b97a-402f-b7de-f5d97ee9b0df)

**Comment by Phantom-Matt** [comment]
Hello, I believe that if you go to the leftmost point until you see a vertical line and pull it back to the right, you may be able to see the options.

**Comment by JOSHUA29092003** [comment]
Thank you it worked out

________________________________

**Comment by aJaaaang** [comment]
You can close this now, since the problem/bug is completed already.
