### ISSUE TITLE
[Feature Request] Render Thumbnails for Stream Deck Integration

### ISSUE THREAD

**Issue by jquyatt** [ChurchApps/FreeShow#959]
### Summary
Requesting an option to export slide thumbnails in real-time for use with Stream Deck via Companion. This feature would let FreeShow users view thumbnails on Stream Deck buttons, making slide navigation more intuitive and reducing mis-triggers in complex presentations.

### Feature Details

- Capture each slide as an image upon load and export to a designated folder.
- Automatically update thumbnails when a new slide loads or changes, so Stream Deck always shows the latest view.
- Companion should detect new images on file change or through a FreeShow trigger for real-time updates.

### Use Cases
Helps Stream Deck users navigate slides visually, especially for events with non-linear slide orders or frequent slide adjustments.

### Potential Challenges
Considerations include performance optimization for real-time updates and managing permissions for folder access if on a network drive.

**Comment by vassbo** [comment]
Possible. I think maybe easier to allow for an API request to get a base64 encoded image thumbnail of the current slide.

**Comment by vassbo** [comment]
All right, I will make it easier yes, and probably also get the actual slide and not just media.

**Comment by vassbo** [comment]
You can use the `custom_message` in Companion, and currently if you know the path you can use the `get_thumbnail` action id to get the thumbnail of a media file.

But from the next version you will be able to use the `get_slide_thumbnail` to get what a slide looks like in the output with text /media. Also with these optional values: `{ showId?: string; layoutId?: string; index?: number }`
