### ISSUE TITLE
[Feature Request] Shortcuts Control Bible Verses

### ISSUE THREAD

**Issue by chalamministries** [ChurchApps/FreeShow#960]
**Describe the feature**
left and right arrows move through slides but it would be nice to either use arrows or some other keys on the keyboard to scroll through verses

**Comment by Gonon-UP** [comment]
Hey chalamministries, you can move through verses using CTR+ left arrow and CTR + right arrow on Windows. I think on Mac it should be CMD instead of CTR. There's a lot of other nice short cuts that come in handy, you can find them on the HELP tab located in the top right corner.

**Comment by chalamministries** [comment]
Ah. Shortcuts say Move Through Drawer Item. I get that now. Scripture is in the Drawer.
