### ISSUE TITLE
[Feature Request] New Show Button

### ISSUE THREAD

**Issue by chalamministries** [ChurchApps/FreeShow#962]
**Describe the feature**
If you right click on the project box, you get New Show and New Section. But it would be nice at the bottom to split that section and have New Show and New Section there as well. 

<img width="294" alt="Screenshot 2024-11-01 at 7 15 43 PM" src="https://github.com/user-attachments/assets/6d5920c4-c8fe-48b1-a38f-af60d428812c">

**Comment by vassbo** [comment]
This would be confusing as shows are not created in the project, they are just added as "shortcuts" to the project.
Press CTRL+N, or the "New show" button in the drawer to create a new show.
