### ISSUE TITLE
[Feature Request] Single Click Verse Option

### ISSUE THREAD

**Issue by chalamministries** [ChurchApps/FreeShow#963]
**Describe the feature**
Single click to bring up verse

**Additional context**
I think this should be an option to set in Settings though. Maybe 3 options: 1) Double Click, 2) Single Click, 3) Verse Number Click

So on option 3, you click on verse and it goes to preview but if you click the colord verse number, it will trigger to Program

**Comment by vassbo** [comment]
Not sure what exactly you mean here, but you can already single click any slide/verse to bring it up in the output.

**Comment by chalamministries** [comment]
Not for me. And I've tried both the production version and the beta. On Mac, if I single click a verse, it shows in preview. I have to double click to make it go to the screen.

[Steven Gauerke](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2uetbe)	[2uetbe]Web Developer

On November 4, 2024 at 7:06 GMT, Kristoffer Vassbø via Info ***@***.***> wrote:

Not sure what exactly you mean here, but you can already single click any slide/verse to bring it up in the output.

**Comment by chalamministries** [comment]
Yup just tried it on a different mac and same issue. You have to double click the verse to make it go to the screens. Otherwise it only updates the preview.

[Steven Gauerke](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2uevyo)	[2uevyo]Web Developer

On November 4, 2024 at 14:32 GMT, Kristoffer Vassbø via Info ***@***.***> wrote:

Strange, that should not happen. Preview should display the same as the output screen.
Not sure what has happened here, but no other mac users has reported this issue!

**Comment by vassbo** [comment]
@chalamministries Could not recreate the issue on Windows or Linux, and I do not have a mac to debug. Are you able to debug this issue?

**Comment by gccmtuba** [comment]
I wonder if @chalamministries is referring to Bible verses, in the scripture tab?

**Comment by vassbo** [comment]
Thanks @gccmtuba, that makes sense!

In that case you can create a "New show" from the scripture verses, use use the arrow keys at the bottom (CTRL+LEFT/RIGHT) to change. The reason it's double click is so you can select multiple verses and preview it before presenting, I can probably change it to be single click if the scripture presenting is already active.

**Comment by chalamministries** [comment]
That's why I was suggesting there be an option you can set. I don't know how well that would look or work. For us we would only ever use one verse at a time. But I get where you're coming from where you might want to select versus one through three. Which brings me to another feature I think I'd like to suggest. Right now if you only type book and chapter, and press enter, it automatically sends versus 1 through 3 to the program output. But I would prefer only The first verse. I'm not sure I know of an application where anyone would want the first three verses all at once. Or when you press enter after typing in the search, don't send anything to program. Just in preview

**Comment by vassbo** [comment]
@chalamministries In that case just press space (auto ":") and type "1" after the chapter to select only the first verse, or reduce the "Max verses per slide" to 1. Also when using search it will show the preview before pressing enter, so in a way you "bypass" the double clicking.
