### ISSUE TITLE
[Feature Request] Have the cameras available from the start up

### ISSUE THREAD

**Issue by Dexiion** [ChurchApps/FreeShow#964]
**Describe the feature**
It would be awesome to have all the available cameras enabled from the start up of the program.
Now If you are not using them on a Program or you are not on Media/Camera they get "disconnected" and have to start everysingle time you want to use them.
To improve the time it takes to turn on the cameras, they could be turned on once at the start of the program and stay on until the program is closed, or have a button to manually deactivate the camera.

**Additional context**

https://github.com/user-attachments/assets/51ddc14f-bf58-4806-90f2-77e6451cd315

**Comment by vassbo** [comment]
I don't see this as an issue. If the camera is active in the output it will always stay on.

But if you really want one camera feed to always stay active, you can create a locked overlay with a hidden "Camera" item.

**Comment by Dexiion** [comment]
Well I didn’t write this as a bug or something that is not working on the program, I write ir as a improvement 😄

This is for example what OBS does, if you have added a cam in any place of the program It will be available all the time on every place of it.

I really don’t want to wait like 2-3 seconds for the camera to load up when I am presenting a song for example and then I want to change to the camera.

I am not sure on how to do the overlay to have the camera allways active, could yo explain it to me please?

Thanks! 😄

**Comment by vassbo** [comment]
I meant I don't see the issue with the camera loading time.

But like this you can keep it always active on startup:
- Create a new overlay
- Add a camera item with positioned outside of the slide area
- Right click the overlay and click "Lock to output"

Now when you click the overlay to present the camera will stay active, even upon repoening.
