### ISSUE TITLE
[Feature Request] {Add a descriptive title here}

### ISSUE THREAD

**Issue by chanx** [ChurchApps/FreeShow#966]
On mobile Control Show, i wonder if we can add the up/down button that can move the previous/next item in project. I think this can help operator control the show more convenient, because he can switch the song/next item in project without using keyboard.

**Comment by vassbo** [comment]
You can go to the next/pervious show in the project by pressing arrow right/left at the end/start of a show, if you want more advanced controls, this is what RemoteShow is for. ControlShow is supposed to be simple.
