### ISSUE TITLE
[Bug Report] {Text sometimes glitches to black when changing slides}

### ISSUE THREAD

**Issue by danivisuals** [ChurchApps/FreeShow#967]
**Describe the bug**
I implemented FreeShow this week at our church for the first time, it was a true blessing to have. I just have one small issue, sometimes when clicking through the slides of a song, the screen glitches to black then immediately displays text again. It's hard to notice, but after a while, it gets really annoying. If hardware acceleration is off, then the issue doesn't occur that much, however, then the software itself is basically useless. I tried using this on a powerful M2 Mac Mini, and turning on hardware acceleration still produces the issue, so its not a hardware overload problem.

**Reproducing**
We use two outputs, a Primary and Stream. 
Primary: goes to projector on HDMI and NDI to OBS which does streaming, uses a modified default template and style, NO TRANSITIONS or background media.
Stream: transparent NDI to OBS, this is just for the lower third text during worship for the stream, this has a template where text is down on lower third level and it also doesn't use any transitions or background media and styles are applied, as far as I can tell, correctly.
To reproduce, all you need is to have hardware acceleration on, have two outputs both running NDI, turn off all transitions, and click through some slides.

**Screenshots (Optional)**
This is really hard to show on screenshots, so I'll attach a couple second video. The first time on the video is when it does everything correctly, the second 2 times is when the fault occurs, please slow the video down if need be. I am open to google meet or any sort of call if needed.
https://github.com/user-attachments/assets/afef18fb-8723-4ddc-b50a-1b3eaadc105e

**Version (Optional)**
 - OS: MacOS
 - FreeShow Version: 1.3.0

**Comment by vassbo** [comment]
Should be a bit better in the comming update!

**Comment by danivisuals** [comment]
Hello! I just updated to 1.3.2 and the issue has not unfortunately gotten better.

**Comment by vassbo** [comment]
Then I'm not sure if anything can be done about this as it seems to be somewhat random.

**Comment by danivisuals** [comment]
I tried it on Windows and MacOS yesterday, and it seems that it works much better! I experienced a lot less text glitching.
