### ISSUE TITLE
It doesn't always change the font size

### ISSUE THREAD

**Issue by odlarhg** [ChurchApps/FreeShow#969]
After updating to the latest version, the font size does not always change. I define a font size on a slide but when I go to Show the font is displayed in the size it had before making the change

It also does not show the button that allowed applying the format of a slide to all slides

**Comment by vassbo** [comment]
Can't reproduce. Make sure auto size is turned off, and no custom output style is set.

The "Apply to all" should show up after pressing "Copy".
