### ISSUE TITLE
Message for stage only

### ISSUE THREAD

**Issue by dangelomda** [ChurchApps/FreeShow#972]
Hello everyone, this is very important in the Stage window, we can send a message only to the Stage, in my opinion we have a free text box with a send button and this message appears only on the Stage screen.

**Comment by vassbo** [comment]
You can do this currently with variables: https://github.com/ChurchApps/FreeShow/issues/791
You can also select a textbox on any slide and select "Specific outputs">"Stage"

Maybe I'll also redo how the stage works sometime.
