### ISSUE TITLE
[Bug Report] Cannot preview show when in focus mode

### ISSUE THREAD

**Issue by gccmtuba** [ChurchApps/FreeShow#973]
**Describe the bug**
When in focus mode, single clicking on a show in the drawer does not preview it (like does happen when you are not in focus mode).

**Reproducing**
- View > Toggle Focus Mode
- Single click a show in the drawer which is not in the current project
- The main view scrolls to the top but does not preview the show

Focus mode looks useful for during a service, but sometimes the worship leader does a song which was not planned and we need to display it. It is useful to preview a song before adding it to the service.

**Version (Optional)**
 - OS: Windows
 - FreeShow Version: 1.3.0

**Comment by vassbo** [comment]
I will make it exit focus mode if opening a show/drawer item not in the project!
