### ISSUE TITLE
[Bug Report] Cannot exit settings when in focus mode

### ISSUE THREAD

**Issue by gccmtuba** [ChurchApps/FreeShow#975]
**Describe the bug**
When in focus mode you cannot get back to the show view from settings.

**Reproducing**
- View > Toggle Focus mode
- Right click in the show view, click settings
- Settings opens but there is no way back to the show view without toggling focus mode off again

**Version (Optional)**
 - OS: Windows
 - FreeShow Version: 1.3.0

**Comment by vassbo** [comment]
You can go back by pressing "1", but I'll add a back button.

**Comment by gccmtuba** [comment]
Thanks, I haven't learned all of the keyboard shortcuts yet
