### ISSUE TITLE
[Bug Report] Stage view puts text in the wrong order with multiple textboxes

### ISSUE THREAD

**Issue by gccmtuba** [ChurchApps/FreeShow#976]
**Describe the bug**
I have shows with two textboxes (for different languages). In stage view, the current slide view combines all of the text from the slide, but with the second textbox displayed first.

**Reproducing**
- Have a slide with multiple textboxes.
- See from text view the order of the textboxes as to which one is `[#1]`
- In stage view `[#2]` is displayed before `[#1]`

**Screenshots**
Grid view of an example song:
![image1](https://github.com/user-attachments/assets/5e67e011-bdb5-4951-8d7a-8b7a8c67df4d)

Text edit view of the same song:
![image2](https://github.com/user-attachments/assets/a3b2ba78-3abb-4d0f-b2bf-8a4b3b408fa5)

Stage view of the song:
![image3](https://github.com/user-attachments/assets/f833de2d-3c8e-4f16-b27e-aac8d2250909)

**Version**
 - OS: Windows
 - FreeShow Version: 1.3.0

**Additional context**
It would be good if I could customise stage view to only show one textbox or alternatively to style the text from each textbox differently, as I have done in the main output.

**Comment by vassbo** [comment]
I actually just fixed that, but it's the text editor that's inverted not the other places.

**Comment by vassbo** [comment]
By the way, you can use "Specific outputs" to hide certain textboxes from the stage view! :)
Or the "Current slide" item to get the same styling as the output.

![bilde](https://github.com/user-attachments/assets/7aaee2ee-e8da-4f4e-95ca-d5e43af02f83)

**Comment by gccmtuba** [comment]
Thanks, and also for the hint about specific outputs
