### ISSUE TITLE
[Feature Request] RemoteShow lyrics view tapping on words should take you to that slide

### ISSUE THREAD

**Issue by gccmtuba** [ChurchApps/FreeShow#977]
**Describe the feature**
When using lyrics view in RemoteShow, it feels like tapping/clicking on the words of a slide should take activate that slide. Instead, as described in [the docs](https://freeshow.app/docs/remote) "Click on the right side of the screen to go to next, and click on the left (1/3) to go to the previous slide."

**Comment by vassbo** [comment]
That's what the show slide view is for. The thing with the lyrics/output on RemoteShow is that you should be able to use it simply without looking. It's a bit getting used to I agree, but it's better.

**Comment by gccmtuba** [comment]
Ok, fair enough.

Thanks for the quick response to this and my other issues. I'm just testing out at the moment and hadn't used it 'live' yet so I'll see how I go.
