### ISSUE TITLE
[Feature Request] {settings for livestream}

### ISSUE THREAD

**Issue by NikolasGregor** [ChurchApps/FreeShow#978]
**settings for livestream like ProPresenter**
to be able to do live from the freeshow without needing the obs

**Additional context**
![{D9E2FAA2-6031-4A5D-BEF0-24C3AE062174}](https://github.com/user-attachments/assets/34de0ad0-0788-4d66-89ae-e839586a18b5)

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/797#issuecomment-2326392276
