### ISSUE TITLE
Text background is not applying all in slides.

### ISSUE THREAD

**Issue by fdccichurch** [ChurchApps/FreeShow#979]
**Describe the bug**
Text highlight feature on which you can "apply to all" is not working instead it reverts the edit to original.

**Reproducing**
Edit mode > Textbox >Text Tab > Background Color  > Copy button below > Apply to all
![462560078_939959868181259_3014063404028871470_n](https://github.com/user-attachments/assets/26d90b45-08f0-4fd5-9162-68d7d7666693)
![462569737_1129404101945041_1575519678729565551_n](https://github.com/user-attachments/assets/73237a71-8d33-4a94-934c-494d007a2ffd)

**Screenshots (Optional)**

**Version (Optional)**
 - OS: [Windows 11]
 - FreeShow Version: [e.g. 1.3.0]

**Additional context**

**Comment by fdccichurch** [comment]
Hello, is this good?

**Comment by fdccichurch** [comment]
Thank you so much, big help! God bless!

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.1-beta.1

**Comment by fdccichurch** [comment]
Hello, I have tried the beta version and I noticed that there is a problem in text tranform. 

https://github.com/user-attachments/assets/b93d1f92-5dad-4466-bcef-3e34f164809e

**Comment by vassbo** [comment]
It's just a visual issue, but I'll see what I can do about it.

**Comment by fdccichurch** [comment]
Ok, thanks.
