### ISSUE TITLE
[Feature Request] {A way to connect BibleShow to FreeShow}

### ISSUE THREAD

**Issue by Beniamin137** [ChurchApps/FreeShow#980]
I really like FreeShow but i think it's not the best at Bible presentation and that's why I like Bibleshow more
I would love a feature so i can connect BibleShow to it, I tried to connect with the NDI feature but i dont know why it doesn't work... So maybe a more easyer way to connect whould be awesome.
Or maybe someone else knows other metods. Please help me if you do

**Comment by vassbo** [comment]
Good suggestion. I don't think there's an easy way to do this, so it will probably not be done.
But what do you like more about BibleShow that FreeShow does not have?
