### ISSUE TITLE
[Bug Report] {Randomly freezes}

### ISSUE THREAD

**Issue by Beniamin137** [ChurchApps/FreeShow#981]
I'm just using the program and editing the slides then somehow nothing works anymore, I had to shutdown the program from task manager.

Version:
 - OS: Windows 11
 - FreeShow Version:  1.3.0

**Comment by vassbo** [comment]
Can you send over the error log from settings>"Other">"Open error log"? So I can try to debug the issue.

**Comment by vassbo** [comment]
Might be related to this if you tried to "Rearrange" items: https://github.com/ChurchApps/FreeShow/issues/997

**Comment by vassbo** [comment]
Closing until it can be reproduced.
