### ISSUE TITLE
[Feature Request] Difficult to accurately zoom show slide view in RemoteShow

### ISSUE THREAD

**Issue by gccmtuba** [ChurchApps/FreeShow#982]
**Describe the feature**
In RemoteShow on mobile, on the show slides view, you can use two fingers to zoom in and out, i.e. to make the slides bigger or smaller. However it takes only a tiny movement of the fingers to change the zoom, making it really difficult to stop on a specific zoom, i.e. number of slides width.

I think the sensitivity of this could do with adjusting to make it easier.

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.1-beta.1
