### ISSUE TITLE
[Feature Request] Being able to drag and drop 

### ISSUE THREAD

**Issue by rfmfriends** [ChurchApps/FreeShow#983]
**Describe the feature**
It would be nice if you could drag and drop media into Freeshow.  For example, grab a background file and drag it into project.

**Additional context**
One of the features that would keep from using this main stream, but otherwise I love the software.

**Comment by rfmfriends** [comment]
Thank you for addressing this and getting in touch.   I was unable to copy
links and paste them in media/web when creating a new video.   I was using
Linux Bazzite and I still had trouble when trying it on my Mac Air M1.

YouTube.com/watch?v=(some string of case sensitive character).  That there
could not be copied and pasted in Freeshow.

Robert M.

**Comment by rfmfriends** [comment]
Drag and drop, I was thinking about another issue.   Anyway I was unable to
move slides around in a different arrangement.  I was using Linux Bazzite.

Robert

**Comment by vassbo** [comment]
Just tested it, seems to work fine on Linux, Windows (and macOS as @Dcanadian pointed out). Have not tested it on Linux Bazzite specifically, but that's most likely an issue with Electron if it does not work!

**Comment by rfmfriends** [comment]
Good,I’m glad it worked well for you.  When  I’m able I’ll make videos of
my issues and send them to you.  Then we can go from there to find a
resolution.   David did send me links and I will watch them later.   Yes,
I’ stil learning Freeshow.   Dragging and dropping, maybe there are
limitations with that between outside programs and Freeware?  I will show
you that it will not work for me.  Also with copying and pasting links.

Robert

**Comment by rfmfriends** [comment]
Ok...Ok, I can't explain, but for some reason I was having trouble dragging
and dropping yesterday.  Now I don't have that issue.  Weird because I'm
not new to this.  I've been using Propresenter since 2014.  I know Freeshow
isn't Propresenter, LOL.

For the groups arrangements, I will later send you a video showing the
issue I'm having.  It was brought up by Kristoffer to use Global groups and
that didn't help.  Global labels look like they are general and not
specific to song.

For the copying and pasting links, again later I will send you a video
showing the issue I'm having.  I watched your videos and with the links it
looks like it should be the normal right click to paste it in there, but I
don't know why that won't work for me.

I'll have to set up a camera so you can see my screens as well as my mouse
so you can see fully and know I'm not try to jerk you around.

I'm not too familiar with Github, so I barely used it.  Since you've been
graciously helping me, I will delete those suggestions if I can.  Maybe
with the link issue it could be a bug and revise it or something.  I'll
wait until we're done here because it looks like communication goes through
Github and the issue.

Thank you so much for your patience and help!

Robert

**Comment by rfmfriends** [comment]
Yesterday I did have trouble and today it seems to be working fine dragging
and dropping.  Weird, I can't explain why that happened.  I'm not new to
presentation software either.  I've been using Propresenter since 2014. I
know this is not the same software, LOL.

**Comment by Phantom-Matt** [comment]
> [...] For the copying and pasting links, again later I will send you a video showing the issue I'm having. I watched your videos and with the links it looks like it should be the normal right click to paste it in there, but I don't know why that won't work for me. [...]

I'm using Linux too (Manjaro Linux, to be more specific, with KDE Plasma environment on Wayland) and i'm not sure on what step you are getting the problem. I tried the steps with a sample video from YouTube:

1. On Drawer, click on Media;
2. On the menu to the lower left, click on Online;
3. On the lower right, click on Add;
4. A window dialog appears with two textboxes to fill with text. A middle click works for me here as well as a Ctrl+V;
5. Now that video is on the Drawer, just double click him.

Should work like that. If it doesn't, try copying the link again.
