### ISSUE TITLE
[Feature Request] Song arrangements

### ISSUE THREAD

**Issue by rfmfriends** [ChurchApps/FreeShow#984]
**Describe the feature**
It would be great if you could add song arrangements.   Where there is a master of the groups of the song and you arrange the groups and/or even have multiples of a group.  For example, v1,v2,C would be a master.  Changing the arrangement could be v1,c,v2.  Having multiples or copying a group to use it again like.....v1,v1,c,v2,bridge.bridge,c

**Additional context**
One of the features that would keep me from using this main stream.

**Comment by rfmfriends** [comment]
I’ll check this out,  thank you for sending me the link to your docs for
Freeshow.

**Comment by rfmfriends** [comment]
I'll have to sent a video of this later to show you my issue.  Maybe I wasn't clear.

**Comment by vassbo** [comment]
@rfmfriends I understand what you mean. This feature is already in the application, please watch the video @Dcanadian made for you!

**Comment by rfmfriends** [comment]
I respectively don't think we're on the same page.  I will still work on
the video to show you.   Your showing me the slides added from the right
groups area, but that's not what I'm referring to.

Here's a video from Youtube of the feature that I would like to see.  Again
I know this isn't Propresenter, I'm using that as an example.
https://www.youtube.com/watch?v=z2wI_KGJKT8

**Comment by vassbo** [comment]
Arrangements in FreeShow are called "Layouts":
Simply create a new layout and rearrange the slides however you would like:
![bilde](https://github.com/user-attachments/assets/4d1f1576-b0d8-4668-9a92-ebf80211a4e7)

Then drag & drop existing slides from the right side!

**Comment by rfmfriends** [comment]
Ok, I'll check that out later today.

Thank you for your patiences and help!
