### ISSUE TITLE
[Feature Request] Copy and paste

### ISSUE THREAD

**Issue by rfmfriends** [ChurchApps/FreeShow#985]
**Describe the feature**
This feature is so basic that I don't know why it can't be done.   You have media, online and when you want to add a link to something it has to be typed out.  You can't copy the link from your browser and past it in Freeshow.   How is this not allowed?

**Additional context**
This is one big feature why I won't use Freeshow main stream.

**Comment by rfmfriends** [comment]
I'll send a video of the issue later.  I'll have to set something up so you can see my screens and mouse to see fully.  It looks like in the video someone is doing the basic right-clicking to paste it in there.  I don't know why but I'm unable to do that inside the Freeshow software.

**Comment by vassbo** [comment]
@rfmfriends You can only do that on mac. But you should be able to paste with CTRL+V!

**Comment by rfmfriends** [comment]
Ok, thank you

**Comment by rfmfriends** [comment]
Thank you, CTRL +V worked.  I either forgot about that or didn't know.
It's been a few years since I've used Linux and recently jumped back in
dumping Windows.
