### ISSUE TITLE
[Feature Request] {Performance optimization of NDI outputs}

### ISSUE THREAD

**Issue by marcosmolina7** [ChurchApps/FreeShow#987]
**Describe the feature**
Currently, when creating NDI outputs in Freeshow, the processor is overloaded, reaching peaks of 100% utilization, even on computers with powerful hardware. This occurs when generating two NDI outputs at 1080p.
To improve performance and efficiency, I suggest exploring the possibility of using the graphics card to manage the NDI outputs instead of the processor. This would allow:

Reduce the load on the processor.
Improve overall stability and performance
Take full advantage of the capabilities of the graphics card.

It is important to note that the competition using NDI also leverages the graphics to manage these outputs, resulting in more stable and balanced performance. Considering that the video outputs are inherently processed by the graphics, it would make sense to allow Freeshow to utilize this capability to improve efficiency.
This enhancement would significantly improve the user experience and position Freeshow on par with similar products on the market.

And one last doubt, the option “Disable hardware acceleration” what does it refer to, since enabling or disabling it does not cause anything to my impression, which may be true.

Likewise, if the option is already integrated or is under development, it would be very good to let you know, and congratulations in advance for the great project that is being created.

**Additional context**
![Captura de pantalla 2024-11-06 202325](https://github.com/user-attachments/assets/6455e188-a8fb-443f-ab02-91a6a7d40ee2)

**Comment by vassbo** [comment]
"Disable hardware acceleration" should use more of the GPU for graphics/videos when hardware acceleration is enabled (toggle disabled). - Did you restart the program and test the CPU/GPU usage again with this toggled?

I have optimized it a bunch in the past, but I'm not sure I can optimize it further as it is built on Electron/Chromium. I also see that it's using less than 3/4 of your processor in this scenario.

**Comment by jerm00** [comment]
not trying to be rude, but have you considered using linux? i am currently using it on a laptop with modest hardware (32GB RAM, ryzen 7 4800H) and it works well. the screenshot shows my cpu usage (30-35%) with two monitors, ndi output enabled in freeshow at 1920x1080 and simultaneously running obs studio to capture that ndi output, spotify playing music and a few other misc apps. i do have the other option "disable hardware acceleration" turned off (meaning hardware accel is enabled) the main reason i did that is the background framerate was very choppy, changing that setting made a huge difference.

![Screenshot from 2024-11-07 19-48-58](https://github.com/user-attachments/assets/b641222d-cc9a-492d-b369-36bbfd07e112)

**Comment by marcosmolina7** [comment]
Very kind of you both, you both helped me, the problem was that apart, I had a Windows update and it caused me excessive CPU usage but I fixed it, and unchecked the box "Disable hardware acceleration" helped me a lot, and if I have considered using Linux, since much of my life I have used it and if it is much better.

One last thing, maybe you can add the option to define which video is the one that follows, let's say you can put the video 1 and can be configured so that as soon as it ends, start the video 2. And if the option is already there, just tell me, I'm new at this, and an apology.

Thanks for your support, we are always in contact. God bless you.

**Comment by vassbo** [comment]
Perfect!
Drag in your two videos into a show, right click the first, and set the slide action "Next on media finished".

**Comment by marcosmolina7** [comment]
> Perfect!
> Drag in your two videos into a show, right click the first, and set the slide action "Next on media finished".

Very kind, yes it worked for me, have a nice day.
