### ISSUE TITLE
[Bug Report] Shrink to Fit / Text on One Line display glitch

### ISSUE THREAD

**Issue by reflecx** [ChurchApps/FreeShow#988]
When either Shrink to Fit or Text on One Line is used, and the text needs to be shrunk, the output displays the unshrunk/wrapped version first, then the shrunk version. This makes the feature kinda unusable

**Reproducing**
Use a song that has more lines than the template, or a song with long lines
Display that song

**Screenshots **

https://github.com/user-attachments/assets/b003493b-24f1-4375-9879-b2773eabb663

**Version **
 - OS: Windows
 - FreeShow Version: 1.3.0

**Comment by vassbo** [comment]
Yep, I fixed that for the next version! :)

**Comment by vassbo** [comment]
Should be fixed: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.1-beta.1
