### ISSUE TITLE
How to Automatically Create Multilingual Bible Slides (English and German) in FreeShow?

### ISSUE THREAD

**Issue by Lpwmack17** [ChurchApps/FreeShow#989]
Hey everyone, I kinda need help
I am working with FreeShow to display Bible verses in a presentation format, and I have both the English and German versions of the Bible available. Currently, I can create a show with the English version of a Bible verse (e.g., John 3:16) by looking it up in FreeShow. However, I would like to know if there is a way to automatically include the corresponding verse from the German Bible in the same show.

For example, when I enter John 3:16, I want FreeShow to:

1. Create a slide with the English version of John 3:16.
2. Automatically include a slide with the German version of John 3:16.

Is there a way to import or link the German Bible alongside the English version in FreeShow, 
so that both versions are displayed together for any verse I search for? 
Any suggestions or solutions on how I can achieve this would be greatly appreciated!

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/236#issuecomment-1683423643
