### ISSUE TITLE
[Bug Report] {Wrong Characters When Import ProPresenter File In Chinese}

### ISSUE THREAD

**Issue by AngangGuo** [ChurchApps/FreeShow#991]
**Describe the bug**
The content of a song in ProPresenter is Chinese character like this:
我尋求你
After I import the .pro to FreeShow, it shows out like this:
\'ce\'d2\'8c\'a4\'c7\'f3Ä\'e3\'a3

**Reproducing**
Please give some steps we can follow to recreate this issue.
I have attached the .pro file and you can import into FreeShow

**Screenshots (Optional)**
[Adonai 我等候你.zip](https://github.com/user-attachments/files/17667011/Adonai.zip)

![image](https://github.com/user-attachments/assets/d8951d7d-e3c2-424e-a0b0-3eb62262862a)

![image](https://github.com/user-attachments/assets/7a74b1da-2e0b-44f6-898b-1dbeb9eed17e)

**Version (Optional)**
 - OS: [Windows 10 Home]
 - FreeShow Version: [1.3.0]

**Additional context**

**Comment by vassbo** [comment]
https://github.com/ChurchApps/FreeShow/issues/577#issuecomment-2288554767
