### ISSUE TITLE
Giving thanks

### ISSUE THREAD

**Issue by rfmfriends** [ChurchApps/FreeShow#992]
I wanted to give thanks to David, Kristoffer and the Freeshow community for helping me through issues that were there but labeled differently and how to's for things i forgot or didn't know.   Great software and excellent support, I really hope Freeshow goes far!  I'm going to try to use it more almost main stream, maybe even where I serve.   Certainly spread how great thou Freeshow.

**Comment by vassbo** [comment]
Thank you for letting us know your appreciation!
