### ISSUE TITLE
[Feature Request and question] Unable to Activate Images or Overlays via RemoteShow

### ISSUE THREAD

**Issue by Lpwmack17** [ChurchApps/FreeShow#993]
I am experiencing an issue with activating images or overlays using the RemoteShow app. 
There doesn’t seem to be any other way to activate it. The images and Overlays on Remoteshow are not clickable and I was checking if that already works.

**Steps to Reproduce:**

1. Open the FreeShow app and load the desired project.
2. Attempt to activate an image or overlay via the RemoteShow app.
3. Observe that the image title is greyed out and not clickable.

**Expected Behavior:** 
The image or overlay should be clickable and activatable via the RemoteShow app.

**Actual Behavior:** 
The image title is greyed out and cannot be activated through RemoteShow.

Additional Information:

FreeShow version: 1.3.0
Operating System: Windows 11

Pictures/screenshots
![image](https://github.com/user-attachments/assets/5eba33cd-51fe-4b02-989e-8d05ac53567b)

Thanks in advance!

**Comment by vassbo** [comment]
This is not possible at the moment, but it's on the todo list.
You can create a show and add the images & overlays to slides, that way they can be activated from the remote!
