### ISSUE TITLE
[Feature Request] Transitions on Overlays in Freeshow

### ISSUE THREAD

**Issue by Lpwmack17** [ChurchApps/FreeShow#995]
Hello! I wanted to ask if it's possible to add different transitions to overlays in Freeshow. Currently, I noticed that transitions are available for text and images, but I didn't find an option for overlays specifically.

Additional Context: I’m not sure if this feature already exists and I might have missed it, but I thought it would be easier to ask directly rather than spend hours searching through the documentation or settings.

Thank you!
God Bless :)

**Comment by Phantom-Matt** [comment]
Hello @Lpwmack17. Yes, this is implemented, but not on the way that we (users) expect it to happen.

If you go to the tab on overlays and right click and select "Edit", you can acess this screen

![Captura de imagem_20241108_020210](https://github.com/user-attachments/assets/81cfb1fe-249b-43d9-93a5-80f83eb4c73d)

From here, is kinda simple. Just select the element and there you go. This may appear confusing, but going this way gives more control over what transition each element can have. 

Hope it helps.

**Comment by Lpwmack17** [comment]
Hey @Phantom-Matt,
So I tried what you suggested, but for some reasons, the transitions don't work, like I activated everything like you said, but when i tried it out, it just poped out, no transition, just dry old slide coming up.

Anyways Thank you for your help tho :) 
God Bless
