### ISSUE TITLE
[Bug Report] Application becomes unresponsive after internal error

### ISSUE THREAD

**Issue by Phantom-Matt** [ChurchApps/FreeShow#997]
If you try to use "Move to the front" or "Move foward" on Edit tab, the application stops responding to commands and inputs. Looking at the error log, however, shows that an error ocurred. @vassbo I attached the error log on the end of the report, if it can help.

**Reproducing**

1. Open any show that has multiple elements;
2. Edit this show;
3. Select one of the elements;
4. Right click and go to "Rearrange" and any of its suboptions.

**Version**
 - OS: Linux
 - FreeShow Version: 1.3.0

**Additional context**
[error_log.json](https://github.com/user-attachments/files/17674258/error_log.json)

**Comment by vassbo** [comment]
I did not experience the freezing as you did for some reason, but I hope I got this fixed thanks to the error log!

**Comment by vassbo** [comment]
Please let me know if you still experience this issue here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.1-beta.1

**Comment by Phantom-Matt** [comment]
> Please let me know if you still experience this issue here: https://github.com/ChurchApps/FreeShow/releases/tag/v1.3.1-beta.1

No issues. Creating a new slide and repeating the steps does not freeze the aplication.

However, applying the "Blue Header" template to the "Example" show that comes by default does stop the aplication. So, maybe is something with the show himself?

Anyway, it is working, thank you very much and God bless.

**Comment by vassbo** [comment]
Great! I used a number for the item ID in the default show, I changed it to a string and that fixed it!
