### ISSUE TITLE
[Bug Report] {Output Window Ignores Font and Color Edits to Scriptures}

### ISSUE THREAD

**Issue by alexpvk75** [ChurchApps/FreeShow#999]
**Describe the bug**
When editing Scriptures with different fonts and colors or templates, the changes appear in the Edit tab but do not reflect in the output window

**Reproducing**
1. Create a Scriptures slide
2. Open Edit Tab
3. Change font family or text color
4. Observe the output result

**Screenshots**
![Screenshot_1](https://github.com/user-attachments/assets/9f62b8cc-6b7b-42a0-a5da-8137f2a8e9c8)
![Screenshot_2](https://github.com/user-attachments/assets/a2a44c84-722d-42da-ae45-93e06ba05ca6)

**Version**
 - OS: Windows 11
 - FreeShow Version: [e.g. 1.3.0]

**Comment by mwb9aa** [comment]
I think you are missing a couple of steps after your third step. FreeShow allows editing that doesn't affect the currently playing show until after the user clicks the Show button. Personally, I love this feature and the lack of it prevented me from using ProPresenter for anything more than the occasional use at a church that had a license.

After step 3:
4. Click Show.
5. Click the slide to display.
6. Observe the output.

**Comment by alexpvk75** [comment]
But the issue is I need the changes to appear, and they don't

сб, 9 лист. 2024 р. о 12:55 mwb9aa ***@***.***> пише:

**Comment by vassbo** [comment]
You probably have set a custom output style template, please update/remove any templates from the settings>Styles:
![bilde](https://github.com/user-attachments/assets/caf06763-5ccd-493f-9a8f-b1069e0f2247)
